// 
package com.hhz.ump.entity.engineer;
// Generated 2012-6-29 13:44:44 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.StringUtils;
import org.hibernate.annotations.GenericGenerator;

/**
 * EngineerEquipAccount generated by hbm2java
 */
@Entity
@Table(name="ENGINEER_EQUIP_ACCOUNT"
    ,schema="POWERDESK"
)
public class EngineerEquipAccount  implements java.io.Serializable {


     private String engineerEquipAccountId;
     private String bisProjectId;
     private String layoutCd;
     private String equipTypeCd;
     private String equipBelongtoCd;
     private String equipCd;
     private String equipName;
     private String equipModels;
     private String equipMaker;
     private String equipSerialNum;
     private String equipSerialDate;
     private BigDecimal equipAmount;
     private String equipPosition;
     private String equipException;
     private String attachFlg;
     private BigDecimal equipStatus;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private Long recordVersion;

    public EngineerEquipAccount() {
    }

	
    public EngineerEquipAccount(String engineerEquipAccountId,
			String bisProjectId, String layoutCd, String equipTypeCd,
			String equipBelongtoCd, String equipCd, String equipName,
			String equipModels, String equipMaker, String equipSerialNum,
			String equipSerialDate, BigDecimal equipAmount,
			String equipPosition, String equipException, String attachFlg,
			BigDecimal equipStatus) {
		super();
		this.engineerEquipAccountId = engineerEquipAccountId;
		this.bisProjectId = bisProjectId;
		this.layoutCd = layoutCd;
		this.equipTypeCd = equipTypeCd;
		this.equipBelongtoCd = equipBelongtoCd;
		this.equipCd = equipCd;
		this.equipName = equipName;
		this.equipModels = equipModels;
		this.equipMaker = equipMaker;
		this.equipSerialNum = equipSerialNum;
		this.equipSerialDate = equipSerialDate;
		this.equipAmount = equipAmount;
		this.equipPosition = equipPosition;
		this.equipException = equipException;
		this.attachFlg = attachFlg;
		this.equipStatus = equipStatus;
	}


	public EngineerEquipAccount(String engineerEquipAccountId) {
        this.engineerEquipAccountId = engineerEquipAccountId;
    }
    public EngineerEquipAccount(String engineerEquipAccountId, String bisProjectId, String layoutCd, String equipTypeCd, String equipBelongtoCd, String equipCd, String equipName, String equipModels, String equipMaker, String equipSerialNum, String equipSerialDate, BigDecimal equipAmount, String equipPosition, String equipException, String attach_Flg, BigDecimal equipStatus, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, Long recordVersion) {
       this.engineerEquipAccountId = engineerEquipAccountId;
       this.bisProjectId = bisProjectId;
       this.layoutCd = layoutCd;
       this.equipTypeCd = equipTypeCd;
       this.equipBelongtoCd = equipBelongtoCd;
       this.equipCd = equipCd;
       this.equipName = equipName;
       this.equipModels = equipModels;
       this.equipMaker = equipMaker;
       this.equipSerialNum = equipSerialNum;
       this.equipSerialDate = equipSerialDate;
       this.equipAmount = equipAmount;
       this.equipPosition = equipPosition;
       this.equipException = equipException;
       this.attachFlg = attach_Flg;
       this.equipStatus = equipStatus;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="ENGINEER_EQUIP_ACCOUNT_ID", unique=true, nullable=false, length=50)
    public String getEngineerEquipAccountId() {
        return this.engineerEquipAccountId;
    }
    
    public void setEngineerEquipAccountId(String engineerEquipAccountId) {
        this.engineerEquipAccountId = engineerEquipAccountId;
    }
    
    @Column(name="BIS_PROJECT_ID", length=50)
    public String getBisProjectId() {
        return this.bisProjectId;
    }
    
    public void setBisProjectId(String bisProjectId) {
        this.bisProjectId = bisProjectId;
    }
    
    @Column(name="LAYOUT_CD", length=5)
    public String getLayoutCd() {
        return this.layoutCd;
    }
    
    public void setLayoutCd(String layoutCd) {
        this.layoutCd = layoutCd;
    }
    
    @Column(name="EQUIP_TYPE_CD", length=50)
    public String getEquipTypeCd() {
        return this.equipTypeCd;
    }
    
    public void setEquipTypeCd(String equipTypeCd) {
        this.equipTypeCd = equipTypeCd;
    }
    
    @Column(name="EQUIP_BELONGTO_CD", length=50)
    public String getEquipBelongtoCd() {
        return this.equipBelongtoCd;
    }
    
    public void setEquipBelongtoCd(String equipBelongtoCd) {
        this.equipBelongtoCd = equipBelongtoCd;
    }
    
    @Column(name="EQUIP_CD", length=50)
    public String getEquipCd() {
        return this.equipCd;
    }
    
    public void setEquipCd(String equipCd) {
        this.equipCd = equipCd;
    }
    
    @Column(name="EQUIP_NAME", length=100)
    public String getEquipName() {
        return this.equipName;
    }
    
    public void setEquipName(String equipName) {
        this.equipName = equipName;
    }
    
    @Column(name="EQUIP_MODELS", length=200)
    public String getEquipModels() {
        return this.equipModels;
    }
    
    public void setEquipModels(String equipModels) {
        this.equipModels = equipModels;
    }
    
    @Column(name="EQUIP_MAKER", length=100)
    public String getEquipMaker() {
        return this.equipMaker;
    }
    
    public void setEquipMaker(String equipMaker) {
        this.equipMaker = equipMaker;
    }
    
    @Column(name="EQUIP_SERIAL_NUM", length=50)
    public String getEquipSerialNum() {
        return this.equipSerialNum;
    }
    
    public void setEquipSerialNum(String equipSerialNum) {
        this.equipSerialNum = equipSerialNum;
    }
    @Column(name="EQUIP_SERIAL_DATE", length=20)
    public String getEquipSerialDate() {
        return this.equipSerialDate;
    }
    
    public void setEquipSerialDate(String equipSerialDate) {
        this.equipSerialDate = equipSerialDate;
    }
    
    @Column(name="EQUIP_AMOUNT", precision=38, scale=0)
    public BigDecimal getEquipAmount() {
        return this.equipAmount;
    }
    
    public void setEquipAmount(BigDecimal equipAmount) {
        this.equipAmount = equipAmount;
    }
    public void setEquipAmount(String equipAmount) {
    	if(StringUtils.isNotBlank(equipAmount)){
    		this.equipAmount = new BigDecimal(equipAmount);
    	}else{
    		this.equipAmount = new BigDecimal("0");
    	}
    	
    }
    
    @Column(name="EQUIP_POSITION", length=100)
    public String getEquipPosition() {
        return this.equipPosition;
    }
    
    public void setEquipPosition(String equipPosition) {
        this.equipPosition = equipPosition;
    }
    
    @Column(name="EQUIP_EXCEPTION", length=200)
    public String getEquipException() {
        return this.equipException;
    }
    
    public void setEquipException(String equipException) {
        this.equipException = equipException;
    }
    
    @Column(name="ATTACH_FLG", length=5)
    public String getAttachFlg() {
		return attachFlg;
	}

	public void setAttachFlg(String attach_Flg) {
		attachFlg = attach_Flg;
	}

    @Column(name="EQUIP_STATUS", precision=38, scale=0)
    public BigDecimal getEquipStatus() {
        return this.equipStatus;
    }
    

	public void setEquipStatus(BigDecimal equipStatus) {
    	this.equipStatus = equipStatus;
    }
    public void setEquipStatus(String equipStatus) {
    	if(StringUtils.isNotBlank(equipStatus)){
    		this.equipStatus = new BigDecimal(equipStatus);
    	}else{
    		this.equipStatus = new BigDecimal("0");
    	}
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", precision=10, scale=0)
    public Long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(Long recordVersion) {
        this.recordVersion = recordVersion;
    }




}


