// 
package com.hhz.uums.entity.plas;
// Generated 2011-1-28 17:13:01 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * PlasAcct generated by hbm2java
 */
@Entity
@Table(name="PLAS_ACCT"
    
)
public class PlasAcct  implements java.io.Serializable {


     private String plasAcctId;
     private PlasUser plasUser;
     private String uiid;
     private String acctSeqNo;
     private String custLoginName;
     private String statusCd;
     private String email;
     private String authenticTypeCd;//IDNO
     private String loginInPassword;
     private Date lockedDate;
     private Date lastLoginDate;
     private Date lastLogoutDate;
     private String lastLoginIp;
     private Date effectDate;
     private Date invalidDate;
     private BigDecimal failureTimes;
     private String macAddress;
     private String macLockedFlg;
     
     private String easFlg;
     private String easPasswordSetFlg;
     
     private String emailFlg;
     private String emailPasswordSetFlg;

     private String mysoftFlg;
     private String mysoftPasswordSetFlg;

     private String cmailFlg;
     private String cmailPasswordSetFlg;
     
     private Boolean activeBl;
     private BigDecimal sequenceNo;
     private String applyStatusCd;
     
     private Date pwdLastModDate;
     private String pwdStrategyCd;

     
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private List<PlasSysPosition> plasSysPositions = new ArrayList<PlasSysPosition>();

    public PlasAcct() {
    }

	
    public PlasAcct(String plasAcctId, String uiid, long recordVersion) {
        this.plasAcctId = plasAcctId;
        this.uiid = uiid;
        this.recordVersion = recordVersion;
    }
    public PlasAcct(String plasAcctId, PlasUser plasUser, String uiid, String acctSeqNo, String custLoginName, String statusCd, String email, String authenticTypeCd, String loginInPassword, Date lockedDate, Date lastLoginDate, Date lastLogoutDate, String lastLoginIp, Date effectDate, Date invalidDate, BigDecimal failureTimes, String macAddress, String macLockedFlg, String easFlg, String easPasswordSetFlg, String emailFlg, String emailPasswordSetFlg, String mysoftFlg, String mysoftPasswordSetFlg, String cmailFlg, String cmailPasswordSetFlg, Boolean activeBl, BigDecimal sequenceNo, String applyStatusCd, Date pwdLastModDate, String pwdStrategyCd, String remark, String creator, String createdCenterCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedPositionCd, Date updatedDate, long recordVersion, List<PlasSysPosition> plasSysPositions) {
       this.plasAcctId = plasAcctId;
       this.plasUser = plasUser;
       this.uiid = uiid;
       this.acctSeqNo = acctSeqNo;
       this.custLoginName = custLoginName;
       this.statusCd = statusCd;
       this.email = email;
       this.authenticTypeCd = authenticTypeCd;
       this.loginInPassword = loginInPassword;
       this.lockedDate = lockedDate;
       this.lastLoginDate = lastLoginDate;
       this.lastLogoutDate = lastLogoutDate;
       this.lastLoginIp = lastLoginIp;
       this.effectDate = effectDate;
       this.invalidDate = invalidDate;
       this.failureTimes = failureTimes;
       this.macAddress = macAddress;
       this.macLockedFlg = macLockedFlg;
       this.easFlg = easFlg;
       this.easPasswordSetFlg = easPasswordSetFlg;
       this.emailFlg = emailFlg;
       this.emailPasswordSetFlg = emailPasswordSetFlg;
       this.mysoftFlg = mysoftFlg;
       this.mysoftPasswordSetFlg = mysoftPasswordSetFlg;
       this.cmailFlg = cmailFlg;
       this.cmailPasswordSetFlg = cmailPasswordSetFlg;
       this.activeBl = activeBl;
       this.sequenceNo = sequenceNo;
       this.pwdLastModDate = pwdLastModDate;
       this.pwdStrategyCd = pwdStrategyCd;
       this.remark = remark;
       this.applyStatusCd = applyStatusCd;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.plasSysPositions = plasSysPositions;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="PLAS_ACCT_ID", unique=true, nullable=false, length=50)
    public String getPlasAcctId() {
        return this.plasAcctId;
    }
    
    public void setPlasAcctId(String plasAcctId) {
        this.plasAcctId = plasAcctId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PLAS_USER_ID")
    public PlasUser getPlasUser() {
        return this.plasUser;
    }
    
    public void setPlasUser(PlasUser plasUser) {
        this.plasUser = plasUser;
    }
    
    @Column(name="UIID", nullable=false, length=50)
    public String getUiid() {
        return this.uiid;
    }
    
    public void setUiid(String uiid) {
        this.uiid = uiid;
    }
    
    @Column(name="ACCT_SEQ_NO", length=20)
    public String getAcctSeqNo() {
        return this.acctSeqNo;
    }
    
    public void setAcctSeqNo(String acctSeqNo) {
        this.acctSeqNo = acctSeqNo;
    }
    
    @Column(name="CUST_LOGIN_NAME", length=50)
    public String getCustLoginName() {
        return this.custLoginName;
    }
    
    public void setCustLoginName(String custLoginName) {
        this.custLoginName = custLoginName;
    }
    
    @Column(name="STATUS_CD", length=20)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }
    
    @Column(name="EMAIL", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="AUTHENTIC_TYPE_CD", length=20)
    public String getAuthenticTypeCd() {
        return this.authenticTypeCd;
    }
    
    public void setAuthenticTypeCd(String authenticTypeCd) {
        this.authenticTypeCd = authenticTypeCd;
    }
    
    @Column(name="LOGIN_IN_PASSWORD", length=100)
    public String getLoginInPassword() {
        return this.loginInPassword;
    }
    
    public void setLoginInPassword(String loginInPassword) {
        this.loginInPassword = loginInPassword;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LOCKED_DATE", length=7)
    public Date getLockedDate() {
        return this.lockedDate;
    }
    
    public void setLockedDate(Date lockedDate) {
        this.lockedDate = lockedDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_LOGIN_DATE", length=7)
    public Date getLastLoginDate() {
        return this.lastLoginDate;
    }
    
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_LOGOUT_DATE", length=7)
    public Date getLastLogoutDate() {
        return this.lastLogoutDate;
    }
    
    public void setLastLogoutDate(Date lastLogoutDate) {
        this.lastLogoutDate = lastLogoutDate;
    }
    
    @Column(name="LAST_LOGIN_IP", length=15)
    public String getLastLoginIp() {
        return this.lastLoginIp;
    }
    
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECT_DATE", length=7)
    public Date getEffectDate() {
        return this.effectDate;
    }
    
    public void setEffectDate(Date effectDate) {
        this.effectDate = effectDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INVALID_DATE", length=7)
    public Date getInvalidDate() {
        return this.invalidDate;
    }
    
    public void setInvalidDate(Date invalidDate) {
        this.invalidDate = invalidDate;
    }
    
    @Column(name="FAILURE_TIMES", precision=38, scale=0)
    public BigDecimal getFailureTimes() {
        return this.failureTimes;
    }
    
    public void setFailureTimes(BigDecimal failureTimes) {
        this.failureTimes = failureTimes;
    }
    
    @Column(name="MAC_ADDRESS", length=200)
    public String getMacAddress() {
        return this.macAddress;
    }
    
    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress;
    }
    
    @Column(name="MAC_LOCKED_FLG", length=1)
    public String getMacLockedFlg() {
        return this.macLockedFlg;
    }
    
    public void setMacLockedFlg(String macLockedFlg) {
        this.macLockedFlg = macLockedFlg;
    }
    
    @Column(name="EAS_FLG", length=1)
    public String getEasFlg() {
        return this.easFlg;
    }
    
    public void setEasFlg(String easFlg) {
        this.easFlg = easFlg;
    }
    
    @Column(name="EAS_PASSWORD_SET_FLG", length=1)
    public String getEasPasswordSetFlg() {
        return this.easPasswordSetFlg;
    }
    
    public void setEasPasswordSetFlg(String easPasswordSetFlg) {
        this.easPasswordSetFlg = easPasswordSetFlg;
    }
    
    @Column(name="EMAIL_FLG", length=1)
    public String getEmailFlg() {
        return this.emailFlg;
    }
    
    public void setEmailFlg(String emailFlg) {
        this.emailFlg = emailFlg;
    }
    
    @Column(name="EMAIL_PASSWORD_SET_FLG", length=1)
    public String getEmailPasswordSetFlg() {
        return this.emailPasswordSetFlg;
    }
    
    public void setEmailPasswordSetFlg(String emailPasswordSetFlg) {
        this.emailPasswordSetFlg = emailPasswordSetFlg;
    }
    
    @Column(name="MYSOFT_FLG", length=1)
    public String getMysoftFlg() {
    	return  this.mysoftFlg;
    }
    
    public void setMysoftFlg(String mysoftFlg) {
    	this.mysoftFlg = mysoftFlg;
    }
    
    @Column(name="MYSOFT_PASSWORD_SET_FLG", length=1)
    public String getMysoftPasswordSetFlg() {
    	return this.mysoftPasswordSetFlg;
    }
    
    public void setMysoftPasswordSetFlg(String mysoftPasswordSetFlg) {
    	this.mysoftPasswordSetFlg = mysoftPasswordSetFlg;
    }
    

    @Column(name="CMAIL_FLG", length=1)
	public String getCmailFlg() {
		return cmailFlg;
	}
	public void setCmailFlg(String cmailFlg) {
		this.cmailFlg = cmailFlg;
	}

    @Column(name="CMAIL_PASSWORD_SET_FLG", length=1)
	public String getCmailPasswordSetFlg() {
		return cmailPasswordSetFlg;
	}
	public void setCmailPasswordSetFlg(String cmailPasswordSetFlg) {
		this.cmailPasswordSetFlg = cmailPasswordSetFlg;
	}
    
    
    @Column(name="ACTIVE_BL", precision=1, scale=0)
    public Boolean getActiveBl() {
        return this.activeBl;
    }
    
    public void setActiveBl(Boolean activeBl) {
        this.activeBl = activeBl;
    }
    
    @Column(name="SEQUENCE_NO", precision=10, scale=0)
    public BigDecimal getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(BigDecimal sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    
    @Column(name="APPLY_STATUS_CD", length=200)
    public String getApplyStatusCd() {
        return this.applyStatusCd;
    }
    
    public void setApplyStatusCd(String applyStatusCd) {
        this.applyStatusCd = applyStatusCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PWD_LAST_MOD_DATE", length=7)
    public Date getPwdLastModDate() {
        return this.pwdLastModDate;
    }
    
    public void setPwdLastModDate(Date pwdLastModDate) {
        this.pwdLastModDate = pwdLastModDate;
    }
    
    @Column(name="PWD_STRATEGY_CD", length=1)
    public String getPwdStrategyCd() {
    	return this.pwdStrategyCd;
    }
    
    public void setPwdStrategyCd(String pwdStrategyCd) {
    	this.pwdStrategyCd = pwdStrategyCd;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="plasAcct")
    @BatchSize(size=10)
public List<PlasSysPosition> getPlasSysPositions() {
        return this.plasSysPositions;
    }
    
    public void setPlasSysPositions(List<PlasSysPosition> plasSysPositions) {
        this.plasSysPositions = plasSysPositions;
    }

    private String createdDeptCd;
    private String updatedDeptCd;
    @Column(name="CREATED_DEPT_CD", length=20)
	public String getCreatedDeptCd() {
		return createdDeptCd;
	}


	public void setCreatedDeptCd(String createdDeptCd) {
		this.createdDeptCd = createdDeptCd;
	}

	@Column(name="UPDATED_DEPT_CD", length=20)
	public String getUpdatedDeptCd() {
		return updatedDeptCd;
	}


	public void setUpdatedDeptCd(String updatedDeptCd) {
		this.updatedDeptCd = updatedDeptCd;
	}




}


