// 
package com.hhz.uums.entity.plas;
// Generated 2011-8-12 16:06:47 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * PlasOperApply generated by hbm2java
 */
@Entity
@Table(name="PLAS_OPER_APPLY"
    
)
public class PlasOperApply  implements java.io.Serializable {


     private String plasOperApplyId;
     private String operTypeCd;
     private String objTypeCd;
     private String objId;
     private String objName;
     private String targetId;
     private String targetName;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;

    public PlasOperApply() {
    }

	
    public PlasOperApply(String plasOperApplyId, long recordVersion) {
        this.plasOperApplyId = plasOperApplyId;
        this.recordVersion = recordVersion;
    }
    public PlasOperApply(String plasOperApplyId, String operTypeCd, String objTypeCd, String objId, String objName, String targetId, String targetName, String remark, String creator, String createdCenterCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedPositionCd, Date updatedDate, long recordVersion) {
       this.plasOperApplyId = plasOperApplyId;
       this.operTypeCd = operTypeCd;
       this.objTypeCd = objTypeCd;
       this.objId = objId;
       this.objName = objName;
       this.targetId = targetId;
       this.targetName = targetName;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="PLAS_OPER_APPLY_ID", unique=true, nullable=false, length=50)
    public String getPlasOperApplyId() {
        return this.plasOperApplyId;
    }
    
    public void setPlasOperApplyId(String plasOperApplyId) {
        this.plasOperApplyId = plasOperApplyId;
    }
    
    @Column(name="OPER_TYPE_CD", length=20)
    public String getOperTypeCd() {
        return this.operTypeCd;
    }
    
    public void setOperTypeCd(String operTypeCd) {
        this.operTypeCd = operTypeCd;
    }
    
    @Column(name="OBJ_TYPE_CD", length=20)
    public String getObjTypeCd() {
        return this.objTypeCd;
    }
    
    public void setObjTypeCd(String objTypeCd) {
        this.objTypeCd = objTypeCd;
    }
    
    @Column(name="OBJ_ID", length=50)
    public String getObjId() {
        return this.objId;
    }
    
    public void setObjId(String objId) {
        this.objId = objId;
    }
    
    @Column(name="OBJ_NAME", length=100)
    public String getObjName() {
        return this.objName;
    }
    
    public void setObjName(String objName) {
        this.objName = objName;
    }
    
    @Column(name="TARGET_ID", length=50)
    public String getTargetId() {
        return this.targetId;
    }
    
    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }
    
    @Column(name="TARGET_NAME", length=100)
    public String getTargetName() {
        return this.targetName;
    }
    
    public void setTargetName(String targetName) {
        this.targetName = targetName;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }




}


