// 
package com.hhz.uums.entity.plas;
// Generated 2011-3-16 13:56:20 by Hibernate Tools 3.2.2.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * PlasOrgDime generated by hbm2java
 */
@Entity
@Table(name="PLAS_ORG_DIME"
    
)
public class PlasOrgDime  implements java.io.Serializable {


     private String plasOrgDimeId;
     private String dimeCd;
     private String dimeName;
     private Long sequenceNo;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private List<PlasDimeOrgRel> plasDimeOrgRels = new ArrayList<PlasDimeOrgRel>();

    public PlasOrgDime() {
    }

	
    public PlasOrgDime(String plasOrgDimeId, String dimeName, long recordVersion) {
        this.plasOrgDimeId = plasOrgDimeId;
        this.dimeName = dimeName;
        this.recordVersion = recordVersion;
    }
    public PlasOrgDime(String plasOrgDimeId, String dimeCd, String dimeName, Long sequenceNo, String creator, String createdCenterCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedPositionCd, Date updatedDate, long recordVersion, String remark, List<PlasDimeOrgRel> plasDimeOrgRels) {
       this.plasOrgDimeId = plasOrgDimeId;
       this.dimeCd = dimeCd;
       this.dimeName = dimeName;
       this.sequenceNo = sequenceNo;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.remark = remark;
       this.plasDimeOrgRels = plasDimeOrgRels;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="PLAS_ORG_DIME_ID", unique=true, nullable=false, length=50)
    public String getPlasOrgDimeId() {
        return this.plasOrgDimeId;
    }
    
    public void setPlasOrgDimeId(String plasOrgDimeId) {
        this.plasOrgDimeId = plasOrgDimeId;
    }
    
    @Column(name="DIME_CD", length=50)
    public String getDimeCd() {
        return this.dimeCd;
    }
    
    public void setDimeCd(String dimeCd) {
        this.dimeCd = dimeCd;
    }
    
    @Column(name="DIME_NAME", nullable=false, length=100)
    public String getDimeName() {
        return this.dimeName;
    }
    
    public void setDimeName(String dimeName) {
        this.dimeName = dimeName;
    }
    
    @Column(name="SEQUENCE_NO", precision=10, scale=0)
    public Long getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Long sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="plasOrgDime")
    @BatchSize(size=10)
public List<PlasDimeOrgRel> getPlasDimeOrgRels() {
        return this.plasDimeOrgRels;
    }
    
    public void setPlasDimeOrgRels(List<PlasDimeOrgRel> plasDimeOrgRels) {
        this.plasDimeOrgRels = plasDimeOrgRels;
    }

    private String createdDeptCd;
    private String updatedDeptCd;
    @Column(name="CREATED_DEPT_CD", length=20)
	public String getCreatedDeptCd() {
		return createdDeptCd;
	}


	public void setCreatedDeptCd(String createdDeptCd) {
		this.createdDeptCd = createdDeptCd;
	}

	@Column(name="UPDATED_DEPT_CD", length=20)
	public String getUpdatedDeptCd() {
		return updatedDeptCd;
	}


	public void setUpdatedDeptCd(String updatedDeptCd) {
		this.updatedDeptCd = updatedDeptCd;
	}




}


