// 
package com.hhz.uums.entity.plas;
// Generated 2011-1-28 17:13:01 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * PlasOperateLog generated by hbm2java
 */
@Entity
@Table(name="PLAS_OPERATE_LOG"
    
)
public class PlasOperateLog  implements java.io.Serializable {


     private String plasOperateLogId;
     private String uiid;
     private String userName;
     private String moduleCd;
     private String sumarry;
     private String operateDetailDesc;
     private String ip;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;

    public PlasOperateLog() {
    }

	
    public PlasOperateLog(String plasOperateLogId, long recordVersion) {
        this.plasOperateLogId = plasOperateLogId;
        this.recordVersion = recordVersion;
    }
    public PlasOperateLog(String plasOperateLogId, String uiid, String userName, String moduleCd, String sumarry, String operateDetailDesc, String ip, String remark, String creator, String createdCenterCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedPositionCd, Date updatedDate, long recordVersion) {
       this.plasOperateLogId = plasOperateLogId;
       this.uiid = uiid;
       this.userName = userName;
       this.moduleCd = moduleCd;
       this.sumarry = sumarry;
       this.operateDetailDesc = operateDetailDesc;
       this.ip = ip;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="PLAS_OPERATE_LOG_ID", unique=true, nullable=false, length=50)
    public String getPlasOperateLogId() {
        return this.plasOperateLogId;
    }
    
    public void setPlasOperateLogId(String plasOperateLogId) {
        this.plasOperateLogId = plasOperateLogId;
    }
    
    @Column(name="UIID", length=50)
    public String getUiid() {
        return this.uiid;
    }
    
    public void setUiid(String uiid) {
        this.uiid = uiid;
    }
    
    @Column(name="USER_NAME", length=50)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="MODULE_CD", length=50)
    public String getModuleCd() {
        return this.moduleCd;
    }
    
    public void setModuleCd(String moduleCd) {
        this.moduleCd = moduleCd;
    }
    
    @Column(name="SUMARRY", length=100)
    public String getSumarry() {
        return this.sumarry;
    }
    
    public void setSumarry(String sumarry) {
        this.sumarry = sumarry;
    }
    
    @Column(name="OPERATE_DETAIL_DESC", length=4000)
    public String getOperateDetailDesc() {
        return this.operateDetailDesc;
    }
    
    public void setOperateDetailDesc(String operateDetailDesc) {
        this.operateDetailDesc = operateDetailDesc;
    }
    
    @Column(name="IP", length=50)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }


    private String createdDeptCd;
    private String updatedDeptCd;
    @Column(name="CREATED_DEPT_CD", length=20)
	public String getCreatedDeptCd() {
		return createdDeptCd;
	}


	public void setCreatedDeptCd(String createdDeptCd) {
		this.createdDeptCd = createdDeptCd;
	}

	@Column(name="UPDATED_DEPT_CD", length=20)
	public String getUpdatedDeptCd() {
		return updatedDeptCd;
	}


	public void setUpdatedDeptCd(String updatedDeptCd) {
		this.updatedDeptCd = updatedDeptCd;
	}



}


