// 
package com.hhz.uums.entity.plas;
// Generated 2011-1-28 17:13:01 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * PlasUser generated by hbm2java
 */
@Entity
@Table(name="PLAS_USER"
    
)
public class PlasUser  implements java.io.Serializable {


     private String plasUserId;
     private PlasOrg plasOrg;
     private String uiid;
     private String userCd;
     private String userBizCd;
     private String userName;
     private String serviceStatusCd;
     private String sexCd;
     private Date birthday;
     private String idno;
     private String nationCd;
     private String nativeProvinceDesc;
     private String nativePlaceDesc;
     private String marrigeStatusCd;
     private String schoolRecordCd;
     private String gradSchoolDesc;
     private String majorDesc;
     private Date attendWorkDate;
     private String memberTypeCd;
     private String workDutyDesc;
     private String responsibility;
     private String realPosCd;
     private String professionTypeCd;
     private String politicsCd;
     private String otherTypeCd;
     private String email;
     private String fixedPhone;
     private String mobilePhone;
     private String mobilePhone2;
     private String idCardTypeCd;
     private String specialUserFlg;
     private String userTypeCd;
     private String sourceTypeCd;
     private String defaultCredenc;
     private String permissionLevelCd;
     private String emailSignContent;
     private Boolean activeBl;
     private BigDecimal sequenceNo;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private List<PlasAcct> plasAccts = new ArrayList<PlasAcct>();
     
     private String centerCd;

    public PlasUser() {
    }

	
    public PlasUser(String plasUserId, String userName, long recordVersion) {
        this.plasUserId = plasUserId;
        this.userName = userName;
        this.recordVersion = recordVersion;
    }
    public PlasUser(String plasUserId, PlasOrg plasOrg, String uiid, String userCd, String userBizCd, String userName, String serviceStatusCd, String sexCd, Date birthday, String idno, String nationCd, String nativeProvinceDesc, String nativePlaceDesc, String marrigeStatusCd, String schoolRecordCd, String gradSchoolDesc, String majorDesc, Date attendWorkDate, String memberTypeCd, String workDutyDesc, String realPosCd, String professionTypeCd, String politicsCd, String otherTypeCd, String email, String fixedPhone, String mobilePhone, String mobilePhone2, String idCardTypeCd, String specialUserFlg, String userTypeCd, String sourceTypeCd, String defaultCredenc, String permissionLevelCd, String emailSignContent, Boolean activeBl, BigDecimal sequenceNo, String remark, String creator, String createdCenterCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedPositionCd, Date updatedDate, long recordVersion, List<PlasAcct> plasAccts,String centerCd) {
       this.plasUserId = plasUserId;
       this.plasOrg = plasOrg;
       this.uiid = uiid;
       this.userCd = userCd;
       this.userBizCd = userBizCd;
       this.userName = userName;
       this.serviceStatusCd = serviceStatusCd;
       this.sexCd = sexCd;
       this.birthday = birthday;
       this.idno = idno;
       this.nationCd = nationCd;
       this.nativeProvinceDesc = nativeProvinceDesc;
       this.nativePlaceDesc = nativePlaceDesc;
       this.marrigeStatusCd = marrigeStatusCd;
       this.schoolRecordCd = schoolRecordCd;
       this.gradSchoolDesc = gradSchoolDesc;
       this.majorDesc = majorDesc;
       this.attendWorkDate = attendWorkDate;
       this.memberTypeCd = memberTypeCd;
       this.workDutyDesc = workDutyDesc;
       this.realPosCd = realPosCd;
       this.professionTypeCd = professionTypeCd;
       this.politicsCd = politicsCd;
       this.otherTypeCd = otherTypeCd;
       this.email = email;
       this.fixedPhone = fixedPhone;
       this.mobilePhone = mobilePhone;
       this.mobilePhone2 = mobilePhone2;
       this.idCardTypeCd = idCardTypeCd;
       this.specialUserFlg = specialUserFlg;
       this.userTypeCd = userTypeCd;
       this.sourceTypeCd = sourceTypeCd;
       this.defaultCredenc = defaultCredenc;
       this.permissionLevelCd = permissionLevelCd;
       this.emailSignContent = emailSignContent;
       this.activeBl = activeBl;
       this.sequenceNo = sequenceNo;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.plasAccts = plasAccts;
       this.centerCd = centerCd;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="PLAS_USER_ID", unique=true, nullable=false, length=50)
    public String getPlasUserId() {
        return this.plasUserId;
    }
    
    public void setPlasUserId(String plasUserId) {
        this.plasUserId = plasUserId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PLAS_ORG_ID")
    public PlasOrg getPlasOrg() {
        return this.plasOrg;
    }
    
    public void setPlasOrg(PlasOrg plasOrg) {
        this.plasOrg = plasOrg;
    }
    
    @Column(name="UIID", length=50)
    public String getUiid() {
        return this.uiid;
    }
    
    public void setUiid(String uiid) {
        this.uiid = uiid;
    }
    
    @Column(name="USER_CD", length=20)
    public String getUserCd() {
    	return this.userCd;
    }
    
    public void setUserCd(String userCd) {
    	this.userCd = userCd;
    }
    
    @Column(name="USER_BIZ_CD", length=20)
    public String getUserBizCd() {
        return this.userBizCd;
    }
    
    public void setUserBizCd(String userBizCd) {
        this.userBizCd = userBizCd;
    }
    
    @Column(name="USER_NAME", nullable=false, length=50)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="SERVICE_STATUS_CD", length=20)
    public String getServiceStatusCd() {
        return this.serviceStatusCd;
    }
    
    public void setServiceStatusCd(String serviceStatusCd) {
        this.serviceStatusCd = serviceStatusCd;
    }
    
    @Column(name="SEX_CD", length=20)
    public String getSexCd() {
        return this.sexCd;
    }
    
    public void setSexCd(String sexCd) {
        this.sexCd = sexCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BIRTHDAY", length=7)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    
    @Column(name="IDNO", length=50)
    public String getIdno() {
        return this.idno;
    }
    
    public void setIdno(String idno) {
        this.idno = idno;
    }
    
    @Column(name="NATION_CD", length=20)
    public String getNationCd() {
        return this.nationCd;
    }
    
    public void setNationCd(String nationCd) {
        this.nationCd = nationCd;
    }
    
    @Column(name="NATIVE_PROVINCE_DESC", length=200)
    public String getNativeProvinceDesc() {
        return this.nativeProvinceDesc;
    }
    
    public void setNativeProvinceDesc(String nativeProvinceDesc) {
        this.nativeProvinceDesc = nativeProvinceDesc;
    }
    
    @Column(name="NATIVE_PLACE_DESC", length=500)
    public String getNativePlaceDesc() {
        return this.nativePlaceDesc;
    }
    
    public void setNativePlaceDesc(String nativePlaceDesc) {
        this.nativePlaceDesc = nativePlaceDesc;
    }
    
    @Column(name="MARRIGE_STATUS_CD", length=20)
    public String getMarrigeStatusCd() {
        return this.marrigeStatusCd;
    }
    
    public void setMarrigeStatusCd(String marrigeStatusCd) {
        this.marrigeStatusCd = marrigeStatusCd;
    }
    
    @Column(name="SCHOOL_RECORD_CD", length=20)
    public String getSchoolRecordCd() {
        return this.schoolRecordCd;
    }
    
    public void setSchoolRecordCd(String schoolRecordCd) {
        this.schoolRecordCd = schoolRecordCd;
    }
    
    @Column(name="GRAD_SCHOOL_DESC", length=200)
    public String getGradSchoolDesc() {
        return this.gradSchoolDesc;
    }
    
    public void setGradSchoolDesc(String gradSchoolDesc) {
        this.gradSchoolDesc = gradSchoolDesc;
    }
    
    @Column(name="MAJOR_DESC", length=200)
    public String getMajorDesc() {
        return this.majorDesc;
    }
    
    public void setMajorDesc(String majorDesc) {
        this.majorDesc = majorDesc;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ATTEND_WORK_DATE", length=7)
    public Date getAttendWorkDate() {
        return this.attendWorkDate;
    }
    
    public void setAttendWorkDate(Date attendWorkDate) {
        this.attendWorkDate = attendWorkDate;
    }
    
    @Column(name="MEMBER_TYPE_CD", length=20)
    public String getMemberTypeCd() {
        return this.memberTypeCd;
    }
    
    public void setMemberTypeCd(String memberTypeCd) {
        this.memberTypeCd = memberTypeCd;
    }
    
    @Column(name="WORK_DUTY_DESC", length=200)
    public String getWorkDutyDesc() {
        return this.workDutyDesc;
    }
    
    public void setWorkDutyDesc(String workDutyDesc) {
        this.workDutyDesc = workDutyDesc;
    }
    @Column(name="RESPONSIBILITY", length=200)
    public String getResponsibility() {
    	return this.responsibility;
    }
    
    public void setResponsibility(String responsibility) {
    	this.responsibility = responsibility;
    }
    
    @Column(name="REAL_POS_CD", length=20)
    public String getRealPosCd() {
        return this.realPosCd;
    }
    
    public void setRealPosCd(String realPosCd) {
        this.realPosCd = realPosCd;
    }
    
    @Column(name="PROFESSION_TYPE_CD", length=20)
    public String getProfessionTypeCd() {
        return this.professionTypeCd;
    }
    
    public void setProfessionTypeCd(String professionTypeCd) {
        this.professionTypeCd = professionTypeCd;
    }
    
    @Column(name="POLITICS_CD", length=20)
    public String getPoliticsCd() {
        return this.politicsCd;
    }
    
    public void setPoliticsCd(String politicsCd) {
        this.politicsCd = politicsCd;
    }
    
    @Column(name="OTHER_TYPE_CD", length=20)
    public String getOtherTypeCd() {
        return this.otherTypeCd;
    }
    
    public void setOtherTypeCd(String otherTypeCd) {
        this.otherTypeCd = otherTypeCd;
    }
    
    @Column(name="EMAIL", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="FIXED_PHONE", length=200)
    public String getFixedPhone() {
        return this.fixedPhone;
    }
    
    public void setFixedPhone(String fixedPhone) {
        this.fixedPhone = fixedPhone;
    }
    
    @Column(name="MOBILE_PHONE", length=200)
    public String getMobilePhone() {
        return this.mobilePhone;
    }
    
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }
    
    @Column(name="MOBILE_PHONE2", length=200)
    public String getMobilePhone2() {
        return this.mobilePhone2;
    }
    
    public void setMobilePhone2(String mobilePhone2) {
        this.mobilePhone2 = mobilePhone2;
    }
    
    @Column(name="ID_CARD_TYPE_CD", length=20)
    public String getIdCardTypeCd() {
        return this.idCardTypeCd;
    }
    
    public void setIdCardTypeCd(String idCardTypeCd) {
        this.idCardTypeCd = idCardTypeCd;
    }
    
    @Column(name="SPECIAL_USER_FLG", length=1)
    public String getSpecialUserFlg() {
        return this.specialUserFlg;
    }
    
    public void setSpecialUserFlg(String specialUserFlg) {
        this.specialUserFlg = specialUserFlg;
    }
    
    @Column(name="USER_TYPE_CD", length=20)
    public String getUserTypeCd() {
        return this.userTypeCd;
    }
    
    public void setUserTypeCd(String userTypeCd) {
        this.userTypeCd = userTypeCd;
    }
    
    @Column(name="SOURCE_TYPE_CD", length=20)
    public String getSourceTypeCd() {
        return this.sourceTypeCd;
    }
    
    public void setSourceTypeCd(String sourceTypeCd) {
        this.sourceTypeCd = sourceTypeCd;
    }
    
    @Column(name="DEFAULT_CREDENC", length=100)
    public String getDefaultCredenc() {
        return this.defaultCredenc;
    }
    
    public void setDefaultCredenc(String defaultCredenc) {
        this.defaultCredenc = defaultCredenc;
    }
    
    @Column(name="PERMISSION_LEVEL_CD", length=20)
    public String getPermissionLevelCd() {
        return this.permissionLevelCd;
    }
    
    public void setPermissionLevelCd(String permissionLevelCd) {
        this.permissionLevelCd = permissionLevelCd;
    }
    
    @Column(name="EMAIL_SIGN_CONTENT", length=4000)
    public String getEmailSignContent() {
        return this.emailSignContent;
    }
    
    public void setEmailSignContent(String emailSignContent) {
        this.emailSignContent = emailSignContent;
    }
    
    @Column(name="ACTIVE_BL", precision=1, scale=0)
    public Boolean getActiveBl() {
        return this.activeBl;
    }
    
    public void setActiveBl(Boolean activeBl) {
        this.activeBl = activeBl;
    }
    
    @Column(name="SEQUENCE_NO", precision=10, scale=0)
    public BigDecimal getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(BigDecimal sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="plasUser")
    @BatchSize(size=10)
public List<PlasAcct> getPlasAccts() {
        return this.plasAccts;
    }
    
    public void setPlasAccts(List<PlasAcct> plasAccts) {
        this.plasAccts = plasAccts;
    }


    private String createdDeptCd;
    private String updatedDeptCd;
    @Column(name="CREATED_DEPT_CD", length=20)
	public String getCreatedDeptCd() {
		return createdDeptCd;
	}


	public void setCreatedDeptCd(String createdDeptCd) {
		this.createdDeptCd = createdDeptCd;
	}

	@Column(name="UPDATED_DEPT_CD", length=20)
	public String getUpdatedDeptCd() {
		return updatedDeptCd;
	}


	public void setUpdatedDeptCd(String updatedDeptCd) {
		this.updatedDeptCd = updatedDeptCd;
	}


    @Column(name="CENTER_CD", length=20)
    public String getCenterCd() {
        return this.centerCd;
    }
    
    public void setCenterCd(String centerCd) {
        this.centerCd = centerCd;
    }
    

}


