create table intt_InboundRePick (warehouseItemId varchar2(255 char) not null, tempJobId varchar2(255 char), primary key (warehouseItemId));
create table intt_InboundRePickItemS (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_InboundRePutAway (warehouseItemId varchar2(255 char) not null, tempJobId varchar2(255 char), primary key (warehouseItemId));
create table intt_InboundRePutItemS (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_OutboundRePick (warehouseItemId varchar2(255 char) not null, tempJobId varchar2(255 char), primary key (warehouseItemId));
create table intt_OutboundRePickItemS (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_OutboundRePutAway (warehouseItemId varchar2(255 char) not null, tempJobId varchar2(255 char), primary key (warehouseItemId));
create table intt_OutboundRePutItemS (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_PutAwayItem (warehouseItemId varchar2(255 char) not null, primary key (warehouseItemId));
create table intt_bin (id varchar2(255 char) not null, remark varchar2(255 char), volume float, height float, breadth float, length float, weight float, state varchar2(255 char), buildingId varchar2(255 char), columnId varchar2(255 char), tierId varchar2(255 char), row_Id varchar2(255 char), floorId varchar2(255 char), warehouseId varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_binState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_building (id varchar2(255 char) not null, state varchar2(255 char), warehouseId varchar2(255 char), alias varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_buildingState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_checkingItem (warehouseItemId varchar2(255 char) not null, intt_errorBinQty float, intt_putawayQty float, arrived_qty float, destroyed_qty float, primary key (warehouseItemId));
create table intt_checkingItemState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_column (id varchar2(255 char) not null, state varchar2(255 char), alias varchar2(255 char), row_id varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_columnState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_destroyedItem (warehouseItemId varchar2(255 char) not null, primary key (warehouseItemId));
create table intt_destroyedItemState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_floor (id varchar2(255 char) not null, state varchar2(255 char), buildingId varchar2(255 char), alias varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_floorState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_inboundOrderItem (orderItemId varchar2(255 char) not null, primary key (orderItemId));
create table intt_inboundOrderItemState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_invoice (intt_id varchar2(255 char) not null, createTime timestamp, lastTime timestamp, intt_code varchar2(255 char), orderId number(10,0), invoiveState varchar2(255 char), primary key (intt_id));
create table intt_invoiceState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_item (id varchar2(255 char) not null, state varchar2(255 char), remark varchar2(255 char), lastModifiedTime timestamp, creationTime timestamp, qty float, unitPackage varchar2(255 char), material varchar2(255 char), intt_sn varchar2(255 char), invoice_id varchar2(255 char), intt_itemTypeId varchar2(255 char), primary key (id));
create table intt_itemState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_itemType (intt_id varchar2(255 char) not null, intt_code varchar2(255 char), intt_alias varchar2(255 char), intt_itemTypeState varchar2(255 char), intt_remark varchar2(255 char), primary key (intt_id));
create table intt_itemTypeState (intt_id varchar2(255 char) not null, intt_description varchar2(255 char), intt_code varchar2(255 char), primary key (intt_id));
create table intt_lastItems (mainItemId varchar2(255 char) not null, lastItemId varchar2(255 char) not null, primary key (mainItemId, lastItemId));
create table intt_logPickedItem (warehouseItemId varchar2(255 char) not null, primary key (warehouseItemId));
create table intt_logStorageItem (warehouseItemId varchar2(255 char) not null, primary key (warehouseItemId));
create table intt_material (id varchar2(255 char) not null, inttClientDetailWSId varchar2(255 char), value float, state varchar2(255 char), lastModifiedTime timestamp, creationTime timestamp, shelflife varchar2(255 char), remark varchar2(255 char), description varchar2(255 char), alias varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_materialState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_nextItems (mainItemId varchar2(255 char) not null, nextItemId varchar2(255 char) not null, primary key (mainItemId, nextItemId));
create table intt_order (id varchar2(255 char) not null, lastModifiedTime timestamp, createTime timestamp, code varchar2(255 char), warehouse varchar2(255 char), owner varchar2(255 char), primary key (id));
create table intt_orderItem (itemId varchar2(255 char) not null, intt_ArrivedQty float, intt_UnArrivedQty float, intt_destoryedQty float, job_id varchar2(255 char), warehouse_id varchar2(255 char), order_id varchar2(255 char), primary key (itemId));
create table intt_orderState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_outboundOrderItem (orderItemId varchar2(255 char) not null, primary key (orderItemId));
create table intt_outboundOrderItemState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_outboundTxtData (id varchar2(255 char) not null, opType number(10,0), orderJobId varchar2(255 char), jobId varchar2(255 char), binCode varchar2(255 char), productCode varchar2(255 char), SN varchar2(255 char), qty varchar2(255 char), primary key (id));
create table intt_owner (id varchar2(255 char) not null, code varchar2(255 char), alias varchar2(255 char), primary key (id));
create table intt_ownerState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_ownerZone (zoneId varchar2(255 char) not null, inttClientDetailWSId varchar2(255 char), primary key (zoneId));
create table intt_ownerZoneState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_packingItem (warehouseItemId varchar2(255 char) not null, primary key (warehouseItemId));
create table intt_packingItemState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_pickedItem (warehouseItemId varchar2(255 char) not null, primary key (warehouseItemId));
create table intt_pickingItem (warehouseItemId varchar2(255 char) not null, primary key (warehouseItemId));
create table intt_pickingItemState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_rate (id varchar2(255 char) not null, priority number(10,0), alias varchar2(255 char), code varchar2(255 char), state varchar2(255 char), primary key (id));
create table intt_rateState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_rates (materialId varchar2(255 char) not null, rateId varchar2(255 char) not null, binId varchar2(255 char) not null, primary key (binId, rateId));
create table intt_row (id varchar2(255 char) not null, state varchar2(255 char), alias varchar2(255 char), floorId varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_rowState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_shelflife (id varchar2(255 char) not null, denomination number(10,0), unit varchar2(255 char), state varchar2(255 char), primary key (id));
create table intt_shelflifeState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_storageItem (warehouseItemId varchar2(255 char) not null, primary key (warehouseItemId));
create table intt_storageItemState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_storageZone (zoneId varchar2(255 char) not null, description varchar2(255 char), primary key (zoneId));
create table intt_storageZoneState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_tier (id varchar2(255 char) not null, state varchar2(255 char), alias varchar2(255 char), code varchar2(255 char), row_id varchar2(255 char), primary key (id));
create table intt_tierState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_uncheckedItem (warehouseItemId varchar2(255 char) not null, unwantedQty float, wantQty float, arrivedQty float, destroyedQty float, putawayQty float, primary key (warehouseItemId));
create table intt_unit (id varchar2(255 char) not null, state varchar2(255 char), code varchar2(255 char), alias varchar2(255 char), primary key (id));
create table intt_unitPackage (id varchar2(255 char) not null, state varchar2(255 char), weight float, length float, breadth float, height float, volume float, unit varchar2(255 char), materialId varchar2(255 char), remark varchar2(255 char), description varchar2(255 char), alias varchar2(255 char), indexId number(10,0), primary key (id));
create table intt_unitPackagePair (id varchar2(255 char) not null, state varchar2(255 char), denomination float, otherUnitPackage varchar2(255 char), unitPackageId varchar2(255 char), primary key (id));
create table intt_unitPackagePairState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_unitPackagesState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_unitState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_unstorageItem (warehouseItemId varchar2(255 char) not null, unwantedQty float, wantQty float, primary key (warehouseItemId));
create table intt_warehouse (id varchar2(255 char) not null, state varchar2(255 char), city varchar2(255 char), area varchar2(255 char), zip varchar2(255 char), phone varchar2(255 char), address varchar2(255 char), code varchar2(255 char), alias varchar2(255 char), primary key (id));
create table intt_warehouseItem (itemId varchar2(255 char) not null, bin varchar2(255 char), warehouse varchar2(255 char), job_id varchar2(255 char), order_id varchar2(255 char), primary key (itemId));
create table intt_warehouseState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_zone (id varchar2(255 char) not null, state varchar2(255 char), alias varchar2(255 char), primary key (id));
create table intt_zoneState (id varchar2(255 char) not null, description varchar2(255 char), code varchar2(255 char), primary key (id));
create table intt_zones_bin (binId varchar2(255 char) not null, zoneId varchar2(255 char) not null, indexId number(10,0) not null, primary key (binId, indexId));
create table intt_zones_material (materialId varchar2(255 char) not null, zoneId varchar2(255 char) not null, indexId number(10,0) not null, primary key (materialId, indexId));
CREATE TABLE INTT_OUTBOUNDASSIGNED (INTT_ID VARCHAR2(255 CHAR) NOT NULL, INTT_OUTORDERITEMID VARCHAR2(255 CHAR), INTT_STORAGEITEMID VARCHAR2(255 CHAR), INTT_ASSIGNEDQTY FLOAT, INTT_ISDELETE INT, PRIMARY KEY (INTT_ID));

alter table INTT_OUTBOUNDASSIGNED add CONSTRAINT FK9D725F786D278E6F FOREIGN KEY (INTT_STORAGEITEMID) REFERENCES INTT_STORAGEITEM;
alter table INTT_OUTBOUNDASSIGNED add CONSTRAINT FK9D725F7875FF532B FOREIGN KEY (INTT_OUTORDERITEMID) REFERENCES INTT_OUTBOUNDORDERITEM;
alter table intt_InboundRePick add constraint FKE655CD536E6BACD9 foreign key (warehouseItemId) references intt_warehouseItem;
alter table intt_InboundRePutAway add constraint FK7039382B6E6BACD9 foreign key (warehouseItemId) references intt_warehouseItem;
alter table intt_OutboundRePick add constraint FKABDF313E6E6BACD9 foreign key (warehouseItemId) references intt_warehouseItem;
alter table intt_OutboundRePutAway add constraint FKFF7BC8606E6BACD9 foreign key (warehouseItemId) references intt_warehouseItem;
alter table intt_PutAwayItem add constraint FK677540566E6BACD9 foreign key (warehouseItemId) references intt_warehouseItem;
alter table intt_bin add constraint FK22CA582DE5499753 foreign key (warehouseId) references intt_warehouse;
alter table intt_bin add constraint FK22CA582D6055A5D1 foreign key (buildingId) references intt_building;
alter table intt_bin add constraint FK22CA582DCAC54215 foreign key (columnId) references intt_column;
alter table intt_bin add constraint FK22CA582DC549226C foreign key (row_Id) references intt_row;
alter table intt_bin add constraint FK22CA582D5D1B67AD foreign key (tierId) references intt_tier;
alter table intt_bin add constraint FK22CA582D66A0C4A5 foreign key (floorId) references intt_floor;
alter table intt_bin add constraint FK22CA582DEC478A9 foreign key (state) references intt_binState;
alter table intt_building add constraint FKFB1A3F4EE5499753 foreign key (warehouseId) references intt_warehouse;
alter table intt_building add constraint FKFB1A3F4E9FCCC740 foreign key (state) references intt_buildingState;
alter table intt_checkingItem add constraint FKA1FFF7A76E6BACD9 foreign key (warehouseItemId) references intt_warehouseItem;
alter table intt_column add constraint FK9B155E70C549226C foreign key (row_id) references intt_row;
alter table intt_column add constraint FK9B155E70CDA6905E foreign key (state) references intt_columnState;
alter table intt_destroyedItem add constraint FK93D974726E6BACD9 foreign key (warehouseItemId) references intt_warehouseItem;
alter table intt_floor add constraint FK99CECDB26055A5D1 foreign key (buildingId) references intt_building;
alter table intt_floor add constraint FK99CECDB2A1FB9144 foreign key (state) references intt_floorState;
alter table intt_inboundOrderItem add constraint FK32AD6EA2C1A83D2F foreign key (orderItemId) references intt_orderItem;
alter table intt_invoice add constraint FK3D11B53B472DA09 foreign key (invoiveState) references intt_invoiceState;
alter table intt_item add constraint FK368404ADBBFD748C foreign key (invoice_id) references intt_invoice;
alter table intt_item add constraint FK368404ADF4C21A9C foreign key (material) references intt_material;
alter table intt_item add constraint FK368404ADD890CB41 foreign key (state) references intt_itemState;
alter table intt_item add constraint FK368404AD8021D1FD foreign key (intt_itemTypeId) references intt_itemType;
alter table intt_item add constraint FK368404ADC8E57956 foreign key (unitPackage) references intt_unitPackage;
alter table intt_itemType add constraint FK968FE987917B6BA0 foreign key (intt_itemTypeState) references intt_itemTypeState;
alter table intt_lastItems add constraint FK326FF970D26848C8 foreign key (mainItemId) references intt_item;
alter table intt_lastItems add constraint FK326FF9702A4FFBE5 foreign key (lastItemId) references intt_item;
alter table intt_logPickedItem add constraint FK64895BD6E6BACD9 foreign key (warehouseItemId) references intt_warehouseItem;
alter table intt_logStorageItem add constraint FKFDFA5F646E6BACD9 foreign key (warehouseItemId) references intt_warehouseItem;
alter table intt_material add constraint FK623391C128A089BE foreign key (shelflife) references intt_shelflife;
alter table intt_material add constraint FK623391C171F404AD foreign key (state) references intt_materialState;
alter table intt_nextItems add constraint FK2FCB333D26848C8 foreign key (mainItemId) references intt_item;
alter table intt_nextItems add constraint FK2FCB3336B5A7A82 foreign key (nextItemId) references intt_item;
alter table intt_order add constraint FK9A5030F49B2127D8 foreign key (owner) references intt_owner;
alter table intt_order add constraint FK9A5030F4642D2EF8 foreign key (warehouse) references intt_warehouse;
alter table intt_orderItem add constraint FKA44986274AEC31CF foreign key (itemId) references intt_item;
alter table intt_orderItem add constraint FKA449862712A6904C foreign key (warehouse_id) references intt_warehouse;
alter table intt_outboundOrderItem add constraint FKA4F00317C1A83D2F foreign key (orderItemId) references intt_orderItem;
alter table intt_ownerZone add constraint FKBCB55FA567B3C0C1 foreign key (zoneId) references intt_zone;
alter table intt_packingItem add constraint FK514EDB026E6BACD9 foreign key (warehouseItemId) references intt_warehouseItem;
alter table intt_pickedItem add constraint FK638725CD6E6BACD9 foreign key (warehouseItemId) references intt_warehouseItem;
alter table intt_pickingItem add constraint FKF39A63FA6E6BACD9 foreign key (warehouseItemId) references intt_warehouseItem;
alter table intt_rate add constraint FK3687D67A65191194 foreign key (state) references intt_rateState;
alter table intt_rates add constraint FK9A72F93959469629 foreign key (rateId) references intt_rate;
alter table intt_rates add constraint FK9A72F939203185B foreign key (binId) references intt_bin;
alter table intt_rates add constraint FK9A72F939CD7D79F7 foreign key (materialId) references intt_material;
alter table intt_row add constraint FK22CA950066A0C4A5 foreign key (floorId) references intt_floor;
alter table intt_row add constraint FK22CA9500D99847B6 foreign key (state) references intt_rowState;
alter table intt_shelflife add constraint FK26CE4ECC91695A56 foreign key (unit) references intt_unit;
alter table intt_shelflife add constraint FK26CE4ECCDFD8366A foreign key (state) references intt_shelflifeState;
alter table intt_storageItem add constraint FK488DD1546E6BACD9 foreign key (warehouseItemId) references intt_warehouseItem;
alter table intt_storageZone add constraint FK489579ED67B3C0C1 foreign key (zoneId) references intt_zone;
alter table intt_tier add constraint FK3688DB7CC549226C foreign key (row_id) references intt_row;
alter table intt_tier add constraint FK3688DB7CC95CDDD2 foreign key (state) references intt_tierState;
alter table intt_uncheckedItem add constraint FKA3703EC76E6BACD9 foreign key (warehouseItemId) references intt_warehouseItem;
alter table intt_unit add constraint FK3689631E3C09CB70 foreign key (state) references intt_unitState;
alter table intt_unitPackage add constraint FK81324B4891695A56 foreign key (unit) references intt_unit;
alter table intt_unitPackage add constraint FK81324B4820BA4A6E foreign key (state) references intt_unitPackagesState;
alter table intt_unitPackage add constraint FK81324B48CD7D79F7 foreign key (materialId) references intt_material;
alter table intt_unitPackagePair add constraint FKBD313E429186FDF1 foreign key (unitPackageId) references intt_unitPackage;
alter table intt_unitPackagePair add constraint FKBD313E421729B4 foreign key (state) references intt_unitPackagePairState;
alter table intt_unitPackagePair add constraint FKBD313E429777F046 foreign key (otherUnitPackage) references intt_unitPackage;
alter table intt_unstorageItem add constraint FK3884279B6E6BACD9 foreign key (warehouseItemId) references intt_warehouseItem;
alter table intt_warehouse add constraint FK4494A169671DFDED foreign key (state) references intt_warehouseState;
alter table intt_warehouseItem add constraint FKBD46B41C4AEC31CF foreign key (itemId) references intt_item;
alter table intt_warehouseItem add constraint FKBD46B41CFC6E3100 foreign key (bin) references intt_bin;
alter table intt_warehouseItem add constraint FKBD46B41C642D2EF8 foreign key (warehouse) references intt_warehouse;
alter table intt_zone add constraint FK368BAD4678279A48 foreign key (state) references intt_zoneState;
alter table intt_zones_bin add constraint FKDCACE9B567B3C0C1 foreign key (zoneId) references intt_zone;
alter table intt_zones_bin add constraint FKDCACE9B5203185B foreign key (binId) references intt_bin;
alter table intt_zones_material add constraint FKDC56B53967B3C0C1 foreign key (zoneId) references intt_zone;
alter table intt_zones_material add constraint FKDC56B539CD7D79F7 foreign key (materialId) references intt_material;
