--有用
  CREATE TABLE INTT_LOGSTOCKMOVEITEM
   (WAREHOUSEITEMID VARCHAR2(255 CHAR) NOT NULL , 
	INTT_FROMID VARCHAR2(255 CHAR), 
	 PRIMARY KEY (WAREHOUSEITEMID));

alter table INTT_LOGSTOCKMOVEITEM ADD CONSTRAINT FKB348AD707A8D0E7F FOREIGN KEY (INTT_FROMID)
	  REFERENCES INTT_STORAGEITEM;

alter table INTT_LOGSTOCKMOVEITEM ADD CONSTRAINT FKB348AD706E6BACD9 FOREIGN KEY (WAREHOUSEITEMID)
	  REFERENCES INTT_WAREHOUSEITEM;

 
