// 
package com.hhz.ump.entity.mes;

// Generated 2012-2-20 16:16:52 by Hibernate Tools 3.2.2.GA

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OrderBy;


/**
 * MesMeetingInfo generated by hbm2java
 */
@Entity
@Table(name = "MES_MEETING_INFO")
public class MesMeetingInfo implements java.io.Serializable {

	private String mesMeetingInfoId;
	private String mesTypeCd;
	private long mesYear;
	private long serialNo;
	private String subject;
	private String mesRoom;
	private Date fromDate;
	private Date toDate;
	private String participators;
	private String applicant;
	private String compere;
	private String recorder;
	private String attention;
	private Long partNum;
	private String relatedDept;
	private String mesVersion;
	private Date startDate;
	private Date applyDate;
	private String userCd;
	private String nodeCd;
	private Long approveLevel;
	private Long timeLimit;
	private String statusCd;
	private String attachFlg;
	private String reportUsers;
	private String ccUsers;
	private String remark;
	private String mainUsers;
	private String sumUserCd;
	private String mesTitle;
	private String creator;
	private String createdCenterCd;
	private String createdDeptCd;
	private String createdPositionCd;
	private Date createdDate;
	private String updator;
	private String updatedCenterCd;
	private String updatedDeptCd;
	private String updatedPositionCd;
	private Date updatedDate;
	private long recordVersion;
    private Long emailSendCnt;
    private Long sequenceNo;
    private Date lastSendDate;
    private Boolean isRst;
    private Date rstCompleteDate;
    private String rstSubject;
    private Short rstYear;
    private Long rstNo;
    private String rstAttachmentId;
    private List<MesMeetingPush> mesMeetingPushs = new ArrayList<MesMeetingPush>();
	private List<MesSummary> mesSummaries = new ArrayList<MesSummary>();
	private List<MesApproveNode> mesApproveNodes = new ArrayList<MesApproveNode>();
	private List<MesDelayInfo> mesDelayInfos = new ArrayList<MesDelayInfo>();
	private List<MesApproveHis> mesApproveHises = new ArrayList<MesApproveHis>();
	private List<MesRstResolution> mesRstResolutions = new ArrayList<MesRstResolution>();

	public MesMeetingInfo() {
	}

	public MesMeetingInfo(String mesMeetingInfoId, String mesTypeCd, long mesYear, long serialNo, String subject,
			String mesRoom, String participators, String compere, String statusCd, long recordVersion) {
		this.mesMeetingInfoId = mesMeetingInfoId;
		this.mesTypeCd = mesTypeCd;
		this.mesYear = mesYear;
		this.serialNo = serialNo;
		this.subject = subject;
		this.mesRoom = mesRoom;
		this.participators = participators;
		this.compere = compere;
		this.statusCd = statusCd;
		this.recordVersion = recordVersion;
	}

	public MesMeetingInfo(String mesMeetingInfoId, String mesTypeCd, long mesYear, long serialNo, String subject,
			String mesRoom, Date fromDate, Date toDate, String participators, String applicant, String compere,
			String recorder, String attention, Long partNum, String relatedDept, String mesVersion, Date startDate,
			Date applyDate, String userCd, String nodeCd, Long approveLevel, Long timeLimit, String statusCd,
			String attachFlg, String reportUsers, String remark, String mainUsers, String sumUserCd, String mesTitle,
			String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate,
			String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate,
			long recordVersion, List<MesSummary> mesSummaries, List<MesApproveNode> mesApproveNodes,
			List<MesDelayInfo> mesDelayInfos, List<MesApproveHis> mesApproveHises) {
		this.mesMeetingInfoId = mesMeetingInfoId;
		this.mesTypeCd = mesTypeCd;
		this.mesYear = mesYear;
		this.serialNo = serialNo;
		this.subject = subject;
		this.mesRoom = mesRoom;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.participators = participators;
		this.applicant = applicant;
		this.compere = compere;
		this.recorder = recorder;
		this.attention = attention;
		this.partNum = partNum;
		this.relatedDept = relatedDept;
		this.mesVersion = mesVersion;
		this.startDate = startDate;
		this.applyDate = applyDate;
		this.userCd = userCd;
		this.nodeCd = nodeCd;
		this.approveLevel = approveLevel;
		this.timeLimit = timeLimit;
		this.statusCd = statusCd;
		this.attachFlg = attachFlg;
		this.reportUsers = reportUsers;
		this.remark = remark;
		this.mainUsers = mainUsers;
		this.sumUserCd = sumUserCd;
		this.mesTitle = mesTitle;
		this.creator = creator;
		this.createdCenterCd = createdCenterCd;
		this.createdDeptCd = createdDeptCd;
		this.createdPositionCd = createdPositionCd;
		this.createdDate = createdDate;
		this.updator = updator;
		this.updatedCenterCd = updatedCenterCd;
		this.updatedDeptCd = updatedDeptCd;
		this.updatedPositionCd = updatedPositionCd;
		this.updatedDate = updatedDate;
		this.recordVersion = recordVersion;
		this.mesSummaries = mesSummaries;
		this.mesApproveNodes = mesApproveNodes;
		this.mesDelayInfos = mesDelayInfos;
		this.mesApproveHises = mesApproveHises;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	@Column(name = "MES_MEETING_INFO_ID", unique = true, nullable = false, length = 50)
	public String getMesMeetingInfoId() {
		return this.mesMeetingInfoId;
	}

	public void setMesMeetingInfoId(String mesMeetingInfoId) {
		this.mesMeetingInfoId = mesMeetingInfoId;
	}

	@Column(name = "MES_TYPE_CD", nullable = false, length = 20)
	public String getMesTypeCd() {
		return this.mesTypeCd;
	}

	public void setMesTypeCd(String mesTypeCd) {
		this.mesTypeCd = mesTypeCd;
	}

	@Column(name = "MES_YEAR", nullable = false, precision = 10, scale = 0)
	public long getMesYear() {
		return this.mesYear;
	}

	public void setMesYear(long mesYear) {
		this.mesYear = mesYear;
	}

	@Column(name = "SERIAL_NO", nullable = false, precision = 10, scale = 0)
	public long getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(long serialNo) {
		this.serialNo = serialNo;
	}

	@Column(name = "SUBJECT", nullable = false, length = 200)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "MES_ROOM", nullable = false, length = 100)
	public String getMesRoom() {
		return this.mesRoom;
	}

	public void setMesRoom(String mesRoom) {
		this.mesRoom = mesRoom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FROM_DATE", length = 7)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TO_DATE", length = 7)
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	@Column(name = "PARTICIPATORS", nullable = false, length = 2000)
	public String getParticipators() {
		return this.participators;
	}

	public void setParticipators(String participators) {
		this.participators = participators;
	}

	@Column(name = "APPLICANT", length = 20)
	public String getApplicant() {
		return this.applicant;
	}

	public void setApplicant(String applicant) {
		this.applicant = applicant;
	}

	@Column(name = "COMPERE", nullable = false, length = 20)
	public String getCompere() {
		return this.compere;
	}

	public void setCompere(String compere) {
		this.compere = compere;
	}

	@Column(name = "RECORDER", length = 20)
	public String getRecorder() {
		return this.recorder;
	}

	public void setRecorder(String recorder) {
		this.recorder = recorder;
	}

	@Column(name = "ATTENTION", length = 2000)
	public String getAttention() {
		return this.attention;
	}

	public void setAttention(String attention) {
		this.attention = attention;
	}

	@Column(name = "PART_NUM", precision = 10, scale = 0)
	public Long getPartNum() {
		return this.partNum;
	}

	public void setPartNum(Long partNum) {
		this.partNum = partNum;
	}

	@Column(name = "RELATED_DEPT", length = 200)
	public String getRelatedDept() {
		return this.relatedDept;
	}

	public void setRelatedDept(String relatedDept) {
		this.relatedDept = relatedDept;
	}

	@Column(name = "MES_VERSION", length = 50)
	public String getMesVersion() {
		return this.mesVersion;
	}

	public void setMesVersion(String mesVersion) {
		this.mesVersion = mesVersion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "APPLY_DATE", length = 7)
	public Date getApplyDate() {
		return this.applyDate;
	}

	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

	@Column(name = "USER_CD", length = 20)
	public String getUserCd() {
		return this.userCd;
	}

	public void setUserCd(String userCd) {
		this.userCd = userCd;
	}

	@Column(name = "NODE_CD", length = 20)
	public String getNodeCd() {
		return this.nodeCd;
	}

	public void setNodeCd(String nodeCd) {
		this.nodeCd = nodeCd;
	}

	@Column(name = "APPROVE_LEVEL", precision = 10, scale = 0)
	public Long getApproveLevel() {
		return this.approveLevel;
	}

	public void setApproveLevel(Long approveLevel) {
		this.approveLevel = approveLevel;
	}

	@Column(name = "TIME_LIMIT", precision = 10, scale = 0)
	public Long getTimeLimit() {
		return this.timeLimit;
	}

	public void setTimeLimit(Long timeLimit) {
		this.timeLimit = timeLimit;
	}

	@Column(name = "STATUS_CD", nullable = false, length = 20)
	public String getStatusCd() {
		return this.statusCd;
	}

	public void setStatusCd(String statusCd) {
		this.statusCd = statusCd;
	}

	@Column(name = "ATTACH_FLG", length = 1)
	public String getAttachFlg() {
		return this.attachFlg;
	}

	public void setAttachFlg(String attachFlg) {
		this.attachFlg = attachFlg;
	}

	@Column(name = "REPORT_USERS", length = 100)
	public String getReportUsers() {
		return this.reportUsers;
	}

	public void setReportUsers(String reportUsers) {
		this.reportUsers = reportUsers;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "MAIN_USERS", length = 100)
	public String getMainUsers() {
		return this.mainUsers;
	}

	public void setMainUsers(String mainUsers) {
		this.mainUsers = mainUsers;
	}

	@Column(name = "SUM_USER_CD", length = 20)
	public String getSumUserCd() {
		return this.sumUserCd;
	}

	public void setSumUserCd(String sumUserCd) {
		this.sumUserCd = sumUserCd;
	}

	@Column(name = "MES_TITLE", length = 200)
	public String getMesTitle() {
		return this.mesTitle;
	}

	public void setMesTitle(String mesTitle) {
		this.mesTitle = mesTitle;
	}

	@Column(name = "CREATOR", length = 20)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATED_CENTER_CD", length = 20)
	public String getCreatedCenterCd() {
		return this.createdCenterCd;
	}

	public void setCreatedCenterCd(String createdCenterCd) {
		this.createdCenterCd = createdCenterCd;
	}

	@Column(name = "CREATED_DEPT_CD", length = 20)
	public String getCreatedDeptCd() {
		return this.createdDeptCd;
	}

	public void setCreatedDeptCd(String createdDeptCd) {
		this.createdDeptCd = createdDeptCd;
	}

	@Column(name = "CREATED_POSITION_CD", length = 20)
	public String getCreatedPositionCd() {
		return this.createdPositionCd;
	}

	public void setCreatedPositionCd(String createdPositionCd) {
		this.createdPositionCd = createdPositionCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATOR", length = 20)
	public String getUpdator() {
		return this.updator;
	}

	public void setUpdator(String updator) {
		this.updator = updator;
	}

	@Column(name = "UPDATED_CENTER_CD", length = 20)
	public String getUpdatedCenterCd() {
		return this.updatedCenterCd;
	}

	public void setUpdatedCenterCd(String updatedCenterCd) {
		this.updatedCenterCd = updatedCenterCd;
	}

	@Column(name = "UPDATED_DEPT_CD", length = 20)
	public String getUpdatedDeptCd() {
		return this.updatedDeptCd;
	}

	public void setUpdatedDeptCd(String updatedDeptCd) {
		this.updatedDeptCd = updatedDeptCd;
	}

	@Column(name = "UPDATED_POSITION_CD", length = 20)
	public String getUpdatedPositionCd() {
		return this.updatedPositionCd;
	}

	public void setUpdatedPositionCd(String updatedPositionCd) {
		this.updatedPositionCd = updatedPositionCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 7)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "RECORD_VERSION", nullable = false, precision = 10, scale = 0)
	@Version
	public long getRecordVersion() {
		return this.recordVersion;
	}

	public void setRecordVersion(long recordVersion) {
		this.recordVersion = recordVersion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mesMeetingInfo")
	@BatchSize(size = 10)
	@OrderBy(clause = "CREATED_DATE ASC")
	public List<MesSummary> getMesSummaries() {
		return this.mesSummaries;
	}

	public void setMesSummaries(List<MesSummary> mesSummaries) {
		this.mesSummaries = mesSummaries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mesMeetingInfo")
	@BatchSize(size = 10)
	@OrderBy(clause = "APPROVE_LEVEL ASC")
	public List<MesApproveNode> getMesApproveNodes() {
		return this.mesApproveNodes;
	}

	public void setMesApproveNodes(List<MesApproveNode> mesApproveNodes) {
		this.mesApproveNodes = mesApproveNodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mesMeetingInfo")
	@BatchSize(size = 10)
	public List<MesDelayInfo> getMesDelayInfos() {
		return this.mesDelayInfos;
	}

	public void setMesDelayInfos(List<MesDelayInfo> mesDelayInfos) {
		this.mesDelayInfos = mesDelayInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mesMeetingInfo")
	@BatchSize(size = 10)
	@OrderBy(clause = "CREATED_DATE ASC")
	public List<MesApproveHis> getMesApproveHises() {
		return this.mesApproveHises;
	}

	public void setMesApproveHises(List<MesApproveHis> mesApproveHises) {
		this.mesApproveHises = mesApproveHises;
	}

	@Column(name = "CC_USERS", length = 200)
	public String getCcUsers() {
		return ccUsers;
	}

	public void setCcUsers(String ccUsers) {
		this.ccUsers = ccUsers;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="mesMeetingInfo")
    @BatchSize(size=10)
	@OrderBy(clause = "CREATED_DATE ASC")
public List<MesRstResolution> getMesRstResolutions() {
        return this.mesRstResolutions;
    }
    
    public void setMesRstResolutions(List<MesRstResolution> mesRstResolutions) {
        this.mesRstResolutions = mesRstResolutions;
    }

    @Column(name="EMAIL_SEND_CNT", precision=10, scale=0)
    public Long getEmailSendCnt() {
        return this.emailSendCnt;
    }
    
    public void setEmailSendCnt(Long emailSendCnt) {
        this.emailSendCnt = emailSendCnt;
    }
    
    @Column(name="SEQUENCE_NO", precision=10, scale=0)
    public Long getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Long sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_SEND_DATE", length=7)
    public Date getLastSendDate() {
        return this.lastSendDate;
    }
    
    public void setLastSendDate(Date lastSendDate) {
        this.lastSendDate = lastSendDate;
    }

    
    @Column(name="IS_RST", precision=1, scale=0)
    public Boolean getIsRst() {
        return this.isRst;
    }
    
    public void setIsRst(Boolean isRst) {
        this.isRst = isRst;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RST_COMPLETE_DATE", length=7)
    public Date getRstCompleteDate() {
        return this.rstCompleteDate;
    }
    
    public void setRstCompleteDate(Date rstCompleteDate) {
        this.rstCompleteDate = rstCompleteDate;
    }
    @OneToMany(fetch=FetchType.LAZY, mappedBy="mesMeetingInfo")
    @BatchSize(size=10)
public List<MesMeetingPush> getMesMeetingPushs() {
        return this.mesMeetingPushs;
    }
    
    public void setMesMeetingPushs(List<MesMeetingPush> mesMeetingPushs) {
        this.mesMeetingPushs = mesMeetingPushs;
    }
    
    @Column(name="RST_SUBJECT", length=200)
    public String getRstSubject() {
        return this.rstSubject;
    }
    
    public void setRstSubject(String rstSubject) {
        this.rstSubject = rstSubject;
    }
    
    @Column(name="RST_YEAR", precision=4, scale=0)
    public Short getRstYear() {
        return this.rstYear;
    }
    
    public void setRstYear(Short rstYear) {
        this.rstYear = rstYear;
    }
    
    @Column(name="RST_NO", precision=10, scale=0)
    public Long getRstNo() {
        return this.rstNo;
    }
    
    public void setRstNo(Long rstNo) {
        this.rstNo = rstNo;
    }
    
    @Column(name="RST_ATTACHMENT_ID", length=50)
    public String getRstAttachmentId() {
        return this.rstAttachmentId;
    }
    
    public void setRstAttachmentId(String rstAttachmentId) {
        this.rstAttachmentId = rstAttachmentId;
    }
}
