// 
package com.hhz.ump.entity.bis;
// Generated 2011-8-3 22:32:28 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * BisContMulti generated by hbm2java
 */
@Entity
@Table(name="BIS_CONT_MULTI"
    
)
public class BisContMulti  implements java.io.Serializable {


     private String bisContMultiId;
     private BisCont bisCont;
     private String paymentTime;
     private String paymentModeCd;
     private String renterName;
     private String operationProjectCd;
     private String operationArea;
     private BigDecimal contPromiseBond;
     private BigDecimal receivedBond;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;

    public BisContMulti() {
    }

	
    public BisContMulti(String bisContMultiId, BisCont bisCont, long recordVersion) {
        this.bisContMultiId = bisContMultiId;
        this.bisCont = bisCont;
        this.recordVersion = recordVersion;
    }
    public BisContMulti(String bisContMultiId, BisCont bisCont, String paymentTime, String paymentModeCd, String renterName, String operationProjectCd, String operationArea, BigDecimal contPromiseBond, BigDecimal receivedBond, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion) {
       this.bisContMultiId = bisContMultiId;
       this.bisCont = bisCont;
       this.paymentTime = paymentTime;
       this.paymentModeCd = paymentModeCd;
       this.renterName = renterName;
       this.operationProjectCd = operationProjectCd;
       this.operationArea = operationArea;
       this.contPromiseBond = contPromiseBond;
       this.receivedBond = receivedBond;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_CONT_MULTI_ID", unique=true, nullable=false, length=50)
    public String getBisContMultiId() {
        return this.bisContMultiId;
    }
    
    public void setBisContMultiId(String bisContMultiId) {
        this.bisContMultiId = bisContMultiId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIS_CONT_ID", nullable=false)
    public BisCont getBisCont() {
        return this.bisCont;
    }
    
    public void setBisCont(BisCont bisCont) {
        this.bisCont = bisCont;
    }

    @Column(name="PAYMENT_TIME", length=100)
    public String getPaymentTime() {
        return this.paymentTime;
    }
    
    public void setPaymentTime(String paymentTime) {
        this.paymentTime = paymentTime;
    }
    
    @Column(name="PAYMENT_MODE_CD", length=20)
    public String getPaymentModeCd() {
        return this.paymentModeCd;
    }
    
    public void setPaymentModeCd(String paymentModeCd) {
        this.paymentModeCd = paymentModeCd;
    }
    
    @Column(name="RENTER_NAME", length=100)
    public String getRenterName() {
        return this.renterName;
    }
    
    public void setRenterName(String renterName) {
        this.renterName = renterName;
    }
    
    @Column(name="OPERATION_PROJECT_CD", length=20)
    public String getOperationProjectCd() {
        return this.operationProjectCd;
    }
    
    public void setOperationProjectCd(String operationProjectCd) {
        this.operationProjectCd = operationProjectCd;
    }
    
    @Column(name="OPERATION_AREA", length=200)
    public String getOperationArea() {
        return this.operationArea;
    }
    
    public void setOperationArea(String operationArea) {
        this.operationArea = operationArea;
    }
    
    @Column(name="CONT_PROMISE_BOND", precision=10)
    public BigDecimal getContPromiseBond() {
        return this.contPromiseBond;
    }
    
    public void setContPromiseBond(BigDecimal contPromiseBond) {
        this.contPromiseBond = contPromiseBond;
    }
    
    @Column(name="RECEIVED_BOND", precision=10)
    public BigDecimal getReceivedBond() {
        return this.receivedBond;
    }
    
    public void setReceivedBond(BigDecimal receivedBond) {
        this.receivedBond = receivedBond;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }




}


