// 
package com.hhz.ump.entity.bis;
// Generated 2012-3-30 15:18:24 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.BatchSize;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BisCollectionRate generated by hbm2java
 */
@Entity
@Table(name="BIS_COLLECTION_RATE"
    
)
public class BisCollectionRate  implements java.io.Serializable {


     private String bisCollectionRateId;
     private String bisProjectId;
     private String commercialCd;
     private String propManaFeeType;
     private BigDecimal monthMoneyMust;
     private BigDecimal monthMoneyFact;
     private BigDecimal monthMoneyRate;
     private BigDecimal yearMoneyMust;
     private BigDecimal yearMoneyFact;
     private BigDecimal yearMoneyRate;
     private BigDecimal beforeOverdue;
     private BigDecimal yearOverdue;
     private BigDecimal overdueRate;
     private String collectionType;
     private String statusCd;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;

    public BisCollectionRate() {
    }

	
    public BisCollectionRate(String bisCollectionRateId, long recordVersion) {
        this.bisCollectionRateId = bisCollectionRateId;
        this.recordVersion = recordVersion;
    }
    public BisCollectionRate(String bisCollectionRateId, String bisProjectId, String commercialCd, String propManaFeeType, BigDecimal monthMoneyMust, BigDecimal monthMoneyFact, BigDecimal monthMoneyRate, BigDecimal yearMoneyMust, BigDecimal yearMoneyFact, BigDecimal yearMoneyRate, BigDecimal beforeOverdue, BigDecimal yearOverdue, BigDecimal overdueRate, String collectionType, String statusCd, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion) {
       this.bisCollectionRateId = bisCollectionRateId;
       this.bisProjectId = bisProjectId;
       this.commercialCd = commercialCd;
       this.propManaFeeType = propManaFeeType;
       this.monthMoneyMust = monthMoneyMust;
       this.monthMoneyFact = monthMoneyFact;
       this.monthMoneyRate = monthMoneyRate;
       this.yearMoneyMust = yearMoneyMust;
       this.yearMoneyFact = yearMoneyFact;
       this.yearMoneyRate = yearMoneyRate;
       this.beforeOverdue = beforeOverdue;
       this.yearOverdue = yearOverdue;
       this.overdueRate = overdueRate;
       this.collectionType = collectionType;
       this.statusCd = statusCd;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_COLLECTION_RATE_ID", unique=true, nullable=false, length=50)
    public String getBisCollectionRateId() {
        return this.bisCollectionRateId;
    }
    
    public void setBisCollectionRateId(String bisCollectionRateId) {
        this.bisCollectionRateId = bisCollectionRateId;
    }
    
    @Column(name="BIS_PROJECT_ID", length=50)
    public String getBisProjectId() {
        return this.bisProjectId;
    }
    
    public void setBisProjectId(String bisProjectId) {
        this.bisProjectId = bisProjectId;
    }
    
    @Column(name="COMMERCIAL_CD", length=2)
    public String getCommercialCd() {
        return this.commercialCd;
    }
    
    public void setCommercialCd(String commercialCd) {
        this.commercialCd = commercialCd;
    }
    
    @Column(name="PROP_MANA_FEE_TYPE", length=2)
    public String getPropManaFeeType() {
        return this.propManaFeeType;
    }
    
    public void setPropManaFeeType(String propManaFeeType) {
        this.propManaFeeType = propManaFeeType;
    }
    
    @Column(name="MONTH_MONEY_MUST", precision=14)
    public BigDecimal getMonthMoneyMust() {
        return this.monthMoneyMust;
    }
    
    public void setMonthMoneyMust(BigDecimal monthMoneyMust) {
        this.monthMoneyMust = monthMoneyMust;
    }
    
    @Column(name="MONTH_MONEY_FACT", precision=14)
    public BigDecimal getMonthMoneyFact() {
        return this.monthMoneyFact;
    }
    
    public void setMonthMoneyFact(BigDecimal monthMoneyFact) {
        this.monthMoneyFact = monthMoneyFact;
    }
    
    @Column(name="MONTH_MONEY_RATE", precision=10)
    public BigDecimal getMonthMoneyRate() {
        return this.monthMoneyRate;
    }
    
    public void setMonthMoneyRate(BigDecimal monthMoneyRate) {
        this.monthMoneyRate = monthMoneyRate;
    }
    
    @Column(name="YEAR_MONEY_MUST", precision=14)
    public BigDecimal getYearMoneyMust() {
        return this.yearMoneyMust;
    }
    
    public void setYearMoneyMust(BigDecimal yearMoneyMust) {
        this.yearMoneyMust = yearMoneyMust;
    }
    
    @Column(name="YEAR_MONEY_FACT", precision=14)
    public BigDecimal getYearMoneyFact() {
        return this.yearMoneyFact;
    }
    
    public void setYearMoneyFact(BigDecimal yearMoneyFact) {
        this.yearMoneyFact = yearMoneyFact;
    }
    
    @Column(name="YEAR_MONEY_RATE", precision=10)
    public BigDecimal getYearMoneyRate() {
        return this.yearMoneyRate;
    }
    
    public void setYearMoneyRate(BigDecimal yearMoneyRate) {
        this.yearMoneyRate = yearMoneyRate;
    }
    
    @Column(name="BEFORE_OVERDUE", precision=14)
    public BigDecimal getBeforeOverdue() {
        return this.beforeOverdue;
    }
    
    public void setBeforeOverdue(BigDecimal beforeOverdue) {
        this.beforeOverdue = beforeOverdue;
    }
    
    @Column(name="YEAR_OVERDUE", precision=14)
    public BigDecimal getYearOverdue() {
        return this.yearOverdue;
    }
    
    public void setYearOverdue(BigDecimal yearOverdue) {
        this.yearOverdue = yearOverdue;
    }
    
    @Column(name="OVERDUE_RATE", precision=10)
    public BigDecimal getOverdueRate() {
        return this.overdueRate;
    }
    
    public void setOverdueRate(BigDecimal overdueRate) {
        this.overdueRate = overdueRate;
    }
    
    @Column(name="COLLECTION_TYPE", length=2)
    public String getCollectionType() {
        return this.collectionType;
    }
    
    public void setCollectionType(String collectionType) {
        this.collectionType = collectionType;
    }
    
    @Column(name="STATUS_CD", length=2)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }




}


