// 
package com.hhz.ump.entity.bis;
// Generated 2011-8-3 22:32:28 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * BisCont generated by hbm2java
 */
@Entity
@Table(name="BIS_CONT"
    
)
public class BisCont  implements java.io.Serializable {


     private String bisContId;
     private String contNo;
     private String bisTenantId;
     private String bisProjectId;
     private String contName;
     private String bisPeople;
     private String brand;
     private String partyA;
     private String partyB;
     private String partyC;
     private String partyD;
     private String connAddr;
     private String connTel;
     private String connPeople;
     private String buildingName;
     private Date rentDate;
     private Date contStartDate;
     private Date contEndDate;
     private String coopWayCd;
     private String contBigTypeCd;
     private String contSmallTypeCd;
     private BigDecimal contMoney;
     private Date signDate;
     private String contContent;
     private String checkUserCd;
     private Date checkDate;
     private String attachFlg;
     private boolean activeBl;
     private String statusCd;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private Date contToFailDate;
     private String chargerTypeArr;
     private Boolean updateBl;
     private String connFax;
     private String connAccountNo;
     private String equityNature;
     private BigDecimal square;
     private BigDecimal innerSquare;
     private BigDecimal rentSquare;
     private String layoutCd;
     private String rentYears;
     private String manageCd;
     private String owner;
     private String changeUser;
     private Date changeDate;
     private String tempHisId;
     private String resApproveInfoId;
     private String invalidBy;
     private String contApproval;
     private String contApprovalId;
     private String approvalAttachFlg;
     private List<BisMultiContRel> bisMultiContRels = new ArrayList<BisMultiContRel>();
     private List<BisContShopProp> bisContShopProps = new ArrayList<BisContShopProp>();
     private List<BisFlatContRel> bisFlatContRels = new ArrayList<BisFlatContRel>();
     private List<BisContShopRent> bisContShopRents = new ArrayList<BisContShopRent>();
     private List<BisContFlatProp> bisContFlatProps = new ArrayList<BisContFlatProp>();
     private List<BisContCredit> bisContCredits = new ArrayList<BisContCredit>();
     private List<BisMust> bisMusts = new ArrayList<BisMust>();
     private List<BisContShopBack> bisContShopBacks = new ArrayList<BisContShopBack>();
     private List<BisStoreContRel> bisStoreContRels = new ArrayList<BisStoreContRel>();
     private List<BisContMulti> bisContMultis = new ArrayList<BisContMulti>();
     private List<BisContAdditional> bisContAdditionals = new ArrayList<BisContAdditional>();
     private List<BisContShopEntr> bisContShopEntrs = new ArrayList<BisContShopEntr>();
     private List<BisMustFormula> bisMustFormulas = new ArrayList<BisMustFormula>();
     private List<BisMustRent> bisMustRents = new ArrayList<BisMustRent>();

    public BisCont() {
    }

	
    public BisCont(String bisContId, String contNo, String bisProjectId, Date contStartDate, Date contEndDate, boolean activeBl, long recordVersion) {
        this.bisContId = bisContId;
        this.contNo = contNo;
        this.bisProjectId = bisProjectId;
        this.contStartDate = contStartDate;
        this.contEndDate = contEndDate;
        this.activeBl = activeBl;
        this.recordVersion = recordVersion;
    }
    public BisCont(String bisContId, String contNo, String bisTenantId, String bisProjectId, String contName, String bisPeople, String brand, String partyA, String partyB, String partyC, String partyD, String connAddr, String connTel, String connPeople, String buildingName, Date rentDate, Date contStartDate, Date contEndDate, String coopWayCd, String contBigTypeCd, String contSmallTypeCd, BigDecimal contMoney, Date signDate, String contContent, String checkUserCd, Date checkDate, String attachFlg, boolean activeBl, String statusCd, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, Date contToFailDate, String chargerTypeArr, Boolean updateBl, String connFax, String connAccountNo, String equityNature, BigDecimal square, BigDecimal innerSquare, BigDecimal rentSquare, String layoutCd, String rentYears, List<BisMultiContRel> bisMultiContRels, List<BisContShopProp> bisContShopProps, List<BisFlatContRel> bisFlatContRels, List<BisContShopRent> bisContShopRents, List<BisContFlatProp> bisContFlatProps, List<BisContCredit> bisContCredits, List<BisMust> bisMusts, List<BisContShopBack> bisContShopBacks, List<BisStoreContRel> bisStoreContRels, List<BisContMulti> bisContMultis, List<BisContAdditional> bisContAdditionals, List<BisContShopEntr> bisContShopEntrs) {
       this.bisContId = bisContId;
       this.contNo = contNo;
       this.bisTenantId = bisTenantId;
       this.bisProjectId = bisProjectId;
       this.contName = contName;
       this.bisPeople = bisPeople;
       this.brand = brand;
       this.partyA = partyA;
       this.partyB = partyB;
       this.partyC = partyC;
       this.partyD = partyD;
       this.connAddr = connAddr;
       this.connTel = connTel;
       this.connPeople = connPeople;
       this.buildingName = buildingName;
       this.rentDate = rentDate;
       this.contStartDate = contStartDate;
       this.contEndDate = contEndDate;
       this.coopWayCd = coopWayCd;
       this.contBigTypeCd = contBigTypeCd;
       this.contSmallTypeCd = contSmallTypeCd;
       this.contMoney = contMoney;
       this.signDate = signDate;
       this.contContent = contContent;
       this.checkUserCd = checkUserCd;
       this.checkDate = checkDate;
       this.attachFlg = attachFlg;
       this.activeBl = activeBl;
       this.statusCd = statusCd;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.contToFailDate = contToFailDate;
       this.chargerTypeArr = chargerTypeArr;
       this.updateBl = updateBl;
       this.connFax = connFax;
       this.connAccountNo = connAccountNo;
       this.equityNature = equityNature;
       this.square = square;
       this.innerSquare = innerSquare;
       this.rentSquare = rentSquare;
       this.layoutCd = layoutCd;
       this.rentYears = rentYears;
       this.bisMultiContRels = bisMultiContRels;
       this.bisContShopProps = bisContShopProps;
       this.bisFlatContRels = bisFlatContRels;
       this.bisContShopRents = bisContShopRents;
       this.bisContFlatProps = bisContFlatProps;
       this.bisContCredits = bisContCredits;
       this.bisMusts = bisMusts;
       this.bisContShopBacks = bisContShopBacks;
       this.bisStoreContRels = bisStoreContRels;
       this.bisContMultis = bisContMultis;
       this.bisContAdditionals = bisContAdditionals;
       this.bisContShopEntrs = bisContShopEntrs;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_CONT_ID", unique=true, nullable=false, length=50)
    public String getBisContId() {
        return this.bisContId;
    }
    
    public void setBisContId(String bisContId) {
        this.bisContId = bisContId;
    }
    
    @Column(name="CONT_NO", nullable=false, length=100)
    public String getContNo() {
        return this.contNo;
    }
    
    public void setContNo(String contNo) {
        this.contNo = contNo;
    }
    
    @Column(name="BIS_TENANT_ID", length=50)
    public String getBisTenantId() {
        return this.bisTenantId;
    }
    
    public void setBisTenantId(String bisTenantId) {
        this.bisTenantId = bisTenantId;
    }
    
    @Column(name="BIS_PROJECT_ID", nullable=false, length=50)
    public String getBisProjectId() {
        return this.bisProjectId;
    }
    
    public void setBisProjectId(String bisProjectId) {
        this.bisProjectId = bisProjectId;
    }
    
    @Column(name="CONT_NAME", length=300)
    public String getContName() {
        return this.contName;
    }
    
    public void setContName(String contName) {
        this.contName = contName;
    }
    
    @Column(name="BIS_PEOPLE", length=100)
    public String getBisPeople() {
        return this.bisPeople;
    }
    
    public void setBisPeople(String bisPeople) {
        this.bisPeople = bisPeople;
    }
    
    @Column(name="BRAND", length=300)
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    
    @Column(name="PARTY_A", length=100)
    public String getPartyA() {
        return this.partyA;
    }
    
    public void setPartyA(String partyA) {
        this.partyA = partyA;
    }
    
    @Column(name="PARTY_B", length=100)
    public String getPartyB() {
        return this.partyB;
    }
    
    public void setPartyB(String partyB) {
        this.partyB = partyB;
    }
    
    @Column(name="PARTY_C", length=100)
    public String getPartyC() {
        return this.partyC;
    }
    
    public void setPartyC(String partyC) {
        this.partyC = partyC;
    }
    
    @Column(name="PARTY_D", length=100)
    public String getPartyD() {
        return this.partyD;
    }
    
    public void setPartyD(String partyD) {
        this.partyD = partyD;
    }
    
    @Column(name="CONN_ADDR", length=1000)
    public String getConnAddr() {
        return this.connAddr;
    }
    
    public void setConnAddr(String connAddr) {
        this.connAddr = connAddr;
    }
    
    @Column(name="CONN_TEL", length=300)
    public String getConnTel() {
        return this.connTel;
    }
    
    public void setConnTel(String connTel) {
        this.connTel = connTel;
    }
    
    @Column(name="CONN_PEOPLE", length=100)
    public String getConnPeople() {
        return this.connPeople;
    }
    
    public void setConnPeople(String connPeople) {
        this.connPeople = connPeople;
    }
    
    @Column(name="BUILDING_NAME", length=300)
    public String getBuildingName() {
        return this.buildingName;
    }
    
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RENT_DATE", length=7)
    public Date getRentDate() {
        return this.rentDate;
    }
    
    public void setRentDate(Date rentDate) {
        this.rentDate = rentDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CONT_START_DATE", nullable=false, length=7)
    public Date getContStartDate() {
        return this.contStartDate;
    }
    
    public void setContStartDate(Date contStartDate) {
        this.contStartDate = contStartDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CONT_END_DATE", length=7)
    public Date getContEndDate() {
        return this.contEndDate;
    }
    
    public void setContEndDate(Date contEndDate) {
        this.contEndDate = contEndDate;
    }
    
    @Column(name="COOP_WAY_CD", length=20)
    public String getCoopWayCd() {
        return this.coopWayCd;
    }
    
    public void setCoopWayCd(String coopWayCd) {
        this.coopWayCd = coopWayCd;
    }
    
    @Column(name="CONT_BIG_TYPE_CD", length=20)
    public String getContBigTypeCd() {
        return this.contBigTypeCd;
    }
    
    public void setContBigTypeCd(String contBigTypeCd) {
        this.contBigTypeCd = contBigTypeCd;
    }
    
    @Column(name="CONT_SMALL_TYPE_CD", length=20)
    public String getContSmallTypeCd() {
        return this.contSmallTypeCd;
    }
    
    public void setContSmallTypeCd(String contSmallTypeCd) {
        this.contSmallTypeCd = contSmallTypeCd;
    }
    
    @Column(name="CONT_MONEY", precision=10)
    public BigDecimal getContMoney() {
        return this.contMoney;
    }
    
    public void setContMoney(BigDecimal contMoney) {
        this.contMoney = contMoney;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SIGN_DATE", length=7)
    public Date getSignDate() {
        return this.signDate;
    }
    
    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }
    
    @Column(name="CONT_CONTENT", length=4000)
    public String getContContent() {
        return this.contContent;
    }
    
    public void setContContent(String contContent) {
        this.contContent = contContent;
    }
    
    @Column(name="CHECK_USER_CD", length=20)
    public String getCheckUserCd() {
        return this.checkUserCd;
    }
    
    public void setCheckUserCd(String checkUserCd) {
        this.checkUserCd = checkUserCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CHECK_DATE", length=7)
    public Date getCheckDate() {
        return this.checkDate;
    }
    
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }
    
    @Column(name="ATTACH_FLG", length=1)
    public String getAttachFlg() {
        return this.attachFlg;
    }
    
    public void setAttachFlg(String attachFlg) {
        this.attachFlg = attachFlg;
    }
    
    @Column(name="ACTIVE_BL", nullable=false, precision=1, scale=0)
    public boolean isActiveBl() {
        return this.activeBl;
    }
    
    public void setActiveBl(boolean activeBl) {
        this.activeBl = activeBl;
    }
    
    @Column(name="STATUS_CD", length=20)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CONT_TO_FAIL_DATE", length=7)
    public Date getContToFailDate() {
        return this.contToFailDate;
    }
    
    public void setContToFailDate(Date contToFailDate) {
        this.contToFailDate = contToFailDate;
    }
    
    @Column(name="CHARGER_TYPE_ARR", length=100)
    public String getChargerTypeArr() {
        return this.chargerTypeArr;
    }
    
    public void setChargerTypeArr(String chargerTypeArr) {
        this.chargerTypeArr = chargerTypeArr;
    }
    
    @Column(name="UPDATE_BL", precision=1, scale=0)
    public Boolean getUpdateBl() {
        return this.updateBl;
    }
    
    public void setUpdateBl(Boolean updateBl) {
        this.updateBl = updateBl;
    }
    
    @Column(name="CONN_FAX", length=100)
    public String getConnFax() {
        return this.connFax;
    }
    
    public void setConnFax(String connFax) {
        this.connFax = connFax;
    }
    
    @Column(name="CONN_ACCOUNT_NO", length=100)
    public String getConnAccountNo() {
        return this.connAccountNo;
    }
    
    public void setConnAccountNo(String connAccountNo) {
        this.connAccountNo = connAccountNo;
    }
    
    @Column(name="EQUITY_NATURE", length=100)
    public String getEquityNature() {
        return this.equityNature;
    }
    
    public void setEquityNature(String equityNature) {
        this.equityNature = equityNature;
    }
    
    @Column(name="SQUARE", precision=10)
    public BigDecimal getSquare() {
        return this.square;
    }
    
    public void setSquare(BigDecimal square) {
        this.square = square;
    }
    
    @Column(name="INNER_SQUARE", precision=10)
    public BigDecimal getInnerSquare() {
        return this.innerSquare;
    }
    
    public void setInnerSquare(BigDecimal innerSquare) {
        this.innerSquare = innerSquare;
    }
    
    @Column(name="RENT_SQUARE", precision=10)
    public BigDecimal getRentSquare() {
        return this.rentSquare;
    }
    
    public void setRentSquare(BigDecimal rentSquare) {
        this.rentSquare = rentSquare;
    }
    
    @Column(name="LAYOUT_CD", length=20)
    public String getLayoutCd() {
        return this.layoutCd;
    }
    
    public void setLayoutCd(String layoutCd) {
        this.layoutCd = layoutCd;
    }
    
    @Column(name="RENT_YEARS", length=50)
    public String getRentYears() {
        return this.rentYears;
    }
    
    public void setRentYears(String rentYears) {
        this.rentYears = rentYears;
    }
    
    @Column(name="MANAGE_CD", length=20)
    public String getManageCd() {
        return this.manageCd;
    }
    
    public void setManageCd(String manageCd) {
        this.manageCd = manageCd;
    }

    @Column(name="OWNER", length=100)
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }

    @Column(name="CHANGE_USER", length=20)
    public String getChangeUser() {
        return this.changeUser;
    }
    
    public void setChangeUser(String changeUser) {
        this.changeUser = changeUser;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CHANGE_DATE", length=7)
    public Date getChangeDate() {
        return this.changeDate;
    }
    
    public void setChangeDate(Date changeDate) {
        this.changeDate = changeDate;
    }
    
    @Column(name="TEMP_HIS_ID", length=50)
    public String getTempHisId() {
		return tempHisId;
	}

	public void setTempHisId(String tempHisId) {
		this.tempHisId = tempHisId;
	}

    @Column(name="RES_APPROVE_INFO_ID", length=50)
    public String getResApproveInfoId() {
        return this.resApproveInfoId;
    }
    
    public void setResApproveInfoId(String resApproveInfoId) {
        this.resApproveInfoId = resApproveInfoId;
    }

    @Column(name="INVALID_BY", length=1)
    public String getInvalidBy() {
		return invalidBy;
	}

	public void setInvalidBy(String invalidBy) {
		this.invalidBy = invalidBy;
	}

    @Column(name="CONT_APPROVAL", length=4000)
    public String getContApproval() {
        return this.contApproval;
    }
    
    public void setContApproval(String contApproval) {
        this.contApproval = contApproval;
    }
    
    @Column(name="CONT_APPROVAL_ID", length=50)
    public String getContApprovalId() {
        return this.contApprovalId;
    }
    
    public void setContApprovalId(String contApprovalId) {
        this.contApprovalId = contApprovalId;
    }
    
    @Column(name="APPROVAL_ATTACH_FLG", length=1)
    public String getApprovalAttachFlg() {
        return this.approvalAttachFlg;
    }
    
    public void setApprovalAttachFlg(String approvalAttachFlg) {
        this.approvalAttachFlg = approvalAttachFlg;
    }
    
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisCont")
    @BatchSize(size=10)
public List<BisMultiContRel> getBisMultiContRels() {
        return this.bisMultiContRels;
    }
    
    public void setBisMultiContRels(List<BisMultiContRel> bisMultiContRels) {
        this.bisMultiContRels = bisMultiContRels;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisCont")
    @BatchSize(size=10)
public List<BisContShopProp> getBisContShopProps() {
        return this.bisContShopProps;
    }
    
    public void setBisContShopProps(List<BisContShopProp> bisContShopProps) {
        this.bisContShopProps = bisContShopProps;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisCont")
    @BatchSize(size=10)
public List<BisFlatContRel> getBisFlatContRels() {
        return this.bisFlatContRels;
    }
    
    public void setBisFlatContRels(List<BisFlatContRel> bisFlatContRels) {
        this.bisFlatContRels = bisFlatContRels;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisCont")
    @BatchSize(size=10)
public List<BisContShopRent> getBisContShopRents() {
        return this.bisContShopRents;
    }
    
    public void setBisContShopRents(List<BisContShopRent> bisContShopRents) {
        this.bisContShopRents = bisContShopRents;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisCont")
    @BatchSize(size=10)
public List<BisContFlatProp> getBisContFlatProps() {
        return this.bisContFlatProps;
    }
    
    public void setBisContFlatProps(List<BisContFlatProp> bisContFlatProps) {
        this.bisContFlatProps = bisContFlatProps;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisCont")
    @BatchSize(size=10)
public List<BisContCredit> getBisContCredits() {
        return this.bisContCredits;
    }
    
    public void setBisContCredits(List<BisContCredit> bisContCredits) {
        this.bisContCredits = bisContCredits;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisCont")
    @BatchSize(size=10)
public List<BisMust> getBisMusts() {
        return this.bisMusts;
    }
    
    public void setBisMusts(List<BisMust> bisMusts) {
        this.bisMusts = bisMusts;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisCont")
    @BatchSize(size=10)
public List<BisContShopBack> getBisContShopBacks() {
        return this.bisContShopBacks;
    }
    
    public void setBisContShopBacks(List<BisContShopBack> bisContShopBacks) {
        this.bisContShopBacks = bisContShopBacks;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisCont")
    @BatchSize(size=10)
public List<BisStoreContRel> getBisStoreContRels() {
        return this.bisStoreContRels;
    }
    
    public void setBisStoreContRels(List<BisStoreContRel> bisStoreContRels) {
        this.bisStoreContRels = bisStoreContRels;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisCont")
    @BatchSize(size=10)
public List<BisContMulti> getBisContMultis() {
        return this.bisContMultis;
    }
    
    public void setBisContMultis(List<BisContMulti> bisContMultis) {
        this.bisContMultis = bisContMultis;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisCont")
    @BatchSize(size=10)
public List<BisContAdditional> getBisContAdditionals() {
        return this.bisContAdditionals;
    }
    
    public void setBisContAdditionals(List<BisContAdditional> bisContAdditionals) {
        this.bisContAdditionals = bisContAdditionals;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisCont")
    @BatchSize(size=10)
public List<BisContShopEntr> getBisContShopEntrs() {
        return this.bisContShopEntrs;
    }
    
    public void setBisContShopEntrs(List<BisContShopEntr> bisContShopEntrs) {
        this.bisContShopEntrs = bisContShopEntrs;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="bisCont")
    @BatchSize(size=10)
    public List<BisMustFormula> getBisMustFormulas() {
        return this.bisMustFormulas;
    }
    
    public void setBisMustFormulas(List<BisMustFormula> bisMustFormulas) {
        this.bisMustFormulas = bisMustFormulas;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="bisCont")
    @BatchSize(size=10)
    public List<BisMustRent> getBisMustRents() {
    	return this.bisMustRents;
    }
    
    public void setBisMustRents(List<BisMustRent> bisMustRents) {
    	this.bisMustRents = bisMustRents;
    }

}


