// 
package com.hhz.ump.entity.bis;
// Generated 2011-8-22 20:20:40 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * BisFactOther generated by hbm2java
 */
@Entity
@Table(name="BIS_FACT_OTHER"
    
)
public class BisFactOther  implements java.io.Serializable {


     private String bisFactOtherId;
     private Long sequenceNo;
     private String chargeTypeCd;
     private String factYear;
     private String factMonth;
     private BigDecimal money;
     private Date factDate;
     private String describe;
     private String checkUserCd;
     private Date checkDate;
     private String statusCd;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String bisShopId;
     private String bisFlatId;
     private String bisMultiId;
     private String bisContId;
     private String bisTenantId;
     private String bisStoreId;
     private BigDecimal disposableMoney;
     private BigDecimal deductMoney;
     private String bisProjectId;
     private String attachFlg;
     private String bisFloorId;
     private BigDecimal quantity;

    public BisFactOther() {
    }

	
    public BisFactOther(String bisFactOtherId, long recordVersion) {
        this.bisFactOtherId = bisFactOtherId;
        this.recordVersion = recordVersion;
    }
    public BisFactOther(String bisFactOtherId, String chargeTypeCd, String factYear, String factMonth, BigDecimal money, Date factDate, String describe, String checkUserCd, Date checkDate, String statusCd, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, String bisShopId, String bisFlatId, String bisMultiId, String bisContId, String bisTenantId, String bisStoreId, BigDecimal disposableMoney, BigDecimal deductMoney, String bisProjectId, String attachFlg, String bisFloorId) {
       this.bisFactOtherId = bisFactOtherId;
       this.chargeTypeCd = chargeTypeCd;
       this.factYear = factYear;
       this.factMonth = factMonth;
       this.money = money;
       this.factDate = factDate;
       this.describe = describe;
       this.checkUserCd = checkUserCd;
       this.checkDate = checkDate;
       this.statusCd = statusCd;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.bisShopId = bisShopId;
       this.bisFlatId = bisFlatId;
       this.bisMultiId = bisMultiId;
       this.bisContId = bisContId;
       this.bisTenantId = bisTenantId;
       this.bisStoreId = bisStoreId;
       this.disposableMoney = disposableMoney;
       this.deductMoney = deductMoney;
       this.bisProjectId = bisProjectId;
       this.attachFlg = attachFlg;
       this.bisFloorId = bisFloorId;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_FACT_OTHER_ID", unique=true, nullable=false, length=50)
    public String getBisFactOtherId() {
        return this.bisFactOtherId;
    }
    
    public void setBisFactOtherId(String bisFactOtherId) {
        this.bisFactOtherId = bisFactOtherId;
    }
    
    @Column(name="SEQUENCE_NO", precision=10, scale=0)
    public Long getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Long sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    
    @Column(name="CHARGE_TYPE_CD", length=20)
    public String getChargeTypeCd() {
        return this.chargeTypeCd;
    }
    
    public void setChargeTypeCd(String chargeTypeCd) {
        this.chargeTypeCd = chargeTypeCd;
    }
    
    @Column(name="FACT_YEAR", length=4)
    public String getFactYear() {
        return this.factYear;
    }
    
    public void setFactYear(String factYear) {
        this.factYear = factYear;
    }
    
    @Column(name="FACT_MONTH", length=2)
    public String getFactMonth() {
        return this.factMonth;
    }
    
    public void setFactMonth(String factMonth) {
        this.factMonth = factMonth;
    }
    
    @Column(name="MONEY", precision=10)
    public BigDecimal getMoney() {
        return this.money;
    }
    
    public void setMoney(BigDecimal money) {
        this.money = money;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FACT_DATE", length=7)
    public Date getFactDate() {
        return this.factDate;
    }
    
    public void setFactDate(Date factDate) {
        this.factDate = factDate;
    }
    
    @Column(name="DESCRIBE", length=300)
    public String getDescribe() {
        return this.describe;
    }
    
    public void setDescribe(String describe) {
        this.describe = describe;
    }
    
    @Column(name="CHECK_USER_CD", length=20)
    public String getCheckUserCd() {
        return this.checkUserCd;
    }
    
    public void setCheckUserCd(String checkUserCd) {
        this.checkUserCd = checkUserCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CHECK_DATE", length=7)
    public Date getCheckDate() {
        return this.checkDate;
    }
    
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }
    
    @Column(name="STATUS_CD", length=20)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="BIS_SHOP_ID", length=50)
    public String getBisShopId() {
        return this.bisShopId;
    }
    
    public void setBisShopId(String bisShopId) {
        this.bisShopId = bisShopId;
    }
    
    @Column(name="BIS_FLAT_ID", length=50)
    public String getBisFlatId() {
        return this.bisFlatId;
    }
    
    public void setBisFlatId(String bisFlatId) {
        this.bisFlatId = bisFlatId;
    }
    
    @Column(name="BIS_MULTI_ID", length=50)
    public String getBisMultiId() {
        return this.bisMultiId;
    }
    
    public void setBisMultiId(String bisMultiId) {
        this.bisMultiId = bisMultiId;
    }
    
    @Column(name="BIS_CONT_ID", length=50)
    public String getBisContId() {
        return this.bisContId;
    }
    
    public void setBisContId(String bisContId) {
        this.bisContId = bisContId;
    }
    
    @Column(name="BIS_TENANT_ID", length=50)
    public String getBisTenantId() {
        return this.bisTenantId;
    }
    
    public void setBisTenantId(String bisTenantId) {
        this.bisTenantId = bisTenantId;
    }
    
    @Column(name="BIS_STORE_ID", length=300)
    public String getBisStoreId() {
        return this.bisStoreId;
    }
    
    public void setBisStoreId(String bisStoreId) {
        this.bisStoreId = bisStoreId;
    }
    
    @Column(name="DISPOSABLE_MONEY", precision=10)
    public BigDecimal getDisposableMoney() {
        return this.disposableMoney;
    }
    
    public void setDisposableMoney(BigDecimal disposableMoney) {
        this.disposableMoney = disposableMoney;
    }
    
    @Column(name="DEDUCT_MONEY", precision=10)
    public BigDecimal getDeductMoney() {
        return this.deductMoney;
    }
    
    public void setDeductMoney(BigDecimal deductMoney) {
        this.deductMoney = deductMoney;
    }
    
    @Column(name="BIS_PROJECT_ID", length=50)
    public String getBisProjectId() {
        return this.bisProjectId;
    }
    
    public void setBisProjectId(String bisProjectId) {
        this.bisProjectId = bisProjectId;
    }
    
    @Column(name="ATTACH_FLG", length=1)
    public String getAttachFlg() {
        return this.attachFlg;
    }
    
    public void setAttachFlg(String attachFlg) {
        this.attachFlg = attachFlg;
    }
    
    @Column(name="BIS_FLOOR_ID", length=50)
    public String getBisFloorId() {
        return this.bisFloorId;
    }
    
    public void setBisFloorId(String bisFloorId) {
        this.bisFloorId = bisFloorId;
    }

    @Column(name="QUANTITY", precision=10)
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }



}


