// 
package com.hhz.ump.entity.bis;

// Generated 2012-5-28 18:23:51 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * BisFlatRecord generated by hbm2java
 */
@Entity
@Table(name = "BIS_FLAT_RECORD")
public class BisFlatRecord implements java.io.Serializable {

	private String bisFlatRecordId;
	private BisFlat bisFlat;
    private String costType;
    private Long recordYear;
    private Long recordMonth;
    private BigDecimal monthSs;
    private String chargeFlg;
    private BigDecimal waterTonnage;
    private BigDecimal elecDegree;
    private BigDecimal monthYs;
    private BigDecimal monthYis;
    private BigDecimal monthYus;
    private BigDecimal monthMonth;
    private BigDecimal currYearDebt;
    private BigDecimal agoYearDebt;
    private BigDecimal oweWaterRate;
    private BigDecimal monthYsTotal;
    private BigDecimal ysTotal;
    private BigDecimal monthSsTotal;
    private BigDecimal ssTotal;
    private BigDecimal currYearWaterRate;
    private BigDecimal currYearYusWaterRate;
    private BigDecimal agoYearOwnfeeTotal;
    private BigDecimal yusTotal;
    private BigDecimal currYearQsTotal;
    private BigDecimal qsTotal;
    private String remark;
    private String creator;
    private String createdCenterCd;
    private String createdDeptCd;
    private String createdPositionCd;
    private Date createdDate;
    private String updator;
    private String updatedCenterCd;
    private String updatedDeptCd;
    private String updatedPositionCd;
    private Date updatedDate;
    private long recordVersion;
    private String paymentIntertemporal;
    private BigDecimal owePropRate;
    private BigDecimal oweElecRate;
    private BigDecimal currYearPropRate;
    private BigDecimal currYearElecRate;
    private BigDecimal currYearYusPropRate;
    private BigDecimal currYearYusElecRate;
    private BigDecimal currYearYsTotal;
    private BigDecimal currYearSsTotal;

	public BisFlatRecord() {
	}

	public BisFlatRecord(String bisFlatRecordId, BisFlat bisFlat,long recordVersion) {
		this.bisFlatRecordId = bisFlatRecordId;
		this.bisFlat = bisFlat;
		this.recordVersion = recordVersion;
	}

	public BisFlatRecord(String bisFlatRecordId, BisFlat bisFlat, String costType, Long recordYear, Long recordMonth, BigDecimal monthSs, String chargeFlg, BigDecimal waterTonnage, BigDecimal elecDegree, BigDecimal monthYs, BigDecimal monthYis, BigDecimal monthYus, BigDecimal monthMonth, BigDecimal currYearDebt, BigDecimal agoYearDebt, BigDecimal oweWaterRate, BigDecimal monthYsTotal, BigDecimal ysTotal, BigDecimal monthSsTotal, BigDecimal ssTotal, BigDecimal currYearWaterRate, BigDecimal currYearYusWaterRate, BigDecimal agoYearOwnfeeTotal, BigDecimal yusTotal, BigDecimal currYearQsTotal, BigDecimal qsTotal, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, String paymentIntertemporal, BigDecimal owePropRate, BigDecimal oweElecRate, BigDecimal currYearPropRate, BigDecimal currYearElecRate, BigDecimal currYearYusPropRate, BigDecimal currYearYusElecRate, BigDecimal currYearYsTotal, BigDecimal currYearSsTotal) {
	       this.bisFlatRecordId = bisFlatRecordId;
	       this.bisFlat = bisFlat;
	       this.costType = costType;
	       this.recordYear = recordYear;
	       this.recordMonth = recordMonth;
	       this.monthSs = monthSs;
	       this.chargeFlg = chargeFlg;
	       this.waterTonnage = waterTonnage;
	       this.elecDegree = elecDegree;
	       this.monthYs = monthYs;
	       this.monthYis = monthYis;
	       this.monthYus = monthYus;
	       this.monthMonth = monthMonth;
	       this.currYearDebt = currYearDebt;
	       this.agoYearDebt = agoYearDebt;
	       this.oweWaterRate = oweWaterRate;
	       this.monthYsTotal = monthYsTotal;
	       this.ysTotal = ysTotal;
	       this.monthSsTotal = monthSsTotal;
	       this.ssTotal = ssTotal;
	       this.currYearWaterRate = currYearWaterRate;
	       this.currYearYusWaterRate = currYearYusWaterRate;
	       this.agoYearOwnfeeTotal = agoYearOwnfeeTotal;
	       this.yusTotal = yusTotal;
	       this.currYearQsTotal = currYearQsTotal;
	       this.qsTotal = qsTotal;
	       this.remark = remark;
	       this.creator = creator;
	       this.createdCenterCd = createdCenterCd;
	       this.createdDeptCd = createdDeptCd;
	       this.createdPositionCd = createdPositionCd;
	       this.createdDate = createdDate;
	       this.updator = updator;
	       this.updatedCenterCd = updatedCenterCd;
	       this.updatedDeptCd = updatedDeptCd;
	       this.updatedPositionCd = updatedPositionCd;
	       this.updatedDate = updatedDate;
	       this.recordVersion = recordVersion;
	       this.paymentIntertemporal = paymentIntertemporal;
	       this.owePropRate = owePropRate;
	       this.oweElecRate = oweElecRate;
	       this.currYearPropRate = currYearPropRate;
	       this.currYearElecRate = currYearElecRate;
	       this.currYearYusPropRate = currYearYusPropRate;
	       this.currYearYusElecRate = currYearYusElecRate;
	       this.currYearYsTotal = currYearYsTotal;
	       this.currYearSsTotal = currYearSsTotal;
	    }

	@Id
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	@Column(name = "BIS_FLAT_RECORD_ID", unique = true, nullable = false, length = 50)
	public String getBisFlatRecordId() {
		return this.bisFlatRecordId;
	}

	public void setBisFlatRecordId(String bisFlatRecordId) {
		this.bisFlatRecordId = bisFlatRecordId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BIS_FLAT_ID", nullable = false)
	public BisFlat getBisFlat() {
		return bisFlat;
	}

	public void setBisFlat(BisFlat bisFlat) {
		this.bisFlat = bisFlat;
	}

	@Column(name = "COST_TYPE", length = 10)
	public String getCostType() {
		return this.costType;
	}

	public void setCostType(String costType) {
		this.costType = costType;
	}

	@Column(name = "RECORD_YEAR", precision = 10, scale = 0)
	public Long getRecordYear() {
		return this.recordYear;
	}

	public void setRecordYear(Long recordYear) {
		this.recordYear = recordYear;
	}

	@Column(name = "RECORD_MONTH", precision = 10, scale = 0)
	public Long getRecordMonth() {
		return this.recordMonth;
	}

	public void setRecordMonth(Long recordMonth) {
		this.recordMonth = recordMonth;
	}
	
	@Column(name = "PAYMENT_INTERTEMPORAL", length = 50)
	public String getPaymentIntertemporal() {
		return paymentIntertemporal;
	}

	public void setPaymentIntertemporal(String paymentIntertemporal) {
		this.paymentIntertemporal = paymentIntertemporal;
	}

	@Column(name = "MONTH_SS", precision = 18)
	public BigDecimal getMonthSs() {
		return this.monthSs;
	}

	public void setMonthSs(BigDecimal monthSs) {
		this.monthSs = monthSs;
	}

	@Column(name = "CHARGE_FLG", length = 10)
	public String getChargeFlg() {
		return this.chargeFlg;
	}

	public void setChargeFlg(String chargeFlg) {
		this.chargeFlg = chargeFlg;
	}

	@Column(name = "WATER_TONNAGE", precision = 18)
	public BigDecimal getWaterTonnage() {
		return this.waterTonnage;
	}

	public void setWaterTonnage(BigDecimal waterTonnage) {
		this.waterTonnage = waterTonnage;
	}

	@Column(name = "ELEC_DEGREE", precision = 18)
	public BigDecimal getElecDegree() {
		return this.elecDegree;
	}

	public void setElecDegree(BigDecimal elecDegree) {
		this.elecDegree = elecDegree;
	}

	@Column(name = "MONTH_YS", precision = 18)
	public BigDecimal getMonthYs() {
		return this.monthYs;
	}

	public void setMonthYs(BigDecimal monthYs) {
		this.monthYs = monthYs;
	}

	@Column(name = "MONTH_YIS", precision = 18)
	public BigDecimal getMonthYis() {
		return this.monthYis;
	}

	public void setMonthYis(BigDecimal monthYis) {
		this.monthYis = monthYis;
	}

	@Column(name = "MONTH_YUS", precision = 18)
	public BigDecimal getMonthYus() {
		return this.monthYus;
	}

	public void setMonthYus(BigDecimal monthYus) {
		this.monthYus = monthYus;
	}

	@Column(name = "MONTH_MONTH", precision = 18)
	public BigDecimal getMonthMonth() {
		return this.monthMonth;
	}

	public void setMonthMonth(BigDecimal monthMonth) {
		this.monthMonth = monthMonth;
	}

	@Column(name = "CURR_YEAR_DEBT", precision = 18)
	public BigDecimal getCurrYearDebt() {
		return this.currYearDebt;
	}

	public void setCurrYearDebt(BigDecimal currYearDebt) {
		this.currYearDebt = currYearDebt;
	}

	@Column(name = "AGO_YEAR_DEBT", precision = 18)
	public BigDecimal getAgoYearDebt() {
		return this.agoYearDebt;
	}

	public void setAgoYearDebt(BigDecimal agoYearDebt) {
		this.agoYearDebt = agoYearDebt;
	}

	@Column(name = "OWE_WATER_RATE", precision = 18)
	public BigDecimal getOweWaterRate() {
		return this.oweWaterRate;
	}

	public void setOweWaterRate(BigDecimal oweWaterRate) {
		this.oweWaterRate = oweWaterRate;
	}

	@Column(name = "MONTH_YS_TOTAL", precision = 18)
	public BigDecimal getMonthYsTotal() {
		return this.monthYsTotal;
	}

	public void setMonthYsTotal(BigDecimal monthYsTotal) {
		this.monthYsTotal = monthYsTotal;
	}

	@Column(name = "YS_TOTAL", precision = 18)
	public BigDecimal getYsTotal() {
		return this.ysTotal;
	}

	public void setYsTotal(BigDecimal ysTotal) {
		this.ysTotal = ysTotal;
	}

	@Column(name = "MONTH_SS_TOTAL", precision = 18)
	public BigDecimal getMonthSsTotal() {
		return this.monthSsTotal;
	}

	public void setMonthSsTotal(BigDecimal monthSsTotal) {
		this.monthSsTotal = monthSsTotal;
	}

	@Column(name = "SS_TOTAL", precision = 18)
	public BigDecimal getSsTotal() {
		return this.ssTotal;
	}

	public void setSsTotal(BigDecimal ssTotal) {
		this.ssTotal = ssTotal;
	}

	@Column(name = "CURR_YEAR_WATER_RATE", precision = 18)
	public BigDecimal getCurrYearWaterRate() {
		return this.currYearWaterRate;
	}

	public void setCurrYearWaterRate(BigDecimal currYearWaterRate) {
		this.currYearWaterRate = currYearWaterRate;
	}

	@Column(name = "AGO_YEAR_OWNFEE_TOTAL", precision = 18)
	public BigDecimal getAgoYearOwnfeeTotal() {
		return this.agoYearOwnfeeTotal;
	}

	public BigDecimal getCurrYearYusWaterRate() {
		return currYearYusWaterRate;
	}

	@Column(name = "CURR_YEAR_YUS_WATER_RATE", precision = 18)
	public void setCurrYearYusWaterRate(BigDecimal currYearYusWaterRate) {
		this.currYearYusWaterRate = currYearYusWaterRate;
	}

	public void setAgoYearOwnfeeTotal(BigDecimal agoYearOwnfeeTotal) {
		this.agoYearOwnfeeTotal = agoYearOwnfeeTotal;
	}

	@Column(name = "YUS_TOTAL", precision = 18)
	public BigDecimal getYusTotal() {
		return this.yusTotal;
	}

	public void setYusTotal(BigDecimal yusTotal) {
		this.yusTotal = yusTotal;
	}

	@Column(name = "CURR_YEAR_QS_TOTAL", precision = 18)
	public BigDecimal getCurrYearQsTotal() {
		return this.currYearQsTotal;
	}

	public void setCurrYearQsTotal(BigDecimal currYearQsTotal) {
		this.currYearQsTotal = currYearQsTotal;
	}

	@Column(name = "QS_TOTAL", precision = 18)
	public BigDecimal getQsTotal() {
		return this.qsTotal;
	}

	public void setQsTotal(BigDecimal qsTotal) {
		this.qsTotal = qsTotal;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "CREATOR", length = 20)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATED_CENTER_CD", length = 20)
	public String getCreatedCenterCd() {
		return this.createdCenterCd;
	}

	public void setCreatedCenterCd(String createdCenterCd) {
		this.createdCenterCd = createdCenterCd;
	}

	@Column(name = "CREATED_DEPT_CD", length = 20)
	public String getCreatedDeptCd() {
		return this.createdDeptCd;
	}

	public void setCreatedDeptCd(String createdDeptCd) {
		this.createdDeptCd = createdDeptCd;
	}

	@Column(name = "CREATED_POSITION_CD", length = 20)
	public String getCreatedPositionCd() {
		return this.createdPositionCd;
	}

	public void setCreatedPositionCd(String createdPositionCd) {
		this.createdPositionCd = createdPositionCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATOR", length = 20)
	public String getUpdator() {
		return this.updator;
	}

	public void setUpdator(String updator) {
		this.updator = updator;
	}

	@Column(name = "UPDATED_CENTER_CD", length = 20)
	public String getUpdatedCenterCd() {
		return this.updatedCenterCd;
	}

	public void setUpdatedCenterCd(String updatedCenterCd) {
		this.updatedCenterCd = updatedCenterCd;
	}

	@Column(name = "UPDATED_DEPT_CD", length = 20)
	public String getUpdatedDeptCd() {
		return this.updatedDeptCd;
	}

	public void setUpdatedDeptCd(String updatedDeptCd) {
		this.updatedDeptCd = updatedDeptCd;
	}

	@Column(name = "UPDATED_POSITION_CD", length = 20)
	public String getUpdatedPositionCd() {
		return this.updatedPositionCd;
	}

	public void setUpdatedPositionCd(String updatedPositionCd) {
		this.updatedPositionCd = updatedPositionCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 7)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "RECORD_VERSION", nullable = false, precision = 10, scale = 0)
	@Version
	public long getRecordVersion() {
		return this.recordVersion;
	}

	public void setRecordVersion(long recordVersion) {
		this.recordVersion = recordVersion;
	}
	
    @Column(name="OWE_PROP_RATE", precision=18)
    public BigDecimal getOwePropRate() {
        return this.owePropRate;
    }
    
    public void setOwePropRate(BigDecimal owePropRate) {
        this.owePropRate = owePropRate;
    }
    
    @Column(name="OWE_ELEC_RATE", precision=18)
    public BigDecimal getOweElecRate() {
        return this.oweElecRate;
    }
    
    public void setOweElecRate(BigDecimal oweElecRate) {
        this.oweElecRate = oweElecRate;
    }
    
    @Column(name="CURR_YEAR_PROP_RATE", precision=18)
    public BigDecimal getCurrYearPropRate() {
        return this.currYearPropRate;
    }
    
    public void setCurrYearPropRate(BigDecimal currYearPropRate) {
        this.currYearPropRate = currYearPropRate;
    }
    
    @Column(name="CURR_YEAR_ELEC_RATE", precision=18)
    public BigDecimal getCurrYearElecRate() {
        return this.currYearElecRate;
    }
    
    public void setCurrYearElecRate(BigDecimal currYearElecRate) {
        this.currYearElecRate = currYearElecRate;
    }
    
    @Column(name="CURR_YEAR_YUS_PROP_RATE", precision=18)
    public BigDecimal getCurrYearYusPropRate() {
        return this.currYearYusPropRate;
    }
    
    public void setCurrYearYusPropRate(BigDecimal currYearYusPropRate) {
        this.currYearYusPropRate = currYearYusPropRate;
    }
    
    @Column(name="CURR_YEAR_YUS_ELEC_RATE", precision=18)
    public BigDecimal getCurrYearYusElecRate() {
        return this.currYearYusElecRate;
    }
    
    public void setCurrYearYusElecRate(BigDecimal currYearYusElecRate) {
        this.currYearYusElecRate = currYearYusElecRate;
    }
    
    @Column(name="CURR_YEAR_YS_TOTAL", precision=18)
    public BigDecimal getCurrYearYsTotal() {
    	return currYearYsTotal;
    }
    
    public void setCurrYearYsTotal(BigDecimal currYearYsTotal) {
    	this.currYearYsTotal = currYearYsTotal;
    }
    
    @Column(name="CURR_YEAR_SS_TOTAL", precision=18)
	public BigDecimal getCurrYearSsTotal() {
		return currYearSsTotal;
	}

	public void setCurrYearSsTotal(BigDecimal currYearSsTotal) {
		this.currYearSsTotal = currYearSsTotal;
	}

}
