// 
package com.hhz.ump.entity.bis;
// Generated 2012-2-29 17:42:28 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * BisManageDay generated by hbm2java
 */
@Entity
@Table(name="BIS_MANAGE_DAY"
    
)
public class BisManageDay  implements java.io.Serializable {


     private String bisManageDayId;
     private BisProject bisProject;
     private BigDecimal superMarket;
     private BigDecimal departmentStore;
     private BigDecimal cinema;
     private BigDecimal mainTotal;
     private BigDecimal storeTotal;
     private BigDecimal plazaTotal;
     private BigDecimal customerTotal;
     private BigDecimal carTotal;
     private String manageEvent;
     private String planActiviteEvent;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private Date authDate;
     private String status;
     private BigDecimal baolai;
     private BigDecimal longmai;
     private BigDecimal caoshangfei;

    public BisManageDay() {
    }

	
    public BisManageDay(String bisManageDayId, BisProject bisProject, long recordVersion) {
        this.bisManageDayId = bisManageDayId;
        this.bisProject = bisProject;
        this.recordVersion = recordVersion;
    }
    public BisManageDay(String bisManageDayId, BisProject bisProject, BigDecimal superMarket, BigDecimal departmentStore, BigDecimal cinema, BigDecimal mainTotal, BigDecimal storeTotal, BigDecimal plazaTotal, BigDecimal customerTotal, BigDecimal carTotal, String manageEvent, String planActiviteEvent, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, Date authDate, String status,BigDecimal baolai,BigDecimal longmai,BigDecimal caoshangfei) {
       this.bisManageDayId = bisManageDayId;
       this.bisProject = bisProject;
       this.superMarket = superMarket;
       this.departmentStore = departmentStore;
       this.cinema = cinema;
       this.mainTotal = mainTotal;
       this.storeTotal = storeTotal;
       this.plazaTotal = plazaTotal;
       this.customerTotal = customerTotal;
       this.carTotal = carTotal;
       this.manageEvent = manageEvent;
       this.planActiviteEvent = planActiviteEvent;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.authDate = authDate;
       this.status = status;
       this.baolai = baolai;
	   this.longmai = longmai;
	   this.caoshangfei = caoshangfei;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_MANAGE_DAY_ID", unique=true, nullable=false, length=50)
    public String getBisManageDayId() {
        return this.bisManageDayId;
    }
    
    public void setBisManageDayId(String bisManageDayId) {
        this.bisManageDayId = bisManageDayId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIS_PROJECT_ID", nullable=false)
    public BisProject getBisProject() {
        return this.bisProject;
    }
    
    public void setBisProject(BisProject bisProject) {
        this.bisProject = bisProject;
    }
    
    @Column(name="SUPER_MARKET", precision=10)
    public BigDecimal getSuperMarket() {
        return this.superMarket;
    }
    
    public void setSuperMarket(BigDecimal superMarket) {
        this.superMarket = superMarket;
    }
    
    @Column(name="DEPARTMENT_STORE", precision=10)
    public BigDecimal getDepartmentStore() {
        return this.departmentStore;
    }
    
    public void setDepartmentStore(BigDecimal departmentStore) {
        this.departmentStore = departmentStore;
    }
    
    @Column(name="CINEMA", precision=10)
    public BigDecimal getCinema() {
        return this.cinema;
    }
    
    public void setCinema(BigDecimal cinema) {
        this.cinema = cinema;
    }
    
    @Column(name="MAIN_TOTAL", precision=10)
    public BigDecimal getMainTotal() {
        return this.mainTotal;
    }
    
    public void setMainTotal(BigDecimal mainTotal) {
        this.mainTotal = mainTotal;
    }
    
    @Column(name="STORE_TOTAL", precision=10)
    public BigDecimal getStoreTotal() {
        return this.storeTotal;
    }
    
    public void setStoreTotal(BigDecimal storeTotal) {
        this.storeTotal = storeTotal;
    }
    
    @Column(name="PLAZA_TOTAL", precision=10)
    public BigDecimal getPlazaTotal() {
        return this.plazaTotal;
    }
    
    public void setPlazaTotal(BigDecimal plazaTotal) {
        this.plazaTotal = plazaTotal;
    }
    
    @Column(name="CUSTOMER_TOTAL", precision=10)
    public BigDecimal getCustomerTotal() {
        return this.customerTotal;
    }
    
    public void setCustomerTotal(BigDecimal customerTotal) {
        this.customerTotal = customerTotal;
    }
    
    @Column(name="CAR_TOTAL", precision=10)
    public BigDecimal getCarTotal() {
        return this.carTotal;
    }
    
    public void setCarTotal(BigDecimal carTotal) {
        this.carTotal = carTotal;
    }
    
    @Column(name="MANAGE_EVENT", length=400)
    public String getManageEvent() {
        return this.manageEvent;
    }
    
    public void setManageEvent(String manageEvent) {
        this.manageEvent = manageEvent;
    }
    
    @Column(name="PLAN_ACTIVITE_EVENT", length=400)
    public String getPlanActiviteEvent() {
        return this.planActiviteEvent;
    }
    
    public void setPlanActiviteEvent(String planActiviteEvent) {
        this.planActiviteEvent = planActiviteEvent;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="AUTH_DATE", length=7)
    public Date getAuthDate() {
        return this.authDate;
    }
    
    public void setAuthDate(Date authDate) {
        this.authDate = authDate;
    }
    
    @Column(name="STATUS", length=2)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="BAOLAI", precision=10)
	public BigDecimal getBaolai() {
		return baolai;
	}

	public void setBaolai(BigDecimal baolai) {
		this.baolai = baolai;
	}
	
	@Column(name="LONGMAI", precision=10)
	public BigDecimal getLongmai() {
		return longmai;
	}
	
	public void setLongmai(BigDecimal longmai) {
		this.longmai = longmai;
	}

	@Column(name="CAOSHANGFEI", precision=10)
	public BigDecimal getCaoshangfei() {
		return caoshangfei;
	}

	public void setCaoshangfei(BigDecimal caoshangfei) {
		this.caoshangfei = caoshangfei;
	}


}


