// 
package com.hhz.ump.entity.bis;
// Generated 2011-8-3 22:32:28 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * BisMulti generated by hbm2java
 */
@Entity
@Table(name="BIS_MULTI"
    
)
public class BisMulti  implements java.io.Serializable {


     private String bisMultiId;
     private String bisProjectId;
     private String bisFloorId;
     private String bisContId;
     private String multiName;
     private String coords;
     private String renterName;
     private String operationProjectCd;
     private String operationArea;
     private BigDecimal square;
     private BigDecimal contPromiseBond;
     private BigDecimal receivedBond;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String multiNo;//MULTI_NO;
     private String multiType;
     private String multiFloor;
     private String multiGrade;
     private String multiPrice;
     private String multiPolicy;
     private List<BisMultiContRel> bisMultiContRels = new ArrayList<BisMultiContRel>();

    public BisMulti() {
    }

	
    public BisMulti(String bisMultiId, String bisProjectId, String multiName, long recordVersion) {
        this.bisMultiId = bisMultiId;
        this.bisProjectId = bisProjectId;
        this.multiName = multiName;
        this.recordVersion = recordVersion;
    }
    public BisMulti(String bisMultiId, String bisProjectId, String bisFloorId,String bisContId, String multiName, String renterName, String operationProjectCd, String operationArea, BigDecimal square, BigDecimal contPromiseBond, BigDecimal receivedBond, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, List<BisMultiContRel> bisMultiContRels,String multiNo,String multiType,String multiFloor,String multiGrade,String multiPrice,String multiPolicy,String coords) {
       this.bisMultiId = bisMultiId;
       this.bisProjectId = bisProjectId;
       this.bisFloorId = bisFloorId;
       this.bisContId = bisContId;
       this.multiName = multiName;
       this.renterName = renterName;
       this.operationProjectCd = operationProjectCd;
       this.operationArea = operationArea;
       this.square = square;
       this.contPromiseBond = contPromiseBond;
       this.receivedBond = receivedBond;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.bisMultiContRels = bisMultiContRels;
       this.multiNo = multiNo;
       this.multiType = multiType;
       this.multiFloor = multiFloor;
       this.multiGrade = multiGrade;
       this.multiPrice = multiPrice;
       this.multiPolicy = multiPolicy;
       this.coords = coords;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_MULTI_ID", unique=true, nullable=false, length=50)
    public String getBisMultiId() {
        return this.bisMultiId;
    }
    
    public void setBisMultiId(String bisMultiId) {
        this.bisMultiId = bisMultiId;
    }
    
    @Column(name="BIS_PROJECT_ID", nullable=false, length=50)
    public String getBisProjectId() {
        return this.bisProjectId;
    }
    
    public void setBisProjectId(String bisProjectId) {
        this.bisProjectId = bisProjectId;
    }
    @Column(name="BIS_FLOOR_ID",  length=50)
    public String getBisFloorId() {
    	return this.bisFloorId;
    }
    
    public void setBisFloorId(String bisFloorId) {
    	this.bisFloorId = bisFloorId;
    }
    
    @Column(name="BIS_CONT_ID", length=50)
    public String getBisContId() {
        return this.bisContId;
    }
    
    public void setBisContId(String bisContId) {
        this.bisContId = bisContId;
    }
    
    @Column(name="MULTI_NAME", nullable=false, length=100)
    public String getMultiName() {
        return this.multiName;
    }
    
    public void setMultiName(String multiName) {
        this.multiName = multiName;
    }
    
    @Column(name="RENTER_NAME", length=100)
    public String getRenterName() {
        return this.renterName;
    }
    
    public void setRenterName(String renterName) {
        this.renterName = renterName;
    }
    
    @Column(name="OPERATION_PROJECT_CD", length=20)
    public String getOperationProjectCd() {
        return this.operationProjectCd;
    }
    
    public void setOperationProjectCd(String operationProjectCd) {
        this.operationProjectCd = operationProjectCd;
    }
    
    @Column(name="OPERATION_AREA", length=100)
    public String getOperationArea() {
        return this.operationArea;
    }
    
    public void setOperationArea(String operationArea) {
        this.operationArea = operationArea;
    }
    
    @Column(name="SQUARE", precision=10)
    public BigDecimal getSquare() {
        return this.square;
    }
    
    public void setSquare(BigDecimal square) {
        this.square = square;
    }
    
    @Column(name="CONT_PROMISE_BOND", precision=10)
    public BigDecimal getContPromiseBond() {
        return this.contPromiseBond;
    }
    
    public void setContPromiseBond(BigDecimal contPromiseBond) {
        this.contPromiseBond = contPromiseBond;
    }
    
    @Column(name="RECEIVED_BOND", precision=10)
    public BigDecimal getReceivedBond() {
        return this.receivedBond;
    }
    
    public void setReceivedBond(BigDecimal receivedBond) {
        this.receivedBond = receivedBond;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisMulti")
    @BatchSize(size=10)
public List<BisMultiContRel> getBisMultiContRels() {
        return this.bisMultiContRels;
    }
    
    public void setBisMultiContRels(List<BisMultiContRel> bisMultiContRels) {
        this.bisMultiContRels = bisMultiContRels;
    }
    
    @Column(name="MULTI_NO", length=50)
	public String getMultiNo() {
		return multiNo;
	}


	public void setMultiNo(String multiNo) {
		this.multiNo = multiNo;
	}


	@Column(name="MULTI_TYPE", length=2)
	public String getMultiType() {
		return multiType;
	}


	public void setMultiType(String multiType) {
		this.multiType = multiType;
	}

	@Column(name="MULTI_FLOOR", length=50)
	public String getMultiFloor() {
		return multiFloor;
	}


	public void setMultiFloor(String multiFloor) {
		this.multiFloor = multiFloor;
	}

	@Column(name="MULTI_GRADE", length=50)
	public String getMultiGrade() {
		return multiGrade;
	}


	public void setMultiGrade(String multiGrade) {
		this.multiGrade = multiGrade;
	}

	@Column(name="MULTI_PRICE", length=1000)
	public String getMultiPrice() {
		return multiPrice;
	}


	public void setMultiPrice(String multiPrice) {
		this.multiPrice = multiPrice;
	}

	@Column(name="MULTI_POLICY", length=1000)
	public String getMultiPolicy() {
		return multiPolicy;
	}


	public void setMultiPolicy(String multiPolicy) {
		this.multiPolicy = multiPolicy;
	}
    @Column(name="COORDS", length=2000)
    public String getCoords() {
        return this.coords;
    }
    
    public void setCoords(String coords) {
        this.coords = coords;
    }



}


