// 
package com.hhz.ump.entity.bis;
// Generated 2012-4-16 13:48:27 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * BisProject generated by hbm2java
 */
@Entity
@Table(name="BIS_PROJECT"
    
)
public class BisProject  implements java.io.Serializable {


     private String bisProjectId;
     private String projectName;
     private String areaCd;
     private String city;
     private String address;
     private String principalName;
     private String principalCd;
     private BigDecimal totalSquare;
     private BigDecimal storeSquare;
     private Long storeNum;
     private BigDecimal flatSquare;
     private Long flatNum;
     private BigDecimal parkSquare;
     private Long parkNum;
     private String discribe;
     private Date openDate;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String orgCd;
     private Long sequenceNo;
     private String projectShortName;
     private String rentSquare;
     private BigDecimal electricPrice;
     private BigDecimal waterPrice;
     private String projectFlg;
     private Boolean active;
     private Long sequenceNo2;
      //记录租费收缴率
     private String rentalCollectionRate;
     //记录主力店招商周报
     private String mainShopReport;
     /**记录商业街*/
     private String businessStreet;
     /**记录小商铺周报*/
     private String smallShopReport;
     /**决策平台-销售情况报表 -add liuzhihui 2012-07-03**/
     private String sellCondition;
    
    public BisProject() {
    }

	
    public BisProject(String bisProjectId, String projectName, long recordVersion, String orgCd, String projectShortName) {
        this.bisProjectId = bisProjectId;
        this.projectName = projectName;
        this.recordVersion = recordVersion;
        this.orgCd = orgCd;
        this.projectShortName = projectShortName;
    }
    public BisProject(String bisProjectId, String projectName, String areaCd, String city, String address, String principalName, String principalCd, BigDecimal totalSquare, BigDecimal storeSquare, Long storeNum, BigDecimal flatSquare, Long flatNum, BigDecimal parkSquare, Long parkNum, String discribe, Date openDate, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, String orgCd, Long sequenceNo, String projectShortName, String rentSquare, BigDecimal electricPrice, BigDecimal waterPrice, String projectFlg, Boolean active, Long sequenceNo2, String rentalCollectionRate, String mainShopReport,String sellCondition) {
       this.bisProjectId = bisProjectId;
       this.projectName = projectName;
       this.areaCd = areaCd;
       this.city = city;
       this.address = address;
       this.principalName = principalName;
       this.principalCd = principalCd;
       this.totalSquare = totalSquare;
       this.storeSquare = storeSquare;
       this.storeNum = storeNum;
       this.flatSquare = flatSquare;
       this.flatNum = flatNum;
       this.parkSquare = parkSquare;
       this.parkNum = parkNum;
       this.discribe = discribe;
       this.openDate = openDate;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.orgCd = orgCd;
       this.sequenceNo = sequenceNo;
       this.projectShortName = projectShortName;
       this.rentSquare = rentSquare;
       this.electricPrice = electricPrice;
       this.waterPrice = waterPrice;
       this.projectFlg = projectFlg;
       this.active = active;
       this.sequenceNo2 = sequenceNo2;
       this.rentalCollectionRate = rentalCollectionRate;
       this.mainShopReport = mainShopReport;
       this.sellCondition = sellCondition;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_PROJECT_ID", unique=true, nullable=false, length=50)
    public String getBisProjectId() {
        return this.bisProjectId;
    }
    
    public void setBisProjectId(String bisProjectId) {
        this.bisProjectId = bisProjectId;
    }
    
    @Column(name="PROJECT_NAME", nullable=false, length=50)
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    
    @Column(name="AREA_CD", length=20)
    public String getAreaCd() {
        return this.areaCd;
    }
    
    public void setAreaCd(String areaCd) {
        this.areaCd = areaCd;
    }
    
    @Column(name="CITY", length=50)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="ADDRESS", length=200)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="PRINCIPAL_NAME", length=50)
    public String getPrincipalName() {
        return this.principalName;
    }
    
    public void setPrincipalName(String principalName) {
        this.principalName = principalName;
    }
    
    @Column(name="PRINCIPAL_CD", length=20)
    public String getPrincipalCd() {
        return this.principalCd;
    }
    
    public void setPrincipalCd(String principalCd) {
        this.principalCd = principalCd;
    }
    
    @Column(name="TOTAL_SQUARE", precision=10)
    public BigDecimal getTotalSquare() {
        return this.totalSquare;
    }
    
    public void setTotalSquare(BigDecimal totalSquare) {
        this.totalSquare = totalSquare;
    }
    
    @Column(name="STORE_SQUARE", precision=10)
    public BigDecimal getStoreSquare() {
        return this.storeSquare;
    }
    
    public void setStoreSquare(BigDecimal storeSquare) {
        this.storeSquare = storeSquare;
    }
    
    @Column(name="STORE_NUM", precision=10, scale=0)
    public Long getStoreNum() {
        return this.storeNum;
    }
    
    public void setStoreNum(Long storeNum) {
        this.storeNum = storeNum;
    }
    
    @Column(name="FLAT_SQUARE", precision=10)
    public BigDecimal getFlatSquare() {
        return this.flatSquare;
    }
    
    public void setFlatSquare(BigDecimal flatSquare) {
        this.flatSquare = flatSquare;
    }
    
    @Column(name="FLAT_NUM", precision=10, scale=0)
    public Long getFlatNum() {
        return this.flatNum;
    }
    
    public void setFlatNum(Long flatNum) {
        this.flatNum = flatNum;
    }
    
    @Column(name="PARK_SQUARE", precision=10)
    public BigDecimal getParkSquare() {
        return this.parkSquare;
    }
    
    public void setParkSquare(BigDecimal parkSquare) {
        this.parkSquare = parkSquare;
    }
    
    @Column(name="PARK_NUM", precision=10, scale=0)
    public Long getParkNum() {
        return this.parkNum;
    }
    
    public void setParkNum(Long parkNum) {
        this.parkNum = parkNum;
    }
    
    @Column(name="DISCRIBE", length=1000)
    public String getDiscribe() {
        return this.discribe;
    }
    
    public void setDiscribe(String discribe) {
        this.discribe = discribe;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="OPEN_DATE", length=7)
    public Date getOpenDate() {
        return this.openDate;
    }
    
    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="ORG_CD", nullable=false, length=50)
    public String getOrgCd() {
        return this.orgCd;
    }
    
    public void setOrgCd(String orgCd) {
        this.orgCd = orgCd;
    }
    
    @Column(name="SEQUENCE_NO", precision=10, scale=0)
    public Long getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Long sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    
    @Column(name="PROJECT_SHORT_NAME", nullable=false, length=50)
    public String getProjectShortName() {
        return this.projectShortName;
    }
    
    public void setProjectShortName(String projectShortName) {
        this.projectShortName = projectShortName;
    }
    
    @Column(name="RENT_SQUARE", length=1)
    public String getRentSquare() {
        return this.rentSquare;
    }
    
    public void setRentSquare(String rentSquare) {
        this.rentSquare = rentSquare;
    }
    
    @Column(name="ELECTRIC_PRICE", precision=10)
    public BigDecimal getElectricPrice() {
        return this.electricPrice;
    }
    
    public void setElectricPrice(BigDecimal electricPrice) {
        this.electricPrice = electricPrice;
    }
    
    @Column(name="WATER_PRICE", precision=10)
    public BigDecimal getWaterPrice() {
        return this.waterPrice;
    }
    
    public void setWaterPrice(BigDecimal waterPrice) {
        this.waterPrice = waterPrice;
    }
    
    @Column(name="PROJECT_FLG", length=2)
    public String getProjectFlg() {
        return this.projectFlg;
    }
    
    public void setProjectFlg(String projectFlg) {
        this.projectFlg = projectFlg;
    }
    
    @Column(name="ACTIVE", precision=1, scale=0)
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    
    @Column(name="SEQUENCE_NO2", precision=10, scale=0)
    public Long getSequenceNo2() {
        return this.sequenceNo2;
    }
    
    public void setSequenceNo2(Long sequenceNo2) {
        this.sequenceNo2 = sequenceNo2;
    }
    
    @Column(name="RENTAL_COLLECTION_RATE", length=5)
    public String getRentalCollectionRate() {
        return this.rentalCollectionRate;
    }
    
    public void setRentalCollectionRate(String rentalCollectionRate) {
        this.rentalCollectionRate = rentalCollectionRate;
    }
    
    @Column(name="MAIN_SHOP_REPORT", length=5)
    public String getMainShopReport() {
        return this.mainShopReport;
    }
    
    public void setMainShopReport(String mainShopReport) {
        this.mainShopReport = mainShopReport;
    }

    @Column(name="SELL_CONDITION", length=5)
	public String getSellCondition() {
		return sellCondition;
	}

	public void setSellCondition(String sellCondition) {
		this.sellCondition = sellCondition;
	}

	public String getBusinessStreet() {
		return businessStreet;
	}


	public void setBusinessStreet(String businessStreet) {
		this.businessStreet = businessStreet;
	}


	public String getSmallShopReport() {
		return smallShopReport;
	}


	public void setSmallShopReport(String smallShopReport) {
		this.smallShopReport = smallShopReport;
	}
    
}


