// 
package com.hhz.ump.entity.bis;
// Generated 2012-6-8 12:50:34 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * BisReport generated by hbm2java
 */
@Entity
@Table(name="BIS_REPORT"
    
)
public class BisReport  implements java.io.Serializable {


     private String bisReportId;
     private String statDimansion;
     private String reportType;
     private String openBl;
     private Date reportMonth;
     private Date statDate;
     private String chargeTypeCd;
     private String bisProjectId;
     private String timeDimansion;
     private BigDecimal moneyMust;
     private BigDecimal moneyFact;
     private BigDecimal moneyRate;
     private String remark;
     private Boolean active;
     private BigDecimal moneyArrear;

    public BisReport() {
    }

	
    public BisReport(String bisReportId) {
        this.bisReportId = bisReportId;
    }
    public BisReport(String bisReportId, String statDimansion, String reportType, String openBl, Date reportMonth, Date statDate, String chargeTypeCd, String bisProjectId, String timeDimansion, BigDecimal moneyMust, BigDecimal moneyFact, BigDecimal moneyRate, String remark, Boolean active, BigDecimal moneyArrear) {
       this.bisReportId = bisReportId;
       this.statDimansion = statDimansion;
       this.reportType = reportType;
       this.openBl = openBl;
       this.reportMonth = reportMonth;
       this.statDate = statDate;
       this.chargeTypeCd = chargeTypeCd;
       this.bisProjectId = bisProjectId;
       this.timeDimansion = timeDimansion;
       this.moneyMust = moneyMust;
       this.moneyFact = moneyFact;
       this.moneyRate = moneyRate;
       this.remark = remark;
       this.active = active;
       this.moneyArrear = moneyArrear;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_REPORT_ID", unique=true, nullable=false, length=50)
    public String getBisReportId() {
        return this.bisReportId;
    }
    
    public void setBisReportId(String bisReportId) {
        this.bisReportId = bisReportId;
    }
    
    @Column(name="STAT_DIMANSION", length=1)
    public String getStatDimansion() {
        return this.statDimansion;
    }
    
    public void setStatDimansion(String statDimansion) {
        this.statDimansion = statDimansion;
    }
    
    @Column(name="REPORT_TYPE", length=1)
    public String getReportType() {
        return this.reportType;
    }
    
    public void setReportType(String reportType) {
        this.reportType = reportType;
    }
    
    @Column(name="OPEN_BL", length=1)
    public String getOpenBl() {
        return this.openBl;
    }
    
    public void setOpenBl(String openBl) {
        this.openBl = openBl;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REPORT_MONTH", length=7)
    public Date getReportMonth() {
        return this.reportMonth;
    }
    
    public void setReportMonth(Date reportMonth) {
        this.reportMonth = reportMonth;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="STAT_DATE", length=7)
    public Date getStatDate() {
        return this.statDate;
    }
    
    public void setStatDate(Date statDate) {
        this.statDate = statDate;
    }
    
    @Column(name="CHARGE_TYPE_CD", length=20)
    public String getChargeTypeCd() {
        return this.chargeTypeCd;
    }
    
    public void setChargeTypeCd(String chargeTypeCd) {
        this.chargeTypeCd = chargeTypeCd;
    }
    
    @Column(name="BIS_PROJECT_ID", length=50)
    public String getBisProjectId() {
        return this.bisProjectId;
    }
    
    public void setBisProjectId(String bisProjectId) {
        this.bisProjectId = bisProjectId;
    }
    
    @Column(name="TIME_DIMANSION", length=1)
    public String getTimeDimansion() {
        return this.timeDimansion;
    }
    
    public void setTimeDimansion(String timeDimansion) {
        this.timeDimansion = timeDimansion;
    }
    
    @Column(name="MONEY_MUST", precision=10)
    public BigDecimal getMoneyMust() {
        return this.moneyMust;
    }
    
    public void setMoneyMust(BigDecimal moneyMust) {
        this.moneyMust = moneyMust;
    }
    
    @Column(name="MONEY_FACT", precision=10)
    public BigDecimal getMoneyFact() {
        return this.moneyFact;
    }
    
    public void setMoneyFact(BigDecimal moneyFact) {
        this.moneyFact = moneyFact;
    }
    
    @Column(name="MONEY_RATE", precision=10)
    public BigDecimal getMoneyRate() {
        return this.moneyRate;
    }
    
    public void setMoneyRate(BigDecimal moneyRate) {
        this.moneyRate = moneyRate;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="ACTIVE", precision=1, scale=0)
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    
    @Column(name="MONEY_ARREAR", precision=10)
    public BigDecimal getMoneyArrear() {
        return this.moneyArrear;
    }
    
    public void setMoneyArrear(BigDecimal moneyArrear) {
        this.moneyArrear = moneyArrear;
    }




}


