// 
package com.hhz.ump.entity.bis;
// Generated 2011-8-3 22:32:28 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * BisShopConn generated by hbm2java
 */
@Entity
@Table(name="BIS_SHOP_CONN"
    
)
public class BisShopConn  implements java.io.Serializable {


     private String bisShopConnId;
     private BisShop bisShop;
     private String partName;
     private String principal;
     private String partAddress;
     private String postCode;
     private String fax;
     private String cooperatedShop;
     private String toCooperateShop;
     private String conditionForCooperation;
     private String principalPos;
     private String principalPhone;
     private String principalTel;
     private String principalEmail;
     private String supplierAttributeCd;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String manageCity;
     private String deleteBl;

    public BisShopConn() {
    }

	
    public BisShopConn(String bisShopConnId, BisShop bisShop, long recordVersion) {
        this.bisShopConnId = bisShopConnId;
        this.bisShop = bisShop;
        this.recordVersion = recordVersion;
    }
    public BisShopConn(String bisShopConnId, BisShop bisShop, String partName, String principal, String partAddress, String postCode, String fax, String cooperatedShop, String toCooperateShop, String conditionForCooperation, String principalPos, String principalPhone, String principalTel, String principalEmail, String supplierAttributeCd, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, String manageCity,String deleteBl) {
       this.bisShopConnId = bisShopConnId;
       this.bisShop = bisShop;
       this.partName = partName;
       this.principal = principal;
       this.partAddress = partAddress;
       this.postCode = postCode;
       this.fax = fax;
       this.cooperatedShop = cooperatedShop;
       this.toCooperateShop = toCooperateShop;
       this.conditionForCooperation = conditionForCooperation;
       this.principalPos = principalPos;
       this.principalPhone = principalPhone;
       this.principalTel = principalTel;
       this.principalEmail = principalEmail;
       this.supplierAttributeCd = supplierAttributeCd;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.manageCity = manageCity;
       this.deleteBl = deleteBl;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_SHOP_CONN_ID", unique=true, nullable=false, length=50)
    public String getBisShopConnId() {
        return this.bisShopConnId;
    }
    
    public void setBisShopConnId(String bisShopConnId) {
        this.bisShopConnId = bisShopConnId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIS_SHOP_ID", nullable=false)
    public BisShop getBisShop() {
        return this.bisShop;
    }
    
    public void setBisShop(BisShop bisShop) {
        this.bisShop = bisShop;
    }
    
    @Column(name="PART_NAME", length=300)
    public String getPartName() {
        return this.partName;
    }
    
    public void setPartName(String partName) {
        this.partName = partName;
    }
    
    @Column(name="PRINCIPAL", length=300)
    public String getPrincipal() {
        return this.principal;
    }
    
    public void setPrincipal(String principal) {
        this.principal = principal;
    }
    
    @Column(name="PART_ADDRESS", length=200)
    public String getPartAddress() {
        return this.partAddress;
    }
    
    public void setPartAddress(String partAddress) {
        this.partAddress = partAddress;
    }
    
    @Column(name="POST_CODE", length=100)
    public String getPostCode() {
        return this.postCode;
    }
    
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }
    
    @Column(name="FAX", length=100)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    
    @Column(name="COOPERATED_SHOP", length=100)
    public String getCooperatedShop() {
        return this.cooperatedShop;
    }
    
    public void setCooperatedShop(String cooperatedShop) {
        this.cooperatedShop = cooperatedShop;
    }
    
    @Column(name="TO_COOPERATE_SHOP", length=100)
    public String getToCooperateShop() {
        return this.toCooperateShop;
    }
    
    public void setToCooperateShop(String toCooperateShop) {
        this.toCooperateShop = toCooperateShop;
    }
    
    @Column(name="CONDITION_FOR_COOPERATION", length=200)
    public String getConditionForCooperation() {
        return this.conditionForCooperation;
    }
    
    public void setConditionForCooperation(String conditionForCooperation) {
        this.conditionForCooperation = conditionForCooperation;
    }
    
    @Column(name="PRINCIPAL_POS", length=300)
    public String getPrincipalPos() {
        return this.principalPos;
    }
    
    public void setPrincipalPos(String principalPos) {
        this.principalPos = principalPos;
    }
    
    @Column(name="PRINCIPAL_PHONE", length=300)
    public String getPrincipalPhone() {
        return this.principalPhone;
    }
    
    public void setPrincipalPhone(String principalPhone) {
        this.principalPhone = principalPhone;
    }
    
    @Column(name="PRINCIPAL_TEL", length=300)
    public String getPrincipalTel() {
        return this.principalTel;
    }
    
    public void setPrincipalTel(String principalTel) {
        this.principalTel = principalTel;
    }
    
    @Column(name="PRINCIPAL_EMAIL", length=300)
    public String getPrincipalEmail() {
        return this.principalEmail;
    }
    
    public void setPrincipalEmail(String principalEmail) {
        this.principalEmail = principalEmail;
    }
    
    @Column(name="SUPPLIER_ATTRIBUTE_CD", length=20)
    public String getSupplierAttributeCd() {
        return this.supplierAttributeCd;
    }
    
    public void setSupplierAttributeCd(String supplierAttributeCd) {
        this.supplierAttributeCd = supplierAttributeCd;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="MANAGE_CITY", length=200)
    public String getManageCity() {
        return this.manageCity;
    }
    
    public void setManageCity(String manageCity) {
        this.manageCity = manageCity;
    }

    @Column(name="DELETE_BL", length=2)
	public String getDeleteBl() {
		return deleteBl;
	}


	public void setDeleteBl(String deleteBl) {
		this.deleteBl = deleteBl;
	}




}


