// 
package com.hhz.ump.entity.bis;
// Generated 2011-8-3 22:32:28 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OrderBy;
import org.hibernate.annotations.Where;

/**
 * BisShop generated by hbm2java
 */
@Entity
@Table(name="BIS_SHOP"
    
)
public class BisShop  implements java.io.Serializable {


	private String bisShopId;
    private String brandDesc;
    private String postCode;
    private String cooperatedShop;
    private String toCooperateShop;
    private String manageCd;
    private String shopTypeCd;
    private String nameCn;
    private String brandLevelCd;
    private String brandCradleland;
    private String nameEn;
    private String registerAddr;
    private String produceAddr;
    private String hqAddr;
    private String companyName;
    private String companyTel;
    private String comCooperCondition;
    private String founderPeople;
    private Date founderDate;
    private String webSite;
    private String principal;
    private String principalPos;
    private String principalPhone;
    private String principal2;
    private String principalPos2;
    private String principalPhone2;
    private String principal3;
    private String principalPos3;
    private String principalPhone3;
    private String principalTel;
    private String principalEmail;
    private Long globalNum;
    private String chinaHqAddr;
    private Date chinaOpenDate;
    private Long chinaNum;
    private String openedCity;
    private Long openedNum;
    private String planCity;
    private BigDecimal avgSingleYearMoney;
    private BigDecimal singleYearMaxMoney;
    private String singleYearMaxName;
    private BigDecimal singleYearMinMoney;
    private String singleYearMinName;
    private String normalCoopWayCd;
    private BigDecimal standardSquare;
    private BigDecimal maxSquare;
    private BigDecimal minSquare;
    private String openBaseRequire;
    private String marketLevelCd;
    private String spokesman;
    private String consumeAge;
    private String consumeObj;
    private String competeBrand;
    private Long yearTotalMoney;
    private String productStyle;
    private String adPos;
    private String businessType;
    private String logo;
    private String contactPhone;
    private String fax;
    private String brandType;
    private String brandDevelopPlan;
    private String radiationRange;
    private BigDecimal sizeOfPopulation;
    private BigDecimal averageIncome;
    private String corrival;
    private String businessDistrict;
    private String trafficRequire;
    private String mallSquare;
    private String kitchenSquare;
    private String warehouseSquare;
    private String logisticsSquare;
    private String receiveStall;
    private String customerStall;
    private String bicycleStall;
    private String mallFloorHeight;
    private String parkFloorHeight;
    private String receivePlace;
    private String mallBearing;
    private String parkBearing;
    private String span;
    private String pillarSize;
    private String distancePillarWall;
    private String cable;
    private String waterSupply;
    private String airSupply;
    private String summerRequire;
    private String winterRequire;
    private String coolingTower;
    private String freshWindPortPosi;
    private String exhaustOutletPosi;
    private String lamblackAbsorber;
    private String pipelineCaliber;
    private String separationTank;
    private String septicTank;
    private String firstDiscuss;
    private String secondDiscuss;
    private String thirdDiscuss;
    private String businessPersonnel;
    private Date createFileDate;
    private String checker;
    private String remark;
    private String creator;
    private String createdCenterCd;
    private String createdDeptCd;
    private String createdPositionCd;
    private Date createdDate;
    private String updator;
    private String updatedCenterCd;
    private String deleteBl;
    private String updatedDeptCd;
    private String updatedPositionCd;
    private Date updatedDate;
    private long recordVersion;
    private String storeImg;
    private String openPlan;
    private String importantArea;
    private String otherArea;
    private BigDecimal totalShopNum;
    private String distributeCoun;
    private BigDecimal countryNum;
    private String distributeCity;
    private String inforConf;
    private String examResu;
    private String manaEval;
    private String gdp;
    private String cooperatedShopUn;
    private String areaCooperStr;
    private String bisShopDept;
    private String bisShopAudit;
    private String bisEvaluate;
    private String userFireBl;
    private String fireArea;
    private String rentPromotions;
    private String supExamResu;
    private String supInfoVeri;
    private String examResuPerson;
    private String examResuContent;
    private String supEvaluate;
    private String supManaEval;
    private String examResuAttch;
    private String supevalattach;
    private String supManaEvalAttach;
    private String salesman;
    private String attention;
    private List<BisShopCredit> bisShopCredits = new ArrayList<BisShopCredit>();
    private List<BisShopVisit> bisShopVisits = new ArrayList<BisShopVisit>();
    private List<BisShopConn> bisShopConns = new ArrayList<BisShopConn>();
    private List<BisShopSortRel> bisShopSortRels = new ArrayList<BisShopSortRel>();
    
    private String shopLevel; //商家级别
    private String cooperateArea; //配合区域
    private String cooperateAreaCd; //配合区域Cd
    private String strategicShop; //战略商家(1：是，0：否)
    private String benchmarkShop; //标杆商家(1：是，0：否)
    private String cooperateArchives; //合作档案
    private String investigationLevel; //考察等级
    private String companyTelBaseinfo; //基本信息-公司电话
     
     
    public BisShop() {
    }

	
    public BisShop(String bisShopId, long recordVersion) {
        this.bisShopId = bisShopId;
        this.recordVersion = recordVersion;
    }
    public BisShop(String bisShopId, String brandDesc, String postCode, String cooperatedShop, String toCooperateShop, String manageCd, String shopTypeCd, String nameCn, String brandLevelCd, String brandCradleland, String nameEn, String registerAddr, String produceAddr, String hqAddr, String companyName, String companyTel, String comCooperCondition, String founderPeople, Date founderDate, String webSite, String principal, String principalPos, String principalPhone, String principal2, String principalPos2, String principalPhone2, String principal3, String principalPos3, String principalPhone3, String principalTel, String principalEmail, Long globalNum, String chinaHqAddr, Date chinaOpenDate, Long chinaNum, String openedCity, Long openedNum, String planCity, BigDecimal avgSingleYearMoney, BigDecimal singleYearMaxMoney, String singleYearMaxName, BigDecimal singleYearMinMoney, String singleYearMinName, String normalCoopWayCd, BigDecimal standardSquare, BigDecimal maxSquare, BigDecimal minSquare, String openBaseRequire, String marketLevelCd, String spokesman, String consumeAge, String consumeObj, String competeBrand, Long yearTotalMoney, String productStyle, String adPos, String businessType, String logo, String contactPhone, String fax, String brandType, String brandDevelopPlan, String radiationRange, BigDecimal sizeOfPopulation, BigDecimal averageIncome, String corrival, String businessDistrict, String trafficRequire, String mallSquare, String kitchenSquare, String warehouseSquare, String logisticsSquare, String receiveStall, String customerStall, String bicycleStall, String mallFloorHeight, String parkFloorHeight, String receivePlace, String mallBearing, String parkBearing, String span, String pillarSize, String distancePillarWall, String cable, String waterSupply, String airSupply, String summerRequire, String winterRequire, String coolingTower, String freshWindPortPosi, String exhaustOutletPosi, String lamblackAbsorber, String pipelineCaliber, String separationTank, String septicTank, String firstDiscuss, String secondDiscuss, String thirdDiscuss, String businessPersonnel, Date createFileDate, String checker, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String deleteBl, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, String storeImg, String openPlan, String importantArea, String otherArea, BigDecimal totalShopNum, String distributeCoun, BigDecimal countryNum, String distributeCity, String inforConf, String examResu, String manaEval, String gdp, String cooperatedShopUn,String areaCooperStr, List<BisShopCredit> bisShopCredits, List<BisShopVisit> bisShopVisits, List<BisShopConn> bisShopConns, List<BisShopSortRel> bisShopSortRels,String bisShopAudit,String bisShopDept,String bisEvaluate,String userFireBl,String fireArea,String rentPromotions,String supExamResu, String supInfoVeri, String examResuPerson, String examResuContent, String supEvaluate, String supManaEval,
    	String examResuAttch,String supevalattach,String supManaEvalAttach,String salesman,String attention, String shopLevel, String cooperateArea,String cooperateAreaCd, String strategicShop, String benchmarkShop, String cooperateArchives, String investigationLevel,String companyTelBaseinfo) {
       this.bisShopId = bisShopId;
       this.brandDesc = brandDesc;
       this.postCode = postCode;
       this.cooperatedShop = cooperatedShop;
       this.toCooperateShop = toCooperateShop;
       this.manageCd = manageCd;
       this.shopTypeCd = shopTypeCd;
       this.nameCn = nameCn;
       this.brandLevelCd = brandLevelCd;
       this.brandCradleland = brandCradleland;
       this.nameEn = nameEn;
       this.registerAddr = registerAddr;
       this.produceAddr = produceAddr;
       this.hqAddr = hqAddr;
       this.companyName = companyName;
       this.companyTel = companyTel;
       this.comCooperCondition = comCooperCondition;
       this.founderPeople = founderPeople;
       this.founderDate = founderDate;
       this.webSite = webSite;
       this.principal = principal;
       this.principalPos = principalPos;
       this.principalPhone = principalPhone;
       this.principal2 = principal2;
       this.principalPos2 = principalPos2;
       this.principalPhone2 = principalPhone2;
       this.principal3 = principal3;
       this.principalPos3 = principalPos3;
       this.principalPhone3 = principalPhone3;
       this.principalTel = principalTel;
       this.principalEmail = principalEmail;
       this.globalNum = globalNum;
       this.chinaHqAddr = chinaHqAddr;
       this.chinaOpenDate = chinaOpenDate;
       this.chinaNum = chinaNum;
       this.openedCity = openedCity;
       this.openedNum = openedNum;
       this.planCity = planCity;
       this.avgSingleYearMoney = avgSingleYearMoney;
       this.singleYearMaxMoney = singleYearMaxMoney;
       this.singleYearMaxName = singleYearMaxName;
       this.singleYearMinMoney = singleYearMinMoney;
       this.singleYearMinName = singleYearMinName;
       this.normalCoopWayCd = normalCoopWayCd;
       this.standardSquare = standardSquare;
       this.maxSquare = maxSquare;
       this.minSquare = minSquare;
       this.openBaseRequire = openBaseRequire;
       this.marketLevelCd = marketLevelCd;
       this.spokesman = spokesman;
       this.consumeAge = consumeAge;
       this.consumeObj = consumeObj;
       this.competeBrand = competeBrand;
       this.yearTotalMoney = yearTotalMoney;
       this.productStyle = productStyle;
       this.adPos = adPos;
       this.businessType = businessType;
       this.logo = logo;
       this.contactPhone = contactPhone;
       this.fax = fax;
       this.brandType = brandType;
       this.brandDevelopPlan = brandDevelopPlan;
       this.radiationRange = radiationRange;
       this.sizeOfPopulation = sizeOfPopulation;
       this.averageIncome = averageIncome;
       this.corrival = corrival;
       this.businessDistrict = businessDistrict;
       this.trafficRequire = trafficRequire;
       this.mallSquare = mallSquare;
       this.kitchenSquare = kitchenSquare;
       this.warehouseSquare = warehouseSquare;
       this.logisticsSquare = logisticsSquare;
       this.receiveStall = receiveStall;
       this.customerStall = customerStall;
       this.bicycleStall = bicycleStall;
       this.mallFloorHeight = mallFloorHeight;
       this.parkFloorHeight = parkFloorHeight;
       this.receivePlace = receivePlace;
       this.mallBearing = mallBearing;
       this.parkBearing = parkBearing;
       this.span = span;
       this.pillarSize = pillarSize;
       this.distancePillarWall = distancePillarWall;
       this.cable = cable;
       this.waterSupply = waterSupply;
       this.airSupply = airSupply;
       this.summerRequire = summerRequire;
       this.winterRequire = winterRequire;
       this.coolingTower = coolingTower;
       this.freshWindPortPosi = freshWindPortPosi;
       this.exhaustOutletPosi = exhaustOutletPosi;
       this.lamblackAbsorber = lamblackAbsorber;
       this.pipelineCaliber = pipelineCaliber;
       this.separationTank = separationTank;
       this.septicTank = septicTank;
       this.firstDiscuss = firstDiscuss;
       this.secondDiscuss = secondDiscuss;
       this.thirdDiscuss = thirdDiscuss;
       this.businessPersonnel = businessPersonnel;
       this.createFileDate = createFileDate;
       this.checker = checker;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.deleteBl = deleteBl;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.storeImg = storeImg;
       this.openPlan = openPlan;
       this.importantArea = importantArea;
       this.otherArea = otherArea;
       this.totalShopNum = totalShopNum;
       this.distributeCoun = distributeCoun;
       this.countryNum = countryNum;
       this.distributeCity = distributeCity;
       this.inforConf = inforConf;
       this.examResu = examResu;
       this.manaEval = manaEval;
       this.gdp = gdp;
       this.cooperatedShopUn = cooperatedShopUn;
       this.areaCooperStr =areaCooperStr;
       this.bisShopCredits = bisShopCredits;
       this.bisShopVisits = bisShopVisits;
       this.bisShopConns = bisShopConns;
       this.bisShopSortRels = bisShopSortRels;
       this.bisShopAudit = bisShopAudit;
       this.bisShopDept = bisShopDept;
       this.bisEvaluate = bisEvaluate;
       this.userFireBl = userFireBl;
       this.fireArea = fireArea;
       this.rentPromotions = rentPromotions;
       this.supExamResu = supExamResu;
       this.supInfoVeri = supInfoVeri;
       this.examResuPerson = examResuPerson;
       this.examResuContent = examResuContent;
       this.supEvaluate = supEvaluate;
       this.supManaEval = supManaEval;
       this.examResuAttch =examResuAttch;
       this.examResuAttch=examResuAttch; 
       this.supevalattach=supevalattach;
       this.supManaEvalAttach =supManaEvalAttach;
       this.salesman = salesman;
       this.attention = attention;
       this.shopLevel = shopLevel;
       this.cooperateArea = cooperateArea;
       this.cooperateAreaCd = cooperateAreaCd;
       this.strategicShop = strategicShop;
       this.benchmarkShop = benchmarkShop;
       this.cooperateArchives = cooperateArchives;
       this.investigationLevel = investigationLevel;
       this.companyTelBaseinfo = companyTelBaseinfo;
    }
   
    @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_SHOP_ID", unique=true, nullable=false, length=50)
    public String getBisShopId() {
        return this.bisShopId;
    }
    
    public void setBisShopId(String bisShopId) {
        this.bisShopId = bisShopId;
    }
    
    @Column(name="BRAND_DESC", length=2000)
    public String getBrandDesc() {
        return this.brandDesc;
    }
    
    public void setBrandDesc(String brandDesc) {
        this.brandDesc = brandDesc;
    }
    
    @Column(name="POST_CODE", length=100)
    public String getPostCode() {
        return this.postCode;
    }
    
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }
    
    @Column(name="COOPERATED_SHOP", length=100)
    public String getCooperatedShop() {
        return this.cooperatedShop;
    }
    
    public void setCooperatedShop(String cooperatedShop) {
        this.cooperatedShop = cooperatedShop;
    }
    
    @Column(name="TO_COOPERATE_SHOP", length=100)
    public String getToCooperateShop() {
        return this.toCooperateShop;
    }
    
    public void setToCooperateShop(String toCooperateShop) {
        this.toCooperateShop = toCooperateShop;
    }
    
    @Column(name="MANAGE_CD", length=20)
    public String getManageCd() {
        return this.manageCd;
    }
    
    public void setManageCd(String manageCd) {
        this.manageCd = manageCd;
    }
    
    @Column(name="SHOP_TYPE_CD", length=100)
    public String getShopTypeCd() {
        return this.shopTypeCd;
    }
    
    public void setShopTypeCd(String shopTypeCd) {
        this.shopTypeCd = shopTypeCd;
    }
    
    @Column(name="NAME_CN", length=100)
    public String getNameCn() {
        return this.nameCn;
    }
    
    public void setNameCn(String nameCn) {
        this.nameCn = nameCn;
    }
    
    @Column(name="BRAND_LEVEL_CD", length=20)
    public String getBrandLevelCd() {
        return this.brandLevelCd;
    }
    
    public void setBrandLevelCd(String brandLevelCd) {
        this.brandLevelCd = brandLevelCd;
    }
    
    @Column(name="BRAND_CRADLELAND", length=200)
    public String getBrandCradleland() {
        return this.brandCradleland;
    }
    
    public void setBrandCradleland(String brandCradleland) {
        this.brandCradleland = brandCradleland;
    }
    
    @Column(name="NAME_EN", length=100)
    public String getNameEn() {
        return this.nameEn;
    }
    
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }
    
    @Column(name="REGISTER_ADDR", length=300)
    public String getRegisterAddr() {
        return this.registerAddr;
    }
    
    public void setRegisterAddr(String registerAddr) {
        this.registerAddr = registerAddr;
    }
    
    @Column(name="PRODUCE_ADDR", length=300)
    public String getProduceAddr() {
        return this.produceAddr;
    }
    
    public void setProduceAddr(String produceAddr) {
        this.produceAddr = produceAddr;
    }
    
    @Column(name="HQ_ADDR", length=300)
    public String getHqAddr() {
        return this.hqAddr;
    }
    
    public void setHqAddr(String hqAddr) {
        this.hqAddr = hqAddr;
    }
    
    @Column(name="COMPANY_NAME", length=300)
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    
    @Column(name="COMPANY_TEL", length=100)
    public String getCompanyTel() {
        return this.companyTel;
    }
    
    public void setCompanyTel(String companyTel) {
        this.companyTel = companyTel;
    }
    
    @Column(name="COM_COOPER_CONDITION", length=400)
    public String getComCooperCondition() {
        return this.comCooperCondition;
    }
    
    public void setComCooperCondition(String comCooperCondition) {
        this.comCooperCondition = comCooperCondition;
    }
    
    @Column(name="FOUNDER_PEOPLE", length=100)
    public String getFounderPeople() {
        return this.founderPeople;
    }
    
    public void setFounderPeople(String founderPeople) {
        this.founderPeople = founderPeople;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FOUNDER_DATE", length=7)
    public Date getFounderDate() {
        return this.founderDate;
    }
    
    public void setFounderDate(Date founderDate) {
        this.founderDate = founderDate;
    }
    
    @Column(name="WEB_SITE", length=300)
    public String getWebSite() {
        return this.webSite;
    }
    
    public void setWebSite(String webSite) {
        this.webSite = webSite;
    }
    
    @Column(name="PRINCIPAL", length=100)
    public String getPrincipal() {
        return this.principal;
    }
    
    public void setPrincipal(String principal) {
        this.principal = principal;
    }
    
    @Column(name="PRINCIPAL_POS", length=100)
    public String getPrincipalPos() {
        return this.principalPos;
    }
    
    public void setPrincipalPos(String principalPos) {
        this.principalPos = principalPos;
    }
    
    @Column(name="PRINCIPAL_PHONE", length=100)
    public String getPrincipalPhone() {
        return this.principalPhone;
    }
    
    public void setPrincipalPhone(String principalPhone) {
        this.principalPhone = principalPhone;
    }
    
    @Column(name="PRINCIPAL2", length=100)
    public String getPrincipal2() {
		return principal2;
	}


	public void setPrincipal2(String principal2) {
		this.principal2 = principal2;
	}

	@Column(name="PRINCIPAL_POS2", length=100)
	public String getPrincipalPos2() {
		return principalPos2;
	}


	public void setPrincipalPos2(String principalPos2) {
		this.principalPos2 = principalPos2;
	}

	@Column(name="PRINCIPAL_PHONE2", length=100)
	public String getPrincipalPhone2() {
		return principalPhone2;
	}


	public void setPrincipalPhone2(String principalPhone2) {
		this.principalPhone2 = principalPhone2;
	}

	@Column(name="PRINCIPAL3", length=100)
	public String getPrincipal3() {
		return principal3;
	}


	public void setPrincipal3(String principal3) {
		this.principal3 = principal3;
	}

	@Column(name="PRINCIPAL_POS3", length=100)
	public String getPrincipalPos3() {
		return principalPos3;
	}


	public void setPrincipalPos3(String principalPos3) {
		this.principalPos3 = principalPos3;
	}

	@Column(name="PRINCIPAL_PHONE3", length=100)
	public String getPrincipalPhone3() {
		return principalPhone3;
	}


	public void setPrincipalPhone3(String principalPhone3) {
		this.principalPhone3 = principalPhone3;
	}


	@Column(name="PRINCIPAL_TEL", length=100)
    public String getPrincipalTel() {
        return this.principalTel;
    }
    
    public void setPrincipalTel(String principalTel) {
        this.principalTel = principalTel;
    }
    
    @Column(name="PRINCIPAL_EMAIL", length=100)
    public String getPrincipalEmail() {
        return this.principalEmail;
    }
    
    public void setPrincipalEmail(String principalEmail) {
        this.principalEmail = principalEmail;
    }
    
    @Column(name="GLOBAL_NUM", precision=10, scale=0)
    public Long getGlobalNum() {
        return this.globalNum;
    }
    
    public void setGlobalNum(Long globalNum) {
        this.globalNum = globalNum;
    }
    
    @Column(name="CHINA_HQ_ADDR", length=300)
    public String getChinaHqAddr() {
        return this.chinaHqAddr;
    }
    
    public void setChinaHqAddr(String chinaHqAddr) {
        this.chinaHqAddr = chinaHqAddr;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CHINA_OPEN_DATE", length=7)
    public Date getChinaOpenDate() {
        return this.chinaOpenDate;
    }
    
    public void setChinaOpenDate(Date chinaOpenDate) {
        this.chinaOpenDate = chinaOpenDate;
    }
    
    @Column(name="CHINA_NUM", precision=10, scale=0)
    public Long getChinaNum() {
        return this.chinaNum;
    }
    
    public void setChinaNum(Long chinaNum) {
        this.chinaNum = chinaNum;
    }
    
    @Column(name="OPENED_CITY", length=1000)
    public String getOpenedCity() {
        return this.openedCity;
    }
    
    public void setOpenedCity(String openedCity) {
        this.openedCity = openedCity;
    }
    
    @Column(name="OPENED_NUM", precision=10, scale=0)
    public Long getOpenedNum() {
        return this.openedNum;
    }
    
    public void setOpenedNum(Long openedNum) {
        this.openedNum = openedNum;
    }
    
    @Column(name="PLAN_CITY", length=1000)
    public String getPlanCity() {
        return this.planCity;
    }
    
    public void setPlanCity(String planCity) {
        this.planCity = planCity;
    }
    
    @Column(name="AVG_SINGLE_YEAR_MONEY", precision=10)
    public BigDecimal getAvgSingleYearMoney() {
        return this.avgSingleYearMoney;
    }
    
    public void setAvgSingleYearMoney(BigDecimal avgSingleYearMoney) {
        this.avgSingleYearMoney = avgSingleYearMoney;
    }
    
    @Column(name="SINGLE_YEAR_MAX_MONEY", precision=10)
    public BigDecimal getSingleYearMaxMoney() {
        return this.singleYearMaxMoney;
    }
    
    public void setSingleYearMaxMoney(BigDecimal singleYearMaxMoney) {
        this.singleYearMaxMoney = singleYearMaxMoney;
    }
    
    @Column(name="SINGLE_YEAR_MAX_NAME", length=100)
    public String getSingleYearMaxName() {
        return this.singleYearMaxName;
    }
    
    public void setSingleYearMaxName(String singleYearMaxName) {
        this.singleYearMaxName = singleYearMaxName;
    }
    
    @Column(name="SINGLE_YEAR_MIN_MONEY", precision=10)
    public BigDecimal getSingleYearMinMoney() {
        return this.singleYearMinMoney;
    }
    
    public void setSingleYearMinMoney(BigDecimal singleYearMinMoney) {
        this.singleYearMinMoney = singleYearMinMoney;
    }
    
    @Column(name="SINGLE_YEAR_MIN_NAME", length=100)
    public String getSingleYearMinName() {
        return this.singleYearMinName;
    }
    
    public void setSingleYearMinName(String singleYearMinName) {
        this.singleYearMinName = singleYearMinName;
    }
    
    @Column(name="NORMAL_COOP_WAY_CD", length=20)
    public String getNormalCoopWayCd() {
        return this.normalCoopWayCd;
    }
    
    public void setNormalCoopWayCd(String normalCoopWayCd) {
        this.normalCoopWayCd = normalCoopWayCd;
    }
    
    @Column(name="STANDARD_SQUARE", precision=10)
    public BigDecimal getStandardSquare() {
        return this.standardSquare;
    }
    
    public void setStandardSquare(BigDecimal standardSquare) {
        this.standardSquare = standardSquare;
    }
    
    @Column(name="MAX_SQUARE", precision=10)
    public BigDecimal getMaxSquare() {
        return this.maxSquare;
    }
    
    public void setMaxSquare(BigDecimal maxSquare) {
        this.maxSquare = maxSquare;
    }
    
    @Column(name="MIN_SQUARE", precision=10)
    public BigDecimal getMinSquare() {
        return this.minSquare;
    }
    
    public void setMinSquare(BigDecimal minSquare) {
        this.minSquare = minSquare;
    }
    
    @Column(name="OPEN_BASE_REQUIRE", length=1000)
    public String getOpenBaseRequire() {
        return this.openBaseRequire;
    }
    
    public void setOpenBaseRequire(String openBaseRequire) {
        this.openBaseRequire = openBaseRequire;
    }
    
    @Column(name="MARKET_LEVEL_CD", length=20)
    public String getMarketLevelCd() {
        return this.marketLevelCd;
    }
    
    public void setMarketLevelCd(String marketLevelCd) {
        this.marketLevelCd = marketLevelCd;
    }
    
    @Column(name="SPOKESMAN", length=100)
    public String getSpokesman() {
        return this.spokesman;
    }
    
    public void setSpokesman(String spokesman) {
        this.spokesman = spokesman;
    }
    
    @Column(name="CONSUME_AGE", length=20)
    public String getConsumeAge() {
        return this.consumeAge;
    }
    
    public void setConsumeAge(String consumeAge) {
        this.consumeAge = consumeAge;
    }
    
    @Column(name="CONSUME_OBJ", length=1000)
    public String getConsumeObj() {
        return this.consumeObj;
    }
    
    public void setConsumeObj(String consumeObj) {
        this.consumeObj = consumeObj;
    }
    
    @Column(name="COMPETE_BRAND", length=1000)
    public String getCompeteBrand() {
        return this.competeBrand;
    }
    
    public void setCompeteBrand(String competeBrand) {
        this.competeBrand = competeBrand;
    }
    
    @Column(name="YEAR_TOTAL_MONEY", precision=10, scale=0)
    public Long getYearTotalMoney() {
        return this.yearTotalMoney;
    }
    
    public void setYearTotalMoney(Long yearTotalMoney) {
        this.yearTotalMoney = yearTotalMoney;
    }
    
    @Column(name="PRODUCT_STYLE", length=300)
    public String getProductStyle() {
        return this.productStyle;
    }
    
    public void setProductStyle(String productStyle) {
        this.productStyle = productStyle;
    }
    
    @Column(name="AD_POS", length=300)
    public String getAdPos() {
        return this.adPos;
    }
    
    public void setAdPos(String adPos) {
        this.adPos = adPos;
    }
    
    @Column(name="BUSINESS_TYPE", length=100)
    public String getBusinessType() {
        return this.businessType;
    }
    
    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }
    
    @Column(name="LOGO", length=200)
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    
    @Column(name="CONTACT_PHONE", length=100)
    public String getContactPhone() {
        return this.contactPhone;
    }
    
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }
    
    @Column(name="FAX", length=100)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    
    @Column(name="BRAND_TYPE", length=100)
    public String getBrandType() {
        return this.brandType;
    }
    
    public void setBrandType(String brandType) {
        this.brandType = brandType;
    }
    
    @Column(name="BRAND_DEVELOP_PLAN", length=1000)
    public String getBrandDevelopPlan() {
        return this.brandDevelopPlan;
    }
    
    public void setBrandDevelopPlan(String brandDevelopPlan) {
        this.brandDevelopPlan = brandDevelopPlan;
    }
    
    @Column(name="RADIATION_RANGE", length=100)
    public String getRadiationRange() {
        return this.radiationRange;
    }
    
    public void setRadiationRange(String radiationRange) {
        this.radiationRange = radiationRange;
    }
    
    @Column(name="SIZE_OF_POPULATION", precision=10)
    public BigDecimal getSizeOfPopulation() {
        return this.sizeOfPopulation;
    }
    
    public void setSizeOfPopulation(BigDecimal sizeOfPopulation) {
        this.sizeOfPopulation = sizeOfPopulation;
    }
    
    @Column(name="AVERAGE_INCOME", precision=10)
    public BigDecimal getAverageIncome() {
        return this.averageIncome;
    }
    
    public void setAverageIncome(BigDecimal averageIncome) {
        this.averageIncome = averageIncome;
    }
    
    @Column(name="CORRIVAL", length=100)
    public String getCorrival() {
        return this.corrival;
    }
    
    public void setCorrival(String corrival) {
        this.corrival = corrival;
    }
    
    @Column(name="BUSINESS_DISTRICT", length=100)
    public String getBusinessDistrict() {
        return this.businessDistrict;
    }
    
    public void setBusinessDistrict(String businessDistrict) {
        this.businessDistrict = businessDistrict;
    }
    
    @Column(name="TRAFFIC_REQUIRE", length=100)
    public String getTrafficRequire() {
        return this.trafficRequire;
    }
    
    public void setTrafficRequire(String trafficRequire) {
        this.trafficRequire = trafficRequire;
    }
    
    @Column(name="MALL_SQUARE", length=100)
    public String getMallSquare() {
        return this.mallSquare;
    }
    
    public void setMallSquare(String mallSquare) {
        this.mallSquare = mallSquare;
    }
    
    @Column(name="KITCHEN_SQUARE", length=100)
    public String getKitchenSquare() {
        return this.kitchenSquare;
    }
    
    public void setKitchenSquare(String kitchenSquare) {
        this.kitchenSquare = kitchenSquare;
    }
    
    @Column(name="WAREHOUSE_SQUARE", length=100)
    public String getWarehouseSquare() {
        return this.warehouseSquare;
    }
    
    public void setWarehouseSquare(String warehouseSquare) {
        this.warehouseSquare = warehouseSquare;
    }
    
    @Column(name="LOGISTICS_SQUARE", length=100)
    public String getLogisticsSquare() {
        return this.logisticsSquare;
    }
    
    public void setLogisticsSquare(String logisticsSquare) {
        this.logisticsSquare = logisticsSquare;
    }
    
    @Column(name="RECEIVE_STALL", length=100)
    public String getReceiveStall() {
        return this.receiveStall;
    }
    
    public void setReceiveStall(String receiveStall) {
        this.receiveStall = receiveStall;
    }
    
    @Column(name="CUSTOMER_STALL", length=100)
    public String getCustomerStall() {
        return this.customerStall;
    }
    
    public void setCustomerStall(String customerStall) {
        this.customerStall = customerStall;
    }
    
    @Column(name="BICYCLE_STALL", length=100)
    public String getBicycleStall() {
        return this.bicycleStall;
    }
    
    public void setBicycleStall(String bicycleStall) {
        this.bicycleStall = bicycleStall;
    }
    
    @Column(name="MALL_FLOOR_HEIGHT", length=100)
    public String getMallFloorHeight() {
        return this.mallFloorHeight;
    }
    
    public void setMallFloorHeight(String mallFloorHeight) {
        this.mallFloorHeight = mallFloorHeight;
    }
    
    @Column(name="PARK_FLOOR_HEIGHT", length=100)
    public String getParkFloorHeight() {
        return this.parkFloorHeight;
    }
    
    public void setParkFloorHeight(String parkFloorHeight) {
        this.parkFloorHeight = parkFloorHeight;
    }
    
    @Column(name="RECEIVE_PLACE", length=100)
    public String getReceivePlace() {
        return this.receivePlace;
    }
    
    public void setReceivePlace(String receivePlace) {
        this.receivePlace = receivePlace;
    }
    
    @Column(name="MALL_BEARING", length=100)
    public String getMallBearing() {
        return this.mallBearing;
    }
    
    public void setMallBearing(String mallBearing) {
        this.mallBearing = mallBearing;
    }
    
    @Column(name="PARK_BEARING", length=100)
    public String getParkBearing() {
        return this.parkBearing;
    }
    
    public void setParkBearing(String parkBearing) {
        this.parkBearing = parkBearing;
    }
    
    @Column(name="SPAN", length=200)
    public String getSpan() {
        return this.span;
    }
    
    public void setSpan(String span) {
        this.span = span;
    }
    
    @Column(name="PILLAR_SIZE", length=200)
    public String getPillarSize() {
        return this.pillarSize;
    }
    
    public void setPillarSize(String pillarSize) {
        this.pillarSize = pillarSize;
    }
    
    @Column(name="DISTANCE_PILLAR_WALL", length=200)
    public String getDistancePillarWall() {
        return this.distancePillarWall;
    }
    
    public void setDistancePillarWall(String distancePillarWall) {
        this.distancePillarWall = distancePillarWall;
    }
    
    @Column(name="CABLE", length=200)
    public String getCable() {
        return this.cable;
    }
    
    public void setCable(String cable) {
        this.cable = cable;
    }
    
    @Column(name="WATER_SUPPLY", length=200)
    public String getWaterSupply() {
        return this.waterSupply;
    }
    
    public void setWaterSupply(String waterSupply) {
        this.waterSupply = waterSupply;
    }
    
    @Column(name="AIR_SUPPLY", length=200)
    public String getAirSupply() {
        return this.airSupply;
    }
    
    public void setAirSupply(String airSupply) {
        this.airSupply = airSupply;
    }
    
    @Column(name="SUMMER_REQUIRE", length=200)
    public String getSummerRequire() {
        return this.summerRequire;
    }
    
    public void setSummerRequire(String summerRequire) {
        this.summerRequire = summerRequire;
    }
    
    @Column(name="WINTER_REQUIRE", length=200)
    public String getWinterRequire() {
        return this.winterRequire;
    }
    
    public void setWinterRequire(String winterRequire) {
        this.winterRequire = winterRequire;
    }
    
    @Column(name="COOLING_TOWER", length=200)
    public String getCoolingTower() {
        return this.coolingTower;
    }
    
    public void setCoolingTower(String coolingTower) {
        this.coolingTower = coolingTower;
    }
    
    @Column(name="FRESH_WIND_PORT_POSI", length=200)
    public String getFreshWindPortPosi() {
        return this.freshWindPortPosi;
    }
    
    public void setFreshWindPortPosi(String freshWindPortPosi) {
        this.freshWindPortPosi = freshWindPortPosi;
    }
    
    @Column(name="EXHAUST_OUTLET_POSI", length=200)
    public String getExhaustOutletPosi() {
        return this.exhaustOutletPosi;
    }
    
    public void setExhaustOutletPosi(String exhaustOutletPosi) {
        this.exhaustOutletPosi = exhaustOutletPosi;
    }
    
    @Column(name="LAMBLACK_ABSORBER", length=200)
    public String getLamblackAbsorber() {
        return this.lamblackAbsorber;
    }
    
    public void setLamblackAbsorber(String lamblackAbsorber) {
        this.lamblackAbsorber = lamblackAbsorber;
    }
    
    @Column(name="PIPELINE_CALIBER", length=200)
    public String getPipelineCaliber() {
        return this.pipelineCaliber;
    }
    
    public void setPipelineCaliber(String pipelineCaliber) {
        this.pipelineCaliber = pipelineCaliber;
    }
    
    @Column(name="SEPARATION_TANK", length=200)
    public String getSeparationTank() {
        return this.separationTank;
    }
    
    public void setSeparationTank(String separationTank) {
        this.separationTank = separationTank;
    }
    
    @Column(name="SEPTIC_TANK", length=200)
    public String getSepticTank() {
        return this.septicTank;
    }
    
    public void setSepticTank(String septicTank) {
        this.septicTank = septicTank;
    }
    
    @Column(name="FIRST_DISCUSS", length=1000)
    public String getFirstDiscuss() {
        return this.firstDiscuss;
    }
    
    public void setFirstDiscuss(String firstDiscuss) {
        this.firstDiscuss = firstDiscuss;
    }
    
    @Column(name="SECOND_DISCUSS", length=1000)
    public String getSecondDiscuss() {
        return this.secondDiscuss;
    }
    
    public void setSecondDiscuss(String secondDiscuss) {
        this.secondDiscuss = secondDiscuss;
    }
    
    @Column(name="THIRD_DISCUSS", length=1000)
    public String getThirdDiscuss() {
        return this.thirdDiscuss;
    }
    
    public void setThirdDiscuss(String thirdDiscuss) {
        this.thirdDiscuss = thirdDiscuss;
    }
    
    @Column(name="BUSINESS_PERSONNEL", length=20)
    public String getBusinessPersonnel() {
        return this.businessPersonnel;
    }
    
    public void setBusinessPersonnel(String businessPersonnel) {
        this.businessPersonnel = businessPersonnel;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_FILE_DATE", length=7)
    public Date getCreateFileDate() {
        return this.createFileDate;
    }
    
    public void setCreateFileDate(Date createFileDate) {
        this.createFileDate = createFileDate;
    }
    
    @Column(name="CHECKER", length=20)
    public String getChecker() {
        return this.checker;
    }
    
    public void setChecker(String checker) {
        this.checker = checker;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="DELETE_BL", length=2)
    public String getDeleteBl() {
        return this.deleteBl;
    }
    
    public void setDeleteBl(String deleteBl) {
        this.deleteBl = deleteBl;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="STORE_IMG", length=50)
    public String getStoreImg() {
        return this.storeImg;
    }
    
    public void setStoreImg(String storeImg) {
        this.storeImg = storeImg;
    }
    
    @Column(name="OPEN_PLAN", length=400)
    public String getOpenPlan() {
        return this.openPlan;
    }
    
    public void setOpenPlan(String openPlan) {
        this.openPlan = openPlan;
    }
    
    @Column(name="IMPORTANT_AREA", length=200)
    public String getImportantArea() {
        return this.importantArea;
    }
    
    public void setImportantArea(String importantArea) {
        this.importantArea = importantArea;
    }
    
    @Column(name="OTHER_AREA", length=200)
    public String getOtherArea() {
        return this.otherArea;
    }
    
    public void setOtherArea(String otherArea) {
        this.otherArea = otherArea;
    }
    
    @Column(name="TOTAL_SHOP_NUM", precision=10)
    public BigDecimal getTotalShopNum() {
        return this.totalShopNum;
    }
    
    public void setTotalShopNum(BigDecimal totalShopNum) {
        this.totalShopNum = totalShopNum;
    }
    
    @Column(name="DISTRIBUTE_COUN", length=200)
    public String getDistributeCoun() {
        return this.distributeCoun;
    }
    
    public void setDistributeCoun(String distributeCoun) {
        this.distributeCoun = distributeCoun;
    }
    
    @Column(name="COUNTRY_NUM", precision=10)
    public BigDecimal getCountryNum() {
        return this.countryNum;
    }
    
    public void setCountryNum(BigDecimal countryNum) {
        this.countryNum = countryNum;
    }
    
    @Column(name="DISTRIBUTE_CITY", length=200)
    public String getDistributeCity() {
        return this.distributeCity;
    }
    
    public void setDistributeCity(String distributeCity) {
        this.distributeCity = distributeCity;
    }
    
    @Column(name="INFOR_CONF", length=200)
    public String getInforConf() {
        return this.inforConf;
    }
    
    public void setInforConf(String inforConf) {
        this.inforConf = inforConf;
    }
    
    @Column(name="EXAM_RESU", length=200)
    public String getExamResu() {
        return this.examResu;
    }
    
    public void setExamResu(String examResu) {
        this.examResu = examResu;
    }
    
    @Column(name="MANA_EVAL", length=200)
    public String getManaEval() {
        return this.manaEval;
    }
    
    public void setManaEval(String manaEval) {
        this.manaEval = manaEval;
    }
    
    @Column(name="GDP", length=100)
    public String getGdp() {
        return this.gdp;
    }
    
    public void setGdp(String gdp) {
        this.gdp = gdp;
    }
    
    @Column(name="COOPERATED_SHOP_UN", length=100)
    public String getCooperatedShopUn() {
        return this.cooperatedShopUn;
    }
    
    public void setCooperatedShopUn(String cooperatedShopUn) {
        this.cooperatedShopUn = cooperatedShopUn;
    }
    
    @Column(name="BIS_SHOP_DEPT", length=50)
    public String getBisShopDept() {
        return this.bisShopDept;
    }
    
    public void setBisShopDept(String bisShopDept) {
        this.bisShopDept = bisShopDept;
    }
    
    @Column(name="BIS_SHOP_AUDIT", length=2)
    public String getBisShopAudit() {
        return this.bisShopAudit;
    }
    
    public void setBisShopAudit(String bisShopAudit) {
        this.bisShopAudit = bisShopAudit;
    }
    
    @Column(name="BIS_EVALUATE", length=50)
    public String getBisEvaluate() {
        return this.bisEvaluate;
    }
    
    public void setBisEvaluate(String bisEvaluate) {
        this.bisEvaluate = bisEvaluate;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisShop")
    @BatchSize(size=10)
    @OrderBy(clause="CREATED_DATE asc")
public List<BisShopCredit> getBisShopCredits() {
        return this.bisShopCredits;
    }
    
    public void setBisShopCredits(List<BisShopCredit> bisShopCredits) {
        this.bisShopCredits = bisShopCredits;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisShop")
    @BatchSize(size=10)
    @OrderBy(clause="CREATED_DATE asc")
public List<BisShopVisit> getBisShopVisits() {
        return this.bisShopVisits;
    }
    
    public void setBisShopVisits(List<BisShopVisit> bisShopVisits) {
        this.bisShopVisits = bisShopVisits;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisShop")
    @BatchSize(size=10)
    @Where(clause="DELETE_BL='0'")
    @OrderBy(clause="CREATED_DATE asc")
public List<BisShopConn> getBisShopConns() {
        return this.bisShopConns;
    }
    
    public void setBisShopConns(List<BisShopConn> bisShopConns) {
        this.bisShopConns = bisShopConns;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisShop")
    @BatchSize(size=10)
public List<BisShopSortRel> getBisShopSortRels() {
        return this.bisShopSortRels;
    }
    
    public void setBisShopSortRels(List<BisShopSortRel> bisShopSortRels) {
        this.bisShopSortRels = bisShopSortRels;
    }

    @Column(name="AREA_COOPER_STR", length=100)
	public String getAreaCooperStr() {
		return areaCooperStr;
	}


	public void setAreaCooperStr(String areaCooperStr) {
		this.areaCooperStr = areaCooperStr;
	}

	@Column(name="USER_FIRE_BL", length=1)
	public String getUserFireBl() {
		return userFireBl;
	}


	public void setUserFireBl(String userFireBl) {
		this.userFireBl = userFireBl;
	}
	
	@Column(name="FIRE_AREA", length=10)
	public String getFireArea() {
		return fireArea;
	}


	public void setFireArea(String fireArea) {
		this.fireArea = fireArea;
	}
	
	@Column(name="RENT_PROMOTIONS", length=400)
	public String getRentPromotions() {
		return rentPromotions;
	}


	public void setRentPromotions(String rentPromotions) {
		this.rentPromotions = rentPromotions;
	}
	
	 @Column(name="SUP_EXAM_RESU", length=2)
    public String getSupExamResu() {
        return this.supExamResu;
    }
    
    public void setSupExamResu(String supExamResu) {
        this.supExamResu = supExamResu;
    }
    
    @Column(name="SUP_INFO_VERI", length=2)
    public String getSupInfoVeri() {
        return this.supInfoVeri;
    }
    
    public void setSupInfoVeri(String supInfoVeri) {
        this.supInfoVeri = supInfoVeri;
    }
    
    @Column(name="EXAM_RESU_PERSON", length=200)
    public String getExamResuPerson() {
        return this.examResuPerson;
    }
    
    public void setExamResuPerson(String examResuPerson) {
        this.examResuPerson = examResuPerson;
    }
    
    @Column(name="EXAM_RESU_CONTENT", length=400)
    public String getExamResuContent() {
        return this.examResuContent;
    }
    
    public void setExamResuContent(String examResuContent) {
        this.examResuContent = examResuContent;
    }
    
    @Column(name="SUP_EVALUATE", length=2)
    public String getSupEvaluate() {
        return this.supEvaluate;
    }
    
    public void setSupEvaluate(String supEvaluate) {
        this.supEvaluate = supEvaluate;
    }
    
    @Column(name="SUP_MANA_EVAL", length=2)
    public String getSupManaEval() {
        return this.supManaEval;
    }
    
    public void setSupManaEval(String supManaEval) {
        this.supManaEval = supManaEval;
    }
    
    @Column(name="EXAM_RESU_ATTCH", length=50)
    public String getExamResuAttch() {
        return this.examResuAttch;
    }
    
    public void setExamResuAttch(String examResuAttch) {
        this.examResuAttch = examResuAttch;
    }
    
    @Column(name="SUPEVALATTACH", length=50)
    public String getSupevalattach() {
        return this.supevalattach;
    }
    
    public void setSupevalattach(String supevalattach) {
        this.supevalattach = supevalattach;
    }

    
    @Column(name="SUP_MANA_EVAL_ATTACH", length=50)
    public String getSupManaEvalAttach() {
        return this.supManaEvalAttach;
    }
    
    public void setSupManaEvalAttach(String supManaEvalAttach) {
        this.supManaEvalAttach = supManaEvalAttach;
    }

    @Column(name="SALESMAN", length=50)
	public String getSalesman() {
		return salesman;
	}


	public void setSalesman(String salesman) {
		this.salesman = salesman;
	}

    @Column(name="ATTENTION", length=2)
	public String getAttention() {
		return attention;
	}

	public void setAttention(String attention) {
		this.attention = attention;
	}

    @Column(name="SHOP_LEVEL", length=20)
    public String getShopLevel() {
        return this.shopLevel;
    }
    
    public void setShopLevel(String shopLevel) {
        this.shopLevel = shopLevel;
    }
    
    @Column(name="COOPERATE_AREA", length=400)
    public String getCooperateArea() {
        return this.cooperateArea;
    }
    
    public void setCooperateArea(String cooperateArea) {
        this.cooperateArea = cooperateArea;
    }
    
    @Column(name="COOPERATE_AREA_CD", length=400)
    public String getCooperateAreaCd() {
		return cooperateAreaCd;
	}

	public void setCooperateAreaCd(String cooperateAreaCd) {
		this.cooperateAreaCd = cooperateAreaCd;
	}


	@Column(name="STRATEGIC_SHOP", length=10)
    public String getStrategicShop() {
        return this.strategicShop;
    }
    
    public void setStrategicShop(String strategicShop) {
        this.strategicShop = strategicShop;
    }
    
    @Column(name="BENCHMARK_SHOP", length=10)
    public String getBenchmarkShop() {
        return this.benchmarkShop;
    }
    
    public void setBenchmarkShop(String benchmarkShop) {
        this.benchmarkShop = benchmarkShop;
    }
    
    @Column(name="COOPERATE_ARCHIVES", length=200)
    public String getCooperateArchives() {
        return this.cooperateArchives;
    }
    
    public void setCooperateArchives(String cooperateArchives) {
        this.cooperateArchives = cooperateArchives;
    }
    
    @Column(name="INVESTIGATION_LEVEL", length=20)
    public String getInvestigationLevel() {
        return this.investigationLevel;
    }
    
    public void setInvestigationLevel(String investigationLevel) {
        this.investigationLevel = investigationLevel;
    }
    
    @Column(name="COMPANY_TEL_BASEINFO", length=50)
	public String getCompanyTelBaseinfo() {
		return companyTelBaseinfo;
	}

	public void setCompanyTelBaseinfo(String companyTelBaseinfo) {
		this.companyTelBaseinfo = companyTelBaseinfo;
	}
    
}