// 
package com.hhz.ump.entity.bis;
// Generated 2011-7-29 15:47:00 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.BatchSize;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BisStoreSplit generated by hbm2java
 */
@Entity
@Table(name="BIS_STORE_SPLIT"
    
)
public class BisStoreSplit  implements java.io.Serializable {


     private String bisStoreSplitId;
     private BisStore bisStore;
     private String storeNo;
     private BigDecimal square;
     private BigDecimal innerSquare;
     private BigDecimal publicSquare;
     private String storeUrl;
     private BigDecimal sellPrice;
     private Date openDate;
     private String layoutCd;
     private String statusCd;
     private String toSellStatusCd;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String useStatus;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;

    public BisStoreSplit() {
    }

	
    public BisStoreSplit(String bisStoreSplitId, BisStore bisStore, String storeNo, long recordVersion) {
        this.bisStoreSplitId = bisStoreSplitId;
        this.bisStore = bisStore;
        this.storeNo = storeNo;
        this.recordVersion = recordVersion;
    }
    public BisStoreSplit(String bisStoreSplitId, BisStore bisStore, String storeNo, BigDecimal square, BigDecimal innerSquare, BigDecimal publicSquare, String storeUrl, BigDecimal sellPrice, Date openDate, String layoutCd, String statusCd, String toSellStatusCd, String remark, String creator, String createdCenterCd, String createdDeptCd, String useStatus, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion) {
       this.bisStoreSplitId = bisStoreSplitId;
       this.bisStore = bisStore;
       this.storeNo = storeNo;
       this.square = square;
       this.innerSquare = innerSquare;
       this.publicSquare = publicSquare;
       this.storeUrl = storeUrl;
       this.sellPrice = sellPrice;
       this.openDate = openDate;
       this.layoutCd = layoutCd;
       this.statusCd = statusCd;
       this.toSellStatusCd = toSellStatusCd;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.useStatus = useStatus;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_STORE_SPLIT_ID", unique=true, nullable=false, length=50)
    public String getBisStoreSplitId() {
        return this.bisStoreSplitId;
    }
    
    public void setBisStoreSplitId(String bisStoreSplitId) {
        this.bisStoreSplitId = bisStoreSplitId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIS_STORE_ID", nullable=false)
    public BisStore getBisStore() {
        return this.bisStore;
    }
    
    public void setBisStore(BisStore bisStore) {
        this.bisStore = bisStore;
    }
    
    @Column(name="STORE_NO", nullable=false, length=100)
    public String getStoreNo() {
        return this.storeNo;
    }
    
    public void setStoreNo(String storeNo) {
        this.storeNo = storeNo;
    }
    
    @Column(name="SQUARE", precision=10)
    public BigDecimal getSquare() {
        return this.square;
    }
    
    public void setSquare(BigDecimal square) {
        this.square = square;
    }
    
    @Column(name="INNER_SQUARE", precision=10)
    public BigDecimal getInnerSquare() {
        return this.innerSquare;
    }
    
    public void setInnerSquare(BigDecimal innerSquare) {
        this.innerSquare = innerSquare;
    }
    
    @Column(name="PUBLIC_SQUARE", precision=10)
    public BigDecimal getPublicSquare() {
        return this.publicSquare;
    }
    
    public void setPublicSquare(BigDecimal publicSquare) {
        this.publicSquare = publicSquare;
    }
    
    @Column(name="STORE_URL", length=1000)
    public String getStoreUrl() {
        return this.storeUrl;
    }
    
    public void setStoreUrl(String storeUrl) {
        this.storeUrl = storeUrl;
    }
    
    @Column(name="SELL_PRICE", precision=10)
    public BigDecimal getSellPrice() {
        return this.sellPrice;
    }
    
    public void setSellPrice(BigDecimal sellPrice) {
        this.sellPrice = sellPrice;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="OPEN_DATE", length=7)
    public Date getOpenDate() {
        return this.openDate;
    }
    
    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }
    
    @Column(name="LAYOUT_CD", length=20)
    public String getLayoutCd() {
        return this.layoutCd;
    }
    
    public void setLayoutCd(String layoutCd) {
        this.layoutCd = layoutCd;
    }
    
    @Column(name="STATUS_CD", length=20)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }
    
    @Column(name="TO_SELL_STATUS_CD", length=20)
    public String getToSellStatusCd() {
        return this.toSellStatusCd;
    }
    
    public void setToSellStatusCd(String toSellStatusCd) {
        this.toSellStatusCd = toSellStatusCd;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="USE_STATUS", length=1)
    public String getUseStatus() {
        return this.useStatus;
    }
    
    public void setUseStatus(String useStatus) {
        this.useStatus = useStatus;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }




}


