// 
package com.hhz.ump.entity.bis;
// Generated 2011-8-3 22:32:28 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * BisStore generated by hbm2java
 */
@Entity
@Table(name="BIS_STORE"
    
)
public class BisStore  implements java.io.Serializable {


     private String bisStoreId;
     private BisFloor bisFloor;
     private String storeNo;
     private BigDecimal square;
     private BigDecimal innerSquare;
     private BigDecimal publicSquare;
     private BigDecimal sellPrice;
     private Date openDate;
     private String layoutCd;
     private String statusCd;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String bisProjectId;
     private String bisTenantId;
     private String storeUrl;
     private String splitStatus;
     private Date splitDate;
     private String parentStoreId;
     private String ifChild;
     private String ifSubmit;
     private BigDecimal rentStandard;
     private BigDecimal tenemStandard;
     private String equityNature;
     private BigDecimal rentSquare;
     private String ifPractice;
     private String shopPosition;
     private String managementStatus;
     private String coords;
     private String virtualArea;
     private String owner;
     private BigDecimal squareReal;
     private BigDecimal innerSquareReal;
     private String storeRemark;
     private List<BisStoreContRel> bisStoreContRels = new ArrayList<BisStoreContRel>();
     private List<BisFactStore> bisFactStores = new ArrayList<BisFactStore>();

    public BisStore() {
    }

	
    public BisStore(String bisStoreId, String storeNo, long recordVersion) {
        this.bisStoreId = bisStoreId;
        this.storeNo = storeNo;
        this.recordVersion = recordVersion;
    }
    public BisStore(String bisStoreId, BisFloor bisFloor, String storeNo, BigDecimal square, BigDecimal innerSquare, BigDecimal publicSquare, BigDecimal sellPrice, Date openDate, String layoutCd, String statusCd, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, String bisProjectId, String bisTenantId, String storeUrl, String splitStatus, Date splitDate, String parentStoreId, String ifChild, String ifSubmit, BigDecimal rentStandard, BigDecimal tenemStandard, String equityNature, BigDecimal rentSquare, String coords, List<BisStoreContRel> bisStoreContRels, List<BisFactStore> bisFactStores,String ifPractice,String shopPosition,String managementStatus,BigDecimal squareReal,String storeRemark,BigDecimal innerSquareReal) {
       this.bisStoreId = bisStoreId;
       this.bisFloor = bisFloor;
       this.storeNo = storeNo;
       this.square = square;
       this.innerSquare = innerSquare;
       this.publicSquare = publicSquare;
       this.sellPrice = sellPrice;
       this.openDate = openDate;
       this.layoutCd = layoutCd;
       this.statusCd = statusCd;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.bisProjectId = bisProjectId;
       this.bisTenantId = bisTenantId;
       this.storeUrl = storeUrl;
       this.splitStatus = splitStatus;
       this.splitDate = splitDate;
       this.parentStoreId = parentStoreId;
       this.ifChild = ifChild;
       this.ifSubmit = ifSubmit;
       this.rentStandard = rentStandard;
       this.tenemStandard = tenemStandard;
       this.equityNature = equityNature;
       this.rentSquare = rentSquare;
       this.coords = coords;
       this.bisStoreContRels = bisStoreContRels;
       this.bisFactStores = bisFactStores;
       this.ifPractice = ifPractice;
       this.shopPosition = shopPosition;
       this.managementStatus = managementStatus;
       this.squareReal = squareReal;
       this.innerSquareReal = innerSquareReal;
       this.storeRemark = storeRemark;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_STORE_ID", unique=true, nullable=false, length=50)
    public String getBisStoreId() {
        return this.bisStoreId;
    }
    
    public void setBisStoreId(String bisStoreId) {
        this.bisStoreId = bisStoreId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIS_FLOOR_ID")
    public BisFloor getBisFloor() {
        return this.bisFloor;
    }
    
    public void setBisFloor(BisFloor bisFloor) {
        this.bisFloor = bisFloor;
    }
    
    @Column(name="STORE_NO", nullable=false, length=300)
    public String getStoreNo() {
        return this.storeNo;
    }
    
    public void setStoreNo(String storeNo) {
        this.storeNo = storeNo;
    }
    
    @Column(name="SQUARE", precision=10)
    public BigDecimal getSquare() {
        return this.square;
    }
    
    public void setSquare(BigDecimal square) {
        this.square = square;
    }
    
    @Column(name="INNER_SQUARE", precision=10)
    public BigDecimal getInnerSquare() {
        return this.innerSquare;
    }
    
    public void setInnerSquare(BigDecimal innerSquare) {
        this.innerSquare = innerSquare;
    }
    
    @Column(name="PUBLIC_SQUARE", precision=10)
    public BigDecimal getPublicSquare() {
        return this.publicSquare;
    }
    
    public void setPublicSquare(BigDecimal publicSquare) {
        this.publicSquare = publicSquare;
    }
    
    @Column(name="SELL_PRICE", precision=10)
    public BigDecimal getSellPrice() {
        return this.sellPrice;
    }
    
    public void setSellPrice(BigDecimal sellPrice) {
        this.sellPrice = sellPrice;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="OPEN_DATE", length=7)
    public Date getOpenDate() {
        return this.openDate;
    }
    
    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }
    
    @Column(name="LAYOUT_CD", length=20)
    public String getLayoutCd() {
        return this.layoutCd;
    }
    
    public void setLayoutCd(String layoutCd) {
        this.layoutCd = layoutCd;
    }
    
    @Column(name="STATUS_CD", length=20)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    @Column(name="VIRTUAL_AREA", length=20)
    public String getVirtualArea() {
    	return this.virtualArea;
    }
    
    public void setVirtualArea(String virtualArea) {
    	this.virtualArea = virtualArea;
    }

    @Column(name="OWNER", length=100)
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="BIS_PROJECT_ID", length=50)
    public String getBisProjectId() {
        return this.bisProjectId;
    }
    
    public void setBisProjectId(String bisProjectId) {
        this.bisProjectId = bisProjectId;
    }
    
    @Column(name="BIS_TENANT_ID", length=50)
    public String getBisTenantId() {
        return this.bisTenantId;
    }
    
    public void setBisTenantId(String bisTenantId) {
        this.bisTenantId = bisTenantId;
    }
    
    @Column(name="STORE_URL", length=1000)
    public String getStoreUrl() {
        return this.storeUrl;
    }
    
    public void setStoreUrl(String storeUrl) {
        this.storeUrl = storeUrl;
    }
    
    @Column(name="SPLIT_STATUS", length=1)
    public String getSplitStatus() {
        return this.splitStatus;
    }
    
    public void setSplitStatus(String splitStatus) {
        this.splitStatus = splitStatus;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SPLIT_DATE", length=7)
    public Date getSplitDate() {
        return this.splitDate;
    }
    
    public void setSplitDate(Date splitDate) {
        this.splitDate = splitDate;
    }
    
    @Column(name="PARENT_STORE_ID", length=50)
    public String getParentStoreId() {
        return this.parentStoreId;
    }
    
    public void setParentStoreId(String parentStoreId) {
        this.parentStoreId = parentStoreId;
    }
    
    @Column(name="IF_CHILD", length=1)
    public String getIfChild() {
        return this.ifChild;
    }
    
    public void setIfChild(String ifChild) {
        this.ifChild = ifChild;
    }
    
    @Column(name="IF_SUBMIT", length=1)
    public String getIfSubmit() {
        return this.ifSubmit;
    }
    
    public void setIfSubmit(String ifSubmit) {
        this.ifSubmit = ifSubmit;
    }
    
    @Column(name="RENT_STANDARD", precision=10)
    public BigDecimal getRentStandard() {
        return this.rentStandard;
    }
    
    public void setRentStandard(BigDecimal rentStandard) {
        this.rentStandard = rentStandard;
    }
    
    @Column(name="TENEM_STANDARD", precision=10)
    public BigDecimal getTenemStandard() {
        return this.tenemStandard;
    }
    
    public void setTenemStandard(BigDecimal tenemStandard) {
        this.tenemStandard = tenemStandard;
    }
    
    @Column(name="EQUITY_NATURE", length=100)
    public String getEquityNature() {
        return this.equityNature;
    }
    
    public void setEquityNature(String equityNature) {
        this.equityNature = equityNature;
    }
    
    @Column(name="RENT_SQUARE", precision=10)
    public BigDecimal getRentSquare() {
        return this.rentSquare;
    }
    
    public void setRentSquare(BigDecimal rentSquare) {
        this.rentSquare = rentSquare;
    }
    @Column(name="COORDS", length=2000)
    public String getCoords() {
        return this.coords;
    }
    
    public void setCoords(String coords) {
        this.coords = coords;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisStore")
    @BatchSize(size=10)
public List<BisStoreContRel> getBisStoreContRels() {
        return this.bisStoreContRels;
    }
    
    public void setBisStoreContRels(List<BisStoreContRel> bisStoreContRels) {
        this.bisStoreContRels = bisStoreContRels;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisStore")
    @BatchSize(size=10)
public List<BisFactStore> getBisFactStores() {
        return this.bisFactStores;
    }
    
    public void setBisFactStores(List<BisFactStore> bisFactStores) {
        this.bisFactStores = bisFactStores;
    }

    @Column(name="IF_PRACTICE", length=2)
	public String getIfPractice() {
		return ifPractice;
	}


	public void setIfPractice(String ifPractice) {
		this.ifPractice = ifPractice;
	}

	@Column(name="SHOP_POSITION", length=2)
	public String getShopPosition() {
		return shopPosition;
	}


	public void setShopPosition(String shopPosition) {
		this.shopPosition = shopPosition;
	}

	@Column(name="MANAGEMENT_STATUS", length=2)
	public String getManagementStatus() {
		return managementStatus;
	}


	public void setManagementStatus(String managementStatus) {
		this.managementStatus = managementStatus;
	}

	@Column(name="STORE_REMARK", length=100)
	public String getStoreRemark() {
		return storeRemark;
	}


	public void setStoreRemark(String storeRemark) {
		this.storeRemark = storeRemark;
	}

	@Column(name="SQUARE_REAL", precision=10)
	public BigDecimal getSquareReal() {
		return squareReal;
	}

	public void setSquareReal(BigDecimal squareReal) {
		this.squareReal = squareReal;
	}

	@Column(name="INNER_SQUARE_REAL", precision=10)
	public BigDecimal getInnerSquareReal() {
		return innerSquareReal;
	}


	public void setInnerSquareReal(BigDecimal innerSquareReal) {
		this.innerSquareReal = innerSquareReal;
	}

}


