// 
package com.hhz.ump.entity.bis;
// Generated 2011-8-3 22:32:28 by Hibernate Tools 3.2.2.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * BisTenant generated by hbm2java
 */
@Entity
@Table(name="BIS_TENANT"
    
)
public class BisTenant  implements java.io.Serializable {


     private String bisTenantId;
     private String bisShopId;
     private Long sequenceNo;
     private String connName;
     private String connTel;
     private String connIdentify;
     private String owner;
     private String renterName;
     private Boolean activeBackrent;
     private Boolean activeUnionManage;
     private String brand;
     private String layoutCd;
     private Date rentStartDate;
     private Date rentEndDate;
     private Boolean activeBl;
     private String statusCd;
     private String shopTypeCd;
     private String firstContId;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String bisProjectId;
     private String bisShopConnId;
     private Boolean debtBl;
     private Boolean reportBl;
     private Boolean imageBl;
     private String manageCd;
     private String TypeCd;
     private String storeIds;
     private String storeNos;
     private String attachFlg;
     private String backReason;
     private Date backDate;
     private List<BisTenantAttach> bisTenantAttachs = new ArrayList<BisTenantAttach>();
     private List<BisTenantMess> bisTenantMesses = new ArrayList<BisTenantMess>();

    public BisTenant() {
    }

	
    public BisTenant(String bisTenantId, String firstContId, long recordVersion, String bisProjectId) {
        this.bisTenantId = bisTenantId;
        this.firstContId = firstContId;
        this.recordVersion = recordVersion;
        this.bisProjectId = bisProjectId;
    }
    public BisTenant(String bisTenantId, String bisShopId, Long sequenceNo, String connName, String connTel, String connIdentify, String owner, String renterName, Boolean activeBackrent, Boolean activeUnionManage, String brand, String layoutCd, Date rentStartDate, Date rentEndDate, Boolean activeBl, String statusCd, String shopTypeCd, String firstContId, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, String bisProjectId, List<BisTenantAttach> bisTenantAttachs, List<BisTenantMess> bisTenantMesses) {
       this.bisTenantId = bisTenantId;
       this.bisShopId = bisShopId;
       this.sequenceNo = sequenceNo;
       this.connName = connName;
       this.connTel = connTel;
       this.connIdentify = connIdentify;
       this.owner = owner;
       this.renterName = renterName;
       this.activeBackrent = activeBackrent;
       this.activeUnionManage = activeUnionManage;
       this.brand = brand;
       this.layoutCd = layoutCd;
       this.rentStartDate = rentStartDate;
       this.rentEndDate = rentEndDate;
       this.activeBl = activeBl;
       this.statusCd = statusCd;
       this.shopTypeCd = shopTypeCd;
       this.firstContId = firstContId;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.bisProjectId = bisProjectId;
       this.bisTenantAttachs = bisTenantAttachs;
       this.bisTenantMesses = bisTenantMesses;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_TENANT_ID", unique=true, nullable=false, length=50)
    public String getBisTenantId() {
        return this.bisTenantId;
    }
    
    public void setBisTenantId(String bisTenantId) {
        this.bisTenantId = bisTenantId;
    }
    
    @Column(name="BIS_SHOP_ID", length=50)
    public String getBisShopId() {
		return bisShopId;
	}

	public void setBisShopId(String bisShopId) {
		this.bisShopId = bisShopId;
	}

	@Column(name="SEQUENCE_NO", precision=10, scale=0)
    public Long getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Long sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    
    @Column(name="CONN_NAME", length=100)
    public String getConnName() {
        return this.connName;
    }
    
    public void setConnName(String connName) {
        this.connName = connName;
    }
    
    @Column(name="CONN_TEL", length=300)
    public String getConnTel() {
        return this.connTel;
    }
    
    public void setConnTel(String connTel) {
        this.connTel = connTel;
    }
    
    @Column(name="CONN_IDENTIFY", length=100)
    public String getConnIdentify() {
        return this.connIdentify;
    }
    
    public void setConnIdentify(String connIdentify) {
        this.connIdentify = connIdentify;
    }
    
    @Column(name="OWNER", length=100)
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }
    
    @Column(name="RENTER_NAME", length=100)
    public String getRenterName() {
        return this.renterName;
    }
    
    public void setRenterName(String renterName) {
        this.renterName = renterName;
    }
    
    @Column(name="ACTIVE_BACKRENT", precision=1, scale=0)
    public Boolean getActiveBackrent() {
        return this.activeBackrent;
    }
    
    public void setActiveBackrent(Boolean activeBackrent) {
        this.activeBackrent = activeBackrent;
    }
    
    @Column(name="ACTIVE_UNION_MANAGE", precision=1, scale=0)
    public Boolean getActiveUnionManage() {
        return this.activeUnionManage;
    }
    
    public void setActiveUnionManage(Boolean activeUnionManage) {
        this.activeUnionManage = activeUnionManage;
    }
    
    @Column(name="BRAND", length=300)
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    
    @Column(name="LAYOUT_CD", length=20)
    public String getLayoutCd() {
        return this.layoutCd;
    }
    
    public void setLayoutCd(String layoutCd) {
        this.layoutCd = layoutCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RENT_START_DATE", length=7)
    public Date getRentStartDate() {
        return this.rentStartDate;
    }
    
    public void setRentStartDate(Date rentStartDate) {
        this.rentStartDate = rentStartDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RENT_END_DATE", length=7)
    public Date getRentEndDate() {
        return this.rentEndDate;
    }
    
    public void setRentEndDate(Date rentEndDate) {
        this.rentEndDate = rentEndDate;
    }
    
    @Column(name="ACTIVE_BL", precision=1, scale=0)
    public Boolean getActiveBl() {
        return this.activeBl;
    }
    
    public void setActiveBl(Boolean activeBl) {
        this.activeBl = activeBl;
    }
    
    @Column(name="STATUS_CD", length=10)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }
    
    @Column(name="SHOP_TYPE_CD", length=20)
    public String getShopTypeCd() {
        return this.shopTypeCd;
    }
    
    public void setShopTypeCd(String shopTypeCd) {
        this.shopTypeCd = shopTypeCd;
    }
    
    @Column(name="FIRST_CONT_ID", length=50)
    public String getFirstContId() {
        return this.firstContId;
    }
    
    public void setFirstContId(String firstContId) {
        this.firstContId = firstContId;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="BIS_PROJECT_ID", nullable=false, length=50)
    public String getBisProjectId() {
        return this.bisProjectId;
    }
    
    public void setBisProjectId(String bisProjectId) {
        this.bisProjectId = bisProjectId;
    }

    @Column(name="BIS_SHOP_CONN_ID", length=50)
    public String getBisShopConnId() {
        return this.bisShopConnId;
    }
    
    public void setBisShopConnId(String bisShopConnId) {
        this.bisShopConnId = bisShopConnId;
    }

    @Column(name="DEBT_BL", precision=1, scale=0)
    public Boolean getDebtBl() {
        return this.debtBl;
    }
    
    public void setDebtBl(Boolean debtBl) {
        this.debtBl = debtBl;
    }
    
    @Column(name="REPORT_BL", precision=1, scale=0)
    public Boolean getReportBl() {
        return this.reportBl;
    }
    
    public void setReportBl(Boolean reportBl) {
        this.reportBl = reportBl;
    }
    
    @Column(name="IMAGE_BL", precision=1, scale=0)
    public Boolean getImageBl() {
        return this.imageBl;
    }
    
    public void setImageBl(Boolean imageBl) {
        this.imageBl = imageBl;
    }

    @Column(name="MANAGE_CD", length=20)
    public String getManageCd() {
        return this.manageCd;
    }
    
    public void setManageCd(String manageCd) {
        this.manageCd = manageCd;
    }
    
    @Column(name="TYPE_CD", length=20)
    public String getTypeCd() {
		return TypeCd;
	}

	public void setTypeCd(String typeCd) {
		TypeCd = typeCd;
	}

	@Column(name="STORE_IDS", length=4000)
	public String getStoreIds() {
		return storeIds;
	}

	public void setStoreIds(String storeIds) {
		this.storeIds = storeIds;
	}

	@Column(name="STORE_NOS", length=500)
	public String getStoreNos() {
		return storeNos;
	}

	public void setStoreNos(String storeNos) {
		this.storeNos = storeNos;
	}

    @Column(name="ATTACH_FLG", length=1)
    public String getAttachFlg() {
        return this.attachFlg;
    }
    
    public void setAttachFlg(String attachFlg) {
        this.attachFlg = attachFlg;
    }
    
    @Column(name="BACK_REASON", length=1)
    public String getBackReason() {
        return this.backReason;
    }
    
    public void setBackReason(String backReason) {
        this.backReason = backReason;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="BACK_DATE", length=7)
    public Date getBackDate() {
        return this.backDate;
    }
    
    public void setBackDate(Date backDate) {
        this.backDate = backDate;
    }
    
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisTenant")
    @BatchSize(size=10)
public List<BisTenantAttach> getBisTenantAttachs() {
        return this.bisTenantAttachs;
    }
    
    public void setBisTenantAttachs(List<BisTenantAttach> bisTenantAttachs) {
        this.bisTenantAttachs = bisTenantAttachs;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisTenant")
    @BatchSize(size=10)
public List<BisTenantMess> getBisTenantMesses() {
        return this.bisTenantMesses;
    }
    
    public void setBisTenantMesses(List<BisTenantMess> bisTenantMesses) {
        this.bisTenantMesses = bisTenantMesses;
    }




}


