package com.intelitune.nwms.model;

/**
 * InttUserRole generated by MyEclipse Persistence Tools
 */

public class InttUserRole implements java.io.Serializable {

	// Fields

	private Integer userRoleId;
	private InttUser inttUser;
	private InttRole inttRole;
	
	//bkt
	private String bkt_lockStatus;

	// Constructors

	/** default constructor */
	public InttUserRole() {
	}

	/** full constructor */
	public InttUserRole(InttUser inttUser, InttRole inttRole) {
		this.inttUser = inttUser;
		this.inttRole = inttRole;
	}

	// Property accessors

	public Integer getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(Integer userRoleId) {
		this.userRoleId = userRoleId;
	}

	public InttUser getInttUser() {
		return this.inttUser;
	}

	public void setInttUser(InttUser inttUser) {
		this.inttUser = inttUser;
	}

	public InttRole getInttRole() {
		return this.inttRole;
	}

	public void setInttRole(InttRole inttRole) {
		this.inttRole = inttRole;
	}

	public String getBkt_lockStatus() {
		return bkt_lockStatus;
	}

	public void setBkt_lockStatus(String bkt_lockStatus) {
		this.bkt_lockStatus = bkt_lockStatus;
	}

}