// 
package com.hhz.ump.entity.bid;
// Generated 2012-6-27 11:01:25 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.BatchSize;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BidDivisitonCust generated by hbm2java
 */
@Entity
@Table(name="BID_DIVISITON_CUST"
    
)
public class BidDivisitonCust  implements java.io.Serializable {


     private String bidDivisitonCustId;
     private BidSup bidSup;
     private BidProject bidProject;
     private String itemNo;
     private String itemName;
     private String itemDesc;
     private String unitDesc;
     private Long batchNo;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private Long rowNo;
     private String quantitie;
     private String compUnitAmt;
     private String totalAmt;

    public BidDivisitonCust() {
    }

	
    public BidDivisitonCust(String bidDivisitonCustId, BidSup bidSup, BidProject bidProject, long recordVersion) {
        this.bidDivisitonCustId = bidDivisitonCustId;
        this.bidSup = bidSup;
        this.bidProject = bidProject;
        this.recordVersion = recordVersion;
    }
    public BidDivisitonCust(String bidDivisitonCustId, BidSup bidSup, BidProject bidProject, String itemNo, String itemName, String itemDesc, String unitDesc, Long batchNo, String remark, String creator, String createdCenterCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedPositionCd, Date updatedDate, long recordVersion, Long rowNo, String quantitie, String compUnitAmt, String totalAmt) {
       this.bidDivisitonCustId = bidDivisitonCustId;
       this.bidSup = bidSup;
       this.bidProject = bidProject;
       this.itemNo = itemNo;
       this.itemName = itemName;
       this.itemDesc = itemDesc;
       this.unitDesc = unitDesc;
       this.batchNo = batchNo;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.rowNo = rowNo;
       this.quantitie = quantitie;
       this.compUnitAmt = compUnitAmt;
       this.totalAmt = totalAmt;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BID_DIVISITON_CUST_ID", unique=true, nullable=false, length=50)
    public String getBidDivisitonCustId() {
        return this.bidDivisitonCustId;
    }
    
    public void setBidDivisitonCustId(String bidDivisitonCustId) {
        this.bidDivisitonCustId = bidDivisitonCustId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BID_SUP_ID", nullable=false)
    public BidSup getBidSup() {
        return this.bidSup;
    }
    
    public void setBidSup(BidSup bidSup) {
        this.bidSup = bidSup;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BID_PROJECT_ID", nullable=false)
    public BidProject getBidProject() {
        return this.bidProject;
    }
    
    public void setBidProject(BidProject bidProject) {
        this.bidProject = bidProject;
    }
    
    @Column(name="ITEM_NO", length=50)
    public String getItemNo() {
        return this.itemNo;
    }
    
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo;
    }
    
    @Column(name="ITEM_NAME", length=100)
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    
    @Column(name="ITEM_DESC", length=500)
    public String getItemDesc() {
        return this.itemDesc;
    }
    
    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc;
    }
    
    @Column(name="UNIT_DESC", length=10)
    public String getUnitDesc() {
        return this.unitDesc;
    }
    
    public void setUnitDesc(String unitDesc) {
        this.unitDesc = unitDesc;
    }
    
    @Column(name="BATCH_NO", precision=18, scale=0)
    public Long getBatchNo() {
        return this.batchNo;
    }
    
    public void setBatchNo(Long batchNo) {
        this.batchNo = batchNo;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="ROW_NO", precision=18, scale=0)
    public Long getRowNo() {
        return this.rowNo;
    }
    
    public void setRowNo(Long rowNo) {
        this.rowNo = rowNo;
    }
    
    @Column(name="QUANTITIE", length=20)
    public String getQuantitie() {
        return this.quantitie;
    }
    
    public void setQuantitie(String quantitie) {
        this.quantitie = quantitie;
    }
    
    @Column(name="COMP_UNIT_AMT", length=20)
    public String getCompUnitAmt() {
        return this.compUnitAmt;
    }
    
    public void setCompUnitAmt(String compUnitAmt) {
        this.compUnitAmt = compUnitAmt;
    }
    
    @Column(name="TOTAL_AMT", length=20)
    public String getTotalAmt() {
        return this.totalAmt;
    }
    
    public void setTotalAmt(String totalAmt) {
        this.totalAmt = totalAmt;
    }




}


