// 
package com.hhz.ump.entity.bid;
// Generated 2012-6-27 11:01:25 by Hibernate Tools 3.2.2.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OrderBy;

/**
 * BidSup generated by hbm2java
 */
@Entity
@Table(name="BID_SUP"
    
)
public class BidSup  implements java.io.Serializable {


     private String bidSupId;
     private BidLedger bidLedger;
     private String relSupBasicId;
     private String supName;
     private String email;
     private String typeCd;
     private String provideLevelCd;
     private String linkMan;
     private String linkDesc;
     private String attachFlg;
     private String receiveStatusCd;
     private Date receiveDate;
     private String submitStatusCd;
     private String submitAttachFlg;
     private Date submitDate;
     private String refundStatusCd;
     private Date refundDate;
     private String supBidStatusCd;
     private Date bidDate;
     private String remark;
     private String techAttachStatusCd;
     private String creator;
     private String createdCenterCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private Long dispOrderNo;
     private String openPlacctFlg;
     private String openPlacctCd;
     private String oriPwd;
     private Date techAttachDate;
     private String guarAttaConfFlg;
     private String guarAttaConfName;
     private String guarAttaConfUiid;
     private Date guarAttaConfDate;
     private List<BidMeasureSupRel2> bidMeasureSupRel2s = new ArrayList<BidMeasureSupRel2>();
     private List<BidOtherItemRel> bidOtherItemRels = new ArrayList<BidOtherItemRel>();
     private List<BidSporadicSupRel> bidSporadicSupRels = new ArrayList<BidSporadicSupRel>();
     private List<BidSupAttachRel> bidSupAttachRels = new ArrayList<BidSupAttachRel>();
     private List<BidSupOtherRel> bidSupOtherRels = new ArrayList<BidSupOtherRel>();
     private List<BidFeesSupRel> bidFeesSupRels = new ArrayList<BidFeesSupRel>();
     private List<BidDivisitonCust> bidDivisitonCusts = new ArrayList<BidDivisitonCust>();
     private List<BidItemSupRel> bidItemSupRels = new ArrayList<BidItemSupRel>();
     private List<BidDivisionSupRel> bidDivisionSupRels = new ArrayList<BidDivisionSupRel>();
     private List<BidMeasureSupRel> bidMeasureSupRels = new ArrayList<BidMeasureSupRel>();
     private List<BidTaxsSupRel> bidTaxsSupRels = new ArrayList<BidTaxsSupRel>();
     private List<BidOpenRecordSup> bidOpenRecordSups = new ArrayList<BidOpenRecordSup>();

    public BidSup() {
    }

	
    public BidSup(String bidSupId, BidLedger bidLedger, long recordVersion) {
        this.bidSupId = bidSupId;
        this.bidLedger = bidLedger;
        this.recordVersion = recordVersion;
    }
    public BidSup(String bidSupId, BidLedger bidLedger, String relSupBasicId, String supName, String email, String typeCd, String provideLevelCd, String linkMan, String linkDesc, String attachFlg, String receiveStatusCd, Date receiveDate, String submitStatusCd, String submitAttachFlg, Date submitDate, String refundStatusCd, Date refundDate, String supBidStatusCd, Date bidDate, String remark, String techAttachStatusCd, String creator, String createdCenterCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedPositionCd, Date updatedDate, long recordVersion, Long dispOrderNo, String openPlacctFlg, String openPlacctCd, String oriPwd, Date techAttachDate, String guarAttaConfFlg, String guarAttaConfName, String guarAttaConfUiid, Date guarAttaConfDate, List<BidMeasureSupRel2> bidMeasureSupRel2s, List<BidOtherItemRel> bidOtherItemRels, List<BidSporadicSupRel> bidSporadicSupRels, List<BidSupAttachRel> bidSupAttachRels, List<BidSupOtherRel> bidSupOtherRels, List<BidFeesSupRel> bidFeesSupRels, List<BidDivisitonCust> bidDivisitonCusts, List<BidItemSupRel> bidItemSupRels, List<BidDivisionSupRel> bidDivisionSupRels, List<BidMeasureSupRel> bidMeasureSupRels, List<BidTaxsSupRel> bidTaxsSupRels) {
       this.bidSupId = bidSupId;
       this.bidLedger = bidLedger;
       this.relSupBasicId = relSupBasicId;
       this.supName = supName;
       this.email = email;
       this.typeCd = typeCd;
       this.provideLevelCd = provideLevelCd;
       this.linkMan = linkMan;
       this.linkDesc = linkDesc;
       this.attachFlg = attachFlg;
       this.receiveStatusCd = receiveStatusCd;
       this.receiveDate = receiveDate;
       this.submitStatusCd = submitStatusCd;
       this.submitAttachFlg = submitAttachFlg;
       this.submitDate = submitDate;
       this.refundStatusCd = refundStatusCd;
       this.refundDate = refundDate;
       this.supBidStatusCd = supBidStatusCd;
       this.bidDate = bidDate;
       this.remark = remark;
       this.techAttachStatusCd = techAttachStatusCd;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.dispOrderNo = dispOrderNo;
       this.openPlacctFlg = openPlacctFlg;
       this.openPlacctCd = openPlacctCd;
       this.oriPwd = oriPwd;
       this.techAttachDate = techAttachDate;
       this.guarAttaConfFlg = guarAttaConfFlg;
       this.guarAttaConfName = guarAttaConfName;
       this.guarAttaConfUiid = guarAttaConfUiid;
       this.guarAttaConfDate = guarAttaConfDate;
       this.bidMeasureSupRel2s = bidMeasureSupRel2s;
       this.bidOtherItemRels = bidOtherItemRels;
       this.bidSporadicSupRels = bidSporadicSupRels;
       this.bidSupAttachRels = bidSupAttachRels;
       this.bidSupOtherRels = bidSupOtherRels;
       this.bidFeesSupRels = bidFeesSupRels;
       this.bidDivisitonCusts = bidDivisitonCusts;
       this.bidItemSupRels = bidItemSupRels;
       this.bidDivisionSupRels = bidDivisionSupRels;
       this.bidMeasureSupRels = bidMeasureSupRels;
       this.bidTaxsSupRels = bidTaxsSupRels;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BID_SUP_ID", unique=true, nullable=false, length=50)
    public String getBidSupId() {
        return this.bidSupId;
    }
    
    public void setBidSupId(String bidSupId) {
        this.bidSupId = bidSupId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BID_LEDGER_ID", nullable=false)
    public BidLedger getBidLedger() {
        return this.bidLedger;
    }
    
    public void setBidLedger(BidLedger bidLedger) {
        this.bidLedger = bidLedger;
    }
    
    @Column(name="REL_SUP_BASIC_ID", length=50)
    public String getRelSupBasicId() {
        return this.relSupBasicId;
    }
    
    public void setRelSupBasicId(String relSupBasicId) {
        this.relSupBasicId = relSupBasicId;
    }
    
    @Column(name="SUP_NAME", length=100)
    public String getSupName() {
        return this.supName;
    }
    
    public void setSupName(String supName) {
        this.supName = supName;
    }
    
    @Column(name="EMAIL", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="TYPE_CD", length=1)
    public String getTypeCd() {
        return this.typeCd;
    }
    
    public void setTypeCd(String typeCd) {
        this.typeCd = typeCd;
    }
    
    @Column(name="PROVIDE_LEVEL_CD", length=20)
    public String getProvideLevelCd() {
        return this.provideLevelCd;
    }
    
    public void setProvideLevelCd(String provideLevelCd) {
        this.provideLevelCd = provideLevelCd;
    }
    
    @Column(name="LINK_MAN", length=100)
    public String getLinkMan() {
        return this.linkMan;
    }
    
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan;
    }
    
    @Column(name="LINK_DESC", length=200)
    public String getLinkDesc() {
        return this.linkDesc;
    }
    
    public void setLinkDesc(String linkDesc) {
        this.linkDesc = linkDesc;
    }
    
    @Column(name="ATTACH_FLG", length=1)
    public String getAttachFlg() {
        return this.attachFlg;
    }
    
    public void setAttachFlg(String attachFlg) {
        this.attachFlg = attachFlg;
    }
    
    @Column(name="RECEIVE_STATUS_CD", length=1)
    public String getReceiveStatusCd() {
        return this.receiveStatusCd;
    }
    
    public void setReceiveStatusCd(String receiveStatusCd) {
        this.receiveStatusCd = receiveStatusCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECEIVE_DATE", length=7)
    public Date getReceiveDate() {
        return this.receiveDate;
    }
    
    public void setReceiveDate(Date receiveDate) {
        this.receiveDate = receiveDate;
    }
    
    @Column(name="SUBMIT_STATUS_CD", length=1)
    public String getSubmitStatusCd() {
        return this.submitStatusCd;
    }
    
    public void setSubmitStatusCd(String submitStatusCd) {
        this.submitStatusCd = submitStatusCd;
    }
    
    @Column(name="SUBMIT_ATTACH_FLG", length=1)
    public String getSubmitAttachFlg() {
        return this.submitAttachFlg;
    }
    
    public void setSubmitAttachFlg(String submitAttachFlg) {
        this.submitAttachFlg = submitAttachFlg;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SUBMIT_DATE", length=7)
    public Date getSubmitDate() {
        return this.submitDate;
    }
    
    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }
    
    @Column(name="REFUND_STATUS_CD", length=1)
    public String getRefundStatusCd() {
        return this.refundStatusCd;
    }
    
    public void setRefundStatusCd(String refundStatusCd) {
        this.refundStatusCd = refundStatusCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REFUND_DATE", length=7)
    public Date getRefundDate() {
        return this.refundDate;
    }
    
    public void setRefundDate(Date refundDate) {
        this.refundDate = refundDate;
    }
    
    @Column(name="SUP_BID_STATUS_CD", length=1)
    public String getSupBidStatusCd() {
        return this.supBidStatusCd;
    }
    
    public void setSupBidStatusCd(String supBidStatusCd) {
        this.supBidStatusCd = supBidStatusCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BID_DATE", length=7)
    public Date getBidDate() {
        return this.bidDate;
    }
    
    public void setBidDate(Date bidDate) {
        this.bidDate = bidDate;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="TECH_ATTACH_STATUS_CD", length=1)
    public String getTechAttachStatusCd() {
        return this.techAttachStatusCd;
    }
    
    public void setTechAttachStatusCd(String techAttachStatusCd) {
        this.techAttachStatusCd = techAttachStatusCd;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="DISP_ORDER_NO", precision=10, scale=0)
    public Long getDispOrderNo() {
        return this.dispOrderNo;
    }
    
    public void setDispOrderNo(Long dispOrderNo) {
        this.dispOrderNo = dispOrderNo;
    }
    
    @Column(name="OPEN_PLACCT_FLG", length=1)
    public String getOpenPlacctFlg() {
        return this.openPlacctFlg;
    }
    
    public void setOpenPlacctFlg(String openPlacctFlg) {
        this.openPlacctFlg = openPlacctFlg;
    }
    
    @Column(name="OPEN_PLACCT_CD", length=50)
    public String getOpenPlacctCd() {
        return this.openPlacctCd;
    }
    
    public void setOpenPlacctCd(String openPlacctCd) {
        this.openPlacctCd = openPlacctCd;
    }
    
    @Column(name="ORI_PWD", length=50)
    public String getOriPwd() {
        return this.oriPwd;
    }
    
    public void setOriPwd(String oriPwd) {
        this.oriPwd = oriPwd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TECH_ATTACH_DATE", length=7)
    public Date getTechAttachDate() {
        return this.techAttachDate;
    }
    
    public void setTechAttachDate(Date techAttachDate) {
        this.techAttachDate = techAttachDate;
    }
    
    @Column(name="GUAR_ATTA_CONF_FLG", length=1)
    public String getGuarAttaConfFlg() {
        return this.guarAttaConfFlg;
    }
    
    public void setGuarAttaConfFlg(String guarAttaConfFlg) {
        this.guarAttaConfFlg = guarAttaConfFlg;
    }
    
    @Column(name="GUAR_ATTA_CONF_NAME", length=100)
    public String getGuarAttaConfName() {
        return this.guarAttaConfName;
    }
    
    public void setGuarAttaConfName(String guarAttaConfName) {
        this.guarAttaConfName = guarAttaConfName;
    }
    
    @Column(name="GUAR_ATTA_CONF_UIID", length=50)
    public String getGuarAttaConfUiid() {
        return this.guarAttaConfUiid;
    }
    
    public void setGuarAttaConfUiid(String guarAttaConfUiid) {
        this.guarAttaConfUiid = guarAttaConfUiid;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="GUAR_ATTA_CONF_DATE", length=7)
    public Date getGuarAttaConfDate() {
        return this.guarAttaConfDate;
    }
    
    public void setGuarAttaConfDate(Date guarAttaConfDate) {
        this.guarAttaConfDate = guarAttaConfDate;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bidSup")
    @BatchSize(size=10)
public List<BidMeasureSupRel2> getBidMeasureSupRel2s() {
        return this.bidMeasureSupRel2s;
    }
    
    public void setBidMeasureSupRel2s(List<BidMeasureSupRel2> bidMeasureSupRel2s) {
        this.bidMeasureSupRel2s = bidMeasureSupRel2s;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bidSup")
    @BatchSize(size=10)
public List<BidOtherItemRel> getBidOtherItemRels() {
        return this.bidOtherItemRels;
    }
    
    public void setBidOtherItemRels(List<BidOtherItemRel> bidOtherItemRels) {
        this.bidOtherItemRels = bidOtherItemRels;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bidSup")
    @BatchSize(size=10)
public List<BidSporadicSupRel> getBidSporadicSupRels() {
        return this.bidSporadicSupRels;
    }
    
    public void setBidSporadicSupRels(List<BidSporadicSupRel> bidSporadicSupRels) {
        this.bidSporadicSupRels = bidSporadicSupRels;
    }
@OneToMany(fetch=FetchType.EAGER, mappedBy="bidSup" )
    @BatchSize(size=10)
    @OrderBy(clause="BATCH_NO asc")
public List<BidSupAttachRel> getBidSupAttachRels() {
        return this.bidSupAttachRels;
    }
    
    public void setBidSupAttachRels(List<BidSupAttachRel> bidSupAttachRels) {
        this.bidSupAttachRels = bidSupAttachRels;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bidSup")
    @BatchSize(size=10)
public List<BidSupOtherRel> getBidSupOtherRels() {
        return this.bidSupOtherRels;
    }
    
    public void setBidSupOtherRels(List<BidSupOtherRel> bidSupOtherRels) {
        this.bidSupOtherRels = bidSupOtherRels;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bidSup")
    @BatchSize(size=10)
public List<BidFeesSupRel> getBidFeesSupRels() {
        return this.bidFeesSupRels;
    }
    
    public void setBidFeesSupRels(List<BidFeesSupRel> bidFeesSupRels) {
        this.bidFeesSupRels = bidFeesSupRels;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bidSup")
    @BatchSize(size=10)
public List<BidDivisitonCust> getBidDivisitonCusts() {
        return this.bidDivisitonCusts;
    }
    
    public void setBidDivisitonCusts(List<BidDivisitonCust> bidDivisitonCusts) {
        this.bidDivisitonCusts = bidDivisitonCusts;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bidSup")
    @BatchSize(size=10)
public List<BidItemSupRel> getBidItemSupRels() {
        return this.bidItemSupRels;
    }
    
    public void setBidItemSupRels(List<BidItemSupRel> bidItemSupRels) {
        this.bidItemSupRels = bidItemSupRels;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bidSup")
    @BatchSize(size=10)
public List<BidDivisionSupRel> getBidDivisionSupRels() {
        return this.bidDivisionSupRels;
    }
    
    public void setBidDivisionSupRels(List<BidDivisionSupRel> bidDivisionSupRels) {
        this.bidDivisionSupRels = bidDivisionSupRels;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bidSup")
    @BatchSize(size=10)
public List<BidMeasureSupRel> getBidMeasureSupRels() {
        return this.bidMeasureSupRels;
    }
    
    public void setBidMeasureSupRels(List<BidMeasureSupRel> bidMeasureSupRels) {
        this.bidMeasureSupRels = bidMeasureSupRels;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bidSup")
    @BatchSize(size=10)
public List<BidTaxsSupRel> getBidTaxsSupRels() {
        return this.bidTaxsSupRels;
    }
    
    public void setBidTaxsSupRels(List<BidTaxsSupRel> bidTaxsSupRels) {
        this.bidTaxsSupRels = bidTaxsSupRels;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="bidSup")
    @BatchSize(size=10)
public List<BidOpenRecordSup> getBidOpenRecordSups() {
        return this.bidOpenRecordSups;
    }
    
    public void setBidOpenRecordSups(List<BidOpenRecordSup> bidOpenRecordSups) {
        this.bidOpenRecordSups = bidOpenRecordSups;
    }


}


