// 
package com.hhz.ump.entity.oa;
// Generated 2010-8-11 13:25:01 by Hibernate Tools 3.2.4.GA


import java.sql.Clob;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * OaEmailBody generated by hbm2java
 */
@Entity
@Table(name="OA_EMAIL_BODY"
    
)
@BatchSize(size=10)
public class OaEmailBody  implements java.io.Serializable {


     private String oaEmailBodyId;
     private String subject;
     private Clob content;
     private Clob toUserNames;
     private Clob toUserCds;
     private Clob copyUserNames;
     private Clob copyUserCds;
     private Clob bccUserNames;
     private Clob bccUserCds;
     private Date sendTime;
     private String uploadFlg;
     private String sendFlg;
     private String remindFlg;
     private String importLevelCd;
     private String remark;
     private String sender;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private String emailType;
     private List<OaEmail> oaEmails = new ArrayList<OaEmail>();

    public OaEmailBody() {
    }

	
    public OaEmailBody(String oaEmailBodyId, long recordVersion) {
        this.oaEmailBodyId = oaEmailBodyId;
        this.recordVersion = recordVersion;
    }
    public OaEmailBody(String oaEmailBodyId, String subject, Clob content, Clob toUserNames, Clob toUserCds, Clob copyUserNames, Clob copyUserCds, Clob bccUserNames, Clob bccUserCds, Date sendTime, String uploadFlg, String sendFlg, String remindFlg, String importLevelCd, String remark, String sender, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion, String emailType, List<OaEmail> oaEmails) {
       this.oaEmailBodyId = oaEmailBodyId;
       this.subject = subject;
       this.content = content;
       this.toUserNames = toUserNames;
       this.toUserCds = toUserCds;
       this.copyUserNames = copyUserNames;
       this.copyUserCds = copyUserCds;
       this.bccUserNames = bccUserNames;
       this.bccUserCds = bccUserCds;
       this.sendTime = sendTime;
       this.uploadFlg = uploadFlg;
       this.sendFlg = sendFlg;
       this.remindFlg = remindFlg;
       this.importLevelCd = importLevelCd;
       this.remark = remark;
       this.sender = sender;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.emailType = emailType;
       this.oaEmails = oaEmails;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="OA_EMAIL_BODY_ID", unique=true, nullable=false, length=50)
    public String getOaEmailBodyId() {
        return this.oaEmailBodyId;
    }
    
    public void setOaEmailBodyId(String oaEmailBodyId) {
        this.oaEmailBodyId = oaEmailBodyId;
    }

    
    @Column(name="SUBJECT", length=2000)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="CONTENT")
    public Clob getContent() {
        return this.content;
    }
    
    public void setContent(Clob content) {
        this.content = content;
    }

    
    @Column(name="TO_USER_NAMES")
    public Clob getToUserNames() {
        return this.toUserNames;
    }
    
    public void setToUserNames(Clob toUserNames) {
        this.toUserNames = toUserNames;
    }

    
    @Column(name="TO_USER_CDS")
    public Clob getToUserCds() {
        return this.toUserCds;
    }
    
    public void setToUserCds(Clob toUserCds) {
        this.toUserCds = toUserCds;
    }

    
    @Column(name="COPY_USER_NAMES")
    public Clob getCopyUserNames() {
        return this.copyUserNames;
    }
    
    public void setCopyUserNames(Clob copyUserNames) {
        this.copyUserNames = copyUserNames;
    }

    
    @Column(name="COPY_USER_CDS")
    public Clob getCopyUserCds() {
        return this.copyUserCds;
    }
    
    public void setCopyUserCds(Clob copyUserCds) {
        this.copyUserCds = copyUserCds;
    }

    
    @Column(name="BCC_USER_NAMES")
    public Clob getBccUserNames() {
        return this.bccUserNames;
    }
    
    public void setBccUserNames(Clob bccUserNames) {
        this.bccUserNames = bccUserNames;
    }

    
    @Column(name="BCC_USER_CDS")
    public Clob getBccUserCds() {
        return this.bccUserCds;
    }
    
    public void setBccUserCds(Clob bccUserCds) {
        this.bccUserCds = bccUserCds;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SEND_TIME", length=7)
    public Date getSendTime() {
        return this.sendTime;
    }
    
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    
    @Column(name="UPLOAD_FLG", length=1)
    public String getUploadFlg() {
        return this.uploadFlg;
    }
    
    public void setUploadFlg(String uploadFlg) {
        this.uploadFlg = uploadFlg;
    }

    
    @Column(name="SEND_FLG", length=1)
    public String getSendFlg() {
        return this.sendFlg;
    }
    
    public void setSendFlg(String sendFlg) {
        this.sendFlg = sendFlg;
    }

    
    @Column(name="REMIND_FLG", length=1)
    public String getRemindFlg() {
        return this.remindFlg;
    }
    
    public void setRemindFlg(String remindFlg) {
        this.remindFlg = remindFlg;
    }

    
    @Column(name="IMPORT_LEVEL_CD", length=20)
    public String getImportLevelCd() {
        return this.importLevelCd;
    }
    
    public void setImportLevelCd(String importLevelCd) {
        this.importLevelCd = importLevelCd;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="SENDER", length=100)
    public String getSender() {
        return this.sender;
    }
    
    public void setSender(String sender) {
        this.sender = sender;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }

    
    @Column(name="EMAIL_TYPE", length=1)
    public String getEmailType() {
        return this.emailType;
    }
    
    public void setEmailType(String emailType) {
        this.emailType = emailType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="oaEmailBody")
    @BatchSize(size=10)
public List<OaEmail> getOaEmails() {
        return this.oaEmails;
    }
    
    public void setOaEmails(List<OaEmail> oaEmails) {
        this.oaEmails = oaEmails;
    }




    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }

}


