// 
package com.hhz.ump.entity.oa;

// Generated 2010-8-11 13:25:01 by Hibernate Tools 3.2.4.GA

import java.sql.Clob;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.GenericGenerator;

/**
 * OaEmail generated by hbm2java
 */
@Entity
@Table(name = "OA_EMAIL")
public class OaEmail implements java.io.Serializable {

	private String oaEmailId;
	private OaEmailBox oaEmailBox;
	private OaEmailBody oaEmailBody;
	private String userCd;
	private String readFlg;
	private String attentionFlg;
	private String deleteFlg;
	private String replyFlg;
	private String userTypeCd;
	private String remark;
	private String creator;
	private String createdDeptCd;
	private Date createdDate;
	private String updator;
	private String updatedDeptCd;
	private Date updatedDate;
	private long recordVersion;

	private String subject;
	private String sender;
	private String sendFlg;
	private Clob toUserNames;
	private String importLevelCd;
	private String uploadFlg;
	private String emailType;

	@Column(name = "UPLOAD_FLG", length = 1)
	public String getUploadFlg() {
		return this.uploadFlg;
	}

	public void setUploadFlg(String uploadFlg) {
		this.uploadFlg = uploadFlg;
	}

	@Column(name = "IMPORT_LEVEL_CD", length = 20)
	public String getImportLevelCd() {
		return this.importLevelCd;
	}

	public void setImportLevelCd(String importLevelCd) {
		this.importLevelCd = importLevelCd;
	}

	@Column(name = "EMAIL_TYPE", length = 1)
	public String getEmailType() {
		return this.emailType;
	}

	public void setEmailType(String emailType) {
		this.emailType = emailType;
	}

	public OaEmail() {
	}

	public OaEmail(String oaEmailId, OaEmailBody oaEmailBody, long recordVersion) {
		this.oaEmailId = oaEmailId;
		this.oaEmailBody = oaEmailBody;
		this.recordVersion = recordVersion;
	}

	public OaEmail(String oaEmailId, OaEmailBox oaEmailBox, OaEmailBody oaEmailBody, String userCd, String readFlg, String attentionFlg,
			String deleteFlg, String replyFlg, String userTypeCd, String remark, String creator, String createdDeptCd, Date createdDate,
			String updator, String updatedDeptCd, Date updatedDate, long recordVersion) {
		this.oaEmailId = oaEmailId;
		this.oaEmailBox = oaEmailBox;
		this.oaEmailBody = oaEmailBody;
		this.userCd = userCd;
		this.readFlg = readFlg;
		this.attentionFlg = attentionFlg;
		this.deleteFlg = deleteFlg;
		this.replyFlg = replyFlg;
		this.userTypeCd = userTypeCd;
		this.remark = remark;
		this.creator = creator;
		this.createdDeptCd = createdDeptCd;
		this.createdDate = createdDate;
		this.updator = updator;
		this.updatedDeptCd = updatedDeptCd;
		this.updatedDate = updatedDate;
		this.recordVersion = recordVersion;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	@Column(name = "OA_EMAIL_ID", unique = true, nullable = false, length = 50)
	public String getOaEmailId() {
		return this.oaEmailId;
	}

	public void setOaEmailId(String oaEmailId) {
		this.oaEmailId = oaEmailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OA_EMAIL_BOX_ID")
	public OaEmailBox getOaEmailBox() {
		return this.oaEmailBox;
	}

	public void setOaEmailBox(OaEmailBox oaEmailBox) {
		this.oaEmailBox = oaEmailBox;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OA_EMAIL_BODY_ID", nullable = false)
	@Fetch(FetchMode.SELECT)
	public OaEmailBody getOaEmailBody() {
		return this.oaEmailBody;
	}

	public void setOaEmailBody(OaEmailBody oaEmailBody) {
		this.oaEmailBody = oaEmailBody;
	}

	@Column(name = "USER_CD", length = 20)
	public String getUserCd() {
		return this.userCd;
	}

	public void setUserCd(String userCd) {
		this.userCd = userCd;
	}

	@Column(name = "READ_FLG", length = 1)
	public String getReadFlg() {
		return this.readFlg;
	}

	public void setReadFlg(String readFlg) {
		this.readFlg = readFlg;
	}

	@Column(name = "ATTENTION_FLG", length = 1)
	public String getAttentionFlg() {
		return this.attentionFlg;
	}

	public void setAttentionFlg(String attentionFlg) {
		this.attentionFlg = attentionFlg;
	}

	@Column(name = "DELETE_FLG", length = 1)
	public String getDeleteFlg() {
		return this.deleteFlg;
	}

	public void setDeleteFlg(String deleteFlg) {
		this.deleteFlg = deleteFlg;
	}

	@Column(name = "REPLY_FLG", length = 1)
	public String getReplyFlg() {
		return this.replyFlg;
	}

	public void setReplyFlg(String replyFlg) {
		this.replyFlg = replyFlg;
	}

	@Column(name = "USER_TYPE_CD", length = 20)
	public String getUserTypeCd() {
		return this.userTypeCd;
	}

	public void setUserTypeCd(String userTypeCd) {
		this.userTypeCd = userTypeCd;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "CREATOR", length = 20)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATED_DEPT_CD", length = 20)
	public String getCreatedDeptCd() {
		return this.createdDeptCd;
	}

	public void setCreatedDeptCd(String createdDeptCd) {
		this.createdDeptCd = createdDeptCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATOR", length = 20)
	public String getUpdator() {
		return this.updator;
	}

	public void setUpdator(String updator) {
		this.updator = updator;
	}

	@Column(name = "UPDATED_DEPT_CD", length = 20)
	public String getUpdatedDeptCd() {
		return this.updatedDeptCd;
	}

	public void setUpdatedDeptCd(String updatedDeptCd) {
		this.updatedDeptCd = updatedDeptCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 7)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "RECORD_VERSION", nullable = false, precision = 10, scale = 0)
	@Version
	public long getRecordVersion() {
		return this.recordVersion;
	}

	public void setRecordVersion(long recordVersion) {
		this.recordVersion = recordVersion;
	}

	@Column(name = "SENDER", length = 100)
	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	@Column(name = "SUBJECT", length = 2000)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "SEND_FLG", length = 1)
	public String getSendFlg() {
		return this.sendFlg;
	}

	public void setSendFlg(String sendFlg) {
		this.sendFlg = sendFlg;
	}

	@Column(name = "TO_USER_NAMES")
	public Clob getToUserNames() {
		return this.toUserNames;
	}

	public void setToUserNames(Clob toUserNames) {
		this.toUserNames = toUserNames;
	}

    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }

}
