// 
package com.hhz.ump.entity.oa;
// Generated 2010-11-9 13:36:52 by Hibernate Tools 3.2.4.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OrderBy;

/**
 * OaManInfo generated by hbm2java
 */
@Entity
@Table(name="OA_MAN_INFO"
    
)
public class OaManInfo  implements java.io.Serializable {


     private String oaManInfoId;
     private String remark;
     private Character attachFlg;
     private String proposalCatInfo;
     private String proposalCatCd;
     private String manInfoCd;
     private String statusCd;
     private Long seriaNo;
     private String approveUserCd;
     private String nodeCd;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private Character rating;
     private List<OaManInfoNode> oaManInfoNodes = new ArrayList<OaManInfoNode>();
     private List<OaManInfoMessage> oaManInfoMessages = new ArrayList<OaManInfoMessage>();

    public OaManInfo() {
    }

	
    public OaManInfo(String oaManInfoId, long recordVersion) {
        this.oaManInfoId = oaManInfoId;
        this.recordVersion = recordVersion;
    }
    public OaManInfo(String statusCd, String oaManInfoId, String remark,Character rating, Character attachFlg, String proposalCatInfo, String proposalCatCd, String manInfoCd, Long seriaNo, String approveUserCd, String nodeCd, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion, List<OaManInfoNode> oaManInfoNodes, List<OaManInfoMessage> oaManInfoMessages) {
       this.oaManInfoId = oaManInfoId;
       this.remark = remark;
       this.attachFlg = attachFlg;
       this.proposalCatInfo = proposalCatInfo;
       this.proposalCatCd = proposalCatCd;
       this.manInfoCd = manInfoCd;
       this.seriaNo = seriaNo;
       this.approveUserCd = approveUserCd;
       this.nodeCd = nodeCd;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.oaManInfoNodes = oaManInfoNodes;
       this.oaManInfoMessages = oaManInfoMessages;
       this.statusCd = statusCd;
       this.rating = rating;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="OA_MAN_INFO_ID", unique=true, nullable=false, length=50)
    public String getOaManInfoId() {
        return this.oaManInfoId;
    }
    
    public void setOaManInfoId(String oaManInfoId) {
        this.oaManInfoId = oaManInfoId;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="ATTACH_FLG", length=1)
    public Character getAttachFlg() {
        return this.attachFlg;
    }
    
    public void setAttachFlg(Character attachFlg) {
        this.attachFlg = attachFlg;
    }

    
    @Column(name="PROPOSAL_CAT_INFO", length=4000)
    public String getProposalCatInfo() {
        return this.proposalCatInfo;
    }
    
    public void setProposalCatInfo(String proposalCatInfo) {
        this.proposalCatInfo = proposalCatInfo;
    }

    
    @Column(name="PROPOSAL_CAT_CD", length=20)
    public String getProposalCatCd() {
        return this.proposalCatCd;
    }
    
    public void setProposalCatCd(String proposalCatCd) {
        this.proposalCatCd = proposalCatCd;
    }

    
    @Column(name="MAN_INFO_CD", length=20)
    public String getManInfoCd() {
        return this.manInfoCd;
    }
    
    public void setManInfoCd(String manInfoCd) {
        this.manInfoCd = manInfoCd;
    }

    
    @Column(name="SERIA_NO", precision=10, scale=0)
    public Long getSeriaNo() {
        return this.seriaNo;
    }
    
    public void setSeriaNo(Long seriaNo) {
        this.seriaNo = seriaNo;
    }

    @Column(name="APPROVE_USER_CD", length=200)
    public String getApproveUserCd() {
		return approveUserCd;
	}

	public void setApproveUserCd(String approveUserCd) {
		this.approveUserCd = approveUserCd;
	}

    @Column(name="NODE_CD", length=200)
	public String getNodeCd() {
		return nodeCd;
	}

	public void setNodeCd(String nodeCd) {
		this.nodeCd = nodeCd;
	}

	@Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    @Column(name="STATUS_CD", length=20)
    public String getStatusCd() {
		return statusCd;
	}


	public void setStatusCd(String statusCd) {
		this.statusCd = statusCd;
	}


	@Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="oaManInfo")
    @BatchSize(size=10)
    @OrderBy(clause="APPROVE_LEVEL ASC")
public List<OaManInfoNode> getOaManInfoNodes() {
        return this.oaManInfoNodes;
    }
    
    public void setOaManInfoNodes(List<OaManInfoNode> oaManInfoNodes) {
        this.oaManInfoNodes = oaManInfoNodes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="oaManInfo")
    @BatchSize(size=10)
    @OrderBy(clause="CREATED_DATE ASC")
public List<OaManInfoMessage> getOaManInfoMessages() {
        return this.oaManInfoMessages;
    }
    
    public void setOaManInfoMessages(List<OaManInfoMessage> oaManInfoMessages) {
        this.oaManInfoMessages = oaManInfoMessages;
    }

    @Column(name="RATING", length=1)
	public Character getRating() {
		return rating;
	}


	public void setRating(Character rating) {
		this.rating = rating;
	}




}


