// 
package com.hhz.ump.entity.oa;
// Generated 2010-11-9 13:36:52 by Hibernate Tools 3.2.4.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * OaManInfoNode generated by hbm2java
 */
@Entity
@Table(name="OA_MAN_INFO_NODE"
    
)
public class OaManInfoNode  implements java.io.Serializable {


     private String oaManInfoNodeId;
     private OaManInfo oaManInfo;
     private String userCd;
     private String userName;
     private String nodeCd;
     private String groupNodeCd;
     private Date approveDate;
     private String approveOptionCd;
     private Long approveLevel;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;

    public OaManInfoNode() {
    }

	
    public OaManInfoNode(String oaManInfoNodeId, OaManInfo oaManInfo, long recordVersion) {
        this.oaManInfoNodeId = oaManInfoNodeId;
        this.oaManInfo = oaManInfo;
        this.recordVersion = recordVersion;
    }
    public OaManInfoNode(String oaManInfoNodeId, OaManInfo oaManInfo, String userCd, String userName, String nodeCd, String groupNodeCd, Date approveDate, String approveOptionCd, Long approveLevel, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion) {
       this.oaManInfoNodeId = oaManInfoNodeId;
       this.oaManInfo = oaManInfo;
       this.userCd = userCd;
       this.userName = userName;
       this.nodeCd = nodeCd;
       this.groupNodeCd = groupNodeCd;
       this.approveDate = approveDate;
       this.approveOptionCd = approveOptionCd;
       this.approveLevel = approveLevel;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="OA_MAN_INFO_NODE_ID", unique=true, nullable=false, length=50)
    public String getOaManInfoNodeId() {
        return this.oaManInfoNodeId;
    }
    
    public void setOaManInfoNodeId(String oaManInfoNodeId) {
        this.oaManInfoNodeId = oaManInfoNodeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OA_MAN_INFO_ID", nullable=false)
    public OaManInfo getOaManInfo() {
        return this.oaManInfo;
    }
    
    public void setOaManInfo(OaManInfo oaManInfo) {
        this.oaManInfo = oaManInfo;
    }

    
    @Column(name="USER_CD", length=20)
    public String getUserCd() {
        return this.userCd;
    }
    
    public void setUserCd(String userCd) {
        this.userCd = userCd;
    }

    
    @Column(name="USER_NAME", length=50)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="NODE_CD", length=20)
    public String getNodeCd() {
        return this.nodeCd;
    }
    
    public void setNodeCd(String nodeCd) {
        this.nodeCd = nodeCd;
    }

    
    @Column(name="GROUP_NODE_CD", length=20)
    public String getGroupNodeCd() {
        return this.groupNodeCd;
    }
    
    public void setGroupNodeCd(String groupNodeCd) {
        this.groupNodeCd = groupNodeCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="APPROVE_DATE", length=7)
    public Date getApproveDate() {
        return this.approveDate;
    }
    
    public void setApproveDate(Date approveDate) {
        this.approveDate = approveDate;
    }

    
    @Column(name="APPROVE_OPTION_CD", length=20)
    public String getApproveOptionCd() {
        return this.approveOptionCd;
    }
    
    public void setApproveOptionCd(String approveOptionCd) {
        this.approveOptionCd = approveOptionCd;
    }

    
    @Column(name="APPROVE_LEVEL", precision=10, scale=0)
    public Long getApproveLevel() {
        return this.approveLevel;
    }
    
    public void setApproveLevel(Long approveLevel) {
        this.approveLevel = approveLevel;
    }

    
    @Column(name="REMARK", length=4000)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }


    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }



}


