// 
package com.hhz.ump.entity.oa;
// Generated 2010-9-20 11:11:30 by Hibernate Tools 3.2.4.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * OaMeetingFile generated by hbm2java
 */
@Entity
@Table(name="OA_MEETING_FILE"
    
)
public class OaMeetingFile  implements java.io.Serializable {


     private String oaMeetingFileId;
     private OaMeetingFolder oaMeetingFolder;
     private String fileName;
     private String disabledFlg;
     private String deletedFlg;
     private String title;
     private String compere;
     private String content;
     private String recorder;
     private Date beginDate;
     private Date endDate;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;

    public OaMeetingFile() {
    }

	
    public OaMeetingFile(String oaMeetingFileId, OaMeetingFolder oaMeetingFolder, long recordVersion) {
        this.oaMeetingFileId = oaMeetingFileId;
        this.oaMeetingFolder = oaMeetingFolder;
        this.recordVersion = recordVersion;
    }
    public OaMeetingFile(String oaMeetingFileId, OaMeetingFolder oaMeetingFolder, String fileName, String disabledFlg, String deletedFlg, String title, String compere, String content, String recorder, Date beginDate, Date endDate, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion) {
       this.oaMeetingFileId = oaMeetingFileId;
       this.oaMeetingFolder = oaMeetingFolder;
       this.fileName = fileName;
       this.disabledFlg = disabledFlg;
       this.deletedFlg = deletedFlg;
       this.title = title;
       this.compere = compere;
       this.content = content;
       this.recorder = recorder;
       this.beginDate = beginDate;
       this.endDate = endDate;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="OA_MEETING_FILE_ID", unique=true, nullable=false, length=50)
    public String getOaMeetingFileId() {
        return this.oaMeetingFileId;
    }
    
    public void setOaMeetingFileId(String oaMeetingFileId) {
        this.oaMeetingFileId = oaMeetingFileId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OA_MEETING_FOLDER_ID", nullable=false)
    public OaMeetingFolder getOaMeetingFolder() {
        return this.oaMeetingFolder;
    }
    
    public void setOaMeetingFolder(OaMeetingFolder oaMeetingFolder) {
        this.oaMeetingFolder = oaMeetingFolder;
    }

    
    @Column(name="FILE_NAME", length=200)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="DISABLED_FLG", length=1)
    public String getDisabledFlg() {
        return this.disabledFlg;
    }
    
    public void setDisabledFlg(String disabledFlg) {
        this.disabledFlg = disabledFlg;
    }

    
    @Column(name="DELETED_FLG", length=1)
    public String getDeletedFlg() {
        return this.deletedFlg;
    }
    
    public void setDeletedFlg(String deletedFlg) {
        this.deletedFlg = deletedFlg;
    }

    
    @Column(name="TITLE", length=256)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="COMPERE", length=32)
    public String getCompere() {
        return this.compere;
    }
    
    public void setCompere(String compere) {
        this.compere = compere;
    }

    
    @Column(name="CONTENT", length=2000)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="RECORDER", length=32)
    public String getRecorder() {
        return this.recorder;
    }
    
    public void setRecorder(String recorder) {
        this.recorder = recorder;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BEGIN_DATE", length=7)
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_DATE", length=7)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }


    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }



}


