// 
package com.hhz.ump.entity.oa;
// Generated 2010-8-4 11:03:50 by Hibernate Tools 3.2.4.GA


import java.sql.Clob;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * SpecialTask generated by hbm2java
 */
@Entity
@Table(name="SPECIAL_TASK"
    
)
public class SpecialTask  implements java.io.Serializable {


     private String specialTaskId;
     private String deletedFlg;
     private String hiddenFlg;
     private String attentionFlg;
     private String waterNum;
     private Clob detail;
     private String sendPerson;
     private String responsiblePerson;
     private String coordinatePerson;
     private Date targetDate;
     private String status;
     private String priority;
     private String subject;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private List<SpecialTaskComment> specialTaskComments = new ArrayList<SpecialTaskComment>();

    public SpecialTask() {
    }

	
    public SpecialTask(String specialTaskId, long recordVersion) {
        this.specialTaskId = specialTaskId;
        this.recordVersion = recordVersion;
    }
    public SpecialTask(String specialTaskId, String deletedFlg, String hiddenFlg, String attentionFlg, String waterNum, Clob detail, String sendPerson, String responsiblePerson, String coordinatePerson, Date targetDate, String status, String priority, String subject, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion, List<SpecialTaskComment> specialTaskComments) {
       this.specialTaskId = specialTaskId;
       this.deletedFlg = deletedFlg;
       this.hiddenFlg = hiddenFlg;
       this.attentionFlg = attentionFlg;
       this.waterNum = waterNum;
       this.detail = detail;
       this.sendPerson = sendPerson;
       this.responsiblePerson = responsiblePerson;
       this.coordinatePerson = coordinatePerson;
       this.targetDate = targetDate;
       this.status = status;
       this.priority = priority;
       this.subject = subject;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.specialTaskComments = specialTaskComments;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="SPECIAL_TASK_ID", unique=true, nullable=false, length=50)
    public String getSpecialTaskId() {
        return this.specialTaskId;
    }
    
    public void setSpecialTaskId(String specialTaskId) {
        this.specialTaskId = specialTaskId;
    }

    
    @Column(name="DELETED_FLG", length=1)
    public String getDeletedFlg() {
        return this.deletedFlg;
    }
    
    public void setDeletedFlg(String deletedFlg) {
        this.deletedFlg = deletedFlg;
    }

    
    @Column(name="HIDDEN_FLG", length=1)
    public String getHiddenFlg() {
        return this.hiddenFlg;
    }
    
    public void setHiddenFlg(String hiddenFlg) {
        this.hiddenFlg = hiddenFlg;
    }

    
    @Column(name="ATTENTION_FLG", length=1)
    public String getAttentionFlg() {
        return this.attentionFlg;
    }
    
    public void setAttentionFlg(String attentionFlg) {
        this.attentionFlg = attentionFlg;
    }

    
    @Column(name="WATER_NUM", length=40)
    public String getWaterNum() {
        return this.waterNum;
    }
    
    public void setWaterNum(String waterNum) {
        this.waterNum = waterNum;
    }

    
    @Column(name="DETAIL")
    public Clob getDetail() {
        return this.detail;
    }
    
    public void setDetail(Clob detail) {
        this.detail = detail;
    }

    
    @Column(name="SEND_PERSON", length=200)
    public String getSendPerson() {
        return this.sendPerson;
    }
    
    public void setSendPerson(String sendPerson) {
        this.sendPerson = sendPerson;
    }

    
    @Column(name="RESPONSIBLE_PERSON", length=200)
    public String getResponsiblePerson() {
        return this.responsiblePerson;
    }
    
    public void setResponsiblePerson(String responsiblePerson) {
        this.responsiblePerson = responsiblePerson;
    }

    
    @Column(name="COORDINATE_PERSON", length=200)
    public String getCoordinatePerson() {
        return this.coordinatePerson;
    }
    
    public void setCoordinatePerson(String coordinatePerson) {
        this.coordinatePerson = coordinatePerson;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TARGET_DATE", length=7)
    public Date getTargetDate() {
        return this.targetDate;
    }
    
    public void setTargetDate(Date targetDate) {
        this.targetDate = targetDate;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="PRIORITY", length=1)
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }

    
    @Column(name="SUBJECT", length=200)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="specialTask")
    @BatchSize(size=10)
public List<SpecialTaskComment> getSpecialTaskComments() {
        return this.specialTaskComments;
    }
    
    public void setSpecialTaskComments(List<SpecialTaskComment> specialTaskComments) {
        this.specialTaskComments = specialTaskComments;
    }


    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }



}


