// 
package com.hhz.ump.entity.ct;
// Generated 2011-12-15 11:03:38 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * CtLedger generated by hbm2java
 */
@Entity
@Table(name="CT_LEDGER"
    
)
public class CtLedger  implements java.io.Serializable {


     private String ctLedgerId;
     private String projectCd;
     private String projectName;
     private String periods;
     private String approvePrivFlg;
     private String searchFlg;
     private Date startDate;
     private Date handDate;
     private BigDecimal totalConsArea;
     private BigDecimal plotRateArea;
     private BigDecimal costTargetTotalAmt;
     private BigDecimal plotRateUnitAmt;
     private String mainContentDesc;
     private String resApproveInfoId;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String ledgerStatus;
     private List<CtLand> ctLands = new ArrayList<CtLand>();
     private List<CtPlan> ctPlans = new ArrayList<CtPlan>();
     private List<CtItem> ctItems = new ArrayList<CtItem>();

    public CtLedger() {
    }

	
    public CtLedger(String ctLedgerId, long recordVersion) {
        this.ctLedgerId = ctLedgerId;
        this.recordVersion = recordVersion;
    }
    public CtLedger(String ctLedgerId, String projectCd, String projectName, String periods, String approvePrivFlg, String searchFlg, Date startDate, Date handDate, BigDecimal totalConsArea, BigDecimal plotRateArea, BigDecimal costTargetTotalAmt, BigDecimal plotRateUnitAmt, String mainContentDesc, String resApproveInfoId, String remark, String creator, String createdCenterCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedPositionCd, Date updatedDate, long recordVersion,String ledgerStatus, List<CtLand> ctLands, List<CtPlan> ctPlans, List<CtItem> ctItems) {
       this.ctLedgerId = ctLedgerId;
       this.projectCd = projectCd;
       this.projectName = projectName;
       this.periods = periods;
       this.approvePrivFlg = approvePrivFlg;
       this.searchFlg = searchFlg;
       this.startDate = startDate;
       this.handDate = handDate;
       this.totalConsArea = totalConsArea;
       this.plotRateArea = plotRateArea;
       this.costTargetTotalAmt = costTargetTotalAmt;
       this.plotRateUnitAmt = plotRateUnitAmt;
       this.mainContentDesc = mainContentDesc;
       this.resApproveInfoId = resApproveInfoId;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.ledgerStatus = ledgerStatus;
       this.ctLands = ctLands;
       this.ctPlans = ctPlans;
       this.ctItems = ctItems;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="CT_LEDGER_ID", unique=true, nullable=false, length=50)
    public String getCtLedgerId() {
        return this.ctLedgerId;
    }
    
    public void setCtLedgerId(String ctLedgerId) {
        this.ctLedgerId = ctLedgerId;
    }
    
    @Column(name="PROJECT_CD", length=20)
    public String getProjectCd() {
        return this.projectCd;
    }
    
    public void setProjectCd(String projectCd) {
        this.projectCd = projectCd;
    }
    
    @Column(name="PROJECT_NAME", length=100)
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    
    @Column(name="PERIODS", length=10)
    public String getPeriods() {
        return this.periods;
    }
    
    public void setPeriods(String periods) {
        this.periods = periods;
    }
    
    @Column(name="APPROVE_PRIV_FLG", length=1)
    public String getApprovePrivFlg() {
        return this.approvePrivFlg;
    }
    
    public void setApprovePrivFlg(String approvePrivFlg) {
        this.approvePrivFlg = approvePrivFlg;
    }
    
    @Column(name="SEARCH_FLG", length=1)
    public String getSearchFlg() {
        return this.searchFlg;
    }
    
    public void setSearchFlg(String searchFlg) {
        this.searchFlg = searchFlg;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="START_DATE", length=7)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="HAND_DATE", length=7)
    public Date getHandDate() {
        return this.handDate;
    }
    
    public void setHandDate(Date handDate) {
        this.handDate = handDate;
    }
    
    @Column(name="TOTAL_CONS_AREA", precision=18)
    public BigDecimal getTotalConsArea() {
        return this.totalConsArea;
    }
    
    public void setTotalConsArea(BigDecimal totalConsArea) {
        this.totalConsArea = totalConsArea;
    }
    
    @Column(name="PLOT_RATE_AREA", precision=18)
    public BigDecimal getPlotRateArea() {
        return this.plotRateArea;
    }
    
    public void setPlotRateArea(BigDecimal plotRateArea) {
        this.plotRateArea = plotRateArea;
    }
    
    @Column(name="COST_TARGET_TOTAL_AMT", precision=18)
    public BigDecimal getCostTargetTotalAmt() {
        return this.costTargetTotalAmt;
    }
    
    public void setCostTargetTotalAmt(BigDecimal costTargetTotalAmt) {
        this.costTargetTotalAmt = costTargetTotalAmt;
    }
    
    @Column(name="PLOT_RATE_UNIT_AMT", precision=18)
    public BigDecimal getPlotRateUnitAmt() {
        return this.plotRateUnitAmt;
    }
    
    public void setPlotRateUnitAmt(BigDecimal plotRateUnitAmt) {
        this.plotRateUnitAmt = plotRateUnitAmt;
    }
    
    @Column(name="MAIN_CONTENT_DESC", length=1000)
    public String getMainContentDesc() {
        return this.mainContentDesc;
    }
    
    public void setMainContentDesc(String mainContentDesc) {
        this.mainContentDesc = mainContentDesc;
    }
    
    @Column(name="RES_APPROVE_INFO_ID", length=50)
    public String getResApproveInfoId() {
        return this.resApproveInfoId;
    }
    
    public void setResApproveInfoId(String resApproveInfoId) {
        this.resApproveInfoId = resApproveInfoId;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    @Column(name="LEDGER_STATUS", length=1)
    public String getLedgerStatus() {
    	return this.ledgerStatus;
    }
    
    public void setLedgerStatus(String ledgerStatus) {
    	this.ledgerStatus = ledgerStatus;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="ctLedger")
    @BatchSize(size=10)
public List<CtLand> getCtLands() {
        return this.ctLands;
    }
    
    public void setCtLands(List<CtLand> ctLands) {
        this.ctLands = ctLands;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="ctLedger")
    @BatchSize(size=10)
public List<CtPlan> getCtPlans() {
        return this.ctPlans;
    }
    
    public void setCtPlans(List<CtPlan> ctPlans) {
        this.ctPlans = ctPlans;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="ctLedger")
    @BatchSize(size=10)
public List<CtItem> getCtItems() {
        return this.ctItems;
    }
    
    public void setCtItems(List<CtItem> ctItems) {
        this.ctItems = ctItems;
    }




}


