// 
package com.hhz.ump.entity.ct;
// Generated 2011-12-9 17:20:36 by Hibernate Tools 3.2.2.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * CtOperation generated by hbm2java
 */
@Entity
@Table(name="CT_OPERATION"
    
)
public class CtOperation  implements java.io.Serializable {


     private String ctOperationId;
     private CtLand ctLand;
     private String operTypeCd;
     private String operTypeName;
     private String contentDesc;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private List<CtOperItemRel> ctOperItemRels = new ArrayList<CtOperItemRel>();

    public CtOperation() {
    }

	
    public CtOperation(String ctOperationId, CtLand ctLand, long recordVersion) {
        this.ctOperationId = ctOperationId;
        this.ctLand = ctLand;
        this.recordVersion = recordVersion;
    }
    public CtOperation(String ctOperationId, CtLand ctLand, String operTypeCd, String operTypeName, String contentDesc, String remark, String creator, String createdCenterCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedPositionCd, Date updatedDate, long recordVersion, List<CtOperItemRel> ctOperItemRels) {
       this.ctOperationId = ctOperationId;
       this.ctLand = ctLand;
       this.operTypeCd = operTypeCd;
       this.operTypeName = operTypeName;
       this.contentDesc = contentDesc;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.ctOperItemRels = ctOperItemRels;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="CT_OPERATION_ID", unique=true, nullable=false, length=50)
    public String getCtOperationId() {
        return this.ctOperationId;
    }
    
    public void setCtOperationId(String ctOperationId) {
        this.ctOperationId = ctOperationId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CT_LAND_ID", nullable=false)
    public CtLand getCtLand() {
        return this.ctLand;
    }
    
    public void setCtLand(CtLand ctLand) {
        this.ctLand = ctLand;
    }
    
    @Column(name="OPER_TYPE_CD", length=20)
    public String getOperTypeCd() {
        return this.operTypeCd;
    }
    
    public void setOperTypeCd(String operTypeCd) {
        this.operTypeCd = operTypeCd;
    }
    
    @Column(name="OPER_TYPE_NAME", length=50)
    public String getOperTypeName() {
        return this.operTypeName;
    }
    
    public void setOperTypeName(String operTypeName) {
        this.operTypeName = operTypeName;
    }
    
    @Column(name="CONTENT_DESC", length=200)
    public String getContentDesc() {
        return this.contentDesc;
    }
    
    public void setContentDesc(String contentDesc) {
        this.contentDesc = contentDesc;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="ctOperation")
    @BatchSize(size=10)
public List<CtOperItemRel> getCtOperItemRels() {
        return this.ctOperItemRels;
    }
    
    public void setCtOperItemRels(List<CtOperItemRel> ctOperItemRels) {
        this.ctOperItemRels = ctOperItemRels;
    }




}


