package com.intelitune.nwms.model;

/**
 * InttUserCustomer generated by MyEclipse Persistence Tools
 */

public class InttUserCustomer implements java.io.Serializable {

	// Fields

	private Integer id;
	private InttUser inttUser;
	private Integer clientId;

	// Constructors

	/** default constructor */
	public InttUserCustomer() {
	}

	/** full constructor */
	public InttUserCustomer(InttUser inttUser, Integer clientId) {
		this.inttUser = inttUser;
		this.clientId = clientId;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public InttUser getInttUser() {
		return this.inttUser;
	}

	public void setInttUser(InttUser inttUser) {
		this.inttUser = inttUser;
	}

	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

}