// 
package com.hhz.ump.entity.sc;
// Generated 2012-2-13 10:23:34 by Hibernate Tools 3.2.2.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * ScContractTempletType generated by hbm2java
 */
@Entity
@Table(name="SC_CONTRACT_TEMPLET_TYPE"
    ,schema="POWERDESK"
)
public class ScContractTempletType  implements java.io.Serializable {


     private String contractTempletTypeId;
     private String typeName;
     private String moduleTypeCd;
     private Long sequenceNo;
     private String parentId;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private Byte isstandard;
     private Byte isDel;
     private String sn;
     private boolean ifNotNeedRes;
   


	private List<ScContractTemplet> scContractTemplets = new ArrayList<ScContractTemplet>();

    public ScContractTempletType() {
    }

	
    public ScContractTempletType(String contractTempletTypeId, long recordVersion) {
        this.contractTempletTypeId = contractTempletTypeId;
        this.recordVersion = recordVersion;
    }
    public ScContractTempletType(String contractTempletTypeId, String typeName, String moduleTypeCd, Long sequenceNo, String parentId, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, List<ScContractTemplet> scContractTemplets) {
       this.contractTempletTypeId = contractTempletTypeId;
       this.typeName = typeName;
       this.moduleTypeCd = moduleTypeCd;
       this.sequenceNo = sequenceNo;
       this.parentId = parentId;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.scContractTemplets = scContractTemplets;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="CONTRACT_TEMPLET_TYPE_ID", unique=true, nullable=false, length=50)
    public String getContractTempletTypeId() {
        return this.contractTempletTypeId;
    }
    
    public void setContractTempletTypeId(String contractTempletTypeId) {
        this.contractTempletTypeId = contractTempletTypeId;
    }
    
    @Column(name="TYPE_NAME", length=50)
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    
    @Column(name="MODULE_TYPE_CD", length=20)
    public String getModuleTypeCd() {
        return this.moduleTypeCd;
    }
    
    public void setModuleTypeCd(String moduleTypeCd) {
        this.moduleTypeCd = moduleTypeCd;
    }
    
    @Column(name="SEQUENCE_NO", precision=18, scale=0)
    public Long getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Long sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    
    @Column(name="PARENT_ID", length=50)
    public String getParentId() {
        return this.parentId;
    }
    
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="scContractTempletType")
    @BatchSize(size=10)
public List<ScContractTemplet> getScContractTemplets() {
        return this.scContractTemplets;
    }
    
    public void setScContractTemplets(List<ScContractTemplet> scContractTemplets) {
        this.scContractTemplets = scContractTemplets;
    }

    /**
	 * @return the isstandard
	 */
     @Column(name="ISSTANDARD", precision=2, scale=0)
	public Byte getIsstandard() {
		return isstandard;
	}


	/**
	 * @param isstandard the isstandard to set
	 */
	public void setIsstandard(Byte isstandard) {
		this.isstandard = isstandard;
	}

	 /**
	 * @return the isdel
	 */
	 @Column(name="IS_DEL", precision=2, scale=0)
	public Byte getIsDel() {
		return isDel;
	}


	/**
	 * @param isdel the isdel to set
	 */
	public void setIsDel(Byte isdel) {
		this.isDel = isdel;
	}
	  /**
	 * @return the sn
	 */
	public String getSn() {
		return sn;
	}


	/**
	 * @param sn the sn to set
	 */
	public void setSn(String sn) {
		this.sn = sn;
	}
	
	@Column(name="IF_NOT_NEED_RES", precision=1, scale=0)
	public Boolean getIfNotNeedRes() {
		return ifNotNeedRes;
	}


	public void setIfNotNeedRes(Boolean ifNotNeedRes) {
		this.ifNotNeedRes = ifNotNeedRes;
	}
}


