// 
package com.hhz.ump.entity.sc;
// Generated 2012-2-13 10:23:34 by Hibernate Tools 3.2.2.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * ScContractTempletHis generated by hbm2java
 */
@Entity
@Table(name="SC_CONTRACT_TEMPLET_HIS"
    ,schema="POWERDESK"
)
public class ScContractTempletHis  implements java.io.Serializable {


     private String contractTempletHisId;
     private ScContractTempletInfo scContractTempletInfo;
     private String templetPath;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private List<ScContractMark> scContractMarks = new ArrayList<ScContractMark>();
     private List<ScContractTempletInfo> scContractTempletInfos = new ArrayList<ScContractTempletInfo>();
     private List<ScContractInfoAttach> scContractInfoAttachs = new ArrayList<ScContractInfoAttach>();
     private List<ScContractInfoSay> scContractInfoSaies = new ArrayList<ScContractInfoSay>();

    public ScContractTempletHis() {
    }

	
    public ScContractTempletHis(String contractTempletHisId, ScContractTempletInfo scContractTempletInfo, long recordVersion) {
        this.contractTempletHisId = contractTempletHisId;
        this.scContractTempletInfo = scContractTempletInfo;
        this.recordVersion = recordVersion;
    }
    public ScContractTempletHis(String contractTempletHisId, ScContractTempletInfo scContractTempletInfo, String templetPath, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, List<ScContractMark> scContractMarks, List<ScContractTempletInfo> scContractTempletInfos) {
       this.contractTempletHisId = contractTempletHisId;
       this.scContractTempletInfo = scContractTempletInfo;
       this.templetPath = templetPath;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.scContractMarks = scContractMarks;
       this.scContractTempletInfos = scContractTempletInfos;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="CONTRACT_TEMPLET_HIS_ID", unique=true, nullable=false, length=50)
    public String getContractTempletHisId() {
        return this.contractTempletHisId;
    }
    
    public void setContractTempletHisId(String contractTempletHisId) {
        this.contractTempletHisId = contractTempletHisId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRACT_TEMPLET_INFO_ID", nullable=false)
    public ScContractTempletInfo getScContractTempletInfo() {
        return this.scContractTempletInfo;
    }
    
    public void setScContractTempletInfo(ScContractTempletInfo scContractTempletInfo) {
        this.scContractTempletInfo = scContractTempletInfo;
    }
    
    @Column(name="TEMPLET_PATH", length=50)
    public String getTempletPath() {
        return this.templetPath;
    }
    
    public void setTempletPath(String templetPath) {
        this.templetPath = templetPath;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="scContractTempletHis")
    @BatchSize(size=10)
public List<ScContractMark> getScContractMarks() {
        return this.scContractMarks;
    }
    
    public void setScContractMarks(List<ScContractMark> scContractMarks) {
        this.scContractMarks = scContractMarks;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="scContractTempletHis")
    @BatchSize(size=10)
public List<ScContractTempletInfo> getScContractTempletInfos() {
        return this.scContractTempletInfos;
    }
    
    public void setScContractTempletInfos(List<ScContractTempletInfo> scContractTempletInfos) {
        this.scContractTempletInfos = scContractTempletInfos;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="scContractTempletInfo")
    @BatchSize(size=10)
    public List<ScContractInfoAttach> getScContractInfoAttachs() {
        return this.scContractInfoAttachs;
    }
    
    public void setScContractInfoAttachs(List<ScContractInfoAttach> scContractInfoAttachs) {
        this.scContractInfoAttachs = scContractInfoAttachs;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="scContractTempletInfo")
    @BatchSize(size=10)
    public List<ScContractInfoSay> getScContractInfoSaies() {
        return this.scContractInfoSaies;
    }
    
    public void setScContractInfoSaies(List<ScContractInfoSay> scContractInfoSaies) {
        this.scContractInfoSaies = scContractInfoSaies;
    }




}


