// 
package com.hhz.ump.entity.oa;
// Generated 2010-8-11 13:25:01 by Hibernate Tools 3.2.4.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * OaMeetingRoomRes generated by hbm2java
 */
@Entity
@Table(name="OA_MEETING_ROOM_RES"
    ,schema="POWERDESK"
)
public class OaMeetingRoomRes  implements java.io.Serializable {


     private String oaMeetingRoomResId;
     private String roomId;
     private String applicant;
     private String compere;
     private String recorder;
     private String subject;
     private Date beginTime;
     private Date endTime;
     private String participators;
     private String relatedDept;
     private Integer partNum;
     private String encryptFlg;
     private String attention;
     private String status;
     private String addrType;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;

    public OaMeetingRoomRes() {
    }

	
    public OaMeetingRoomRes(String oaMeetingRoomResId, long recordVersion) {
        this.oaMeetingRoomResId = oaMeetingRoomResId;
        this.recordVersion = recordVersion;
    }
    public OaMeetingRoomRes(String oaMeetingRoomResId, String roomId, String applicant, String compere, String recorder, String subject, Date beginTime, Date endTime, String participators, String relatedDept, Integer partNum, String encryptFlg, String attention, String status,String addrType, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion) {
       this.oaMeetingRoomResId = oaMeetingRoomResId;
       this.roomId = roomId;
       this.applicant = applicant;
       this.compere = compere;
       this.recorder = recorder;
       this.subject = subject;
       this.beginTime = beginTime;
       this.endTime = endTime;
       this.participators = participators;
       this.relatedDept = relatedDept;
       this.partNum = partNum;
       this.encryptFlg = encryptFlg;
       this.attention = attention;
       this.status = status;
       this.addrType = addrType;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="OA_MEETING_ROOM_RES_ID", unique=true, nullable=false, length=50)
    public String getOaMeetingRoomResId() {
        return this.oaMeetingRoomResId;
    }
    
    public void setOaMeetingRoomResId(String oaMeetingRoomResId) {
        this.oaMeetingRoomResId = oaMeetingRoomResId;
    }

    
    @Column(name="ROOM_ID", length=5)
    public String getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }

    
    @Column(name="APPLICANT", length=20)
    public String getApplicant() {
        return this.applicant;
    }
    
    public void setApplicant(String applicant) {
        this.applicant = applicant;
    }

    
    @Column(name="COMPERE", length=20)
    public String getCompere() {
        return this.compere;
    }
    
    public void setCompere(String compere) {
        this.compere = compere;
    }

    
    @Column(name="RECORDER", length=20)
    public String getRecorder() {
        return this.recorder;
    }
    
    public void setRecorder(String recorder) {
        this.recorder = recorder;
    }

    
    @Column(name="SUBJECT", length=2000)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BEGIN_TIME", length=7)
    public Date getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_TIME", length=7)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    
    @Column(name="PARTICIPATORS", length=1000)
    public String getParticipators() {
        return this.participators;
    }
    
    public void setParticipators(String participators) {
        this.participators = participators;
    }

    
    @Column(name="RELATED_DEPT", length=200)
    public String getRelatedDept() {
        return this.relatedDept;
    }
    
    public void setRelatedDept(String relatedDept) {
        this.relatedDept = relatedDept;
    }

    
    @Column(name="PART_NUM", precision=5, scale=0)
    public Integer getPartNum() {
        return this.partNum;
    }
    
    public void setPartNum(Integer partNum) {
        this.partNum = partNum;
    }

    
    @Column(name="ENCRYPT_FLG", length=1)
    public String getEncryptFlg() {
        return this.encryptFlg;
    }
    
    public void setEncryptFlg(String encryptFlg) {
        this.encryptFlg = encryptFlg;
    }

    
    @Column(name="ATTENTION", length=2000)
    public String getAttention() {
        return this.attention;
    }
    
    public void setAttention(String attention) {
        this.attention = attention;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name="ADDR_TYPE", length=20)
    public String getAddrType() {
		return addrType;
	}


	public void setAddrType(String addrType) {
		this.addrType = addrType;
	}


	@Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }


    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }



}


