// 
package com.hhz.ump.entity.oa;
// Generated 2010-8-11 13:25:01 by Hibernate Tools 3.2.4.GA


import java.sql.Clob;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * OaNotify generated by hbm2java
 */
@Entity
@Table(name="OA_NOTIFY"
    ,schema="POWERDESK"
)
public class OaNotify  implements java.io.Serializable {


     private String oaNotifyId;
     private String toDeptCds;
     private String subject;
     private Clob content;
     private Clob readers;
     private Date sendTime;
     private Date startDate;
     private Date endDate;
     private String uploadFlg;
     private String typeCd;
     private String topFlg;
     private String enabledFlg;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;

    public OaNotify() {
    }

	
    public OaNotify(String oaNotifyId, long recordVersion) {
        this.oaNotifyId = oaNotifyId;
        this.recordVersion = recordVersion;
    }
    public OaNotify(String oaNotifyId, String toDeptCds, String subject, Clob content, Clob readers, Date sendTime, Date startDate, Date endDate, String uploadFlg, String typeCd, String topFlg, String enabledFlg, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion) {
       this.oaNotifyId = oaNotifyId;
       this.toDeptCds = toDeptCds;
       this.subject = subject;
       this.content = content;
       this.readers = readers;
       this.sendTime = sendTime;
       this.startDate = startDate;
       this.endDate = endDate;
       this.uploadFlg = uploadFlg;
       this.typeCd = typeCd;
       this.topFlg = topFlg;
       this.enabledFlg = enabledFlg;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="OA_NOTIFY_ID", unique=true, nullable=false, length=50)
    public String getOaNotifyId() {
        return this.oaNotifyId;
    }
    
    public void setOaNotifyId(String oaNotifyId) {
        this.oaNotifyId = oaNotifyId;
    }

    
    @Column(name="TO_DEPT_CDS", length=2000)
    public String getToDeptCds() {
        return this.toDeptCds;
    }
    
    public void setToDeptCds(String toDeptCds) {
        this.toDeptCds = toDeptCds;
    }

    
    @Column(name="SUBJECT", length=500)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="CONTENT")
    public Clob getContent() {
        return this.content;
    }
    
    public void setContent(Clob content) {
        this.content = content;
    }

    
    @Column(name="READERS")
    public Clob getReaders() {
        return this.readers;
    }
    
    public void setReaders(Clob readers) {
        this.readers = readers;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SEND_TIME", length=7)
    public Date getSendTime() {
        return this.sendTime;
    }
    
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="START_DATE", length=7)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_DATE", length=7)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="UPLOAD_FLG", length=1)
    public String getUploadFlg() {
        return this.uploadFlg;
    }
    
    public void setUploadFlg(String uploadFlg) {
        this.uploadFlg = uploadFlg;
    }

    
    @Column(name="TYPE_CD", length=20)
    public String getTypeCd() {
        return this.typeCd;
    }
    
    public void setTypeCd(String typeCd) {
        this.typeCd = typeCd;
    }

    
    @Column(name="TOP_FLG", length=1)
    public String getTopFlg() {
        return this.topFlg;
    }
    
    public void setTopFlg(String topFlg) {
        this.topFlg = topFlg;
    }

    
    @Column(name="ENABLED_FLG", length=1)
    public String getEnabledFlg() {
        return this.enabledFlg;
    }
    
    public void setEnabledFlg(String enabledFlg) {
        this.enabledFlg = enabledFlg;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }

    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }




}


