// 
package com.hhz.uums.entity.app;
// Generated 2011-1-24 17:36:15 by Hibernate Tools 3.2.2.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * AppFunction generated by hbm2java
 */
@Entity
@Table(name="APP_FUNCTION"
    
)
public class AppFunction  implements java.io.Serializable {


     private String appFunctionId;
     private AppPage appPage;
     private String functionCd;
     private String functionBizCd;
     private String functionName;
     private String functionTip;
     private String functionTypeCd;
     private String remark;
     private Long sequenceNo;
     private String creator;
     private String createdCenterCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private List<AppRoleFunctionRel> appRoleFunctionRels = new ArrayList<AppRoleFunctionRel>();
     private List<AppRule> appRules = new ArrayList<AppRule>();

    public AppFunction() {
    }

	
    public AppFunction(String appFunctionId, AppPage appPage, long recordVersion) {
        this.appFunctionId = appFunctionId;
        this.appPage = appPage;
        this.recordVersion = recordVersion;
    }
    public AppFunction(String appFunctionId, AppPage appPage, String functionCd, String functionBizCd, String functionName, String functionTip, String functionTypeCd, String remark, Long sequenceNo, String creator, String createdCenterCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedPositionCd, Date updatedDate, long recordVersion, List<AppRoleFunctionRel> appRoleFunctionRels, List<AppRule> appRules) {
       this.appFunctionId = appFunctionId;
       this.appPage = appPage;
       this.functionCd = functionCd;
       this.functionBizCd = functionBizCd;
       this.functionName = functionName;
       this.functionTip = functionTip;
       this.functionTypeCd = functionTypeCd;
       this.remark = remark;
       this.sequenceNo = sequenceNo;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.appRoleFunctionRels = appRoleFunctionRels;
       this.appRules = appRules;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="APP_FUNCTION_ID", unique=true, nullable=false, length=50)
    public String getAppFunctionId() {
        return this.appFunctionId;
    }
    
    public void setAppFunctionId(String appFunctionId) {
        this.appFunctionId = appFunctionId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APP_PAGE_ID", nullable=false)
    public AppPage getAppPage() {
        return this.appPage;
    }
    
    public void setAppPage(AppPage appPage) {
        this.appPage = appPage;
    }
    
    @Column(name="FUNCTION_CD", length=20)
    public String getFunctionCd() {
        return this.functionCd;
    }
    
    public void setFunctionCd(String functionCd) {
        this.functionCd = functionCd;
    }
    
    @Column(name="FUNCTION_BIZ_CD", length=20)
    public String getFunctionBizCd() {
        return this.functionBizCd;
    }
    
    public void setFunctionBizCd(String functionBizCd) {
        this.functionBizCd = functionBizCd;
    }
    
    @Column(name="FUNCTION_NAME", length=50)
    public String getFunctionName() {
        return this.functionName;
    }
    
    public void setFunctionName(String functionName) {
        this.functionName = functionName;
    }
    
    @Column(name="FUNCTION_TIP", length=100)
    public String getFunctionTip() {
        return this.functionTip;
    }
    
    public void setFunctionTip(String functionTip) {
        this.functionTip = functionTip;
    }
    
    @Column(name="FUNCTION_TYPE_CD", length=20)
    public String getFunctionTypeCd() {
        return this.functionTypeCd;
    }
    
    public void setFunctionTypeCd(String functionTypeCd) {
        this.functionTypeCd = functionTypeCd;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="SEQUENCE_NO", precision=10, scale=0)
    public Long getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Long sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="appFunction")
    @BatchSize(size=10)
public List<AppRoleFunctionRel> getAppRoleFunctionRels() {
        return this.appRoleFunctionRels;
    }
    
    public void setAppRoleFunctionRels(List<AppRoleFunctionRel> appRoleFunctionRels) {
        this.appRoleFunctionRels = appRoleFunctionRels;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="appFunction")
    @BatchSize(size=10)
public List<AppRule> getAppRules() {
        return this.appRules;
    }
    
    public void setAppRules(List<AppRule> appRules) {
        this.appRules = appRules;
    }

    private String createdDeptCd;
    private String updatedDeptCd;
    @Column(name="CREATED_DEPT_CD", length=20)
	public String getCreatedDeptCd() {
		return createdDeptCd;
	}


	public void setCreatedDeptCd(String createdDeptCd) {
		this.createdDeptCd = createdDeptCd;
	}

	@Column(name="UPDATED_DEPT_CD", length=20)
	public String getUpdatedDeptCd() {
		return updatedDeptCd;
	}


	public void setUpdatedDeptCd(String updatedDeptCd) {
		this.updatedDeptCd = updatedDeptCd;
	}




}


