// 
package com.hhz.uums.entity.app;
// Generated 2011-1-24 17:36:15 by Hibernate Tools 3.2.2.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * AppRule generated by hbm2java
 */
@Entity
@Table(name="APP_RULE"
    
)
public class AppRule  implements java.io.Serializable {


     private String appRuleId;
     private AppFunction appFunction;
     private String ruleName;
     private String ruleCd;
     private String ruleBizCd;
     private String contentDesc;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private List<AppRoleRuleRel> appRoleRuleRels = new ArrayList<AppRoleRuleRel>();

    public AppRule() {
    }

	
    public AppRule(String appRuleId, AppFunction appFunction, long recordVersion) {
        this.appRuleId = appRuleId;
        this.appFunction = appFunction;
        this.recordVersion = recordVersion;
    }
    public AppRule(String appRuleId, AppFunction appFunction, String ruleName, String ruleCd, String ruleBizCd, String contentDesc, String remark, String creator, String createdCenterCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedPositionCd, Date updatedDate, long recordVersion, List<AppRoleRuleRel> appRoleRuleRels) {
       this.appRuleId = appRuleId;
       this.appFunction = appFunction;
       this.ruleName = ruleName;
       this.ruleCd = ruleCd;
       this.ruleBizCd = ruleBizCd;
       this.contentDesc = contentDesc;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.appRoleRuleRels = appRoleRuleRels;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="APP_RULE_ID", unique=true, nullable=false, length=50)
    public String getAppRuleId() {
        return this.appRuleId;
    }
    
    public void setAppRuleId(String appRuleId) {
        this.appRuleId = appRuleId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APP_FUNCTION_ID", nullable=false)
    public AppFunction getAppFunction() {
        return this.appFunction;
    }
    
    public void setAppFunction(AppFunction appFunction) {
        this.appFunction = appFunction;
    }
    
    @Column(name="RULE_NAME", length=50)
    public String getRuleName() {
        return this.ruleName;
    }
    
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }
    
    @Column(name="RULE_CD", length=20)
    public String getRuleCd() {
        return this.ruleCd;
    }
    
    public void setRuleCd(String ruleCd) {
        this.ruleCd = ruleCd;
    }
    
    @Column(name="RULE_BIZ_CD", length=20)
    public String getRuleBizCd() {
        return this.ruleBizCd;
    }
    
    public void setRuleBizCd(String ruleBizCd) {
        this.ruleBizCd = ruleBizCd;
    }
    
    @Column(name="CONTENT_DESC", length=500)
    public String getContentDesc() {
        return this.contentDesc;
    }
    
    public void setContentDesc(String contentDesc) {
        this.contentDesc = contentDesc;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="appRule")
    @BatchSize(size=10)
public List<AppRoleRuleRel> getAppRoleRuleRels() {
        return this.appRoleRuleRels;
    }
    
    public void setAppRoleRuleRels(List<AppRoleRuleRel> appRoleRuleRels) {
        this.appRoleRuleRels = appRoleRuleRels;
    }

    private String createdDeptCd;
    private String updatedDeptCd;
    @Column(name="CREATED_DEPT_CD", length=20)
	public String getCreatedDeptCd() {
		return createdDeptCd;
	}


	public void setCreatedDeptCd(String createdDeptCd) {
		this.createdDeptCd = createdDeptCd;
	}

	@Column(name="UPDATED_DEPT_CD", length=20)
	public String getUpdatedDeptCd() {
		return updatedDeptCd;
	}


	public void setUpdatedDeptCd(String updatedDeptCd) {
		this.updatedDeptCd = updatedDeptCd;
	}




}


