// 
package com.hhz.ump.entity.jbpm;
// Generated 2010-8-4 11:22:38 by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.BatchSize;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JbpmReimburse generated by hbm2java
 */
@Entity
@Table(name="JBPM_REIMBURSE"
    
)
public class JbpmReimburse  implements java.io.Serializable {


     private String jbpmReimburseId;
     private String reimburseCd;
     private String userCd;
     private String executionId;
     private String curTaskId;
     private String userName;
     private String deptCd;
     private String centerCd;
     private String positionCd;
     private String travelReason;
     private String travelPlace;
     private Date reiDate;
     private BigDecimal amountFee;
     private BigDecimal selfPayAmount;
     private String statusCd;
     private String inOutFlg;
     private String approver;
     private String sendTypeCd;
     private String bankName;
     private String bankNo;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private List<JbpmReimburseHis> jbpmReimburseHises = new ArrayList<JbpmReimburseHis>();
     private List<JbpmReimburseDetl> jbpmReimburseDetls = new ArrayList<JbpmReimburseDetl>();

    public JbpmReimburse() {
    }

	
    public JbpmReimburse(String jbpmReimburseId, BigDecimal amountFee, long recordVersion) {
        this.jbpmReimburseId = jbpmReimburseId;
        this.amountFee = amountFee;
        this.recordVersion = recordVersion;
    }
    public JbpmReimburse(String jbpmReimburseId, String reimburseCd, String userCd, String executionId, String curTaskId, String userName, String deptCd, String centerCd, String positionCd, String travelReason, String travelPlace, Date reiDate, BigDecimal amountFee, BigDecimal selfPayAmount, String statusCd, String inOutFlg, String approver, String sendTypeCd, String bankName, String bankNo, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion, List<JbpmReimburseHis> jbpmReimburseHises, List<JbpmReimburseDetl> jbpmReimburseDetls) {
       this.jbpmReimburseId = jbpmReimburseId;
       this.reimburseCd = reimburseCd;
       this.userCd = userCd;
       this.executionId = executionId;
       this.curTaskId = curTaskId;
       this.userName = userName;
       this.deptCd = deptCd;
       this.centerCd = centerCd;
       this.positionCd = positionCd;
       this.travelReason = travelReason;
       this.travelPlace = travelPlace;
       this.reiDate = reiDate;
       this.amountFee = amountFee;
       this.selfPayAmount = selfPayAmount;
       this.statusCd = statusCd;
       this.inOutFlg = inOutFlg;
       this.approver = approver;
       this.sendTypeCd = sendTypeCd;
       this.bankName = bankName;
       this.bankNo = bankNo;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.jbpmReimburseHises = jbpmReimburseHises;
       this.jbpmReimburseDetls = jbpmReimburseDetls;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="JBPM_REIMBURSE_ID", unique=true, nullable=false, length=50)
    public String getJbpmReimburseId() {
        return this.jbpmReimburseId;
    }
    
    public void setJbpmReimburseId(String jbpmReimburseId) {
        this.jbpmReimburseId = jbpmReimburseId;
    }

    
    @Column(name="REIMBURSE_CD", length=20)
    public String getReimburseCd() {
        return this.reimburseCd;
    }
    
    public void setReimburseCd(String reimburseCd) {
        this.reimburseCd = reimburseCd;
    }

    
    @Column(name="USER_CD", length=20)
    public String getUserCd() {
        return this.userCd;
    }
    
    public void setUserCd(String userCd) {
        this.userCd = userCd;
    }

    
    @Column(name="EXECUTION_ID", length=50)
    public String getExecutionId() {
        return this.executionId;
    }
    
    public void setExecutionId(String executionId) {
        this.executionId = executionId;
    }

    
    @Column(name="CUR_TASK_ID", length=50)
    public String getCurTaskId() {
        return this.curTaskId;
    }
    
    public void setCurTaskId(String curTaskId) {
        this.curTaskId = curTaskId;
    }

    
    @Column(name="USER_NAME", length=50)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="DEPT_CD", length=20)
    public String getDeptCd() {
        return this.deptCd;
    }
    
    public void setDeptCd(String deptCd) {
        this.deptCd = deptCd;
    }

    
    @Column(name="CENTER_CD", length=20)
    public String getCenterCd() {
        return this.centerCd;
    }
    
    public void setCenterCd(String centerCd) {
        this.centerCd = centerCd;
    }

    
    @Column(name="POSITION_CD", length=20)
    public String getPositionCd() {
        return this.positionCd;
    }
    
    public void setPositionCd(String positionCd) {
        this.positionCd = positionCd;
    }

    
    @Column(name="TRAVEL_REASON", length=500)
    public String getTravelReason() {
        return this.travelReason;
    }
    
    public void setTravelReason(String travelReason) {
        this.travelReason = travelReason;
    }

    
    @Column(name="TRAVEL_PLACE", length=200)
    public String getTravelPlace() {
        return this.travelPlace;
    }
    
    public void setTravelPlace(String travelPlace) {
        this.travelPlace = travelPlace;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REI_DATE", length=7)
    public Date getReiDate() {
        return this.reiDate;
    }
    
    public void setReiDate(Date reiDate) {
        this.reiDate = reiDate;
    }

    
    @Column(name="AMOUNT_FEE", nullable=false, precision=18, scale=4)
    public BigDecimal getAmountFee() {
        return this.amountFee;
    }
    
    public void setAmountFee(BigDecimal amountFee) {
        this.amountFee = amountFee;
    }

    
    @Column(name="SELF_PAY_AMOUNT", precision=18, scale=4)
    public BigDecimal getSelfPayAmount() {
        return this.selfPayAmount;
    }
    
    public void setSelfPayAmount(BigDecimal selfPayAmount) {
        this.selfPayAmount = selfPayAmount;
    }

    
    @Column(name="STATUS_CD", length=20)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }

    
    @Column(name="IN_OUT_FLG", length=1)
    public String getInOutFlg() {
        return this.inOutFlg;
    }
    
    public void setInOutFlg(String inOutFlg) {
        this.inOutFlg = inOutFlg;
    }

    
    @Column(name="APPROVER", length=200)
    public String getApprover() {
        return this.approver;
    }
    
    public void setApprover(String approver) {
        this.approver = approver;
    }

    
    @Column(name="SEND_TYPE_CD", length=20)
    public String getSendTypeCd() {
        return this.sendTypeCd;
    }
    
    public void setSendTypeCd(String sendTypeCd) {
        this.sendTypeCd = sendTypeCd;
    }

    
    @Column(name="BANK_NAME", length=50)
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    
    @Column(name="BANK_NO", length=50)
    public String getBankNo() {
        return this.bankNo;
    }
    
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jbpmReimburse")
    @BatchSize(size=10)
public List<JbpmReimburseHis> getJbpmReimburseHises() {
        return this.jbpmReimburseHises;
    }
    
    public void setJbpmReimburseHises(List<JbpmReimburseHis> jbpmReimburseHises) {
        this.jbpmReimburseHises = jbpmReimburseHises;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jbpmReimburse")
    @BatchSize(size=10)
public List<JbpmReimburseDetl> getJbpmReimburseDetls() {
        return this.jbpmReimburseDetls;
    }
    
    public void setJbpmReimburseDetls(List<JbpmReimburseDetl> jbpmReimburseDetls) {
        this.jbpmReimburseDetls = jbpmReimburseDetls;
    }




}


