// 
package com.hhz.ump.entity.hr;
// Generated 2011-10-28 15:32:47 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * HrTipEas generated by hbm2java
 */
@Entity
@Table(name="HR_TIP_EAS"
    
)
public class HrTipEas  implements java.io.Serializable {


     private String hrTipEasId;
     private String tipTypeCd;
     private Date relDate;
     private String relUserUiid;
     private String relUserName;
     private String relHrUiid;
     private String relHrName;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;

    public HrTipEas() {
    }

	
    public HrTipEas(String hrTipEasId, long recordVersion) {
        this.hrTipEasId = hrTipEasId;
        this.recordVersion = recordVersion;
    }
    public HrTipEas(String hrTipEasId, String tipTypeCd, Date relDate, String relUserUiid, String relUserName, String relHrUiid, String relHrName, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion) {
       this.hrTipEasId = hrTipEasId;
       this.tipTypeCd = tipTypeCd;
       this.relDate = relDate;
       this.relUserUiid = relUserUiid;
       this.relUserName = relUserName;
       this.relHrUiid = relHrUiid;
       this.relHrName = relHrName;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="HR_TIP_EAS_ID", unique=true, nullable=false, length=50)
    public String getHrTipEasId() {
        return this.hrTipEasId;
    }
    
    public void setHrTipEasId(String hrTipEasId) {
        this.hrTipEasId = hrTipEasId;
    }
    
    @Column(name="TIP_TYPE_CD", length=1)
    public String getTipTypeCd() {
        return this.tipTypeCd;
    }
    
    public void setTipTypeCd(String tipTypeCd) {
        this.tipTypeCd = tipTypeCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REL_DATE", length=7)
    public Date getRelDate() {
        return this.relDate;
    }
    
    public void setRelDate(Date relDate) {
        this.relDate = relDate;
    }
    
    @Column(name="REL_USER_UIID", length=20)
    public String getRelUserUiid() {
        return this.relUserUiid;
    }
    
    public void setRelUserUiid(String relUserUiid) {
        this.relUserUiid = relUserUiid;
    }
    
    @Column(name="REL_USER_NAME", length=50)
    public String getRelUserName() {
        return this.relUserName;
    }
    
    public void setRelUserName(String relUserName) {
        this.relUserName = relUserName;
    }
    
    @Column(name="REL_HR_UIID", length=20)
    public String getRelHrUiid() {
        return this.relHrUiid;
    }
    
    public void setRelHrUiid(String relHrUiid) {
        this.relHrUiid = relHrUiid;
    }
    
    @Column(name="REL_HR_NAME", length=50)
    public String getRelHrName() {
        return this.relHrName;
    }
    
    public void setRelHrName(String relHrName) {
        this.relHrName = relHrName;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }




}


