// 
package com.hhz.ump.entity.assm;
// Generated 2012-4-17 9:46:50 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * AssmDepreciation generated by hbm2java
 */
@Entity
@Table(name="ASSM_DEPRECIATION"
    ,schema="POWERDESK"
)
public class AssmDepreciation  implements java.io.Serializable {


     private String assmDepreciationId;
     private String assmModelId;
     private String assmName;
     private Long deprePeriod;
     private BigDecimal preRemain;
     private BigDecimal depreRate;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;

    public AssmDepreciation() {
    }

	
    public AssmDepreciation(String assmDepreciationId, long recordVersion) {
        this.assmDepreciationId = assmDepreciationId;
        this.recordVersion = recordVersion;
    }
    public AssmDepreciation(String assmDepreciationId, String assmModelId,String assmName, Long deprePeriod, BigDecimal preRemain, BigDecimal depreRate, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion) {
       this.assmDepreciationId = assmDepreciationId;
       this.assmModelId = assmModelId;
       this.assmName = assmName;
       this.deprePeriod = deprePeriod;
       this.preRemain = preRemain;
       this.depreRate = depreRate;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="ASSM_DEPRECIATION_ID", unique=true, nullable=false, length=50)
    public String getAssmDepreciationId() {
        return this.assmDepreciationId;
    }
    
    public void setAssmDepreciationId(String assmDepreciationId) {
        this.assmDepreciationId = assmDepreciationId;
    }
    
    @Column(name="ASSM_MODEL_ID", length=50)
     public String getAssmModelId() {
		return assmModelId;
	}

    public void setAssmModelId(String assmModelId) {
		this.assmModelId = assmModelId;
	}
	
	@Column(name="ASSM_NAME", length=50)
	public String getAssmName() {
		return assmName;
	}

	public void setAssmName(String assmName) {
		this.assmName = assmName;
	}
    
    @Column(name="DEPRE_PERIOD", precision=18, scale=0)
    public Long getDeprePeriod() {
		return deprePeriod;
	}

    public void setDeprePeriod(Long deprePeriod) {
		this.deprePeriod = deprePeriod;
	}
    
    @Column(name="PRE_REMAIN", precision=10, scale=3)
    public BigDecimal getPreRemain() {
        return this.preRemain;
    }

	public void setPreRemain(BigDecimal preRemain) {
        this.preRemain = preRemain;
    }
    
    @Column(name="DEPRE_RATE", precision=10, scale=3)
    public BigDecimal getDepreRate() {
        return this.depreRate;
    }
    
    public void setDepreRate(BigDecimal depreRate) {
        this.depreRate = depreRate;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }




}


