// 
package com.hhz.ump.entity.app;
// Generated 2010-8-4 13:27:58 by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * AppAttachFile generated by hbm2java
 */
@Entity
@Table(name="APP_ATTACH_FILE"
    ,schema="POWERDESK"
)
public class AppAttachFile  implements java.io.Serializable {


     private String appAttachFileId;
     private String bizEntityId;
     private String bizModuleCd;
     private String fileName;
     private String smallPicName;
     private String realFileName;
     private String filePath;
     private String fileTypeName;
     private BigDecimal fileSize;
     private String statusCd;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private String bizFieldName;
     private String ipAddr;
     private Long downloadTimes;

    public AppAttachFile() {
    }

	
    public AppAttachFile(String appAttachFileId, String bizEntityId, String fileName, String realFileName, String filePath, String fileTypeName, BigDecimal fileSize, long recordVersion) {
        this.appAttachFileId = appAttachFileId;
        this.bizEntityId = bizEntityId;
        this.fileName = fileName;
        this.realFileName = realFileName;
        this.filePath = filePath;
        this.fileTypeName = fileTypeName;
        this.fileSize = fileSize;
        this.recordVersion = recordVersion;
    }
    public AppAttachFile(String appAttachFileId, String bizEntityId, String bizModuleCd, String fileName, String realFileName, String filePath, String fileTypeName, BigDecimal fileSize, String statusCd, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion) {
       this.appAttachFileId = appAttachFileId;
       this.bizEntityId = bizEntityId;
       this.bizModuleCd = bizModuleCd;
       this.fileName = fileName;
       this.realFileName = realFileName;
       this.filePath = filePath;
       this.fileTypeName = fileTypeName;
       this.fileSize = fileSize;
       this.statusCd = statusCd;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="APP_ATTACH_FILE_ID", unique=true, nullable=false, length=50)
    public String getAppAttachFileId() {
        return this.appAttachFileId;
    }
    
    public void setAppAttachFileId(String appAttachFileId) {
        this.appAttachFileId = appAttachFileId;
    }

    
    @Column(name="BIZ_ENTITY_ID", nullable=false, length=50)
    public String getBizEntityId() {
        return this.bizEntityId;
    }
    
    public void setBizEntityId(String bizEntityId) {
        this.bizEntityId = bizEntityId;
    }

    
    @Column(name="BIZ_MODULE_CD", length=20)
    public String getBizModuleCd() {
        return this.bizModuleCd;
    }
    
    public void setBizModuleCd(String bizModuleCd) {
        this.bizModuleCd = bizModuleCd;
    }

    
    @Column(name="FILE_NAME", nullable=false, length=500)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="REAL_FILE_NAME", nullable=false, length=500)
    public String getRealFileName() {
        return this.realFileName;
    }
    
    public void setRealFileName(String realFileName) {
        this.realFileName = realFileName;
    }

    
    @Column(name="FILE_PATH", nullable=false, length=500)
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    
    @Column(name="FILE_TYPE_NAME", nullable=false, length=100)
    public String getFileTypeName() {
        return this.fileTypeName;
    }
    
    public void setFileTypeName(String fileTypeName) {
        this.fileTypeName = fileTypeName;
    }

    
    @Column(name="FILE_SIZE", nullable=false, scale=4)
    public BigDecimal getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(BigDecimal fileSize) {
        this.fileSize = fileSize;
    }

    
    @Column(name="STATUS_CD", length=20)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }

    @Column(name="SMALL_PIC_NAME", length=100)
	public String getSmallPicName() {
		return smallPicName;
	}


	public void setSmallPicName(String smallPicName) {
		this.smallPicName = smallPicName;
	}


    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }

    @Column(name="BIZ_FIELD_NAME", length=50)
	public String getBizFieldName() {
		return bizFieldName;
	}


	public void setBizFieldName(String bizFieldName) {
		this.bizFieldName = bizFieldName;
	}

	@Column(name="IP_ADDR", length=200)
	public String getIpAddr() {
		return ipAddr;
	}


	public void setIpAddr(String ipAddr) {
		this.ipAddr = ipAddr;
	}

	@Column(name="DOWNLOAD_TIMES", precision=10, scale=0)
	public Long getDownloadTimes() {
		return downloadTimes;
	}


	public void setDownloadTimes(Long downloadTimes) {
		this.downloadTimes = downloadTimes;
	}



}


