// 
package com.hhz.ump.entity.app;
// Generated 2010-8-4 13:27:58 by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * AppFunction generated by hbm2java
 */
@Entity
@Table(name="APP_FUNCTION"
    ,schema="POWERDESK"
)
public class AppFunction  implements java.io.Serializable {


     private String appFunctionId;
     private AppPage appPage;
     private String functionCd;
     private String functionName;
     private String functionTip;
     private String functionPath;
     private String functionTypeCd;
     private BigDecimal dispOrderNo;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private List<AppRoleFunctionRel> appRoleFunctionRels = new ArrayList<AppRoleFunctionRel>();
     private List<AppRule> appRules = new ArrayList<AppRule>();

    public AppFunction() {
    }

	
    public AppFunction(String appFunctionId, AppPage appPage, long recordVersion) {
        this.appFunctionId = appFunctionId;
        this.appPage = appPage;
        this.recordVersion = recordVersion;
    }
    public AppFunction(String appFunctionId, AppPage appPage, String functionCd, String functionName, String functionTip, String functionTypeCd, BigDecimal dispOrderNo, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion, List<AppRoleFunctionRel> appRoleFunctionRels, List<AppRule> appRules) {
       this.appFunctionId = appFunctionId;
       this.appPage = appPage;
       this.functionCd = functionCd;
       this.functionName = functionName;
       this.functionTip = functionTip;
       this.functionTypeCd = functionTypeCd;
       this.dispOrderNo = dispOrderNo;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.appRoleFunctionRels = appRoleFunctionRels;
       this.appRules = appRules;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="APP_FUNCTION_ID", unique=true, nullable=false, length=50)
    public String getAppFunctionId() {
        return this.appFunctionId;
    }
    
    public void setAppFunctionId(String appFunctionId) {
        this.appFunctionId = appFunctionId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APP_PAGE_ID", nullable=false)
    public AppPage getAppPage() {
        return this.appPage;
    }
    
    public void setAppPage(AppPage appPage) {
        this.appPage = appPage;
    }

    
    @Column(name="FUNCTION_CD", length=20)
    public String getFunctionCd() {
        return this.functionCd;
    }
    
    public void setFunctionCd(String functionCd) {
        this.functionCd = functionCd;
    }

    
    @Column(name="FUNCTION_NAME", length=50)
    public String getFunctionName() {
        return this.functionName;
    }
    
    public void setFunctionName(String functionName) {
        this.functionName = functionName;
    }

    
    @Column(name="FUNCTION_TIP", length=100)
    public String getFunctionTip() {
        return this.functionTip;
    }
    
    public void setFunctionTip(String functionTip) {
        this.functionTip = functionTip;
    }

    
    @Column(name="FUNCTION_TYPE_CD", length=20)
    public String getFunctionTypeCd() {
        return this.functionTypeCd;
    }
    
    public void setFunctionTypeCd(String functionTypeCd) {
        this.functionTypeCd = functionTypeCd;
    }

    
    @Column(name="DISP_ORDER_NO", precision=38, scale=0)
    public BigDecimal getDispOrderNo() {
        return this.dispOrderNo;
    }
    
    public void setDispOrderNo(BigDecimal dispOrderNo) {
        this.dispOrderNo = dispOrderNo;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="appFunction")
    @BatchSize(size=10)
public List<AppRoleFunctionRel> getAppRoleFunctionRels() {
        return this.appRoleFunctionRels;
    }
    
    public void setAppRoleFunctionRels(List<AppRoleFunctionRel> appRoleFunctionRels) {
        this.appRoleFunctionRels = appRoleFunctionRels;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="appFunction")
    @BatchSize(size=10)
public List<AppRule> getAppRules() {
        return this.appRules;
    }
    
    public void setAppRules(List<AppRule> appRules) {
        this.appRules = appRules;
    }

    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }

    @Column(name="FUNCTION_PATH", length=100)
	public String getFunctionPath() {
		return functionPath;
	}


	public void setFunctionPath(String functionPath) {
		this.functionPath = functionPath;
	}




}


