// 
package com.hhz.ump.entity.app;
// Generated 2010-8-4 13:27:58 by Hibernate Tools 3.2.4.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * AppPage generated by hbm2java
 */
@Entity
@Table(name="APP_PAGE"
    ,schema="POWERDESK"
)
public class AppPage  implements java.io.Serializable {


     private String appPageId;
     private String pageCd;
     private String pageName;
     private String pagePath;
     private String pageStatusCd;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private List<AppMenu> appMenus = new ArrayList<AppMenu>();
     private List<AppFunction> appFunctions = new ArrayList<AppFunction>();

    public AppPage() {
    }

	
    public AppPage(String appPageId, long recordVersion) {
        this.appPageId = appPageId;
        this.recordVersion = recordVersion;
    }
    public AppPage(String appPageId, String pageCd, String pageName, String pagePath, String pageStatusCd, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion, List<AppMenu> appMenus, List<AppFunction> appFunctions) {
       this.appPageId = appPageId;
       this.pageCd = pageCd;
       this.pageName = pageName;
       this.pagePath = pagePath;
       this.pageStatusCd = pageStatusCd;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.appMenus = appMenus;
       this.appFunctions = appFunctions;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="APP_PAGE_ID", unique=true, nullable=false, length=50)
    public String getAppPageId() {
        return this.appPageId;
    }
    
    public void setAppPageId(String appPageId) {
        this.appPageId = appPageId;
    }

    
    @Column(name="PAGE_CD", length=20)
    public String getPageCd() {
        return this.pageCd;
    }
    
    public void setPageCd(String pageCd) {
        this.pageCd = pageCd;
    }

    
    @Column(name="PAGE_NAME", length=50)
    public String getPageName() {
        return this.pageName;
    }
    
    public void setPageName(String pageName) {
        this.pageName = pageName;
    }

    
    @Column(name="PAGE_PATH", length=500)
    public String getPagePath() {
        return this.pagePath;
    }
    
    public void setPagePath(String pagePath) {
        this.pagePath = pagePath;
    }

    
    @Column(name="PAGE_STATUS_CD", length=20)
    public String getPageStatusCd() {
        return this.pageStatusCd;
    }
    
    public void setPageStatusCd(String pageStatusCd) {
        this.pageStatusCd = pageStatusCd;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="appPage")
    @BatchSize(size=10)
public List<AppMenu> getAppMenus() {
        return this.appMenus;
    }
    
    public void setAppMenus(List<AppMenu> appMenus) {
        this.appMenus = appMenus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="appPage")
    @BatchSize(size=10)
public List<AppFunction> getAppFunctions() {
        return this.appFunctions;
    }
    
    public void setAppFunctions(List<AppFunction> appFunctions) {
        this.appFunctions = appFunctions;
    }

    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }




}


