// 
package com.hhz.ump.entity.app;
// Generated 2010-8-4 13:27:58 by Hibernate Tools 3.2.4.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * AppRoleFunctionRel generated by hbm2java
 */
@Entity
@Table(name="APP_ROLE_FUNCTION_REL"
    ,schema="POWERDESK"
)
public class AppRoleFunctionRel  implements java.io.Serializable {


     private String appRoleFunctionRelId;
     private AppFunction appFunction;
     private String roleCd;
     private String menuCd;
     private String permisionStatusCd;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;

    public AppRoleFunctionRel() {
    }

	
    public AppRoleFunctionRel(String appRoleFunctionRelId, AppFunction appFunction, long recordVersion) {
        this.appRoleFunctionRelId = appRoleFunctionRelId;
        this.appFunction = appFunction;
        this.recordVersion = recordVersion;
    }
    public AppRoleFunctionRel(String appRoleFunctionRelId, AppFunction appFunction, String roleCd, String menuCd, String permisionStatusCd, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion) {
       this.appRoleFunctionRelId = appRoleFunctionRelId;
       this.appFunction = appFunction;
       this.roleCd = roleCd;
       this.menuCd = menuCd;
       this.permisionStatusCd = permisionStatusCd;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="APP_ROLE_FUNCTION_REL_ID", unique=true, nullable=false, length=50)
    public String getAppRoleFunctionRelId() {
        return this.appRoleFunctionRelId;
    }
    
    public void setAppRoleFunctionRelId(String appRoleFunctionRelId) {
        this.appRoleFunctionRelId = appRoleFunctionRelId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APP_FUNCTION_ID", nullable=false)
    public AppFunction getAppFunction() {
        return this.appFunction;
    }
    
    public void setAppFunction(AppFunction appFunction) {
        this.appFunction = appFunction;
    }

    
    @Column(name="ROLE_CD", length=20)
    public String getRoleCd() {
        return this.roleCd;
    }
    
    public void setRoleCd(String roleCd) {
        this.roleCd = roleCd;
    }

    
    @Column(name="MENU_CD", length=20)
    public String getMenuCd() {
        return this.menuCd;
    }
    
    public void setMenuCd(String menuCd) {
        this.menuCd = menuCd;
    }

    
    @Column(name="PERMISION_STATUS_CD", length=20)
    public String getPermisionStatusCd() {
        return this.permisionStatusCd;
    }
    
    public void setPermisionStatusCd(String permisionStatusCd) {
        this.permisionStatusCd = permisionStatusCd;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }


    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }



}


