// 
package com.hhz.ump.entity.app;
// Generated 2010-1-22 15:26:01 by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * AppSeq generated by hbm2java
 */
@Entity
@Table(name="APP_SEQ"
, schema = "POWERDESK"
)
public class AppSeq  implements java.io.Serializable {


     private String seqType;
     private String seqName;
     private Integer seqOrderNo;
     private String seqDesc;

    public AppSeq() {
    }

	
    public AppSeq(String seqType) {
        this.seqType = seqType;
    }
    public AppSeq(String seqType, String seqName, Integer seqOrderNo, String seqDesc) {
       this.seqType = seqType;
       this.seqName = seqName;
       this.seqOrderNo = seqOrderNo;
       this.seqDesc = seqDesc;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="SEQ_TYPE", unique=true, nullable=false, length=50)
    public String getSeqType() {
        return this.seqType;
    }
    
    public void setSeqType(String seqType) {
        this.seqType = seqType;
    }

    
    @Column(name="SEQ_NAME", length=50)
    public String getSeqName() {
        return this.seqName;
    }
    
    public void setSeqName(String seqName) {
        this.seqName = seqName;
    }

    
    @Column(name="SEQ_ORDER_NO")
    public Integer getSeqOrderNo() {
        return this.seqOrderNo;
    }
    
    public void setSeqOrderNo(Integer seqOrderNo) {
        this.seqOrderNo = seqOrderNo;
    }

    
    @Column(name="SEQ_DESC", length=200)
    public String getSeqDesc() {
        return this.seqDesc;
    }
    
    public void setSeqDesc(String seqDesc) {
        this.seqDesc = seqDesc;
    }

    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }




}


