// 
package com.hhz.ump.entity.app;
// Generated 2010-8-4 13:27:58 by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * AppModule generated by hbm2java
 */
@Entity
@Table(name="APP_MODULE"
    
)
public class AppModule  implements java.io.Serializable {


     private String appModuleId;
     private String moduleCd;
     private String moduleName;
     private String moduleTip;
     private BigDecimal dispOrderNo;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     
	private String pageCd;
     private String parentModuleCd;
     
     private List<AppModuleMenuRel> appModuleMenuRels = new ArrayList<AppModuleMenuRel>();

    public AppModule() {
    }

	
    public AppModule(String appModuleId, long recordVersion) {
        this.appModuleId = appModuleId;
        this.recordVersion = recordVersion;
    }
    public AppModule(String appModuleId, String moduleCd, String moduleName, String moduleTip, BigDecimal dispOrderNo, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion,String pageCd,String parentModuleCd, List<AppModuleMenuRel> appModuleMenuRels) {
       this.appModuleId = appModuleId;
       this.moduleCd = moduleCd;
       this.moduleName = moduleName;
       this.moduleTip = moduleTip;
       this.dispOrderNo = dispOrderNo;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.pageCd = pageCd;
       this.parentModuleCd = parentModuleCd;
       this.appModuleMenuRels = appModuleMenuRels;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="APP_MODULE_ID", unique=true, nullable=false, length=50)
    public String getAppModuleId() {
        return this.appModuleId;
    }
    
    public void setAppModuleId(String appModuleId) {
        this.appModuleId = appModuleId;
    }

    
    @Column(name="MODULE_CD", length=20)
    public String getModuleCd() {
        return this.moduleCd;
    }
    
    public void setModuleCd(String moduleCd) {
        this.moduleCd = moduleCd;
    }

    
    @Column(name="MODULE_NAME", length=50)
    public String getModuleName() {
        return this.moduleName;
    }
    
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    
    @Column(name="MODULE_TIP", length=100)
    public String getModuleTip() {
        return this.moduleTip;
    }
    
    public void setModuleTip(String moduleTip) {
        this.moduleTip = moduleTip;
    }

    
    @Column(name="DISP_ORDER_NO", precision=38, scale=0)
    public BigDecimal getDispOrderNo() {
        return this.dispOrderNo;
    }
    
    public void setDispOrderNo(BigDecimal dispOrderNo) {
        this.dispOrderNo = dispOrderNo;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }


    @Column(name="PAGE_CD", length=20)
    public String getPageCd() {
		return pageCd;
	}


	public void setPageCd(String pageCd) {
		this.pageCd = pageCd;
	}


    @Column(name="PARENT_MODULE_CD", length=20)
	public String getParentModuleCd() {
		return parentModuleCd;
	}


	public void setParentModuleCd(String parentModuleCd) {
		this.parentModuleCd = parentModuleCd;
	}

@OneToMany(fetch=FetchType.LAZY, mappedBy="appModule")
    @BatchSize(size=10)
public List<AppModuleMenuRel> getAppModuleMenuRels() {
        return this.appModuleMenuRels;
    }
    
    public void setAppModuleMenuRels(List<AppModuleMenuRel> appModuleMenuRels) {
        this.appModuleMenuRels = appModuleMenuRels;
    }


    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }



}


