// 
package com.hhz.ump.entity.cost;
// Generated 2012-6-14 19:08:43 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * CostMateCol generated by hbm2java
 */
@Entity
@Table(name="COST_MATE_COL"
    
)
public class CostMateCol  implements java.io.Serializable {


     private String costMateColId;
     private CostMate costMate;
     private String colField;
     private String colName;
     private String colDataTypeCd;
     private BigDecimal levelCd;
     private Long sequenceNo;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String extFlg;
     private String extPrice;

    public CostMateCol() {
    }

	
    public CostMateCol(String costMateColId, CostMate costMate, long recordVersion) {
        this.costMateColId = costMateColId;
        this.costMate = costMate;
        this.recordVersion = recordVersion;
    }
    public CostMateCol(String costMateColId, CostMate costMate, String colField, String colName, String colDataTypeCd, BigDecimal levelCd, Long sequenceNo, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, String extFlg, String extPrice) {
       this.costMateColId = costMateColId;
       this.costMate = costMate;
       this.colField = colField;
       this.colName = colName;
       this.colDataTypeCd = colDataTypeCd;
       this.levelCd = levelCd;
       this.sequenceNo = sequenceNo;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.extFlg = extFlg;
       this.extPrice = extPrice;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="COST_MATE_COL_ID", unique=true, nullable=false, length=50)
    public String getCostMateColId() {
        return this.costMateColId;
    }
    
    public void setCostMateColId(String costMateColId) {
        this.costMateColId = costMateColId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COST_MATE_ID", nullable=false)
    public CostMate getCostMate() {
        return this.costMate;
    }
    
    public void setCostMate(CostMate costMate) {
        this.costMate = costMate;
    }
    
    @Column(name="COL_FIELD", length=50)
    public String getColField() {
        return this.colField;
    }
    
    public void setColField(String colField) {
        this.colField = colField;
    }
    
    @Column(name="COL_NAME", length=50)
    public String getColName() {
        return this.colName;
    }
    
    public void setColName(String colName) {
        this.colName = colName;
    }
    
    @Column(name="COL_DATA_TYPE_CD", length=100)
    public String getColDataTypeCd() {
        return this.colDataTypeCd;
    }
    
    public void setColDataTypeCd(String colDataTypeCd) {
        this.colDataTypeCd = colDataTypeCd;
    }
    
    @Column(name="LEVEL_CD", precision=18)
    public BigDecimal getLevelCd() {
        return this.levelCd;
    }
    
    public void setLevelCd(BigDecimal levelCd) {
        this.levelCd = levelCd;
    }
    
    @Column(name="SEQUENCE_NO", precision=10, scale=0)
    public Long getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Long sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="EXT_FLG", length=1)
    public String getExtFlg() {
        return this.extFlg;
    }
    
    public void setExtFlg(String extFlg) {
        this.extFlg = extFlg;
    }
    
    @Column(name="EXT_PRICE", length=1)
    public String getExtPrice() {
        return this.extPrice;
    }
    
    public void setExtPrice(String extPrice) {
        this.extPrice = extPrice;
    }




}


