// 
package com.hhz.ump.entity.cost;
// Generated 2012-2-20 20:44:07 by Hibernate Tools 3.2.2.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * CostBudgetMonth generated by hbm2java
 */
@Entity
@Table(name="COST_BUDGET_MONTH"
    
)
public class CostBudgetMonth  implements java.io.Serializable {


     private String costBudgetMonthId;
     private CostProjectSection costProjectSection;
     private Long budegetYear;
     private Long budegetMonth;
     private String statusCd;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private List<CostBudgetMonthDetail> costBudgetMonthDetails = new ArrayList<CostBudgetMonthDetail>();

    public CostBudgetMonth() {
    }

	
    public CostBudgetMonth(String costBudgetMonthId, CostProjectSection costProjectSection, long recordVersion) {
        this.costBudgetMonthId = costBudgetMonthId;
        this.costProjectSection = costProjectSection;
        this.recordVersion = recordVersion;
    }
    public CostBudgetMonth(String costBudgetMonthId, CostProjectSection costProjectSection, Long budegetYear, Long budegetMonth, String statusCd, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, List<CostBudgetMonthDetail> costBudgetMonthDetails) {
       this.costBudgetMonthId = costBudgetMonthId;
       this.costProjectSection = costProjectSection;
       this.budegetYear = budegetYear;
       this.budegetMonth = budegetMonth;
       this.statusCd = statusCd;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.costBudgetMonthDetails = costBudgetMonthDetails;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="COST_BUDGET_MONTH_ID", unique=true, nullable=false, length=50)
    public String getCostBudgetMonthId() {
        return this.costBudgetMonthId;
    }
    
    public void setCostBudgetMonthId(String costBudgetMonthId) {
        this.costBudgetMonthId = costBudgetMonthId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COST_PROJECT_SECTION_ID", nullable=false)
    public CostProjectSection getCostProjectSection() {
        return this.costProjectSection;
    }
    
    public void setCostProjectSection(CostProjectSection costProjectSection) {
        this.costProjectSection = costProjectSection;
    }
    
    @Column(name="BUDEGET_YEAR", precision=10, scale=0)
    public Long getBudegetYear() {
        return this.budegetYear;
    }
    
    public void setBudegetYear(Long budegetYear) {
        this.budegetYear = budegetYear;
    }
    
    @Column(name="BUDEGET_MONTH", precision=10, scale=0)
    public Long getBudegetMonth() {
        return this.budegetMonth;
    }
    
    public void setBudegetMonth(Long budegetMonth) {
        this.budegetMonth = budegetMonth;
    }
    
    @Column(name="STATUS_CD", length=20)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="costBudgetMonth")
    @BatchSize(size=10)
public List<CostBudgetMonthDetail> getCostBudgetMonthDetails() {
        return this.costBudgetMonthDetails;
    }
    
    public void setCostBudgetMonthDetails(List<CostBudgetMonthDetail> costBudgetMonthDetails) {
        this.costBudgetMonthDetails = costBudgetMonthDetails;
    }




}


