// 
package com.hhz.ump.entity.cost;
// Generated 2012-6-14 19:08:43 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * CostMatePrice generated by hbm2java
 */
@Entity
@Table(name="COST_MATE_PRICE"
    
)
public class CostMatePrice  implements java.io.Serializable {


     private String costMatePriceId;
     private CostMate costMate;
     private String groupName;
     private String groupName2;
     private String groupName3;
     private String groupName4;
     private String materialName;
     private String specName;
     private String modelName;
     private BigDecimal price;
     private String f01;
     private String f02;
     private String f03;
     private String f04;
     private String f05;
     private String f06;
     private String f07;
     private String f08;
     private String f09;
     private String f10;
     private String f11;
     private String f12;
     private String f13;
     private String f14;
     private String f15;
     private String f16;
     private String f17;
     private String f18;
     private String f19;
     private String f20;
     private String f21;
     private String f22;
     private String f23;
     private String f24;
     private String f25;
     private String f26;
     private String f27;
     private String f28;
     private String f29;
     private String f30;
     private Long enableFlg;
     private String memoDesc;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private Long sequenceNo;

    public CostMatePrice() {
    }

	
    public CostMatePrice(String costMatePriceId, CostMate costMate, long recordVersion) {
        this.costMatePriceId = costMatePriceId;
        this.costMate = costMate;
        this.recordVersion = recordVersion;
    }
    public CostMatePrice(String costMatePriceId, CostMate costMate,String groupName,String groupName2,String groupName3, String groupName4, String specName, String modelName, BigDecimal price, String f01, String f02, String f03, String f04, String f05, String f06, String f07, String f08, String f09, String f10, String f11, String f12, String f13, String f14, String f15, Long enableFlg, String memoDesc, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, Long sequenceNo, String materialName, String f16, String f17, String f18, String f19, String f20, String f21, String f22, String f23, String f24, String f25, String f26, String f27, String f28, String f29, String f30) {
       this.costMatePriceId = costMatePriceId;
       this.costMate = costMate;
       this.groupName = groupName;
       this.groupName2 = groupName2;
       this.groupName3 = groupName3;
       this.groupName4 = groupName4;
       this.materialName = materialName;
       this.specName = specName;
       this.modelName = modelName;
       this.price = price;
       this.f01 = f01;
       this.f02 = f02;
       this.f03 = f03;
       this.f04 = f04;
       this.f05 = f05;
       this.f06 = f06;
       this.f07 = f07;
       this.f08 = f08;
       this.f09 = f09;
       this.f10 = f10;
       this.f11 = f11;
       this.f12 = f12;
       this.f13 = f13;
       this.f14 = f14;
       this.f15 = f15;
       this.f16 = f16;
       this.f17 = f17;
       this.f18 = f18;
       this.f19 = f19;
       this.f20 = f20;
       this.f21 = f21;
       this.f22 = f22;
       this.f23 = f23;
       this.f24 = f24;
       this.f25 = f25;
       this.f26 = f26;
       this.f27 = f27;
       this.f28 = f28;
       this.f29 = f29;
       this.f30 = f30;
       this.enableFlg = enableFlg;
       this.memoDesc = memoDesc;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.sequenceNo = sequenceNo;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="COST_MATE_PRICE_ID", unique=true, nullable=false, length=50)
    public String getCostMatePriceId() {
        return this.costMatePriceId;
    }
    
    public void setCostMatePriceId(String costMatePriceId) {
        this.costMatePriceId = costMatePriceId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COST_MATE_ID", nullable=false)
    public CostMate getCostMate() {
        return this.costMate;
    }
    
    public void setCostMate(CostMate costMate) {
        this.costMate = costMate;
    }
    
    @Column(name="SPEC_NAME", length=100)
    public String getSpecName() {
        return this.specName;
    }
    
    public void setSpecName(String specName) {
        this.specName = specName;
    }
    
    @Column(name="MODEL_NAME", length=100)
    public String getModelName() {
        return this.modelName;
    }
    
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }
    
    @Column(name="PRICE", precision=18, scale=2)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    
    @Column(name="F01", length=200)
    public String getF01() {
        return this.f01;
    }
    
    public void setF01(String f01) {
        this.f01 = f01;
    }
    
    @Column(name="F02", length=200)
    public String getF02() {
        return this.f02;
    }
    
    public void setF02(String f02) {
        this.f02 = f02;
    }
    
    @Column(name="F03", length=200)
    public String getF03() {
        return this.f03;
    }
    
    public void setF03(String f03) {
        this.f03 = f03;
    }
    
    @Column(name="F04", length=200)
    public String getF04() {
        return this.f04;
    }
    
    public void setF04(String f04) {
        this.f04 = f04;
    }
    
    @Column(name="F05", length=200)
    public String getF05() {
        return this.f05;
    }
    
    public void setF05(String f05) {
        this.f05 = f05;
    }
    
    @Column(name="F06", length=200)
    public String getF06() {
        return this.f06;
    }
    
    public void setF06(String f06) {
        this.f06 = f06;
    }
    
    @Column(name="F07", length=200)
    public String getF07() {
        return this.f07;
    }
    
    public void setF07(String f07) {
        this.f07 = f07;
    }
    
    @Column(name="F08", length=200)
    public String getF08() {
        return this.f08;
    }
    
    public void setF08(String f08) {
        this.f08 = f08;
    }
    
    @Column(name="F09", length=200)
    public String getF09() {
        return this.f09;
    }
    
    public void setF09(String f09) {
        this.f09 = f09;
    }
    
    @Column(name="F10", length=200)
    public String getF10() {
        return this.f10;
    }
    
    public void setF10(String f10) {
        this.f10 = f10;
    }
    
    @Column(name="F11", length=200)
    public String getF11() {
        return this.f11;
    }
    
    public void setF11(String f11) {
        this.f11 = f11;
    }
    
    @Column(name="F12", length=12)
    public String getF12() {
        return this.f12;
    }
    
    public void setF12(String f12) {
        this.f12 = f12;
    }
    
    @Column(name="F13", length=200)
    public String getF13() {
        return this.f13;
    }
    
    public void setF13(String f13) {
        this.f13 = f13;
    }
    
    @Column(name="F14", length=200)
    public String getF14() {
        return this.f14;
    }
    
    public void setF14(String f14) {
        this.f14 = f14;
    }
    
    @Column(name="F15", length=200)
    public String getF15() {
        return this.f15;
    }
    
    public void setF15(String f15) {
        this.f15 = f15;
    }
    
    @Column(name="ENABLE_FLG", precision=10, scale=0)
    public Long getEnableFlg() {
        return this.enableFlg;
    }
    
    public void setEnableFlg(Long enableFlg) {
        this.enableFlg = enableFlg;
    }
    
    @Column(name="MEMO_DESC", length=400)
    public String getMemoDesc() {
        return this.memoDesc;
    }
    
    public void setMemoDesc(String memoDesc) {
        this.memoDesc = memoDesc;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="SEQUENCE_NO", precision=10, scale=0)
    public Long getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Long sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

    @Column(name="MATERIAL_NAME", length=100)
    public String getMaterialName() {
        return this.materialName;
    }
    
    public void setMaterialName(String materialName) {
        this.materialName = materialName;
    }
    
    @Column(name="GROUP_NAME", length=100)
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }


    
    @Column(name="GROUP_NAME2", length=100)
    public String getGroupName2() {
        return this.groupName2;
    }
    
    public void setGroupName2(String groupName2) {
        this.groupName2 = groupName2;
    }
    
    @Column(name="GROUP_NAME3", length=100)
    public String getGroupName3() {
        return this.groupName3;
    }
    
    public void setGroupName3(String groupName3) {
        this.groupName3 = groupName3;
    }

    @Column(name="GROUP_NAME4", length=100)
    public String getGroupName4() {
        return this.groupName4;
    }
    
    public void setGroupName4(String groupName4) {
        this.groupName4 = groupName4;
    }

    @Column(name="F16", length=200)
    public String getF16() {
        return this.f16;
    }
    
    public void setF16(String f16) {
        this.f16 = f16;
    }
    
    @Column(name="F17", length=200)
    public String getF17() {
        return this.f17;
    }
    
    public void setF17(String f17) {
        this.f17 = f17;
    }
    
    @Column(name="F18", length=200)
    public String getF18() {
        return this.f18;
    }
    
    public void setF18(String f18) {
        this.f18 = f18;
    }
    
    @Column(name="F19", length=200)
    public String getF19() {
        return this.f19;
    }
    
    public void setF19(String f19) {
        this.f19 = f19;
    }
    
    @Column(name="F20", length=200)
    public String getF20() {
        return this.f20;
    }
    
    public void setF20(String f20) {
        this.f20 = f20;
    }
    
    @Column(name="F21", length=200)
    public String getF21() {
        return this.f21;
    }
    
    public void setF21(String f21) {
        this.f21 = f21;
    }
    
    @Column(name="F22", length=200)
    public String getF22() {
        return this.f22;
    }
    
    public void setF22(String f22) {
        this.f22 = f22;
    }
    
    @Column(name="F23", length=200)
    public String getF23() {
        return this.f23;
    }
    
    public void setF23(String f23) {
        this.f23 = f23;
    }
    
    @Column(name="F24", length=200)
    public String getF24() {
        return this.f24;
    }
    
    public void setF24(String f24) {
        this.f24 = f24;
    }
    
    @Column(name="F25", length=200)
    public String getF25() {
        return this.f25;
    }
    
    public void setF25(String f25) {
        this.f25 = f25;
    }
    
    @Column(name="F26", length=200)
    public String getF26() {
        return this.f26;
    }
    
    public void setF26(String f26) {
        this.f26 = f26;
    }
    
    @Column(name="F27", length=200)
    public String getF27() {
        return this.f27;
    }
    
    public void setF27(String f27) {
        this.f27 = f27;
    }
    
    @Column(name="F28", length=200)
    public String getF28() {
        return this.f28;
    }
    
    public void setF28(String f28) {
        this.f28 = f28;
    }
    
    @Column(name="F29", length=200)
    public String getF29() {
        return this.f29;
    }
    
    public void setF29(String f29) {
        this.f29 = f29;
    }
    
    @Column(name="F30", length=200)
    public String getF30() {
        return this.f30;
    }
    
    public void setF30(String f30) {
        this.f30 = f30;
    }




}


