// 
package com.hhz.ump.entity.cost;
// Generated 2012-3-29 14:45:31 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * CostContPlanTplStat generated by hbm2java
 */
@Entity
@Table(name="COST_CONT_PLAN_TPL_STAT"
    
)
public class CostContPlanTplStat  implements java.io.Serializable {


     private String costContPlanTplStatId;
     private CostContPlanTpl costContPlanTpl;
     private String dispOrderDesc;
     private String subjectCd;
     private String rowTypeCd;
     private BigDecimal contSubTargAmt;
     private String statName;
     private String memoDesc;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private long subjectSequNo;
     private long subSequNo;

    public CostContPlanTplStat() {
    }

	
    public CostContPlanTplStat(String costContPlanTplStatId, CostContPlanTpl costContPlanTpl, long recordVersion) {
        this.costContPlanTplStatId = costContPlanTplStatId;
        this.costContPlanTpl = costContPlanTpl;
        this.recordVersion = recordVersion;
    }
    public CostContPlanTplStat(String costContPlanTplStatId, CostContPlanTpl costContPlanTpl, String dispOrderDesc, String subjectCd, String rowTypeCd, BigDecimal contSubTargAmt, String statName, String memoDesc, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion,long subjectSequNo,long subSequNo) {
       this.costContPlanTplStatId = costContPlanTplStatId;
       this.costContPlanTpl = costContPlanTpl;
       this.dispOrderDesc = dispOrderDesc;
       this.subjectCd = subjectCd;
       this.rowTypeCd = rowTypeCd;
       this.contSubTargAmt = contSubTargAmt;
       this.statName = statName;
       this.memoDesc = memoDesc;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.subjectSequNo=subjectSequNo;
       this.subSequNo=subSequNo;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="COST_CONT_PLAN_TPL_STAT_ID", unique=true, nullable=false, length=50)
    public String getCostContPlanTplStatId() {
        return this.costContPlanTplStatId;
    }
    
    public void setCostContPlanTplStatId(String costContPlanTplStatId) {
        this.costContPlanTplStatId = costContPlanTplStatId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COST_CONT_PLAN_TPL_ID", nullable=false)
    public CostContPlanTpl getCostContPlanTpl() {
        return this.costContPlanTpl;
    }
    
    public void setCostContPlanTpl(CostContPlanTpl costContPlanTpl) {
        this.costContPlanTpl = costContPlanTpl;
    }
    
    @Column(name="DISP_ORDER_DESC", length=40)
    public String getDispOrderDesc() {
        return this.dispOrderDesc;
    }
    
    public void setDispOrderDesc(String dispOrderDesc) {
        this.dispOrderDesc = dispOrderDesc;
    }
    
    @Column(name="SUBJECT_CD", length=20)
    public String getSubjectCd() {
        return this.subjectCd;
    }
    
    public void setSubjectCd(String subjectCd) {
        this.subjectCd = subjectCd;
    }
    
    @Column(name="ROW_TYPE_CD", length=20)
    public String getRowTypeCd() {
        return this.rowTypeCd;
    }
    
    public void setRowTypeCd(String rowTypeCd) {
        this.rowTypeCd = rowTypeCd;
    }
    
    @Column(name="CONT_SUB_TARG_AMT", precision=18)
    public BigDecimal getContSubTargAmt() {
        return this.contSubTargAmt;
    }
    
    public void setContSubTargAmt(BigDecimal contSubTargAmt) {
        this.contSubTargAmt = contSubTargAmt;
    }
    
    @Column(name="STAT_NAME", length=100)
    public String getStatName() {
        return this.statName;
    }
    
    public void setStatName(String statName) {
        this.statName = statName;
    }
    
    @Column(name="MEMO_DESC", length=1000)
    public String getMemoDesc() {
        return this.memoDesc;
    }
    
    public void setMemoDesc(String memoDesc) {
        this.memoDesc = memoDesc;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }

    @Column(name="SUBJECT_SEQU_NO", nullable=false, precision=10, scale=0)
	public long getSubjectSequNo() {
		return subjectSequNo;
	}


	public void setSubjectSequNo(long subjectSequNo) {
		this.subjectSequNo = subjectSequNo;
	}

	@Column(name="SUB_SEQU_NO", nullable=false, precision=10, scale=0)
	public long getSubSequNo() {
		return subSequNo;
	}


	public void setSubSequNo(long subSequNo) {
		this.subSequNo = subSequNo;
	}
	
}


