// 
package com.hhz.ump.entity.fin;
// Generated 2010-8-4 11:02:15 by Hibernate Tools 3.2.4.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * FinItem generated by hbm2java
 */
@Entity
@Table(name="FIN_ITEM"
    ,schema="POWERDESK"
)
public class FinItem  implements java.io.Serializable {


     private String finItemId;
     private String finItemTypeCd;
     private String finItemCd;
     private String finItemName;
     private String parentItemCd;
     private Long dispOrderNum;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private String remark;

    public FinItem() {
    }

	
    public FinItem(String finItemId, long recordVersion) {
        this.finItemId = finItemId;
        this.recordVersion = recordVersion;
    }
    public FinItem(String finItemId, String finItemTypeCd, String finItemCd, String finItemName, String parentItemCd, Long dispOrderNum, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion, String remark) {
       this.finItemId = finItemId;
       this.finItemTypeCd = finItemTypeCd;
       this.finItemCd = finItemCd;
       this.finItemName = finItemName;
       this.parentItemCd = parentItemCd;
       this.dispOrderNum = dispOrderNum;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.remark = remark;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="FIN_ITEM_ID", unique=true, nullable=false, length=50)
    public String getFinItemId() {
        return this.finItemId;
    }
    
    public void setFinItemId(String finItemId) {
        this.finItemId = finItemId;
    }

    
    @Column(name="FIN_ITEM_TYPE_CD", length=20)
    public String getFinItemTypeCd() {
        return this.finItemTypeCd;
    }
    
    public void setFinItemTypeCd(String finItemTypeCd) {
        this.finItemTypeCd = finItemTypeCd;
    }

    
    @Column(name="FIN_ITEM_CD", length=20)
    public String getFinItemCd() {
        return this.finItemCd;
    }
    
    public void setFinItemCd(String finItemCd) {
        this.finItemCd = finItemCd;
    }

    
    @Column(name="FIN_ITEM_NAME", length=50)
    public String getFinItemName() {
        return this.finItemName;
    }
    
    public void setFinItemName(String finItemName) {
        this.finItemName = finItemName;
    }

    
    @Column(name="PARENT_ITEM_CD", length=50)
    public String getParentItemCd() {
        return this.parentItemCd;
    }
    
    public void setParentItemCd(String parentItemCd) {
        this.parentItemCd = parentItemCd;
    }

    
    @Column(name="DISP_ORDER_NUM", precision=10, scale=0)
    public Long getDispOrderNum() {
        return this.dispOrderNum;
    }
    
    public void setDispOrderNum(Long dispOrderNum) {
        this.dispOrderNum = dispOrderNum;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }


    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }



}


