// 
package com.hhz.ump.entity.fin;
// Generated 2010-8-4 11:02:15 by Hibernate Tools 3.2.4.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * FinProject generated by hbm2java
 */
@Entity
@Table(name="FIN_PROJECT"
    ,schema="POWERDESK"
)
public class FinProject  implements java.io.Serializable {


     private String finProjectId;
     private String projectCd;
     private String projectName;
     private String userCds;
     private String deptCd;
     private String statusCd;
     private Date statusDate;
     private Long sequenceNo;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private String remark;
     private String publicFlg;
     private String deleteFlg;
     private List<FinProjectAcctRel> finProjectAcctRels = new ArrayList<FinProjectAcctRel>();

    public FinProject() {
    }

	
    public FinProject(String finProjectId, long recordVersion) {
        this.finProjectId = finProjectId;
        this.recordVersion = recordVersion;
    }
    public FinProject(String finProjectId, String projectCd, String projectName, String userCds, String deptCd, String statusCd, Date statusDate, Long sequenceNo, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion, String remark,String publicFlg,List<FinProjectAcctRel> finProjectAcctRels,String deleteFlg) {
       this.finProjectId = finProjectId;
       this.projectCd = projectCd;
       this.projectName = projectName;
       this.userCds = userCds;
       this.deptCd = deptCd;
       this.statusCd = statusCd;
       this.statusDate = statusDate;
       this.sequenceNo = sequenceNo;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.remark = remark;
       this.publicFlg =publicFlg;
       this.finProjectAcctRels = finProjectAcctRels;
       this.deleteFlg = deleteFlg;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="FIN_PROJECT_ID", unique=true, nullable=false, length=50)
    public String getFinProjectId() {
        return this.finProjectId;
    }
    
    public void setFinProjectId(String finProjectId) {
        this.finProjectId = finProjectId;
    }

    
    @Column(name="PROJECT_CD", length=20)
    public String getProjectCd() {
        return this.projectCd;
    }
    
    public void setProjectCd(String projectCd) {
        this.projectCd = projectCd;
    }

    
    @Column(name="PROJECT_NAME", length=100)
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    
    @Column(name="USER_CDS", length=1000)
    public String getUserCds() {
        return this.userCds;
    }
    
    public void setUserCds(String userCds) {
        this.userCds = userCds;
    }

    
    @Column(name="DEPT_CD", length=20)
    public String getDeptCd() {
        return this.deptCd;
    }
    
    public void setDeptCd(String deptCd) {
        this.deptCd = deptCd;
    }

    
    @Column(name="STATUS_CD", length=20)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="STATUS_DATE", length=7)
    public Date getStatusDate() {
        return this.statusDate;
    }
    
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    
    @Column(name="SEQUENCE_NO", precision=10, scale=0)
    public Long getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Long sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="finProject")
    @BatchSize(size=10)
public List<FinProjectAcctRel> getFinProjectAcctRels() {
        return this.finProjectAcctRels;
    }
    
    public void setFinProjectAcctRels(List<FinProjectAcctRel> finProjectAcctRels) {
        this.finProjectAcctRels = finProjectAcctRels;
    }


    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }


    @Column(name="PUBLIC_FLG", length=20)
	public String getPublicFlg() {
		return publicFlg;
	}


	public void setPublicFlg(String publicFlg) {
		this.publicFlg = publicFlg;
	}

	@Column(name="DELETE_FLG", length=1)
	public String getDeleteFlg() {
		return deleteFlg;
	}


	public void setDeleteFlg(String deleteFlg) {
		this.deleteFlg = deleteFlg;
	}


}


