// 
package com.hhz.ump.entity.plan;
// Generated 2011-8-5 9:59:39 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * CostCheckSchedule generated by hbm2java
 */
@Entity
@Table(name="COST_CHECK_SCHEDULE"
    ,schema="POWERDESK"
)
public class CostCheckSchedule  implements java.io.Serializable {


     private String costCheckScheduleId;
     private CostCheck costCheck;
     private Integer serialNo;
     private String scheduleTypeCd;
     private String scheduleTypeName;
     private Date targetDate;
     private Date completeDate;
     private String completeStatusCd;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String createdDeptCd;
     private String updatedDeptCd;

    public CostCheckSchedule() {
    }

	
    public CostCheckSchedule(String costCheckScheduleId, CostCheck costCheck, long recordVersion) {
        this.costCheckScheduleId = costCheckScheduleId;
        this.costCheck = costCheck;
        this.recordVersion = recordVersion;
    }
    public CostCheckSchedule(String costCheckScheduleId, CostCheck costCheck, Integer serialNo, String scheduleTypeCd, String scheduleTypeName, Date targetDate, Date completeDate, String completeStatusCd, String remark, String creator, String createdCenterCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedPositionCd, Date updatedDate, long recordVersion, String createdDeptCd, String updatedDeptCd) {
       this.costCheckScheduleId = costCheckScheduleId;
       this.costCheck = costCheck;
       this.serialNo = serialNo;
       this.scheduleTypeCd = scheduleTypeCd;
       this.scheduleTypeName = scheduleTypeName;
       this.targetDate = targetDate;
       this.completeDate = completeDate;
       this.completeStatusCd = completeStatusCd;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.createdDeptCd = createdDeptCd;
       this.updatedDeptCd = updatedDeptCd;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="COST_CHECK_SCHEDULE_ID", unique=true, nullable=false, length=50)
    public String getCostCheckScheduleId() {
        return this.costCheckScheduleId;
    }
    
    public void setCostCheckScheduleId(String costCheckScheduleId) {
        this.costCheckScheduleId = costCheckScheduleId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COST_CHECK_ID", nullable=false)
    public CostCheck getCostCheck() {
        return this.costCheck;
    }
    
    public void setCostCheck(CostCheck costCheck) {
        this.costCheck = costCheck;
    }
    
    @Column(name="SERIAL_NO", precision=5, scale=0)
    public Integer getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(Integer serialNo) {
        this.serialNo = serialNo;
    }
    
    @Column(name="SCHEDULE_TYPE_CD", length=20)
    public String getScheduleTypeCd() {
        return this.scheduleTypeCd;
    }
    
    public void setScheduleTypeCd(String scheduleTypeCd) {
        this.scheduleTypeCd = scheduleTypeCd;
    }
    
    @Column(name="SCHEDULE_TYPE_NAME", length=50)
    public String getScheduleTypeName() {
        return this.scheduleTypeName;
    }
    
    public void setScheduleTypeName(String scheduleTypeName) {
        this.scheduleTypeName = scheduleTypeName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TARGET_DATE", length=7)
    public Date getTargetDate() {
        return this.targetDate;
    }
    
    public void setTargetDate(Date targetDate) {
        this.targetDate = targetDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="COMPLETE_DATE", length=7)
    public Date getCompleteDate() {
        return this.completeDate;
    }
    
    public void setCompleteDate(Date completeDate) {
        this.completeDate = completeDate;
    }
    
    @Column(name="COMPLETE_STATUS_CD", length=1)
    public String getCompleteStatusCd() {
        return this.completeStatusCd;
    }
    
    public void setCompleteStatusCd(String completeStatusCd) {
        this.completeStatusCd = completeStatusCd;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }




}


