// 
package com.hhz.ump.entity.plan;

// Generated 2011-9-24 13:27:44 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * ExecPlanDetailPlus generated by hbm2java
 */
@Entity
@Table(name = "EXEC_PLAN_PROCESSING", schema = "POWERDESK")
public class ExecPlanProcessing implements java.io.Serializable {

	private String execPlanProcessingId;
	private String projectCd;
	private String projectName;
	private String resOrgName;
	private String noConfirmStatus;
	private String goingStatus;
	private String suspendStatus;
	private String completeStatus;
	private String noActiveStatus;
	private String noReplyStatus;
	private Date createdDate;
	private String remark;

	public ExecPlanProcessing() {
	}

	public ExecPlanProcessing(String execPlanProcessingId, String projectCd,
			String projectName, String resOrgName, String noConfirmStatus,
			String goingStatus, String suspendStatus, String completeStatus,
			String noActiveStatus, String noReplyStatus,Date createdDate, String remark) {
		super();
		this.execPlanProcessingId = execPlanProcessingId;
		this.projectCd = projectCd;
		this.projectName = projectName;
		this.resOrgName = resOrgName;
		this.noConfirmStatus = noConfirmStatus;
		this.goingStatus = goingStatus;
		this.suspendStatus = suspendStatus;
		this.completeStatus = completeStatus;
		this.noActiveStatus = noActiveStatus;
		this.noReplyStatus = noReplyStatus;
		this.createdDate = createdDate;
		this.remark = remark;
	}

	@Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="EXEC_PLAN_PROCESSING_ID", unique=true, nullable=false, length=50)
	public String getExecPlanProcessingId() {
		return execPlanProcessingId;
	}

	public void setExecPlanProcessingId(String execPlanProcessingId) {
		this.execPlanProcessingId = execPlanProcessingId;
	}

	@Column(name="PROJECT_CD", length=50)
	public String getProjectCd() {
		return projectCd;
	}

	public void setProjectCd(String projectCd) {
		this.projectCd = projectCd;
	}

	@Column(name="PROJECT_NAME", length=100)
	public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name="RES_ORG_NAME", length=100)
	public String getResOrgName() {
		return resOrgName;
	}

	public void setResOrgName(String resOrgName) {
		this.resOrgName = resOrgName;
	}

	@Column(name="NO_CONFIRM_STATUS", length=5)
	public String getNoConfirmStatus() {
		return noConfirmStatus;
	}

	public void setNoConfirmStatus(String noConfirmStatus) {
		this.noConfirmStatus = noConfirmStatus;
	}

	@Column(name="GOING_STATUS", length=5)
	public String getGoingStatus() {
		return goingStatus;
	}

	public void setGoingStatus(String goingStatus) {
		this.goingStatus = goingStatus;
	}

	@Column(name="SUSPEND_STATUS", length=5)
	public String getSuspendStatus() {
		return suspendStatus;
	}

	public void setSuspendStatus(String suspendStatus) {
		this.suspendStatus = suspendStatus;
	}

	@Column(name="COMPLETE_STATUS", length=5)
	public String getCompleteStatus() {
		return completeStatus;
	}

	public void setCompleteStatus(String completeStatus) {
		this.completeStatus = completeStatus;
	}

	@Column(name="NO_ACTIVE_STATUS", length=5)
	public String getNoActiveStatus() {
		return noActiveStatus;
	}

	public void setNoActiveStatus(String noActiveStatus) {
		this.noActiveStatus = noActiveStatus;
	}

	@Column(name="NO_REPLY_STATUS", length=5)
	public String getNoReplyStatus() {
		return noReplyStatus;
	}

	public void setNoReplyStatus(String noReplyStatus) {
		this.noReplyStatus = noReplyStatus;
	}

	@Column(name="REMARK", length=200)
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}
