// 
package com.hhz.ump.entity.plan;
// Generated 2010-10-15 9:33:54 by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * PlanWorkSnap generated by hbm2java
 */
@Entity
@Table(name="PLAN_WORK_SNAP"
    ,schema="POWERDESK"
)
public class PlanWorkSnap  implements java.io.Serializable {


     private String workplanSnapId;
     private String planWorkId;
     private Short planYear;
     private Short planWeek;
     private String orgCd;
     private String serialNumber;
     private BigDecimal serialOrder;
     private String targetPointCd;
     private String area;
     private String content;
     private String statusCd;
     private String attachFlg;
     private String principal;
     private Date targetDate;
     private Date endDate;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private String remark;
     private long recordVersion;
     private Long sequenceNo;
     private Short planMonth;

    public PlanWorkSnap() {
    }

	
    public PlanWorkSnap(String workplanSnapId, long recordVersion) {
        this.workplanSnapId = workplanSnapId;
        this.recordVersion = recordVersion;
    }
    public PlanWorkSnap(String workplanSnapId, String planWorkId, Short planYear, Short planWeek, String orgCd, String serialNumber, BigDecimal serialOrder, String targetPointCd, String area, String content, String statusCd, String attachFlg, String principal, Date targetDate, Date endDate, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, String remark, long recordVersion, Long sequenceNo, Short planMonth) {
       this.workplanSnapId = workplanSnapId;
       this.planWorkId = planWorkId;
       this.planYear = planYear;
       this.planWeek = planWeek;
       this.orgCd = orgCd;
       this.serialNumber = serialNumber;
       this.serialOrder = serialOrder;
       this.targetPointCd = targetPointCd;
       this.area = area;
       this.content = content;
       this.statusCd = statusCd;
       this.attachFlg = attachFlg;
       this.principal = principal;
       this.targetDate = targetDate;
       this.endDate = endDate;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.remark = remark;
       this.recordVersion = recordVersion;
       this.sequenceNo = sequenceNo;
       this.planMonth = planMonth;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="WORKPLAN_SNAP_ID", unique=true, nullable=false, length=50)
    public String getWorkplanSnapId() {
        return this.workplanSnapId;
    }
    
    public void setWorkplanSnapId(String workplanSnapId) {
        this.workplanSnapId = workplanSnapId;
    }

    
    @Column(name="PLAN_WORK_ID", length=50)
    public String getPlanWorkId() {
        return this.planWorkId;
    }
    
    public void setPlanWorkId(String planWorkId) {
        this.planWorkId = planWorkId;
    }

    
    @Column(name="PLAN_YEAR", precision=4, scale=0)
    public Short getPlanYear() {
        return this.planYear;
    }
    
    public void setPlanYear(Short planYear) {
        this.planYear = planYear;
    }

    
    @Column(name="PLAN_WEEK", precision=4, scale=0)
    public Short getPlanWeek() {
        return this.planWeek;
    }
    
    public void setPlanWeek(Short planWeek) {
        this.planWeek = planWeek;
    }

    
    @Column(name="ORG_CD", length=20)
    public String getOrgCd() {
        return this.orgCd;
    }
    
    public void setOrgCd(String orgCd) {
        this.orgCd = orgCd;
    }

    
    @Column(name="SERIAL_NUMBER", length=50)
    public String getSerialNumber() {
        return this.serialNumber;
    }
    
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    
    @Column(name="SERIAL_ORDER", precision=38, scale=0)
    public BigDecimal getSerialOrder() {
        return this.serialOrder;
    }
    
    public void setSerialOrder(BigDecimal serialOrder) {
        this.serialOrder = serialOrder;
    }

    
    @Column(name="TARGET_POINT_CD", length=20)
    public String getTargetPointCd() {
        return this.targetPointCd;
    }
    
    public void setTargetPointCd(String targetPointCd) {
        this.targetPointCd = targetPointCd;
    }

    
    @Column(name="AREA", length=50)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }

    
    @Column(name="CONTENT", length=4000)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="STATUS_CD", length=20)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }

    
    @Column(name="ATTACH_FLG", length=1)
    public String getAttachFlg() {
        return this.attachFlg;
    }
    
    public void setAttachFlg(String attachFlg) {
        this.attachFlg = attachFlg;
    }

    
    @Column(name="PRINCIPAL", length=200)
    public String getPrincipal() {
        return this.principal;
    }
    
    public void setPrincipal(String principal) {
        this.principal = principal;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TARGET_DATE", length=7)
    public Date getTargetDate() {
        return this.targetDate;
    }
    
    public void setTargetDate(Date targetDate) {
        this.targetDate = targetDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_DATE", length=7)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }

    
    @Column(name="SEQUENCE_NO", precision=10, scale=0)
    public Long getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Long sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

    
    @Column(name="PLAN_MONTH", precision=4, scale=0)
    public Short getPlanMonth() {
        return this.planMonth;
    }
    
    public void setPlanMonth(Short planMonth) {
        this.planMonth = planMonth;
    }


    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }



}


