// 
package com.hhz.ump.entity.ctdb;
// Generated 2011-12-19 15:49:26 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * CtdbListContent generated by hbm2java
 */
@Entity
@Table(name="CTDB_LIST_CONTENT"
    
)
public class CtdbListContent  implements java.io.Serializable {


     private String listContentId;
     private String listCd;
     private String listName;
     private String listDesc;
     private BigDecimal qty;
     private String measurement;
     private BigDecimal unitPrice;
     private BigDecimal personalPrice;
     private BigDecimal mainMatePrice;
     private BigDecimal aidMatePrice;
     private BigDecimal machinePrice;
     private BigDecimal manageFees;
     private BigDecimal tax;
     private BigDecimal mainMateRate;
     private String importFlg;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String firstCat;
     private String secCate;
     //价格来源
     private String priceFrom;
     //状态(0-新增，1-提交，2-已确认)
     private String statusCd;
     //附件状态(0-不存在，1-存在)
     private String attachFlg;
     

    public CtdbListContent() {
    }

	
    public CtdbListContent(String listContentId, long recordVersion) {
        this.listContentId = listContentId;
        this.recordVersion = recordVersion;
    }
    public CtdbListContent(String listContentId, String listCd, String listName, String listDesc, BigDecimal qty, String measurement, BigDecimal unitPrice, BigDecimal personalPrice, BigDecimal mainMatePrice, BigDecimal aidMatePrice, BigDecimal machinePrice, BigDecimal manageFees, BigDecimal tax, BigDecimal mainMateRate, String importFlg, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion) {
       this.listContentId = listContentId;
       this.listCd = listCd;
       this.listName = listName;
       this.listDesc = listDesc;
       this.qty = qty;
       this.measurement = measurement;
       this.unitPrice = unitPrice;
       this.personalPrice = personalPrice;
       this.mainMatePrice = mainMatePrice;
       this.aidMatePrice = aidMatePrice;
       this.machinePrice = machinePrice;
       this.manageFees = manageFees;
       this.tax = tax;
       this.mainMateRate = mainMateRate;
       this.importFlg = importFlg;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="LIST_CONTENT_ID", unique=true, nullable=false, length=50)
    public String getListContentId() {
        return this.listContentId;
    }
    
    public void setListContentId(String listContentId) {
        this.listContentId = listContentId;
    }
    
    @Column(name="LIST_CD", length=100)
    public String getListCd() {
        return this.listCd;
    }
    
    public void setListCd(String listCd) {
        this.listCd = listCd;
    }
    
    @Column(name="LIST_NAME", length=100)
    public String getListName() {
        return this.listName;
    }
    
    public void setListName(String listName) {
        this.listName = listName;
    }
    
    @Column(name="LIST_DESC", length=500)
    public String getListDesc() {
        return this.listDesc;
    }
    
    public void setListDesc(String listDesc) {
        this.listDesc = listDesc;
    }
    
    @Column(name="QTY", precision=18, scale=6)
    public BigDecimal getQty() {
        return this.qty;
    }
    
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }
    
    @Column(name="MEASUREMENT", length=10)
    public String getMeasurement() {
        return this.measurement;
    }
    
    public void setMeasurement(String measurement) {
        this.measurement = measurement;
    }
    
    @Column(name="UNIT_PRICE", precision=18, scale=6)
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
    
    @Column(name="PERSONAL_PRICE", precision=18, scale=6)
    public BigDecimal getPersonalPrice() {
        return this.personalPrice;
    }
    
    public void setPersonalPrice(BigDecimal personalPrice) {
        this.personalPrice = personalPrice;
    }
    
    @Column(name="MAIN_MATE_PRICE", precision=18, scale=6)
    public BigDecimal getMainMatePrice() {
        return this.mainMatePrice;
    }
    
    public void setMainMatePrice(BigDecimal mainMatePrice) {
        this.mainMatePrice = mainMatePrice;
    }
    
    @Column(name="AID_MATE_PRICE", precision=18, scale=6)
    public BigDecimal getAidMatePrice() {
        return this.aidMatePrice;
    }
    
    public void setAidMatePrice(BigDecimal aidMatePrice) {
        this.aidMatePrice = aidMatePrice;
    }
    
    @Column(name="MACHINE_PRICE", precision=18, scale=6)
    public BigDecimal getMachinePrice() {
        return this.machinePrice;
    }
    
    public void setMachinePrice(BigDecimal machinePrice) {
        this.machinePrice = machinePrice;
    }
    
    @Column(name="MANAGE_FEES", precision=18, scale=6)
    public BigDecimal getManageFees() {
        return this.manageFees;
    }
    
    public void setManageFees(BigDecimal manageFees) {
        this.manageFees = manageFees;
    }
    
    @Column(name="TAX", precision=18, scale=6)
    public BigDecimal getTax() {
        return this.tax;
    }
    
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }
    
    @Column(name="MAIN_MATE_RATE", precision=18, scale=6)
    public BigDecimal getMainMateRate() {
        return this.mainMateRate;
    }
    
    public void setMainMateRate(BigDecimal mainMateRate) {
        this.mainMateRate = mainMateRate;
    }
    
    @Column(name="IMPORT_FLG", length=1)
    public String getImportFlg() {
        return this.importFlg;
    }
    
    public void setImportFlg(String importFlg) {
        this.importFlg = importFlg;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }

    @Column(name="FIRST_CAT", length=50)
	public String getFirstCat() {
		return firstCat;
	}


	public void setFirstCat(String firstCat) {
		this.firstCat = firstCat;
	}

	@Column(name="SEC_CATE", length=50)
	public String getSecCate() {
		return secCate;
	}


	public void setSecCate(String secCate) {
		this.secCate = secCate;
	}

	@Column(name="PRICE_FROM", length=200)
	public String getPriceFrom() {
		return priceFrom;
	}


	public void setPriceFrom(String priceFrom) {
		this.priceFrom = priceFrom;
	}

	@Column(name="STATUS_CD", length=1)
	public String getStatusCd() {
		return statusCd;
	}


	public void setStatusCd(String statusCd) {
		this.statusCd = statusCd;
	}

	@Column(name="ATTACH_FLG", length=1)
	public String getAttachFlg() {
		return attachFlg;
	}


	public void setAttachFlg(String attachFlg) {
		this.attachFlg = attachFlg;
	}

	
	
	
	

    



}


