// 
package com.hhz.ump.entity.jbpm;
// Generated 2010-8-4 11:22:38 by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.BatchSize;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JbpmReimburseDetl generated by hbm2java
 */
@Entity
@Table(name="JBPM_REIMBURSE_DETL"
    ,schema="POWERDESK"
)
public class JbpmReimburseDetl  implements java.io.Serializable {


     private String jbpmReimburseDetlId;
     private JbpmReimburse jbpmReimburse;
     private BigDecimal travelDays;
     private BigDecimal travelFee;
     private String oriDestPlace;
     private Date startDate;
     private Date endDate;
     private String feeTypeCd;
     private BigDecimal feeAmount;
     private BigDecimal ticketFee;
     private BigDecimal fareFee;
     private BigDecimal otherFee;
     private BigDecimal lodgingStan;
     private BigDecimal lodgingFee;
     private BigDecimal lodgingDays;
     private BigDecimal billCount;
     private BigDecimal totalFee;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;

    public JbpmReimburseDetl() {
    }

	
    public JbpmReimburseDetl(String jbpmReimburseDetlId, JbpmReimburse jbpmReimburse, BigDecimal travelFee, long recordVersion) {
        this.jbpmReimburseDetlId = jbpmReimburseDetlId;
        this.jbpmReimburse = jbpmReimburse;
        this.travelFee = travelFee;
        this.recordVersion = recordVersion;
    }
    public JbpmReimburseDetl(String jbpmReimburseDetlId, JbpmReimburse jbpmReimburse, BigDecimal travelDays, BigDecimal travelFee, String oriDestPlace, Date startDate, Date endDate, String feeTypeCd, BigDecimal feeAmount, BigDecimal ticketFee, BigDecimal fareFee, BigDecimal otherFee, BigDecimal lodgingStan, BigDecimal lodgingFee, BigDecimal lodgingDays, BigDecimal billCount, BigDecimal totalFee, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion) {
       this.jbpmReimburseDetlId = jbpmReimburseDetlId;
       this.jbpmReimburse = jbpmReimburse;
       this.travelDays = travelDays;
       this.travelFee = travelFee;
       this.oriDestPlace = oriDestPlace;
       this.startDate = startDate;
       this.endDate = endDate;
       this.feeTypeCd = feeTypeCd;
       this.feeAmount = feeAmount;
       this.ticketFee = ticketFee;
       this.fareFee = fareFee;
       this.otherFee = otherFee;
       this.lodgingStan = lodgingStan;
       this.lodgingFee = lodgingFee;
       this.lodgingDays = lodgingDays;
       this.billCount = billCount;
       this.totalFee = totalFee;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="JBPM_REIMBURSE_DETL_ID", unique=true, nullable=false, length=50)
    public String getJbpmReimburseDetlId() {
        return this.jbpmReimburseDetlId;
    }
    
    public void setJbpmReimburseDetlId(String jbpmReimburseDetlId) {
        this.jbpmReimburseDetlId = jbpmReimburseDetlId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="JBPM_REIMBURSE_ID", nullable=false)
    public JbpmReimburse getJbpmReimburse() {
        return this.jbpmReimburse;
    }
    
    public void setJbpmReimburse(JbpmReimburse jbpmReimburse) {
        this.jbpmReimburse = jbpmReimburse;
    }

    
    @Column(name="TRAVEL_DAYS", precision=4, scale=1)
    public BigDecimal getTravelDays() {
        return this.travelDays;
    }
    
    public void setTravelDays(BigDecimal travelDays) {
        this.travelDays = travelDays;
    }

    
    @Column(name="TRAVEL_FEE", nullable=false, precision=18, scale=4)
    public BigDecimal getTravelFee() {
        return this.travelFee;
    }
    
    public void setTravelFee(BigDecimal travelFee) {
        this.travelFee = travelFee;
    }

    
    @Column(name="ORI_DEST_PLACE", length=200)
    public String getOriDestPlace() {
        return this.oriDestPlace;
    }
    
    public void setOriDestPlace(String oriDestPlace) {
        this.oriDestPlace = oriDestPlace;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="START_DATE", length=11)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_DATE", length=11)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="FEE_TYPE_CD", length=20)
    public String getFeeTypeCd() {
        return this.feeTypeCd;
    }
    
    public void setFeeTypeCd(String feeTypeCd) {
        this.feeTypeCd = feeTypeCd;
    }

    
    @Column(name="FEE_AMOUNT", precision=18, scale=4)
    public BigDecimal getFeeAmount() {
        return this.feeAmount;
    }
    
    public void setFeeAmount(BigDecimal feeAmount) {
        this.feeAmount = feeAmount;
    }

    
    @Column(name="TICKET_FEE", precision=18, scale=4)
    public BigDecimal getTicketFee() {
        return this.ticketFee;
    }
    
    public void setTicketFee(BigDecimal ticketFee) {
        this.ticketFee = ticketFee;
    }

    
    @Column(name="FARE_FEE", precision=18, scale=4)
    public BigDecimal getFareFee() {
        return this.fareFee;
    }
    
    public void setFareFee(BigDecimal fareFee) {
        this.fareFee = fareFee;
    }

    
    @Column(name="OTHER_FEE", precision=18, scale=4)
    public BigDecimal getOtherFee() {
        return this.otherFee;
    }
    
    public void setOtherFee(BigDecimal otherFee) {
        this.otherFee = otherFee;
    }

    
    @Column(name="LODGING_STAN", precision=18, scale=4)
    public BigDecimal getLodgingStan() {
        return this.lodgingStan;
    }
    
    public void setLodgingStan(BigDecimal lodgingStan) {
        this.lodgingStan = lodgingStan;
    }

    
    @Column(name="LODGING_FEE", precision=18, scale=4)
    public BigDecimal getLodgingFee() {
        return this.lodgingFee;
    }
    
    public void setLodgingFee(BigDecimal lodgingFee) {
        this.lodgingFee = lodgingFee;
    }

    
    @Column(name="LODGING_DAYS", precision=38, scale=0)
    public BigDecimal getLodgingDays() {
        return this.lodgingDays;
    }
    
    public void setLodgingDays(BigDecimal lodgingDays) {
        this.lodgingDays = lodgingDays;
    }

    
    @Column(name="BILL_COUNT", precision=38, scale=0)
    public BigDecimal getBillCount() {
        return this.billCount;
    }
    
    public void setBillCount(BigDecimal billCount) {
        this.billCount = billCount;
    }

    
    @Column(name="TOTAL_FEE", precision=18, scale=4)
    public BigDecimal getTotalFee() {
        return this.totalFee;
    }
    
    public void setTotalFee(BigDecimal totalFee) {
        this.totalFee = totalFee;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }




}


