// 
package com.hhz.ump.entity.jbpm;
// Generated 2010-8-4 11:22:38 by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.BatchSize;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JbpmTravelHis generated by hbm2java
 */
@Entity
@Table(name="JBPM_TRAVEL_HIS"
    ,schema="POWERDESK"
)
public class JbpmTravelHis  implements java.io.Serializable {


     private String jbpmTravelHisId;
     private JbpmTravelApply jbpmTravelApply;
     private String userCd;
     private String userName;
     private String deptCd;
     private String positionCd;
     private String activeName;
     private String taskId;
     private String optionCd;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;

    public JbpmTravelHis() {
    }

	
    public JbpmTravelHis(String jbpmTravelHisId, JbpmTravelApply jbpmTravelApply, long recordVersion) {
        this.jbpmTravelHisId = jbpmTravelHisId;
        this.jbpmTravelApply = jbpmTravelApply;
        this.recordVersion = recordVersion;
    }
    public JbpmTravelHis(String jbpmTravelHisId, JbpmTravelApply jbpmTravelApply, String userCd, String userName, String deptCd, String positionCd, String activeName, String taskId, String optionCd, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion) {
       this.jbpmTravelHisId = jbpmTravelHisId;
       this.jbpmTravelApply = jbpmTravelApply;
       this.userCd = userCd;
       this.userName = userName;
       this.deptCd = deptCd;
       this.positionCd = positionCd;
       this.activeName = activeName;
       this.taskId = taskId;
       this.optionCd = optionCd;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="JBPM_TRAVEL_HIS_ID", unique=true, nullable=false, length=50)
    public String getJbpmTravelHisId() {
        return this.jbpmTravelHisId;
    }
    
    public void setJbpmTravelHisId(String jbpmTravelHisId) {
        this.jbpmTravelHisId = jbpmTravelHisId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="JBPM_TRAVEL_APPLY_ID", nullable=false)
    public JbpmTravelApply getJbpmTravelApply() {
        return this.jbpmTravelApply;
    }
    
    public void setJbpmTravelApply(JbpmTravelApply jbpmTravelApply) {
        this.jbpmTravelApply = jbpmTravelApply;
    }

    
    @Column(name="USER_CD", length=20)
    public String getUserCd() {
        return this.userCd;
    }
    
    public void setUserCd(String userCd) {
        this.userCd = userCd;
    }

    
    @Column(name="USER_NAME", length=50)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="DEPT_CD", length=20)
    public String getDeptCd() {
        return this.deptCd;
    }
    
    public void setDeptCd(String deptCd) {
        this.deptCd = deptCd;
    }

    
    @Column(name="POSITION_CD", length=20)
    public String getPositionCd() {
        return this.positionCd;
    }
    
    public void setPositionCd(String positionCd) {
        this.positionCd = positionCd;
    }

    
    @Column(name="ACTIVE_NAME", length=50)
    public String getActiveName() {
        return this.activeName;
    }
    
    public void setActiveName(String activeName) {
        this.activeName = activeName;
    }

    
    @Column(name="TASK_ID", length=50)
    public String getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    
    @Column(name="OPTION_CD", length=20)
    public String getOptionCd() {
        return this.optionCd;
    }
    
    public void setOptionCd(String optionCd) {
        this.optionCd = optionCd;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }




}


