// 
package com.hhz.ump.entity.bid;
// Generated 2012-6-27 11:01:25 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.BatchSize;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BidConsult generated by hbm2java
 */
@Entity
@Table(name="BID_CONSULT"
    ,schema="POWERDESK"
)
public class BidConsult  implements java.io.Serializable {


     private String bidConsultId;
     private String briefName;
     private String fullName;
     private String isLatestRelFlg;
     private String consultTypeCd;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String plAcct;
     private String plOriPwd;
     private String isSimulateFlg;

    public BidConsult() {
    }

	
    public BidConsult(String bidConsultId, long recordVersion) {
        this.bidConsultId = bidConsultId;
        this.recordVersion = recordVersion;
    }
    public BidConsult(String bidConsultId, String briefName, String fullName, String isLatestRelFlg, String consultTypeCd, String remark, String creator, String createdCenterCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedPositionCd, Date updatedDate, long recordVersion, String plAcct, String plOriPwd, String isSimulateFlg) {
       this.bidConsultId = bidConsultId;
       this.briefName = briefName;
       this.fullName = fullName;
       this.isLatestRelFlg = isLatestRelFlg;
       this.consultTypeCd = consultTypeCd;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.plAcct = plAcct;
       this.plOriPwd = plOriPwd;
       this.isSimulateFlg = isSimulateFlg;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BID_CONSULT_ID", unique=true, nullable=false, length=50)
    public String getBidConsultId() {
        return this.bidConsultId;
    }
    
    public void setBidConsultId(String bidConsultId) {
        this.bidConsultId = bidConsultId;
    }
    
    @Column(name="BRIEF_NAME", length=50)
    public String getBriefName() {
        return this.briefName;
    }
    
    public void setBriefName(String briefName) {
        this.briefName = briefName;
    }
    
    @Column(name="FULL_NAME", length=100)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    
    @Column(name="IS_LATEST_REL_FLG", length=1)
    public String getIsLatestRelFlg() {
        return this.isLatestRelFlg;
    }
    
    public void setIsLatestRelFlg(String isLatestRelFlg) {
        this.isLatestRelFlg = isLatestRelFlg;
    }
    
    @Column(name="CONSULT_TYPE_CD", length=20)
    public String getConsultTypeCd() {
        return this.consultTypeCd;
    }
    
    public void setConsultTypeCd(String consultTypeCd) {
        this.consultTypeCd = consultTypeCd;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="PL_ACCT", length=50)
    public String getPlAcct() {
        return this.plAcct;
    }
    
    public void setPlAcct(String plAcct) {
        this.plAcct = plAcct;
    }
    
    @Column(name="PL_ORI_PWD", length=50)
    public String getPlOriPwd() {
        return this.plOriPwd;
    }
    
    public void setPlOriPwd(String plOriPwd) {
        this.plOriPwd = plOriPwd;
    }
    
    @Column(name="IS_SIMULATE_FLG", length=1)
    public String getIsSimulateFlg() {
        return this.isSimulateFlg;
    }
    
    public void setIsSimulateFlg(String isSimulateFlg) {
        this.isSimulateFlg = isSimulateFlg;
    }




}


