// 
package com.hhz.ump.entity.bid;
// Generated 2012-6-27 11:01:25 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * BidLedger generated by hbm2java
 */
@Entity
@Table(name="BID_LEDGER"
    ,schema="POWERDESK"
)
public class BidLedger  implements java.io.Serializable {


     private String bidLedgerId;
     private String orgCd;
     private String bidSectionName;
     private String visableFlg;
     private BigDecimal targetAmt;
     private String sectionNo;
     private String budgetInFlg;
     private String budgetOutFlg;
     private BigDecimal guaranteeAmt;
     private String operDesc;
     private String placeDesc;
     private BigDecimal sectionTotalArea;
     private BigDecimal bizArea;
     private BigDecimal houseArea;
     private String followNames;
     private String followCds;
     private Date bidOpenPlanDate;
     private Date bidOpenRealDate;
     private Date bidConfirmPlanDate;
     private Date bidConfirmRealDate;
     private String bidStatusCd;
     private String bidDesc;
     private String resApproveInfoId;
     private Long batchNo;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String orgName;
     private String judgeCd;
     private String judgeName;
     private Date judgeDate;
     private String totalRankDesc;
     private String bidAreaDesc;
     private Date startDate;
     private Date endDate;
     private String quanDemandDesc;
     private String bidModeCd;
     private String calcModeCd;
     private String payTypeDesc;
     private String overallTypeFlg;
     private String bidContAttachId;
     private Long rankDateNum;
     private String consultFlg;
     private String srcTypeCd;
     private String projIntrDesc;
     private String needGuarFlg;
     private Date lastGuarDate;
     private Date lastReceDate;
     private String attaTendFileFlg;
     private String attaDrawFileFlg;
     private String attaListFlg;
     private String attaTechStanFlg;
     private String resApproveCd;
     private String periodNum;
     private String construction;
     private String ccbpId;
     private String ccbpNo;
     private List<BidSup> bidSups = new ArrayList<BidSup>();
     private List<BidTechItem> bidTechItems = new ArrayList<BidTechItem>();
     private List<BidProject> bidProjects = new ArrayList<BidProject>();
     private List<BidLedgAttaRel> bidLedgAttaRels = new ArrayList<BidLedgAttaRel>();
     private List<BidOpenRecord> bidOpenRecords = new ArrayList<BidOpenRecord>();

     //招标单网批ID
     private String callResId;
     private String callResAttachId;
     //定标单网批ID
     private String bidResId;
     //战略编号
     private String serialType;
     //战略序号
     private Long serialNo;
     
    public BidLedger() {
    }

	
    public BidLedger(String bidLedgerId, long recordVersion) {
        this.bidLedgerId = bidLedgerId;
        this.recordVersion = recordVersion;
    }
    public BidLedger(String bidLedgerId, String orgCd, String bidSectionName, String visableFlg, BigDecimal targetAmt, String sectionNo, String budgetInFlg, String budgetOutFlg, BigDecimal guaranteeAmt, String operDesc, String placeDesc, BigDecimal sectionTotalArea, BigDecimal bizArea, BigDecimal houseArea, String followNames, String followCds, Date bidOpenPlanDate, Date bidOpenRealDate, Date bidConfirmPlanDate, Date bidConfirmRealDate, String bidStatusCd, String bidDesc, String resApproveInfoId, Long batchNo, String remark, String creator, String createdCenterCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedPositionCd, Date updatedDate, long recordVersion, String orgName, String judgeCd, String judgeName, Date judgeDate, String totalRankDesc, String bidAreaDesc, Date startDate, Date endDate, String quanDemandDesc, String bidModeCd, String calcModeCd, String payTypeDesc, String overallTypeFlg, String bidContAttachId, Long rankDateNum, String consultFlg, String srcTypeCd, String projIntrDesc, String needGuarFlg, Date lastGuarDate, Date lastReceDate, String attaTendFileFlg, String attaDrawFileFlg, String attaListFlg, String attaTechStanFlg, String resApproveCd, String periodNum, String construction, String ccbpId, String ccbpNo,String callResId,String callResAttachId, String bidResId, List<BidSup> bidSups, List<BidTechItem> bidTechItems, List<BidProject> bidProjects, List<BidLedgAttaRel> bidLedgAttaRels, String serialType, Long serialNo) {
       this.bidLedgerId = bidLedgerId;
       this.orgCd = orgCd;
       this.bidSectionName = bidSectionName;
       this.visableFlg = visableFlg;
       this.targetAmt = targetAmt;
       this.sectionNo = sectionNo;
       this.budgetInFlg = budgetInFlg;
       this.budgetOutFlg = budgetOutFlg;
       this.guaranteeAmt = guaranteeAmt;
       this.operDesc = operDesc;
       this.placeDesc = placeDesc;
       this.sectionTotalArea = sectionTotalArea;
       this.bizArea = bizArea;
       this.houseArea = houseArea;
       this.followNames = followNames;
       this.followCds = followCds;
       this.bidOpenPlanDate = bidOpenPlanDate;
       this.bidOpenRealDate = bidOpenRealDate;
       this.bidConfirmPlanDate = bidConfirmPlanDate;
       this.bidConfirmRealDate = bidConfirmRealDate;
       this.bidStatusCd = bidStatusCd;
       this.bidDesc = bidDesc;
       this.resApproveInfoId = resApproveInfoId;
       this.batchNo = batchNo;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.orgName = orgName;
       this.judgeCd = judgeCd;
       this.judgeName = judgeName;
       this.judgeDate = judgeDate;
       this.totalRankDesc = totalRankDesc;
       this.bidAreaDesc = bidAreaDesc;
       this.startDate = startDate;
       this.endDate = endDate;
       this.quanDemandDesc = quanDemandDesc;
       this.bidModeCd = bidModeCd;
       this.calcModeCd = calcModeCd;
       this.payTypeDesc = payTypeDesc;
       this.overallTypeFlg = overallTypeFlg;
       this.bidContAttachId = bidContAttachId;
       this.rankDateNum = rankDateNum;
       this.consultFlg = consultFlg;
       this.srcTypeCd = srcTypeCd;
       this.projIntrDesc = projIntrDesc;
       this.needGuarFlg = needGuarFlg;
       this.lastGuarDate = lastGuarDate;
       this.lastReceDate = lastReceDate;
       this.attaTendFileFlg = attaTendFileFlg;
       this.attaDrawFileFlg = attaDrawFileFlg;
       this.attaListFlg = attaListFlg;
       this.attaTechStanFlg = attaTechStanFlg;
       this.resApproveCd = resApproveCd;
       this.periodNum = periodNum;
       this.construction = construction;
       this.ccbpId = ccbpId;
       this.ccbpNo = ccbpNo;
       this.callResId = callResId;
       this.callResAttachId = callResAttachId;
       this.bidResId = bidResId;
       this.bidSups = bidSups;
       this.bidTechItems = bidTechItems;
       this.bidProjects = bidProjects;
       this.bidLedgAttaRels = bidLedgAttaRels;
       this.serialType = serialType;
       this.serialNo = serialNo;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BID_LEDGER_ID", unique=true, nullable=false, length=50)
    public String getBidLedgerId() {
        return this.bidLedgerId;
    }
    
    public void setBidLedgerId(String bidLedgerId) {
        this.bidLedgerId = bidLedgerId;
    }
    
    @Column(name="ORG_CD", length=20)
    public String getOrgCd() {
        return this.orgCd;
    }
    
    public void setOrgCd(String orgCd) {
        this.orgCd = orgCd;
    }
    
    @Column(name="BID_SECTION_NAME", length=100)
    public String getBidSectionName() {
        return this.bidSectionName;
    }
    
    public void setBidSectionName(String bidSectionName) {
        this.bidSectionName = bidSectionName;
    }
    
    @Column(name="VISABLE_FLG", length=1)
    public String getVisableFlg() {
        return this.visableFlg;
    }
    
    public void setVisableFlg(String visableFlg) {
        this.visableFlg = visableFlg;
    }
    
    @Column(name="TARGET_AMT", precision=18)
    public BigDecimal getTargetAmt() {
        return this.targetAmt;
    }
    
    public void setTargetAmt(BigDecimal targetAmt) {
        this.targetAmt = targetAmt;
    }
    
    @Column(name="SECTION_NO", length=50)
    public String getSectionNo() {
        return this.sectionNo;
    }
    
    public void setSectionNo(String sectionNo) {
        this.sectionNo = sectionNo;
    }
    
    @Column(name="BUDGET_IN_FLG", length=1)
    public String getBudgetInFlg() {
        return this.budgetInFlg;
    }
    
    public void setBudgetInFlg(String budgetInFlg) {
        this.budgetInFlg = budgetInFlg;
    }
    
    @Column(name="BUDGET_OUT_FLG", length=1)
    public String getBudgetOutFlg() {
        return this.budgetOutFlg;
    }
    
    public void setBudgetOutFlg(String budgetOutFlg) {
        this.budgetOutFlg = budgetOutFlg;
    }
    
    @Column(name="GUARANTEE_AMT", precision=18)
    public BigDecimal getGuaranteeAmt() {
        return this.guaranteeAmt;
    }
    
    public void setGuaranteeAmt(BigDecimal guaranteeAmt) {
        this.guaranteeAmt = guaranteeAmt;
    }
    
    @Column(name="OPER_DESC", length=200)
    public String getOperDesc() {
        return this.operDesc;
    }
    
    public void setOperDesc(String operDesc) {
        this.operDesc = operDesc;
    }
    
    @Column(name="PLACE_DESC", length=1000)
    public String getPlaceDesc() {
        return this.placeDesc;
    }
    
    public void setPlaceDesc(String placeDesc) {
        this.placeDesc = placeDesc;
    }
    
    @Column(name="SECTION_TOTAL_AREA", precision=10)
    public BigDecimal getSectionTotalArea() {
        return this.sectionTotalArea;
    }
    
    public void setSectionTotalArea(BigDecimal sectionTotalArea) {
        this.sectionTotalArea = sectionTotalArea;
    }
    
    @Column(name="BIZ_AREA", precision=10)
    public BigDecimal getBizArea() {
        return this.bizArea;
    }
    
    public void setBizArea(BigDecimal bizArea) {
        this.bizArea = bizArea;
    }
    
    @Column(name="HOUSE_AREA", precision=10)
    public BigDecimal getHouseArea() {
        return this.houseArea;
    }
    
    public void setHouseArea(BigDecimal houseArea) {
        this.houseArea = houseArea;
    }
    
    @Column(name="FOLLOW_NAMES", length=100)
    public String getFollowNames() {
        return this.followNames;
    }
    
    public void setFollowNames(String followNames) {
        this.followNames = followNames;
    }
    
    @Column(name="FOLLOW_CDS", length=100)
    public String getFollowCds() {
        return this.followCds;
    }
    
    public void setFollowCds(String followCds) {
        this.followCds = followCds;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BID_OPEN_PLAN_DATE", length=7)
    public Date getBidOpenPlanDate() {
        return this.bidOpenPlanDate;
    }
    
    public void setBidOpenPlanDate(Date bidOpenPlanDate) {
        this.bidOpenPlanDate = bidOpenPlanDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BID_OPEN_REAL_DATE", length=7)
    public Date getBidOpenRealDate() {
        return this.bidOpenRealDate;
    }
    
    public void setBidOpenRealDate(Date bidOpenRealDate) {
        this.bidOpenRealDate = bidOpenRealDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BID_CONFIRM_PLAN_DATE", length=7)
    public Date getBidConfirmPlanDate() {
        return this.bidConfirmPlanDate;
    }
    
    public void setBidConfirmPlanDate(Date bidConfirmPlanDate) {
        this.bidConfirmPlanDate = bidConfirmPlanDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BID_CONFIRM_REAL_DATE", length=7)
    public Date getBidConfirmRealDate() {
        return this.bidConfirmRealDate;
    }
    
    public void setBidConfirmRealDate(Date bidConfirmRealDate) {
        this.bidConfirmRealDate = bidConfirmRealDate;
    }
    
    @Column(name="BID_STATUS_CD", length=1)
    public String getBidStatusCd() {
        return this.bidStatusCd;
    }
    
    public void setBidStatusCd(String bidStatusCd) {
        this.bidStatusCd = bidStatusCd;
    }
    
    @Column(name="BID_DESC", length=1000)
    public String getBidDesc() {
        return this.bidDesc;
    }
    
    public void setBidDesc(String bidDesc) {
        this.bidDesc = bidDesc;
    }
    
    @Column(name="RES_APPROVE_INFO_ID", length=50)
    public String getResApproveInfoId() {
        return this.resApproveInfoId;
    }
    
    public void setResApproveInfoId(String resApproveInfoId) {
        this.resApproveInfoId = resApproveInfoId;
    }
    
    @Column(name="BATCH_NO", precision=18, scale=0)
    public Long getBatchNo() {
        return this.batchNo;
    }
    
    public void setBatchNo(Long batchNo) {
        this.batchNo = batchNo;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="ORG_NAME", length=100)
    public String getOrgName() {
        return this.orgName;
    }
    
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }
    
    @Column(name="JUDGE_CD", length=50)
    public String getJudgeCd() {
        return this.judgeCd;
    }
    
    public void setJudgeCd(String judgeCd) {
        this.judgeCd = judgeCd;
    }
    
    @Column(name="JUDGE_NAME", length=100)
    public String getJudgeName() {
        return this.judgeName;
    }
    
    public void setJudgeName(String judgeName) {
        this.judgeName = judgeName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="JUDGE_DATE", length=7)
    public Date getJudgeDate() {
        return this.judgeDate;
    }
    
    public void setJudgeDate(Date judgeDate) {
        this.judgeDate = judgeDate;
    }
    
    @Column(name="TOTAL_RANK_DESC", length=500)
    public String getTotalRankDesc() {
        return this.totalRankDesc;
    }
    
    public void setTotalRankDesc(String totalRankDesc) {
        this.totalRankDesc = totalRankDesc;
    }
    
    @Column(name="BID_AREA_DESC", length=500)
    public String getBidAreaDesc() {
        return this.bidAreaDesc;
    }
    
    public void setBidAreaDesc(String bidAreaDesc) {
        this.bidAreaDesc = bidAreaDesc;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="START_DATE", length=7)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_DATE", length=7)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    
    @Column(name="QUAN_DEMAND_DESC", length=500)
    public String getQuanDemandDesc() {
        return this.quanDemandDesc;
    }
    
    public void setQuanDemandDesc(String quanDemandDesc) {
        this.quanDemandDesc = quanDemandDesc;
    }
    
    @Column(name="BID_MODE_CD", length=1)
    public String getBidModeCd() {
        return this.bidModeCd;
    }
    
    public void setBidModeCd(String bidModeCd) {
        this.bidModeCd = bidModeCd;
    }
    
    @Column(name="CALC_MODE_CD", length=1)
    public String getCalcModeCd() {
        return this.calcModeCd;
    }
    
    public void setCalcModeCd(String calcModeCd) {
        this.calcModeCd = calcModeCd;
    }
    
    @Column(name="PAY_TYPE_DESC", length=200)
    public String getPayTypeDesc() {
        return this.payTypeDesc;
    }
    
    public void setPayTypeDesc(String payTypeDesc) {
        this.payTypeDesc = payTypeDesc;
    }
    
    @Column(name="OVERALL_TYPE_FLG", length=1)
    public String getOverallTypeFlg() {
        return this.overallTypeFlg;
    }
    
    public void setOverallTypeFlg(String overallTypeFlg) {
        this.overallTypeFlg = overallTypeFlg;
    }
    
    @Column(name="BID_CONT_ATTACH_ID", length=50)
    public String getBidContAttachId() {
        return this.bidContAttachId;
    }
    
    public void setBidContAttachId(String bidContAttachId) {
        this.bidContAttachId = bidContAttachId;
    }
    
    @Column(name="RANK_DATE_NUM", precision=10, scale=0)
    public Long getRankDateNum() {
        return this.rankDateNum;
    }
    
    public void setRankDateNum(Long rankDateNum) {
        this.rankDateNum = rankDateNum;
    }
    
    @Column(name="CONSULT_FLG", length=1)
    public String getConsultFlg() {
        return this.consultFlg;
    }
    
    public void setConsultFlg(String consultFlg) {
        this.consultFlg = consultFlg;
    }
    
    @Column(name="SRC_TYPE_CD", length=20)
    public String getSrcTypeCd() {
        return this.srcTypeCd;
    }
    
    public void setSrcTypeCd(String srcTypeCd) {
        this.srcTypeCd = srcTypeCd;
    }
    
    @Column(name="PROJ_INTR_DESC", length=2000)
    public String getProjIntrDesc() {
        return this.projIntrDesc;
    }
    
    public void setProjIntrDesc(String projIntrDesc) {
        this.projIntrDesc = projIntrDesc;
    }
    
    @Column(name="NEED_GUAR_FLG", length=1)
    public String getNeedGuarFlg() {
        return this.needGuarFlg;
    }
    
    public void setNeedGuarFlg(String needGuarFlg) {
        this.needGuarFlg = needGuarFlg;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_GUAR_DATE", length=7)
    public Date getLastGuarDate() {
        return this.lastGuarDate;
    }
    
    public void setLastGuarDate(Date lastGuarDate) {
        this.lastGuarDate = lastGuarDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_RECE_DATE", length=7)
    public Date getLastReceDate() {
        return this.lastReceDate;
    }
    
    public void setLastReceDate(Date lastReceDate) {
        this.lastReceDate = lastReceDate;
    }
    
    @Column(name="ATTA_TEND_FILE_FLG", length=1)
    public String getAttaTendFileFlg() {
        return this.attaTendFileFlg;
    }
    
    public void setAttaTendFileFlg(String attaTendFileFlg) {
        this.attaTendFileFlg = attaTendFileFlg;
    }
    
    @Column(name="ATTA_DRAW_FILE_FLG", length=1)
    public String getAttaDrawFileFlg() {
        return this.attaDrawFileFlg;
    }
    
    public void setAttaDrawFileFlg(String attaDrawFileFlg) {
        this.attaDrawFileFlg = attaDrawFileFlg;
    }
    
    @Column(name="ATTA_LIST_FLG", length=1)
    public String getAttaListFlg() {
        return this.attaListFlg;
    }
    
    public void setAttaListFlg(String attaListFlg) {
        this.attaListFlg = attaListFlg;
    }
    
    @Column(name="ATTA_TECH_STAN_FLG", length=1)
    public String getAttaTechStanFlg() {
        return this.attaTechStanFlg;
    }
    
    public void setAttaTechStanFlg(String attaTechStanFlg) {
        this.attaTechStanFlg = attaTechStanFlg;
    }
    
    @Column(name="RES_APPROVE_CD", length=100)
    public String getResApproveCd() {
        return this.resApproveCd;
    }
    
    public void setResApproveCd(String resApproveCd) {
        this.resApproveCd = resApproveCd;
    }
    
    @Column(name="PERIOD_NUM", length=20)
    public String getPeriodNum() {
        return this.periodNum;
    }
    
    public void setPeriodNum(String periodNum) {
        this.periodNum = periodNum;
    }
    
    @Column(name="CONSTRUCTION", length=200)
    public String getConstruction() {
        return this.construction;
    }
    
    public void setConstruction(String construction) {
        this.construction = construction;
    }
    
    @Column(name="CCBP_ID", length=50)
    public String getCcbpId() {
        return this.ccbpId;
    }
    
    public void setCcbpId(String ccbpId) {
        this.ccbpId = ccbpId;
    }
    
    @Column(name="CCBP_NO", length=50)
    public String getCcbpNo() {
        return this.ccbpNo;
    }
    
    public void setCcbpNo(String ccbpNo) {
        this.ccbpNo = ccbpNo;
    }


    @Column(name="CALL_RES_ID", length=50)
	public String getCallResId() {
		return callResId;
	}


	public void setCallResId(String callResId) {
		this.callResId = callResId;
	}
	

    @Column(name="CALL_RES_ATTACH_ID", length=50)
	public String getCallResAttachId() {
		return callResAttachId;
	}


	public void setCallResAttachId(String callResAttachId) {
		this.callResAttachId = callResAttachId;
	}


    @Column(name="BID_RES_ID", length=50)
    public String getBidResId() {
        return this.bidResId;
    }
    
    public void setBidResId(String bidResId) {
        this.bidResId = bidResId;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bidLedger")
    @BatchSize(size=10)
public List<BidSup> getBidSups() {
        return this.bidSups;
    }
    
    public void setBidSups(List<BidSup> bidSups) {
        this.bidSups = bidSups;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bidLedger")
    @BatchSize(size=10)
public List<BidTechItem> getBidTechItems() {
        return this.bidTechItems;
    }
    
    public void setBidTechItems(List<BidTechItem> bidTechItems) {
        this.bidTechItems = bidTechItems;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bidLedger")
    @BatchSize(size=10)
public List<BidProject> getBidProjects() {
        return this.bidProjects;
    }
    
    public void setBidProjects(List<BidProject> bidProjects) {
        this.bidProjects = bidProjects;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bidLedger")
    @BatchSize(size=10)
public List<BidLedgAttaRel> getBidLedgAttaRels() {
        return this.bidLedgAttaRels;
    }
    
    public void setBidLedgAttaRels(List<BidLedgAttaRel> bidLedgAttaRels) {
        this.bidLedgAttaRels = bidLedgAttaRels;
    }


    @Column(name="SERIAL_TYPE", length=50)
    public String getSerialType() {
        return this.serialType;
    }
    
    public void setSerialType(String serialType) {
        this.serialType = serialType;
    }
    
    @Column(name="SERIAL_NO", precision=10, scale=0)
    public Long getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(Long serialNo) {
        this.serialNo = serialNo;
    }
    @OneToMany(fetch=FetchType.LAZY, mappedBy="bidLedger")
    @BatchSize(size=10)
public List<BidOpenRecord> getBidOpenRecords() {
        return this.bidOpenRecords;
    }
    
    public void setBidOpenRecords(List<BidOpenRecord> bidOpenRecords) {
        this.bidOpenRecords = bidOpenRecords;
    }
}


