// 
package com.hhz.ump.entity.bid;
// Generated 2012-6-27 11:01:25 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.BatchSize;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BidOtherItemRel generated by hbm2java
 */
@Entity
@Table(name="BID_OTHER_ITEM_REL"
    ,schema="POWERDESK"
)
public class BidOtherItemRel  implements java.io.Serializable {


     private String bidOtherItemRelId;
     private BidSup bidSup;
     private BidProject bidProject;
     private String itemNo;
     private String itemName;
     private String calcBasicDesc;
     private Long batchNo;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private Long rowNo;
     private String quantitie;
     private String amt;

    public BidOtherItemRel() {
    }

	
    public BidOtherItemRel(String bidOtherItemRelId, BidSup bidSup, BidProject bidProject, long recordVersion) {
        this.bidOtherItemRelId = bidOtherItemRelId;
        this.bidSup = bidSup;
        this.bidProject = bidProject;
        this.recordVersion = recordVersion;
    }
    public BidOtherItemRel(String bidOtherItemRelId, BidSup bidSup, BidProject bidProject, String itemNo, String itemName, String calcBasicDesc, Long batchNo, String remark, String creator, String createdCenterCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedPositionCd, Date updatedDate, long recordVersion, Long rowNo, String quantitie, String amt) {
       this.bidOtherItemRelId = bidOtherItemRelId;
       this.bidSup = bidSup;
       this.bidProject = bidProject;
       this.itemNo = itemNo;
       this.itemName = itemName;
       this.calcBasicDesc = calcBasicDesc;
       this.batchNo = batchNo;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.rowNo = rowNo;
       this.quantitie = quantitie;
       this.amt = amt;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BID_OTHER_ITEM_REL_ID", unique=true, nullable=false, length=50)
    public String getBidOtherItemRelId() {
        return this.bidOtherItemRelId;
    }
    
    public void setBidOtherItemRelId(String bidOtherItemRelId) {
        this.bidOtherItemRelId = bidOtherItemRelId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BID_SUP_ID", nullable=false)
    public BidSup getBidSup() {
        return this.bidSup;
    }
    
    public void setBidSup(BidSup bidSup) {
        this.bidSup = bidSup;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BID_PROJECT_ID", nullable=false)
    public BidProject getBidProject() {
        return this.bidProject;
    }
    
    public void setBidProject(BidProject bidProject) {
        this.bidProject = bidProject;
    }
    
    @Column(name="ITEM_NO", length=50)
    public String getItemNo() {
        return this.itemNo;
    }
    
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo;
    }
    
    @Column(name="ITEM_NAME", length=100)
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    
    @Column(name="CALC_BASIC_DESC", length=100)
    public String getCalcBasicDesc() {
        return this.calcBasicDesc;
    }
    
    public void setCalcBasicDesc(String calcBasicDesc) {
        this.calcBasicDesc = calcBasicDesc;
    }
    
    @Column(name="BATCH_NO", precision=18, scale=0)
    public Long getBatchNo() {
        return this.batchNo;
    }
    
    public void setBatchNo(Long batchNo) {
        this.batchNo = batchNo;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="ROW_NO", precision=18, scale=0)
    public Long getRowNo() {
        return this.rowNo;
    }
    
    public void setRowNo(Long rowNo) {
        this.rowNo = rowNo;
    }
    
    @Column(name="QUANTITIE", length=20)
    public String getQuantitie() {
        return this.quantitie;
    }
    
    public void setQuantitie(String quantitie) {
        this.quantitie = quantitie;
    }
    
    @Column(name="AMT", length=20)
    public String getAmt() {
        return this.amt;
    }
    
    public void setAmt(String amt) {
        this.amt = amt;
    }




}


