// 
package com.hhz.ump.entity.sc;
// Generated 2012-2-13 10:23:34 by Hibernate Tools 3.2.2.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OrderBy;

/**
 * ScContractTempletInfo generated by hbm2java
 */
@Entity
@Table(name="SC_CONTRACT_TEMPLET_INFO"
    
)
public class ScContractTempletInfo  implements java.io.Serializable {


     private String contractTempletInfoId;
     private ScContractTempletHis scContractTempletHis;
     private ScContractTemplet scContractTemplet;
     private String contractName;
     private String resApproveInfoId;
     private String resApproveInfoNo;
     private String statusCd;
     private String contractNo;
     private String inviteNo;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Byte isstandard;
     private Byte isDel;
    

	private Date updatedDate;
     private long recordVersion;
     private String projectCd;
     private String projectName;
     private String contractPrice;
     private String approveNo;
     private String approveId;
     private String approveNo1;
     private String approveId1;
     private String approveNo2;
     private String approveId2;
     private String approveNo3;
     private String approveId3;
     private String contNo;
     private String contID;
     private List<ScContractPrint> scContractPrints = new ArrayList<ScContractPrint>();
     private List<ScContractTempletHis> scContractTempletHises = new ArrayList<ScContractTempletHis>();
     private List<ScContractTempletFill> scContractTempletFills = new ArrayList<ScContractTempletFill>();
     private List<ScContractInfoFlow> scContractInfoFlow = new ArrayList<ScContractInfoFlow>();
     private List<ScContractTempletUser> scContractTempletUser = new ArrayList<ScContractTempletUser>();
     private List<ScContractInfoAttach> scContractInfoAttachs = new ArrayList<ScContractInfoAttach>();
     private List<ScContractInfoSay> scContractInfoSaies = new ArrayList<ScContractInfoSay>();

    public ScContractTempletInfo() {
    }

	
    public ScContractTempletInfo(String contractTempletInfoId, ScContractTemplet scContractTemplet, long recordVersion) {
        this.contractTempletInfoId = contractTempletInfoId;
        this.scContractTemplet = scContractTemplet;
        this.recordVersion = recordVersion;
    }
    public ScContractTempletInfo(String contractTempletInfoId, ScContractTempletHis scContractTempletHis, ScContractTemplet scContractTemplet, String contractName, String resApproveInfoId, String resApproveInfoNo, String statusCd, String contractNo,String inviteNo, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, List<ScContractPrint> scContractPrints, List<ScContractTempletHis> scContractTempletHises, List<ScContractTempletFill> scContractTempletFills,String contractPrice,String approveNo,String approveId,String approveNo1,String approveId1,String approveNo2,String approveId2,String approveNo3,String approveId3, String contNo, String contID) {
       this.contractTempletInfoId = contractTempletInfoId;
       this.scContractTempletHis = scContractTempletHis;
       this.scContractTemplet = scContractTemplet;
       this.contractName = contractName;
       this.resApproveInfoId = resApproveInfoId;
       this.resApproveInfoNo = resApproveInfoNo;
       this.statusCd = statusCd;
       this.contractNo = contractNo;
       this.inviteNo = inviteNo;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.scContractPrints = scContractPrints;
       this.scContractTempletHises = scContractTempletHises;
       this.scContractTempletFills = scContractTempletFills;
       this.contractPrice = contractPrice;
       this.approveNo = approveNo;
       this.approveId = approveId;
       this.approveNo1 = approveNo1;
       this.approveId1 = approveId1;
       this.approveNo2 = approveNo2;
       this.approveId2 = approveId2;
       this.approveNo3 = approveNo3;
       this.approveId3 = approveId3;
       this.contNo = contNo;
       this.contID = contID;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="CONTRACT_TEMPLET_INFO_ID", unique=true, nullable=false, length=50)
    public String getContractTempletInfoId() {
        return this.contractTempletInfoId;
    }
    
    public void setContractTempletInfoId(String contractTempletInfoId) {
        this.contractTempletInfoId = contractTempletInfoId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRACT_TEMPLET_HIS_ID")
    public ScContractTempletHis getScContractTempletHis() {
        return this.scContractTempletHis;
    }
    
    public void setScContractTempletHis(ScContractTempletHis scContractTempletHis) {
        this.scContractTempletHis = scContractTempletHis;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRACT_TEMPLET_ID", nullable=false)
    public ScContractTemplet getScContractTemplet() {
        return this.scContractTemplet;
    }
    
    public void setScContractTemplet(ScContractTemplet scContractTemplet) {
        this.scContractTemplet = scContractTemplet;
    }
    
    @Column(name="CONTRACT_NAME", length=200)
    public String getContractName() {
        return this.contractName;
    }
    
    public void setContractName(String contractName) {
        this.contractName = contractName;
    }
    
    @Column(name="RES_APPROVE_INFO_ID", length=50)
    public String getResApproveInfoId() {
        return this.resApproveInfoId;
    }
    
    public void setResApproveInfoId(String resApproveInfoId) {
        this.resApproveInfoId = resApproveInfoId;
    }

    @Column(name="RES_APPROVE_INFO_NO", length=50)
    public String getResApproveInfoNo() {
        return this.resApproveInfoNo;
    }
    
    public void setResApproveInfoNo(String resApproveInfoNo) {
        this.resApproveInfoNo = resApproveInfoNo;
    }
    
    @Column(name="STATUS_CD", length=20)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }
    
    @Column(name="CONTRACT_NO", length=30)
    public String getContractNo() {
        return this.contractNo;
    }
    
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo;
    }
    
    @Column(name="INVITE_NO", length=30)
    public String getInviteNo() {
        return this.inviteNo;
    }
    
    public void setInviteNo(String inviteNo) {
        this.inviteNo = inviteNo;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="scContractTempletInfo")
    @BatchSize(size=10)
public List<ScContractPrint> getScContractPrints() {
        return this.scContractPrints;
    }
    
    public void setScContractPrints(List<ScContractPrint> scContractPrints) {
        this.scContractPrints = scContractPrints;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="scContractTempletInfo")
    @BatchSize(size=10)
public List<ScContractTempletHis> getScContractTempletHises() {
        return this.scContractTempletHises;
    }
    
    public void setScContractTempletHises(List<ScContractTempletHis> scContractTempletHises) {
        this.scContractTempletHises = scContractTempletHises;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="scContractTempletInfo")
    @BatchSize(size=10)
public List<ScContractTempletFill> getScContractTempletFills() {
        return this.scContractTempletFills;
    }
    
    public void setScContractTempletFills(List<ScContractTempletFill> scContractTempletFills) {
        this.scContractTempletFills = scContractTempletFills;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="scContractTempletInfo")
    @BatchSize(size=10)
    public List<ScContractTempletUser> getScContractTempletUser() {
        return this.scContractTempletUser;
    }
    
    public void setScContractTempletUser(List<ScContractTempletUser> scContractTempletUser) {
        this.scContractTempletUser = scContractTempletUser;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="scContractTempletInfo")
    @BatchSize(size=10)
    @OrderBy(clause="CREATED_DATE DESC")
public List<ScContractInfoFlow> getScContractInfoFlow() {
        return this.scContractInfoFlow;
    }
    
    public void setScContractInfoFlow(List<ScContractInfoFlow> scContractInfoFlow) {
        this.scContractInfoFlow = scContractInfoFlow;
    }

    @Column(name="PROJECT_CD", length=50)
    public String getProjectCd() {
        return this.projectCd;
    }
    
    public void setProjectCd(String projectCd) {
        this.projectCd = projectCd;
    }
    
    @Column(name="PROJECT_NAME", length=50)
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="scContractTempletInfo")
    @BatchSize(size=10)
    public List<ScContractInfoAttach> getScContractInfoAttachs() {
        return this.scContractInfoAttachs;
    }
    
    public void setScContractInfoAttachs(List<ScContractInfoAttach> scContractInfoAttachs) {
        this.scContractInfoAttachs = scContractInfoAttachs;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="scContractTempletInfo")
    @BatchSize(size=10)
    public List<ScContractInfoSay> getScContractInfoSaies() {
        return this.scContractInfoSaies;
    }
    
    public void setScContractInfoSaies(List<ScContractInfoSay> scContractInfoSaies) {
        this.scContractInfoSaies = scContractInfoSaies;
    }

    /**
	 * @return the isstandard
	 */
     @Column(name="ISSTANDARD", precision=2, scale=0)
	public Byte getIsstandard() {
		return isstandard;
	}


	/**
	 * @param isstandard the isstandard to set
	 */
	public void setIsstandard(Byte isstandard) {
		this.isstandard = isstandard;
	}

	
	 /**
	 * @return the isdel
	 */
	 @Column(name="IS_DEL", precision=2, scale=0)
	public Byte getIsDel() {
		return isDel;
	}


	/**
	 * @param isdel the isdel to set
	 */
	public void setIsDel(Byte isdel) {
		this.isDel = isdel;
	}


	/**
	 * @return the contractPrice
	 */
	 @Column(name="CONTRACT_PRICE", length=30)
	public String getContractPrice() {
		return contractPrice;
	}


	/**
	 * @param contractPrice the contractPrice to set
	 */
	public void setContractPrice(String contractPrice) {
		this.contractPrice = contractPrice;
	}
	
	/**
	 * @return the approveNo
	 */
	 @Column(name="APPROVE_NO", length=30)
	public String getApproveNo() {
		return approveNo;
	}


	/**
	 * @param approveNo the approveNo to set
	 */
	public void setApproveNo(String approveNo) {
		this.approveNo = approveNo;
	}
	
	/**
	 * @return the approveNo1
	 */
	 @Column(name="APPROVE_NO1", length=100)
	public String getApproveNo1() {
		return approveNo1;
	}


	/**
	 * @param approveNo1 the approveNo1 to set
	 */
	public void setApproveNo1(String approveNo1) {
		this.approveNo1 = approveNo1;
	}

	/**
	 * @return the approveNo2
	 */
	 @Column(name="APPROVE_NO2", length=100)
	public String getApproveNo2() {
		return approveNo2;
	}


	/**
	 * @param approveNo2 the approveNo2 to set
	 */
	public void setApproveNo2(String approveNo2) {
		this.approveNo2 = approveNo2;
	}

	/**
	 * @return the approveNo3
	 */
	 @Column(name="APPROVE_NO3", length=100)
	public String getApproveNo3() {
		return approveNo3;
	}


	/**
	 * @param approveNo3 the approveNo3 to set
	 */
	public void setApproveNo3(String approveNo3) {
		this.approveNo3 = approveNo3;
	}

	/**
	 * @return the approveId
	 */
	 @Column(name="APPROVE_ID", length=30)
	public String getApproveId() {
		return approveId;
	}

	/**
	 * @param approveId the approveId to set
	 */
	public void setApproveId(String approveId) {
		this.approveId = approveId;
	}
	
	/**
	 * @return the approveId1
	 */
	 @Column(name="APPROVE_ID1", length=100)
	public String getApproveId1() {
		return approveId1;
	}

	/**
	 * @param approveId1 the approveId1 to set
	 */
	public void setApproveId1(String approveId1) {
		this.approveId1 = approveId1;
	}
	
	/**
	 * @return the approveId2
	 */
	 @Column(name="APPROVE_ID2", length=100)
	public String getApproveId2() {
		return approveId2;
	}

	/**
	 * @param approveId2 the approveId2 to set
	 */
	public void setApproveId2(String approveId2) {
		this.approveId2 = approveId2;
	}
	
	/**
	 * @return the approveId3
	 */
	 @Column(name="APPROVE_ID3", length=100)
	public String getApproveId3() {
		return approveId3;
	}


	/**
	 * @param approveId3 the approveId3 to set
	 */
	public void setApproveId3(String approveId3) {
		this.approveId3 = approveId3;
	}


	/**
	 * @return the contNo
	 */
	 @Column(name="CONT_NO", length=50)
	public String getContNo() {
		return contNo;
	}


	/**
	 * @param contNo the contNo to set
	 */
	public void setContNo(String contNo) {
		this.contNo = contNo;
	}


	/**
	 * @return the contID
	 */
	 @Column(name="CONT_ID", length=50)
	public String getContID() {
		return contID;
	}


	/**
	 * @param contID the contID to set
	 */
	public void setContID(String contID) {
		this.contID = contID;
	}

}


