// 
package com.hhz.ump.entity.sc;
// Generated 2012-2-23 18:19:11 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.BatchSize;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ScContractInfoSay generated by hbm2java
 */
@Entity
@Table(name="SC_CONTRACT_INFO_SAY"
    
)
public class ScContractInfoSay  implements java.io.Serializable {


     private String scContractInfoSayId;
     private ScContractTempletHis scContractTempletHis;
     private ScContractTempletInfo scContractTempletInfo;
     private Long sequenceNo;
     private String msgContent;
     private String quotetoConInfoSayId;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;

    public ScContractInfoSay() {
    }

	
    public ScContractInfoSay(String scContractInfoSayId, ScContractTempletHis scContractTempletHis, ScContractTempletInfo scContractTempletInfo, long recordVersion) {
        this.scContractInfoSayId = scContractInfoSayId;
        this.scContractTempletHis = scContractTempletHis;
        this.scContractTempletInfo = scContractTempletInfo;
        this.recordVersion = recordVersion;
    }
    public ScContractInfoSay(String scContractInfoSayId, ScContractTempletHis scContractTempletHis, ScContractTempletInfo scContractTempletInfo, Long sequenceNo, String msgContent, String quotetoConInfoSayId, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion) {
       this.scContractInfoSayId = scContractInfoSayId;
       this.scContractTempletHis = scContractTempletHis;
       this.scContractTempletInfo = scContractTempletInfo;
       this.sequenceNo = sequenceNo;
       this.msgContent = msgContent;
       this.quotetoConInfoSayId = quotetoConInfoSayId;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="SC_CONTRACT_INFO_SAY_ID", unique=true, nullable=false, length=50)
    public String getScContractInfoSayId() {
        return this.scContractInfoSayId;
    }
    
    public void setScContractInfoSayId(String scContractInfoSayId) {
        this.scContractInfoSayId = scContractInfoSayId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRACT_TEMPLET_HIS_ID", nullable=false)
    public ScContractTempletHis getScContractTempletHis() {
        return this.scContractTempletHis;
    }
    
    public void setScContractTempletHis(ScContractTempletHis scContractTempletHis) {
        this.scContractTempletHis = scContractTempletHis;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRACT_TEMPLET_INFO_ID", nullable=false)
    public ScContractTempletInfo getScContractTempletInfo() {
        return this.scContractTempletInfo;
    }
    
    public void setScContractTempletInfo(ScContractTempletInfo scContractTempletInfo) {
        this.scContractTempletInfo = scContractTempletInfo;
    }
    
    @Column(name="SEQUENCE_NO", precision=18, scale=0)
    public Long getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Long sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    
    @Column(name="MSG_CONTENT", length=1000)
    public String getMsgContent() {
        return this.msgContent;
    }
    
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent;
    }
    
    @Column(name="QUOTETO_CON_INFO_SAY_ID", length=50)
    public String getQuotetoConInfoSayId() {
        return this.quotetoConInfoSayId;
    }
    
    public void setQuotetoConInfoSayId(String quotetoConInfoSayId) {
        this.quotetoConInfoSayId = quotetoConInfoSayId;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }




}


