// 
package com.hhz.ump.entity.sc;
// Generated 2012-2-20 17:38:01 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * ScContractInfoFlow generated by hbm2java
 */
@Entity
@Table(name="SC_CONTRACT_INFO_FLOW"
    
)
public class ScContractInfoFlow  implements java.io.Serializable {


     private String scContractInfoFlowId;
     private String resApproveInfoId;
     private String approveCd;
     /**
	 * @return the approveCd
	 */
	public String getApproveCd() {
		return approveCd;
	}


	/**
	 * @param approveCd the approveCd to set
	 */
	public void setApproveCd(String approveCd) {
		this.approveCd = approveCd;
	}

	private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String contractTempletHisId;
     private ScContractTempletInfo scContractTempletInfo;

    public ScContractInfoFlow() {
    }

	
    public ScContractInfoFlow(String scContractInfoFlowId, long recordVersion, ScContractTempletInfo scContractTempletInfo) {
        this.scContractInfoFlowId = scContractInfoFlowId;
        this.recordVersion = recordVersion;
        this.scContractTempletInfo = scContractTempletInfo;
    }
    public ScContractInfoFlow(String scContractInfoFlowId, String resApproveInfoId, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, ScContractTempletInfo scContractTempletInfo) {
       this.scContractInfoFlowId = scContractInfoFlowId;
       this.resApproveInfoId = resApproveInfoId;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.scContractTempletInfo = scContractTempletInfo;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="SC_CONTRACT_INFO_FLOW_ID", unique=true, nullable=false, length=50)
    public String getScContractInfoFlowId() {
        return this.scContractInfoFlowId;
    }
    
    public void setScContractInfoFlowId(String scContractInfoFlowId) {
        this.scContractInfoFlowId = scContractInfoFlowId;
    }
    
    @Column(name="RES_APPROVE_INFO_ID", length=50)
    public String getResApproveInfoId() {
        return this.resApproveInfoId;
    }
    
    public void setResApproveInfoId(String resApproveInfoId) {
        this.resApproveInfoId = resApproveInfoId;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    
    @Column(name="CONTRACT_TEMPLET_HIS_ID", length=50)
    public String getContractTempletHisId() {
        return this.contractTempletHisId;
    }
    
    public void setContractTempletHisId(String contractTempletHisId) {
        this.contractTempletHisId = contractTempletHisId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRACT_TEMPLET_INFO_ID", nullable=false)
    public ScContractTempletInfo getScContractTempletInfo() {
        return this.scContractTempletInfo;
    }
    
    public void setScContractTempletInfo(ScContractTempletInfo scContractTempletInfo) {
        this.scContractTempletInfo = scContractTempletInfo;
    }




}


