{'data':[
{'resRightId':'工程','items':[{'func':'func4'},{'func':'func16'}]},
{'resRightId':'材料设备','items':[{'func':'func16'}]},
{'resRightId':'设计','items':[{'func':'func16'}]},
{'resRightId':'品牌策划、品牌市调','items':[{'func':'func16'}]},
{'resRightId':'战略','items':[{'func':'func16'},{'func':'func3'}]},
{'resRightId':'设备','items':[{'func':'func4'},{'func':'func16'}]},
{'resRightId':'经营物料','items':[{'func':'func4'},{'func':'func16'}]},
{'resRightId':'外包项目-保安、保洁、绿化','items':[{'func':'func4'},{'func':'func16'}]},
{'resRightId':'大型成套IT设备供应商','items':[{'func':'func16'}]},
{'resRightId':'日常IT设备供应商','items':[{'func':'func16'}]},
{'resRightId':'预算内','items':[{'func':'func16'},{'func':'func5_1'}]},
{'resRightId':'预算外','items':[{'func':'func16'},{'func':'func5_2'}]},
{'resRightId':'招标文件编号','items':[{'func':'func1'}]},
{'resRightId':'合同文本库','items':[{'func':'func1'}]},
{'authTypeCd':'ZB_ZBWJ_10','resRightName':'地产_工程','items':[{"func": "func1"},{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func9"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func14"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'ZB_ZBWJ_03','resRightName':'地产_材料设备','items':[{"func": "func1"},{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func14"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'ZB_ZBWJ_15','resRightName':'地产_设计','items':[{"func": "func1"},{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func14"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'ZB_ZBWJ_16','resRightName':'地产_营销 媒体','items':[{"func": "func1"},{"func": "func5"},{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func9"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func14"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'ZB_ZBWJ_19','resRightName':'地产_营销 策划','items':[{"func": "func1"},{"func": "func5"},{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func14"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'ZB_ZBWJ_31','resRightName':'地产_IT(大型)','items':[{"func": "func1"},{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func14"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'ZB_ZBWJ_35','resRightName':'地产_IT(日常)','items':[{"func": "func1"},{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func14"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'ZB_ZBWJ_91','resRightName':'地产_品牌策划','items':[{"func": "func1"},{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func14"},{"func": "func15"},{"func": "func16"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'ZB_ZBWJ_17','resRightName':'地产_战略','items':[{"func": "func2"},{"func": "func3"},{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func10"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func14"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'BLSY_ZCGL_ZB_10','resRightName':'商业集团_工程','items':[{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func14"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'BLSY_ZCGL_ZB_20','resRightName':'商业集团_设备','items':[{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'BLSY_ZCGL_ZB_30','resRightName':'商业集团_经营物料','items':[{"func": "func1"},{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'BLSY_ZCGL_ZB_40','resRightName':'商业集团_外包项目','items':[{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'SYGS_ZCGL_ZB_10','resRightName':'商业公司_工程','items':[{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func14"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'SYGS_ZCGL_ZB_20','resRightName':'商业公司_设备','items':[{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'SYGS_ZCGL_ZB_30','resRightName':'商业公司_经营物料','items':[{"func": "func1"},{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'SYGS_ZCGL_ZB_40','resRightName':'商业公司_外包项目','items':[{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'JD_ZCGL_ZB_10','resRightName':'酒店_HOE供应商','items':[{"func": "func1"},{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func14"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'JD_ZCGL_ZB_20','resRightName':'酒店_设计单位','items':[{"func": "func1"},{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func14"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'JD_ZCGL_ZB_30','resRightName':'酒店_工程承包商','items':[{"func": "func1"},{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func14"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]},
{'authTypeCd':'JD_ZCGL_ZB_40','resRightName':'酒店_材料设备供应商','items':[{"func": "func1"},{"func": "func6"},{"func": "func7"},{"func": "func8"},{"func": "func11"},{"func": "func12"},{"func": "func13"},{"func": "func14"},{"func": "func15"},{"func": "func17"},{"func": "func18"}]}
]}