// 
package com.hhz.ump.entity.mate;
// Generated 2011-8-4 11:53:15 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * MateCountBasic generated by hbm2java
 */
@Entity
@Table(name="MATE_COUNT_BASIC"
    ,schema="POWERDESK"
)
public class MateCountBasic  implements java.io.Serializable {


     private String mateCountBasicId;
     private String contNo;
     private String suppUnitName;
     private BigDecimal realSupplyAll;
     private Boolean instalBl;
     private BigDecimal budAdjust;
     private BigDecimal stockAll;
     private String projectCd;
     private BigDecimal countSupplyBud;
     private BigDecimal exeUnitRealUse;
     private BigDecimal budSupplyAll;
     private String realSupplyRate;
     private String ownerMaterialType;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String useStatus;
     private String contName;
     private BigDecimal endSupplyAll;
     private BigDecimal noClearAudit;
     private BigDecimal clearAudit;
     private String clearStatus;
     private String exeContNo;
     private String exeContName;
     private String exeUnitName;
     private List<MateCountDetail> mateCountDetails = new ArrayList<MateCountDetail>();

    public MateCountBasic() {
    }

	
    public MateCountBasic(String mateCountBasicId, long recordVersion) {
        this.mateCountBasicId = mateCountBasicId;
        this.recordVersion = recordVersion;
    }
    public MateCountBasic(String mateCountBasicId, String contNo, String suppUnitName, BigDecimal realSupplyAll, Boolean instalBl, BigDecimal budAdjust, BigDecimal stockAll, String projectCd, BigDecimal countSupplyBud, BigDecimal exeUnitRealUse, BigDecimal budSupplyAll, String realSupplyRate, String ownerMaterialType, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, String useStatus, String contName, BigDecimal endSupplyAll, BigDecimal noClearAudit, BigDecimal clearAudit, String clearStatus, String exeContNo, String exeContName, String exeUnitName, List<MateCountDetail> mateCountDetails) {
       this.mateCountBasicId = mateCountBasicId;
       this.contNo = contNo;
       this.suppUnitName = suppUnitName;
       this.realSupplyAll = realSupplyAll;
       this.instalBl = instalBl;
       this.budAdjust = budAdjust;
       this.stockAll = stockAll;
       this.projectCd = projectCd;
       this.countSupplyBud = countSupplyBud;
       this.exeUnitRealUse = exeUnitRealUse;
       this.budSupplyAll = budSupplyAll;
       this.realSupplyRate = realSupplyRate;
       this.ownerMaterialType = ownerMaterialType;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.useStatus = useStatus;
       this.contName = contName;
       this.endSupplyAll = endSupplyAll;
       this.noClearAudit = noClearAudit;
       this.clearAudit = clearAudit;
       this.clearStatus = clearStatus;
       this.exeContNo = exeContNo;
       this.exeContName = exeContName;
       this.exeUnitName = exeUnitName;
       this.mateCountDetails = mateCountDetails;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="MATE_COUNT_BASIC_ID", unique=true, nullable=false, length=50)
    public String getMateCountBasicId() {
        return this.mateCountBasicId;
    }
    
    public void setMateCountBasicId(String mateCountBasicId) {
        this.mateCountBasicId = mateCountBasicId;
    }
    
    @Column(name="CONT_NO", length=50)
    public String getContNo() {
        return this.contNo;
    }
    
    public void setContNo(String contNo) {
        this.contNo = contNo;
    }
    
    @Column(name="SUPP_UNIT_NAME", length=100)
    public String getSuppUnitName() {
        return this.suppUnitName;
    }
    
    public void setSuppUnitName(String suppUnitName) {
        this.suppUnitName = suppUnitName;
    }
    
    @Column(name="REAL_SUPPLY_ALL", precision=21, scale=3)
    public BigDecimal getRealSupplyAll() {
        return this.realSupplyAll;
    }
    
    public void setRealSupplyAll(BigDecimal realSupplyAll) {
        this.realSupplyAll = realSupplyAll;
    }
    
    @Column(name="INSTAL_BL", precision=1, scale=0)
    public Boolean getInstalBl() {
        return this.instalBl;
    }
    
    public void setInstalBl(Boolean instalBl) {
        this.instalBl = instalBl;
    }
    
    @Column(name="BUD_ADJUST", precision=15, scale=3)
    public BigDecimal getBudAdjust() {
        return this.budAdjust;
    }
    
    public void setBudAdjust(BigDecimal budAdjust) {
        this.budAdjust = budAdjust;
    }
    
    @Column(name="STOCK_ALL", precision=21, scale=3)
    public BigDecimal getStockAll() {
        return this.stockAll;
    }
    
    public void setStockAll(BigDecimal stockAll) {
        this.stockAll = stockAll;
    }
    
    @Column(name="PROJECT_CD", length=10)
    public String getProjectCd() {
        return this.projectCd;
    }
    
    public void setProjectCd(String projectCd) {
        this.projectCd = projectCd;
    }
    
    @Column(name="COUNT_SUPPLY_BUD", precision=15, scale=3)
    public BigDecimal getCountSupplyBud() {
        return this.countSupplyBud;
    }
    
    public void setCountSupplyBud(BigDecimal countSupplyBud) {
        this.countSupplyBud = countSupplyBud;
    }
    
    @Column(name="EXE_UNIT_REAL_USE", precision=21, scale=3)
    public BigDecimal getExeUnitRealUse() {
        return this.exeUnitRealUse;
    }
    
    public void setExeUnitRealUse(BigDecimal exeUnitRealUse) {
        this.exeUnitRealUse = exeUnitRealUse;
    }
    
    @Column(name="BUD_SUPPLY_ALL", precision=15, scale=3)
    public BigDecimal getBudSupplyAll() {
        return this.budSupplyAll;
    }
    
    public void setBudSupplyAll(BigDecimal budSupplyAll) {
        this.budSupplyAll = budSupplyAll;
    }
    
    @Column(name="REAL_SUPPLY_RATE", length=20)
    public String getRealSupplyRate() {
        return this.realSupplyRate;
    }
    
    public void setRealSupplyRate(String realSupplyRate) {
        this.realSupplyRate = realSupplyRate;
    }
    
    @Column(name="OWNER_MATERIAL_TYPE", length=10)
    public String getOwnerMaterialType() {
        return this.ownerMaterialType;
    }
    
    public void setOwnerMaterialType(String ownerMaterialType) {
        this.ownerMaterialType = ownerMaterialType;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="USE_STATUS", length=2)
    public String getUseStatus() {
        return this.useStatus;
    }
    
    public void setUseStatus(String useStatus) {
        this.useStatus = useStatus;
    }
    
    @Column(name="CONT_NAME", length=100)
    public String getContName() {
        return this.contName;
    }
    
    public void setContName(String contName) {
        this.contName = contName;
    }
    
    @Column(name="END_SUPPLY_ALL", precision=21, scale=3)
    public BigDecimal getEndSupplyAll() {
        return this.endSupplyAll;
    }
    
    public void setEndSupplyAll(BigDecimal endSupplyAll) {
        this.endSupplyAll = endSupplyAll;
    }
    
    @Column(name="NO_CLEAR_AUDIT", precision=21, scale=3)
    public BigDecimal getNoClearAudit() {
        return this.noClearAudit;
    }
    
    public void setNoClearAudit(BigDecimal noClearAudit) {
        this.noClearAudit = noClearAudit;
    }
    
    @Column(name="CLEAR_AUDIT", precision=21, scale=3)
    public BigDecimal getClearAudit() {
        return this.clearAudit;
    }
    
    public void setClearAudit(BigDecimal clearAudit) {
        this.clearAudit = clearAudit;
    }
    
    @Column(name="CLEAR_STATUS", length=2)
    public String getClearStatus() {
        return this.clearStatus;
    }
    
    public void setClearStatus(String clearStatus) {
        this.clearStatus = clearStatus;
    }
    
    @Column(name="EXE_CONT_NO", length=50)
    public String getExeContNo() {
        return this.exeContNo;
    }
    
    public void setExeContNo(String exeContNo) {
        this.exeContNo = exeContNo;
    }
    
    @Column(name="EXE_CONT_NAME", length=100)
    public String getExeContName() {
        return this.exeContName;
    }
    
    public void setExeContName(String exeContName) {
        this.exeContName = exeContName;
    }
    
    @Column(name="EXE_UNIT_NAME", length=100)
    public String getExeUnitName() {
        return this.exeUnitName;
    }
    
    public void setExeUnitName(String exeUnitName) {
        this.exeUnitName = exeUnitName;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="mateCountBasic")
    @BatchSize(size=10)
public List<MateCountDetail> getMateCountDetails() {
        return this.mateCountDetails;
    }
    
    public void setMateCountDetails(List<MateCountDetail> mateCountDetails) {
        this.mateCountDetails = mateCountDetails;
    }




}


