// 
package com.hhz.ump.entity.fin;
// Generated 2010-8-4 11:02:15 by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * FinProjectAcctRel generated by hbm2java
 */
@Entity
@Table(name="FIN_PROJECT_ACCT_REL"
    
    , uniqueConstraints = @UniqueConstraint(columnNames={"ACCOUNT_NO", "FIN_PROJECT_ID"}) 
)
public class FinProjectAcctRel  implements java.io.Serializable {


     private String finProjectAcctRelId;
     private FinProject finProject;
     private String accountNo;
     private String projectCd;
     private String enableFlg;
     private String currencyCd;
     private String bankCd;
     private String bankName;
     private BigDecimal totalAmount;
     private String accountTypeCd;
     private BigDecimal balance;
     private String statusCd;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private String remark;
     private List<FinInOutDetail> finInOutDetails = new ArrayList<FinInOutDetail>();

    public FinProjectAcctRel() {
    }

	
    public FinProjectAcctRel(String finProjectAcctRelId, FinProject finProject, long recordVersion) {
        this.finProjectAcctRelId = finProjectAcctRelId;
        this.finProject = finProject;
        this.recordVersion = recordVersion;
    }
    public FinProjectAcctRel(String finProjectAcctRelId, FinProject finProject, String accountNo, String projectCd, String enableFlg, String currencyCd, String bankCd, String bankName, BigDecimal totalAmount, String accountTypeCd, BigDecimal balance, String statusCd, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion, String remark, List<FinInOutDetail> finInOutDetails) {
       this.finProjectAcctRelId = finProjectAcctRelId;
       this.finProject = finProject;
       this.accountNo = accountNo;
       this.projectCd = projectCd;
       this.enableFlg = enableFlg;
       this.currencyCd = currencyCd;
       this.bankCd = bankCd;
       this.bankName = bankName;
       this.totalAmount = totalAmount;
       this.accountTypeCd = accountTypeCd;
       this.balance = balance;
       this.statusCd = statusCd;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.remark = remark;
       this.finInOutDetails = finInOutDetails;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="FIN_PROJECT_ACCT_REL_ID", unique=true, nullable=false, length=50)
    public String getFinProjectAcctRelId() {
        return this.finProjectAcctRelId;
    }
    
    public void setFinProjectAcctRelId(String finProjectAcctRelId) {
        this.finProjectAcctRelId = finProjectAcctRelId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FIN_PROJECT_ID", nullable=false)
    public FinProject getFinProject() {
        return this.finProject;
    }
    
    public void setFinProject(FinProject finProject) {
        this.finProject = finProject;
    }

    
    @Column(name="ACCOUNT_NO", length=50)
    public String getAccountNo() {
        return this.accountNo;
    }
    
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    
    @Column(name="PROJECT_CD", length=20)
    public String getProjectCd() {
        return this.projectCd;
    }
    
    public void setProjectCd(String projectCd) {
        this.projectCd = projectCd;
    }

    
    @Column(name="ENABLE_FLG", length=1)
    public String getEnableFlg() {
        return this.enableFlg;
    }
    
    public void setEnableFlg(String enableFlg) {
        this.enableFlg = enableFlg;
    }

    
    @Column(name="CURRENCY_CD", length=20)
    public String getCurrencyCd() {
        return this.currencyCd;
    }
    
    public void setCurrencyCd(String currencyCd) {
        this.currencyCd = currencyCd;
    }

    
    @Column(name="BANK_CD", length=20)
    public String getBankCd() {
        return this.bankCd;
    }
    
    public void setBankCd(String bankCd) {
        this.bankCd = bankCd;
    }

    
    @Column(name="BANK_NAME", length=50)
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    
    @Column(name="TOTAL_AMOUNT")
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    
    @Column(name="ACCOUNT_TYPE_CD", length=5)
    public String getAccountTypeCd() {
        return this.accountTypeCd;
    }
    
    public void setAccountTypeCd(String accountTypeCd) {
        this.accountTypeCd = accountTypeCd;
    }

    
    @Column(name="BALANCE", precision=18, scale=4)
    public BigDecimal getBalance() {
        return this.balance;
    }
    
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    
    @Column(name="STATUS_CD", length=20)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="finProjectAcctRel")
    @BatchSize(size=10)
public List<FinInOutDetail> getFinInOutDetails() {
        return this.finInOutDetails;
    }
    
    public void setFinInOutDetails(List<FinInOutDetail> finInOutDetails) {
        this.finInOutDetails = finInOutDetails;
    }


    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }



}


