// 
package com.hhz.ump.entity.cont;
// Generated 2011-5-31 16:09:18 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OrderBy;

/**
 * ContLedger generated by hbm2java
 */
@Entity
@Table(name="CONT_LEDGER"
    
)
public class ContLedger  implements java.io.Serializable {


     private String contLedgerId;
     private String contNo;
     private String projectCd;
     private String contTypeCd;
     private String contTypeCd2;
     private String contName;
     private String partA;
     private String partATel;
     private String partB;
     private String partBTel;
     private String partC;
     private String partCTel;
     private String section;
     private String period;
     private String rangeNum;
     private BigDecimal totalPrice;
     private BigDecimal totalPriceParta;
     private String contProperty;
     private BigDecimal downRate;
     private String payWay;
     private BigDecimal payPercent;
     private BigDecimal repairPercent;
     private BigDecimal perfBond;
     private String perfBank;
     private String agreeAttaId;
     private String specialAttaId;
     private String clearAttaId;
     private BigDecimal visaTotal;
     private BigDecimal agreeTotal;
     private BigDecimal updateTotal;
     private BigDecimal clearPrice;
     private BigDecimal clearPriceParta;
     private BigDecimal payRate;
     private Date contStatusDate;
     private Date statusDate;
     private String contStatus;
     private Date planBeginDate;
     private Date planEndDate;
     private Date realBeginDate;
     private Date realEndDate;
     private Date guarBeginDate;
     private Date guarEndDate;
     private String repairAttaId;
     private String procStatus;
     private Integer delayDay;
     private String delayDesc;
     private String contPriceType;
     private String contAuditStatus;
     private BigDecimal updateRate;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private String createdCenterCd;
     private String createdPositionCd;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private String resApproveCd;
     private String resApproveId;
     private String targetCost;
     private String clearResApproveCd;
     private String clearResApproveId;
     private BigDecimal completeNum;
     private BigDecimal payNum;
     private String contractTempletInfoId;
     private String contractName;
     private String contractNo;
     private String contractTempletHisId;
     private List<ContVisaUpdate> contVisaUpdates = new ArrayList<ContVisaUpdate>();
     private List<ContPay> contPaies = new ArrayList<ContPay>();
     private List<ContSettlement> contSettlements = new ArrayList<ContSettlement>();
     private List<ContDelay> contDelaies = new ArrayList<ContDelay>();
     private List<ContGuarantee> contGuarantees = new ArrayList<ContGuarantee>();
     private List<ContRemark> contRemarks = new ArrayList<ContRemark>();
     private List<ContAddAgreement> contAddAgreements = new ArrayList<ContAddAgreement>();
     
     private String realProvName;
     private String strageFlg;
     private String enableFlg;

    public ContLedger() {
    }

	
    public ContLedger(String contLedgerId, String procStatus, long recordVersion) {
        this.contLedgerId = contLedgerId;
        this.procStatus = procStatus;
        this.recordVersion = recordVersion;
    }
    public ContLedger(String contLedgerId, String contNo, String projectCd, String contTypeCd, String contTypeCd2, String contName, String partA, String partATel, String partB, String partBTel, String section, String period, String rangeNum, BigDecimal totalPrice,BigDecimal totalPriceParta, String contProperty, BigDecimal downRate, String payWay, BigDecimal payPercent, BigDecimal repairPercent, BigDecimal perfBond, String perfBank, String agreeAttaId, String specialAttaId, String clearAttaId, BigDecimal visaTotal, BigDecimal agreeTotal, BigDecimal updateTotal, BigDecimal clearPrice,BigDecimal clearPriceParta, BigDecimal payRate, Date contStatusDate, Date statusDate, String contStatus, Date planBeginDate, Date planEndDate, Date realBeginDate, Date realEndDate, Date guarBeginDate, Date guarEndDate, String repairAttaId, String procStatus, Integer delayDay, String delayDesc, String contPriceType, String contAuditStatus, BigDecimal updateRate, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion, String createdCenterCd, String createdPositionCd, String updatedCenterCd, String updatedPositionCd,String resApproveCd,String resApproveId, List<ContVisaUpdate> contVisaUpdates, List<ContPay> contPaies, List<ContSettlement> contSettlements, List<ContDelay> contDelaies, List<ContGuarantee> contGuarantees, List<ContRemark> contRemarks, List<ContAddAgreement> contAddAgreements,String partC,String partCTel,String targetCost,String clearResApproveCd,String clearResApproveId,BigDecimal completeNum,BigDecimal payNum, String contractTempletInfoId, String contractName, String contractNo, String contractTempletHisId, String realProvName, String strageFlg,String enableFlg) {
       this.contLedgerId = contLedgerId;
       this.contNo = contNo;
       this.projectCd = projectCd;
       this.contTypeCd = contTypeCd;
       this.contTypeCd2 = contTypeCd2;
       this.contName = contName;
       this.partA = partA;
       this.partATel = partATel;
       this.partB = partB;
       this.partBTel = partBTel;
       this.section = section;
       this.period = period;
       this.rangeNum = rangeNum;
       this.totalPrice = totalPrice;
       this.totalPriceParta = totalPriceParta;
       this.contProperty = contProperty;
       this.downRate = downRate;
       this.payWay = payWay;
       this.payPercent = payPercent;
       this.repairPercent = repairPercent;
       this.perfBond = perfBond;
       this.perfBank = perfBank;
       this.agreeAttaId = agreeAttaId;
       this.specialAttaId = specialAttaId;
       this.clearAttaId = clearAttaId;
       this.visaTotal = visaTotal;
       this.agreeTotal = agreeTotal;
       this.updateTotal = updateTotal;
       this.clearPrice = clearPrice;
       this.clearPriceParta = clearPriceParta;
       this.payRate = payRate;
       this.contStatusDate = contStatusDate;
       this.statusDate = statusDate;
       this.contStatus = contStatus;
       this.planBeginDate = planBeginDate;
       this.planEndDate = planEndDate;
       this.realBeginDate = realBeginDate;
       this.realEndDate = realEndDate;
       this.guarBeginDate = guarBeginDate;
       this.guarEndDate = guarEndDate;
       this.repairAttaId = repairAttaId;
       this.procStatus = procStatus;
       this.delayDay = delayDay;
       this.delayDesc = delayDesc;
       this.contPriceType = contPriceType;
       this.contAuditStatus = contAuditStatus;
       this.updateRate = updateRate;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.contVisaUpdates = contVisaUpdates;
       this.contPaies = contPaies;
       this.contSettlements = contSettlements;
       this.contDelaies = contDelaies;
       this.contGuarantees = contGuarantees;
       this.contRemarks = contRemarks;
       this.contAddAgreements = contAddAgreements;
       this.partC = partC;
       this.partCTel = partCTel;
       this.resApproveCd = resApproveCd;
       this.resApproveId = resApproveId;
       this.targetCost = targetCost;
       this.clearResApproveCd = clearResApproveCd;
       this.clearResApproveId = clearResApproveId;
       this.completeNum = completeNum;
       this.payNum = payNum;
       this.contractTempletInfoId = contractTempletInfoId;
       this.contractName = contractName;
       this.contractNo = contractNo;
       this.contractTempletHisId = contractTempletHisId;
       this.realProvName = realProvName;
       this.strageFlg = strageFlg;
       this.enableFlg = enableFlg;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="CONT_LEDGER_ID", unique=true, nullable=false, length=50)
    public String getContLedgerId() {
        return this.contLedgerId;
    }
    
    public void setContLedgerId(String contLedgerId) {
        this.contLedgerId = contLedgerId;
    }
    
    @Column(name="CONT_NO", length=50)
    public String getContNo() {
        return this.contNo;
    }
    
    public void setContNo(String contNo) {
        this.contNo = contNo;
    }
    
    @Column(name="PROJECT_CD", length=50)
    public String getProjectCd() {
        return this.projectCd;
    }
    
    public void setProjectCd(String projectCd) {
        this.projectCd = projectCd;
    }
    
    @Column(name="CONT_TYPE_CD", length=50)
    public String getContTypeCd() {
        return this.contTypeCd;
    }
    
    public void setContTypeCd(String contTypeCd) {
        this.contTypeCd = contTypeCd;
    }
    
    @Column(name="CONT_TYPE_CD2", length=50)
    public String getContTypeCd2() {
		return contTypeCd2;
	}


	public void setContTypeCd2(String contTypeCd2) {
		this.contTypeCd2 = contTypeCd2;
	}


	@Column(name="CONT_NAME", length=200)
    public String getContName() {
        return this.contName;
    }
    
    public void setContName(String contName) {
        this.contName = contName;
    }
    
    @Column(name="PART_A", length=100)
    public String getPartA() {
        return this.partA;
    }
    
    public void setPartA(String partA) {
        this.partA = partA;
    }
    
    @Column(name="PART_A_TEL", length=200)
    public String getPartATel() {
        return this.partATel;
    }
    
    public void setPartATel(String partATel) {
        this.partATel = partATel;
    }
    
    @Column(name="PART_B", length=100)
    public String getPartB() {
        return this.partB;
    }
    
    public void setPartB(String partB) {
        this.partB = partB;
    }
    
    @Column(name="PART_B_TEL", length=200)
    public String getPartBTel() {
        return this.partBTel;
    }
    
    public void setPartBTel(String partBTel) {
        this.partBTel = partBTel;
    }
    
    @Column(name="SECTION", length=100)
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }
    
    @Column(name="PERIOD", length=50)
    public String getPeriod() {
        return this.period;
    }
    
    public void setPeriod(String period) {
        this.period = period;
    }
    
    @Column(name="RANGE_NUM", length=100)
    public String getRangeNum() {
        return this.rangeNum;
    }
    
    public void setRangeNum(String rangeNum) {
        this.rangeNum = rangeNum;
    }

    @Column(name="TOTAL_PRICE", precision=18, scale=2)
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }
    @Column(name="TOTAL_PRICE_PARTA", precision=18, scale=2)
    public BigDecimal getTotalPriceParta() {
        return this.totalPriceParta;
    }
    
    public void setTotalPriceParta(BigDecimal totalPriceParta) {
        this.totalPriceParta = totalPriceParta;
    }
    
    @Column(name="CONT_PROPERTY", length=100)
    public String getContProperty() {
        return this.contProperty;
    }
    
    public void setContProperty(String contProperty) {
        this.contProperty = contProperty;
    }
    
    @Column(name="DOWN_RATE", precision=6, scale=3)
    public BigDecimal getDownRate() {
        return this.downRate;
    }
    
    public void setDownRate(BigDecimal downRate) {
        this.downRate = downRate;
    }
    
    @Column(name="PAY_WAY", length=200)
    public String getPayWay() {
        return this.payWay;
    }
    
    public void setPayWay(String payWay) {
        this.payWay = payWay;
    }
    
    @Column(name="PAY_PERCENT", precision=6, scale=3)
    public BigDecimal getPayPercent() {
        return this.payPercent;
    }
    
    public void setPayPercent(BigDecimal payPercent) {
        this.payPercent = payPercent;
    }
    
    @Column(name="REPAIR_PERCENT", precision=6, scale=3)
    public BigDecimal getRepairPercent() {
        return this.repairPercent;
    }
    
    public void setRepairPercent(BigDecimal repairPercent) {
        this.repairPercent = repairPercent;
    }
    
    @Column(name="PERF_BOND", precision=18, scale=2)
    public BigDecimal getPerfBond() {
        return this.perfBond;
    }
    
    public void setPerfBond(BigDecimal perfBond) {
        this.perfBond = perfBond;
    }
    
    @Column(name="PERF_BANK", length=50)
    public String getPerfBank() {
        return this.perfBank;
    }
    
    public void setPerfBank(String perfBank) {
        this.perfBank = perfBank;
    }
    
    @Column(name="AGREE_ATTA_ID", length=50)
    public String getAgreeAttaId() {
        return this.agreeAttaId;
    }
    
    public void setAgreeAttaId(String agreeAttaId) {
        this.agreeAttaId = agreeAttaId;
    }
    
    @Column(name="SPECIAL_ATTA_ID", length=50)
    public String getSpecialAttaId() {
        return this.specialAttaId;
    }
    
    public void setSpecialAttaId(String specialAttaId) {
        this.specialAttaId = specialAttaId;
    }
    
    @Column(name="CLEAR_ATTA_ID", length=50)
    public String getClearAttaId() {
        return this.clearAttaId;
    }
    
    public void setClearAttaId(String clearAttaId) {
        this.clearAttaId = clearAttaId;
    }
    
    @Column(name="VISA_TOTAL", precision=18, scale=2)
    public BigDecimal getVisaTotal() {
        return this.visaTotal;
    }
    
    public void setVisaTotal(BigDecimal visaTotal) {
        this.visaTotal = visaTotal;
    }
    
    @Column(name="AGREE_TOTAL", precision=18, scale=2)
    public BigDecimal getAgreeTotal() {
        return this.agreeTotal;
    }
    
    public void setAgreeTotal(BigDecimal agreeTotal) {
        this.agreeTotal = agreeTotal;
    }
    
    @Column(name="UPDATE_TOTAL", precision=18, scale=2)
    public BigDecimal getUpdateTotal() {
        return this.updateTotal;
    }
    
    public void setUpdateTotal(BigDecimal updateTotal) {
        this.updateTotal = updateTotal;
    }

    @Column(name="CLEAR_PRICE", precision=18, scale=2)
    public BigDecimal getClearPrice() {
        return this.clearPrice;
    }
    
    public void setClearPrice(BigDecimal clearPrice) {
        this.clearPrice = clearPrice;
    }
    @Column(name="CLEAR_PRICE_PARTA", precision=18, scale=2)
    public BigDecimal getClearPriceParta() {
        return this.clearPriceParta;
    }
    
    public void setClearPriceParta(BigDecimal clearPriceParta) {
        this.clearPriceParta = clearPriceParta;
    }
    
    @Column(name="PAY_RATE", precision=6, scale=3)
    public BigDecimal getPayRate() {
        return this.payRate;
    }
    
    public void setPayRate(BigDecimal payRate) {
        this.payRate = payRate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CONT_STATUS_DATE", length=7)
    public Date getContStatusDate() {
        return this.contStatusDate;
    }
    
    public void setContStatusDate(Date contStatusDate) {
        this.contStatusDate = contStatusDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="STATUS_DATE", length=7)
    public Date getStatusDate() {
        return this.statusDate;
    }
    
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }
    
    @Column(name="CONT_STATUS", length=1)
    public String getContStatus() {
        return this.contStatus;
    }
    
    public void setContStatus(String contStatus) {
        this.contStatus = contStatus;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PLAN_BEGIN_DATE", length=7)
    public Date getPlanBeginDate() {
        return this.planBeginDate;
    }
    
    public void setPlanBeginDate(Date planBeginDate) {
        this.planBeginDate = planBeginDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PLAN_END_DATE", length=7)
    public Date getPlanEndDate() {
        return this.planEndDate;
    }
    
    public void setPlanEndDate(Date planEndDate) {
        this.planEndDate = planEndDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REAL_BEGIN_DATE", length=7)
    public Date getRealBeginDate() {
        return this.realBeginDate;
    }
    
    public void setRealBeginDate(Date realBeginDate) {
        this.realBeginDate = realBeginDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REAL_END_DATE", length=7)
    public Date getRealEndDate() {
        return this.realEndDate;
    }
    
    public void setRealEndDate(Date realEndDate) {
        this.realEndDate = realEndDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="GUAR_BEGIN_DATE", length=7)
    public Date getGuarBeginDate() {
        return this.guarBeginDate;
    }
    
    public void setGuarBeginDate(Date guarBeginDate) {
        this.guarBeginDate = guarBeginDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="GUAR_END_DATE", length=7)
    public Date getGuarEndDate() {
        return this.guarEndDate;
    }
    
    public void setGuarEndDate(Date guarEndDate) {
        this.guarEndDate = guarEndDate;
    }
    
    @Column(name="REPAIR_ATTA_ID", length=50)
    public String getRepairAttaId() {
        return this.repairAttaId;
    }
    
    public void setRepairAttaId(String repairAttaId) {
        this.repairAttaId = repairAttaId;
    }
    
    @Column(name="PROC_STATUS", nullable=false, length=5)
    public String getProcStatus() {
        return this.procStatus;
    }
    
    public void setProcStatus(String procStatus) {
        this.procStatus = procStatus;
    }
    
    @Column(name="DELAY_DAY", precision=5, scale=0)
    public Integer getDelayDay() {
        return this.delayDay;
    }
    
    public void setDelayDay(Integer delayDay) {
        this.delayDay = delayDay;
    }
    
    @Column(name="DELAY_DESC", length=1000)
    public String getDelayDesc() {
        return this.delayDesc;
    }
    
    public void setDelayDesc(String delayDesc) {
        this.delayDesc = delayDesc;
    }
    
    @Column(name="CONT_PRICE_TYPE", length=1)
    public String getContPriceType() {
        return this.contPriceType;
    }
    
    public void setContPriceType(String contPriceType) {
        this.contPriceType = contPriceType;
    }
    
    @Column(name="CONT_AUDIT_STATUS", length=1)
    public String getContAuditStatus() {
        return this.contAuditStatus;
    }
    
    public void setContAuditStatus(String contAuditStatus) {
        this.contAuditStatus = contAuditStatus;
    }
    
    @Column(name="UPDATE_RATE", precision=18, scale=2)
    public BigDecimal getUpdateRate() {
        return this.updateRate;
    }
    
    public void setUpdateRate(BigDecimal updateRate) {
        this.updateRate = updateRate;
    }
    
    @Column(name="REMARK", length=4000)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="contLedger")
    @BatchSize(size=100)
	@OrderBy(clause="CREATED_DATE asc")
public List<ContVisaUpdate> getContVisaUpdates() {
        return this.contVisaUpdates;
    }
    
    public void setContVisaUpdates(List<ContVisaUpdate> contVisaUpdates) {
        this.contVisaUpdates = contVisaUpdates;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="contLedger")
    @BatchSize(size=100)
	@OrderBy(clause="CREATED_DATE asc")
public List<ContPay> getContPaies() {
        return this.contPaies;
    }
    
    public void setContPaies(List<ContPay> contPaies) {
        this.contPaies = contPaies;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="contLedger")
    @BatchSize(size=100)
	@OrderBy(clause="CREATED_DATE asc")
public List<ContSettlement> getContSettlements() {
        return this.contSettlements;
    }
    
    public void setContSettlements(List<ContSettlement> contSettlements) {
        this.contSettlements = contSettlements;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="contLedger")
    @BatchSize(size=100)
	@OrderBy(clause="CREATED_DATE asc")
public List<ContDelay> getContDelaies() {
        return this.contDelaies;
    }
    
    public void setContDelaies(List<ContDelay> contDelaies) {
        this.contDelaies = contDelaies;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="contLedger")
    @BatchSize(size=10)
	@OrderBy(clause="CREATED_DATE asc")
public List<ContGuarantee> getContGuarantees() {
        return this.contGuarantees;
    }
    
    public void setContGuarantees(List<ContGuarantee> contGuarantees) {
        this.contGuarantees = contGuarantees;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="contLedger")
    @BatchSize(size=10)
    @OrderBy(clause="CREATED_DATE asc")
public List<ContRemark> getContRemarks() {
        return this.contRemarks;
    }
    
    public void setContRemarks(List<ContRemark> contRemarks) {
        this.contRemarks = contRemarks;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="contLedger")
    @BatchSize(size=10)
	@OrderBy(clause="CREATED_DATE asc")
public List<ContAddAgreement> getContAddAgreements() {
        return this.contAddAgreements;
    }
    
    public void setContAddAgreements(List<ContAddAgreement> contAddAgreements) {
        this.contAddAgreements = contAddAgreements;
    }

    @Column(name="PART_C", length=100)
	public String getPartC() {
		return partC;
	}


	public void setPartC(String partC) {
		this.partC = partC;
	}

	 @Column(name="PART_C_TEL", length=200)
	public String getPartCTel() {
		return partCTel;
	}


	public void setPartCTel(String partCTel) {
		this.partCTel = partCTel;
	}

	@Column(name="RES_APPROVE_CD", length=50)
	public String getResApproveCd() {
		return resApproveCd;
	}


	public void setResApproveCd(String resApproveCd) {
		this.resApproveCd = resApproveCd;
	}

	@Column(name="RES_APPROVE_ID", length=50)
	public String getResApproveId() {
		return resApproveId;
	}


	public void setResApproveId(String resApproveId) {
		this.resApproveId = resApproveId;
	}

	@Column(name="TARGET_COST", precision=18, scale=2)
	public String getTargetCost() {
		return targetCost;
	}


	public void setTargetCost(String targetCost) {
		this.targetCost = targetCost;
	}


	@Column(name="CLEAR_RES_APPROVE_CD", precision=50)
	public String getClearResApproveCd() {
		return clearResApproveCd;
	}


	public void setClearResApproveCd(String clearResApproveCd) {
		this.clearResApproveCd = clearResApproveCd;
	}

	@Column(name="CLEAR_RES_APPROVE_ID", precision=50)
	public String getClearResApproveId() {
		return clearResApproveId;
	}


	public void setClearResApproveId(String clearResApproveId) {
		this.clearResApproveId = clearResApproveId;
	}

	@Column(name="COMPLETE_NUM", precision=18, scale=2)
	public BigDecimal getCompleteNum() {
		return completeNum;
	}


	public void setCompleteNum(BigDecimal completeNum) {
		this.completeNum = completeNum;
	}

	@Column(name="PAY_NUM", precision=18, scale=2)
	public BigDecimal getPayNum() {
		return payNum;
	}


	public void setPayNum(BigDecimal payNum) {
		this.payNum = payNum;
	}
	
	@Column(name="CONTRACT_TEMPLET_INFO_ID", length=50)
    public String getContractTempletInfoId() {
        return this.contractTempletInfoId;
    }
    
    public void setContractTempletInfoId(String contractTempletInfoId) {
        this.contractTempletInfoId = contractTempletInfoId;
    }
    
    @Column(name="CONTRACT_NAME", length=200)
    public String getContractName() {
        return this.contractName;
    }
    
    public void setContractName(String contractName) {
        this.contractName = contractName;
    }
    
    @Column(name="CONTRACT_NO", length=50)
    public String getContractNo() {
        return this.contractNo;
    }
    
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo;
    }
    
    @Column(name="CONTRACT_TEMPLET_HIS_ID", length=50)
    public String getContractTempletHisId() {
        return this.contractTempletHisId;
    }
    
    public void setContractTempletHisId(String contractTempletHisId) {
        this.contractTempletHisId = contractTempletHisId;
    }

    @Column(name="REAL_PROV_NAME", length=100)
	public String getRealProvName() {
		return realProvName;
	}


	public void setRealProvName(String realProvName) {
		this.realProvName = realProvName;
	}

    @Column(name="STRAGE_FLG", length=1)
	public String getStrageFlg() {
		return strageFlg;
	}
	public void setStrageFlg(String strageFlg) {
		this.strageFlg = strageFlg;
	}

    @Column(name="ENABLE_FLG", length=1)
	public String getEnableFlg() {
		return enableFlg;
	}
	public void setEnableFlg(String enableFlg) {
		this.enableFlg = enableFlg;
	}
	
}


