// 
package com.hhz.ump.entity.cont;
// Generated 2010-12-2 14:55:08 by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * ContVisaUpdate generated by hbm2java
 */
@Entity
@Table(name="CONT_VISA_UPDATE"
    
)
public class ContVisaUpdate  implements java.io.Serializable {


     private String contVisaUpdateId;
     private ContLedger contLedger;
     private String visaUpdateNo;
     private BigDecimal amountUpdate;
     private String content;
     private String cause;
     private String attaBizId;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private BigDecimal prepareFee;
     private String resApproveCd;
     private String resApproveId;
     private String preVisaContent;//  PRE_VISA_CONTENT
     private String approveCheckId;

    public ContVisaUpdate() {
    }

	
    public ContVisaUpdate(String contVisaUpdateId, ContLedger contLedger, long recordVersion) {
        this.contVisaUpdateId = contVisaUpdateId;
        this.contLedger = contLedger;
        this.recordVersion = recordVersion;
    }
    public ContVisaUpdate(String contVisaUpdateId, ContLedger contLedger, String visaUpdateNo, BigDecimal amountUpdate, String content, String cause, String attaBizId, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion,BigDecimal prepareFee,String resApproveCd,String resApproveId,String preVisaContent,String approveCheckId) {
       this.contVisaUpdateId = contVisaUpdateId;
       this.contLedger = contLedger;
       this.visaUpdateNo = visaUpdateNo;
       this.amountUpdate = amountUpdate;
       this.content = content;
       this.cause = cause;
       this.attaBizId = attaBizId;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.prepareFee = prepareFee;
       this.resApproveCd = resApproveCd;
       this.resApproveId = resApproveId;
       this.preVisaContent = preVisaContent;
       this.approveCheckId = approveCheckId;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="CONT_VISA_UPDATE_ID", unique=true, nullable=false, length=50)
    public String getContVisaUpdateId() {
        return this.contVisaUpdateId;
    }
    
    public void setContVisaUpdateId(String contVisaUpdateId) {
        this.contVisaUpdateId = contVisaUpdateId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONT_LEDGER_ID", nullable=false)
    public ContLedger getContLedger() {
        return this.contLedger;
    }
    
    public void setContLedger(ContLedger contLedger) {
        this.contLedger = contLedger;
    }

    
    @Column(name="VISA_UPDATE_NO", length=50)
    public String getVisaUpdateNo() {
        return this.visaUpdateNo;
    }
    
    public void setVisaUpdateNo(String visaUpdateNo) {
        this.visaUpdateNo = visaUpdateNo;
    }

    
    @Column(name="AMOUNT_UPDATE", precision=18, scale=2)
    public BigDecimal getAmountUpdate() {
        return this.amountUpdate;
    }
    
    public void setAmountUpdate(BigDecimal amountUpdate) {
        this.amountUpdate = amountUpdate;
    }

    
    @Column(name="CONTENT", length=2000)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="CAUSE", length=200)
    public String getCause() {
        return this.cause;
    }
    
    public void setCause(String cause) {
        this.cause = cause;
    }

    
    @Column(name="ATTA_BIZ_ID", length=100)
    public String getAttaBizId() {
        return this.attaBizId;
    }
    
    public void setAttaBizId(String attaBizId) {
        this.attaBizId = attaBizId;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }


    @Column(name="PREPARE_FEE", precision=18, scale=2)
	public BigDecimal getPrepareFee() {
		return prepareFee;
	}


	public void setPrepareFee(BigDecimal prepareFee) {
		this.prepareFee = prepareFee;
	}


	@Column(name="RES_APPROVE_CD", length=50)
	public String getResApproveCd() {
		return resApproveCd;
	}


	public void setResApproveCd(String resApproveCd) {
		this.resApproveCd = resApproveCd;
	}


	@Column(name="RES_APPROVE_ID", length=50)
	public String getResApproveId() {
		return resApproveId;
	}


	public void setResApproveId(String resApproveId) {
		this.resApproveId = resApproveId;
	}

    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }

    @Column(name="PRE_VISA_CONTENT", length=400)
	public String getPreVisaContent() {
		return preVisaContent;
	}


	public void setPreVisaContent(String preVisaContent) {
		this.preVisaContent = preVisaContent;
	}

	@Column(name="APPROVE_CHECK_ID", length=50)
	public String getApproveCheckId() {
		return approveCheckId;
	}


	public void setApproveCheckId(String approveCheckId) {
		this.approveCheckId = approveCheckId;
	}




}


