// 
package com.hhz.ump.entity.cont;
// Generated 2011-5-31 16:09:18 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * ContGuarantee generated by hbm2java
 */
@Entity
@Table(name="CONT_GUARANTEE"
    
)
public class ContGuarantee  implements java.io.Serializable {


     private String contGuaranteeId;
     private ContLedger contLedger;
     private BigDecimal realGuarantee;
     private BigDecimal cutPayment;
     private BigDecimal leaveGuarantee;
     private BigDecimal payMoeny;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String resApproveCd;
     private String resApproveId;

    public ContGuarantee() {
    }

	
    public ContGuarantee(String contGuaranteeId, ContLedger contLedger, long recordVersion) {
        this.contGuaranteeId = contGuaranteeId;
        this.contLedger = contLedger;
        this.recordVersion = recordVersion;
    }
    public ContGuarantee(String contGuaranteeId, ContLedger contLedger, BigDecimal realGuarantee, BigDecimal cutPayment, BigDecimal leaveGuarantee, BigDecimal payMoeny, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, String resApproveCd, String resApproveId) {
       this.contGuaranteeId = contGuaranteeId;
       this.contLedger = contLedger;
       this.realGuarantee = realGuarantee;
       this.cutPayment = cutPayment;
       this.leaveGuarantee = leaveGuarantee;
       this.payMoeny = payMoeny;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.resApproveCd = resApproveCd;
       this.resApproveId = resApproveId;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="CONT_GUARANTEE_ID", unique=true, nullable=false, length=50)
    public String getContGuaranteeId() {
        return this.contGuaranteeId;
    }
    
    public void setContGuaranteeId(String contGuaranteeId) {
        this.contGuaranteeId = contGuaranteeId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONT_LEDGER_ID", nullable=false)
    public ContLedger getContLedger() {
        return this.contLedger;
    }
    
    public void setContLedger(ContLedger contLedger) {
        this.contLedger = contLedger;
    }
    
    @Column(name="REAL_GUARANTEE", precision=18, scale=2)
    public BigDecimal getRealGuarantee() {
        return this.realGuarantee;
    }
    
    public void setRealGuarantee(BigDecimal realGuarantee) {
        this.realGuarantee = realGuarantee;
    }
    
    @Column(name="CUT_PAYMENT", precision=18, scale=2)
    public BigDecimal getCutPayment() {
        return this.cutPayment;
    }
    
    public void setCutPayment(BigDecimal cutPayment) {
        this.cutPayment = cutPayment;
    }
    
    @Column(name="LEAVE_GUARANTEE", precision=18, scale=2)
    public BigDecimal getLeaveGuarantee() {
        return this.leaveGuarantee;
    }
    
    public void setLeaveGuarantee(BigDecimal leaveGuarantee) {
        this.leaveGuarantee = leaveGuarantee;
    }
    
    @Column(name="PAY_MOENY", precision=18, scale=2)
    public BigDecimal getPayMoeny() {
        return this.payMoeny;
    }
    
    public void setPayMoeny(BigDecimal payMoeny) {
        this.payMoeny = payMoeny;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="RES_APPROVE_CD", length=50)
    public String getResApproveCd() {
        return this.resApproveCd;
    }
    
    public void setResApproveCd(String resApproveCd) {
        this.resApproveCd = resApproveCd;
    }
    
    @Column(name="RES_APPROVE_ID", length=50)
    public String getResApproveId() {
        return this.resApproveId;
    }
    
    public void setResApproveId(String resApproveId) {
        this.resApproveId = resApproveId;
    }




}


