// 
package com.hhz.ump.entity.bis;
// Generated 2012-4-5 15:20:28 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * BisBudget generated by hbm2java
 */
@Entity
@Table(name="BIS_BUDGET"
    ,schema="POWERDESK"
)
public class BisBudget  implements java.io.Serializable {


     private String bisBudgetId;
     private BigDecimal propManage;
     private BigDecimal carParking;
     private BigDecimal carManage;
     private BigDecimal carTemporary;
     private BigDecimal multiTotal;
     private BigDecimal multiAdvert;
     private BigDecimal multiService;
     private BigDecimal multiRepair;
     private BigDecimal multiClean;
     private BigDecimal multiOther;
     private BigDecimal inviteMerchant;
     private BigDecimal inviteAgent;
     private BigDecimal inviteRent;
     private BigDecimal agencyRent;
     private BigDecimal agencyFund;
     private BigDecimal welfare;
     private BigDecimal otherPersonnel;	
     private BigDecimal administraFee;
     private BigDecimal travelFee;
     private BigDecimal businessServe;
     private BigDecimal adivertise;
     private BigDecimal inviteReward;
     private BigDecimal cleanHealthCost;
     private BigDecimal safeGuard;
     private BigDecimal afforeMainten;
     private BigDecimal engineerMainten;
     private BigDecimal energyCost;
     private BigDecimal otherPay;
     private BigDecimal capitalExpend;
     private BigDecimal salesExtra;
     private BigDecimal proxyRent;
     private BigDecimal setupProject;
     private BigDecimal prePayFee;
     private BigDecimal netProfit;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String bisProjectId;
     private String monthStr;
     private BigDecimal payTotal;
     private BigDecimal incomeTotal;
     private String yearStatus;
     private BigDecimal rentTotal;
     private BigDecimal salaryFareBiscost; //工资福利费(营业成本)SALARYFARE_BISCOST
     private BigDecimal salaryFareSales; //工资福利费(销售费用)SALARYFARE_SALES
     private BigDecimal parkCharge;      //停车场成本PARK_CHARGE
     private BigDecimal otherBisCost;    //其他营业成本OTHER_BISCOST
     private BigDecimal otherMgCharge;   //其他管理费用OTHER_MG_CHARGE
     private BigDecimal finacialCharge;  //财务费用FINANCIAL_CHARGE
     private BigDecimal bisProfit;    //营业利润BIS_PROFIT
     private BigDecimal bisIncome;  //加：营业外收入BIS_INCOME
     private BigDecimal bisExpense; //减：营业外支出BIS_EXPENSE
     private BigDecimal profitTotal; //利润总额PROFIT_TOTAL
     private BigDecimal incomeTax; //所得税INCOME_TAX
     private BigDecimal otherSaleCharge; // 其他销售费用
     private BigDecimal saleChargeTotal; //销售费用
    public BisBudget() {
    }

    public static void main(String[] args){
    	BisBudget  b = new BisBudget();
    	System.out.println("b="+b.inviteRent);
    }
	
    public BisBudget(String bisBudgetId, long recordVersion) {
        this.bisBudgetId = bisBudgetId;
        this.recordVersion = recordVersion;
    }
    public BisBudget(String bisBudgetId, BigDecimal propManage, BigDecimal carParking, BigDecimal carManage, BigDecimal carTemporary, BigDecimal multiTotal, BigDecimal multiAdvert, BigDecimal multiService, BigDecimal multiRepair, BigDecimal multiClean, BigDecimal multiOther, BigDecimal inviteMerchant, BigDecimal inviteAgent, BigDecimal inviteRent, BigDecimal agencyRent, BigDecimal agencyFund, BigDecimal welfare, BigDecimal otherPersonnel, BigDecimal administraFee, BigDecimal travelFee, BigDecimal businessServe, BigDecimal adivertise, BigDecimal inviteReward, BigDecimal cleanHealthCost, BigDecimal safeGuard, BigDecimal afforeMainten, BigDecimal engineerMainten, BigDecimal energyCost, BigDecimal otherPay, BigDecimal capitalExpend, BigDecimal salesExtra, BigDecimal proxyRent, BigDecimal setupProject, BigDecimal prePayFee, BigDecimal netProfit, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, String bisProjectId, String monthStr, BigDecimal payTotal, BigDecimal incomeTotal,String yearStatus,BigDecimal rentTotal,BigDecimal salaryFareBiscost,BigDecimal salaryFareSales,BigDecimal parkCharge,BigDecimal otherBisCost,BigDecimal otherMgCharge,BigDecimal finacialCharge,BigDecimal bisProfit,BigDecimal bisIncome,BigDecimal bisExpense,BigDecimal profitTotal,BigDecimal incomeTax,BigDecimal otherSaleCharge,BigDecimal saleChargeTotal) {
       this.bisBudgetId = bisBudgetId;
       this.propManage = propManage;
       this.carParking = carParking;
       this.carManage = carManage;
       this.carTemporary = carTemporary;
       this.multiTotal = multiTotal;
       this.multiAdvert = multiAdvert;
       this.multiService = multiService;
       this.multiRepair = multiRepair;
       this.multiClean = multiClean;
       this.multiOther = multiOther;
       this.inviteMerchant = inviteMerchant;
       this.inviteAgent = inviteAgent;
       this.inviteRent = inviteRent;
       this.agencyRent = agencyRent;
       this.agencyFund = agencyFund;
       this.welfare = welfare;
       this.otherPersonnel = otherPersonnel;
       this.administraFee = administraFee;
       this.travelFee = travelFee;
       this.businessServe = businessServe;
       this.adivertise = adivertise;
       this.inviteReward = inviteReward;
       this.cleanHealthCost = cleanHealthCost;
       this.safeGuard = safeGuard;
       this.afforeMainten = afforeMainten;
       this.engineerMainten = engineerMainten;
       this.energyCost = energyCost;
       this.otherPay = otherPay;
       this.capitalExpend = capitalExpend;
       this.salesExtra = salesExtra;
       this.proxyRent = proxyRent;
       this.setupProject = setupProject;
       this.prePayFee = prePayFee;
       this.netProfit = netProfit;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.bisProjectId = bisProjectId;
       this.monthStr = monthStr;
       this.payTotal = payTotal;
       this.incomeTotal = incomeTotal;
       this.yearStatus = yearStatus;
       this.rentTotal = rentTotal;
       //新增最新字段 author: wangming data:2012.6.6
       this.salaryFareBiscost = salaryFareBiscost;
       this.salaryFareSales = salaryFareSales;
       this.parkCharge = parkCharge;
       this.otherBisCost = otherBisCost;
       this.otherMgCharge = otherMgCharge;
       this.finacialCharge = finacialCharge;
       this.bisProfit = bisProfit;
       this.bisIncome = bisIncome;
       this.bisExpense = bisExpense;
       this.profitTotal = profitTotal;
       this.incomeTax = incomeTax;
       this.otherSaleCharge = otherSaleCharge;
       this.saleChargeTotal = saleChargeTotal;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_BUDGET_ID", unique=true, nullable=false, length=50)
    public String getBisBudgetId() {
        return this.bisBudgetId;
    }
    
    public void setBisBudgetId(String bisBudgetId) {
        this.bisBudgetId = bisBudgetId;
    }
    
    @Column(name="PROP_MANAGE", precision=14)
    public BigDecimal getPropManage() {
        return this.propManage;
    }
    
    public void setPropManage(BigDecimal propManage) {
        this.propManage = propManage;
    }
    
    @Column(name="CAR_PARKING", precision=14)
    public BigDecimal getCarParking() {
        return this.carParking;
    }
    
    public void setCarParking(BigDecimal carParking) {
        this.carParking = carParking;
    }
    
    @Column(name="CAR_MANAGE", precision=14)
    public BigDecimal getCarManage() {
        return this.carManage;
    }
    
    public void setCarManage(BigDecimal carManage) {
        this.carManage = carManage;
    }
    
    @Column(name="CAR_TEMPORARY", precision=14)
    public BigDecimal getCarTemporary() {
        return this.carTemporary;
    }
    
    public void setCarTemporary(BigDecimal carTemporary) {
        this.carTemporary = carTemporary;
    }
    
    @Column(name="MULTI_TOTAL", precision=14)
    public BigDecimal getMultiTotal() {
        return this.multiTotal;
    }
    
    public void setMultiTotal(BigDecimal multiTotal) {
        this.multiTotal = multiTotal;
    }
    
    @Column(name="MULTI_ADVERT", precision=14)
    public BigDecimal getMultiAdvert() {
        return this.multiAdvert;
    }
    
    public void setMultiAdvert(BigDecimal multiAdvert) {
        this.multiAdvert = multiAdvert;
    }
    
    @Column(name="MULTI_SERVICE", precision=14)
    public BigDecimal getMultiService() {
        return this.multiService;
    }
    
    public void setMultiService(BigDecimal multiService) {
        this.multiService = multiService;
    }
    
    @Column(name="MULTI_REPAIR", precision=14)
    public BigDecimal getMultiRepair() {
        return this.multiRepair;
    }
    
    public void setMultiRepair(BigDecimal multiRepair) {
        this.multiRepair = multiRepair;
    }
    
    @Column(name="MULTI_CLEAN", precision=14)
    public BigDecimal getMultiClean() {
        return this.multiClean;
    }
    
    public void setMultiClean(BigDecimal multiClean) {
        this.multiClean = multiClean;
    }
    
    @Column(name="MULTI_OTHER", precision=14)
    public BigDecimal getMultiOther() {
        return this.multiOther;
    }
    
    public void setMultiOther(BigDecimal multiOther) {
        this.multiOther = multiOther;
    }
    
    @Column(name="INVITE_MERCHANT", precision=14)
    public BigDecimal getInviteMerchant() {
        return this.inviteMerchant;
    }
    
    public void setInviteMerchant(BigDecimal inviteMerchant) {
        this.inviteMerchant = inviteMerchant;
    }
    
    @Column(name="INVITE_AGENT", precision=14)
    public BigDecimal getInviteAgent() {
        return this.inviteAgent;
    }
    
    public void setInviteAgent(BigDecimal inviteAgent) {
        this.inviteAgent = inviteAgent;
    }
    
    @Column(name="INVITE_RENT", precision=14)
    public BigDecimal getInviteRent() {
        return this.inviteRent;
    }
    
    public void setInviteRent(BigDecimal inviteRent) {
        this.inviteRent = inviteRent;
    }
    
    @Column(name="AGENCY_RENT", precision=14)
    public BigDecimal getAgencyRent() {
        return this.agencyRent;
    }
    
    public void setAgencyRent(BigDecimal agencyRent) {
        this.agencyRent = agencyRent;
    }
    
    @Column(name="AGENCY_FUND", precision=14)
    public BigDecimal getAgencyFund() {
        return this.agencyFund;
    }
    
    public void setAgencyFund(BigDecimal agencyFund) {
        this.agencyFund = agencyFund;
    }
    
    @Column(name="WELFARE", precision=14)
    public BigDecimal getWelfare() {
        return this.welfare;
    }
    
    public void setWelfare(BigDecimal welfare) {
        this.welfare = welfare;
    }
    
    @Column(name="OTHER_PERSONNEL", precision=14)
    public BigDecimal getOtherPersonnel() {
        return this.otherPersonnel;
    }
    
    public void setOtherPersonnel(BigDecimal otherPersonnel) {
        this.otherPersonnel = otherPersonnel;
    }
    
    @Column(name="ADMINISTRA_FEE", precision=14)
    public BigDecimal getAdministraFee() {
        return this.administraFee;
    }
    
    public void setAdministraFee(BigDecimal administraFee) {
        this.administraFee = administraFee;
    }
    
    @Column(name="TRAVEL_FEE", precision=14)
    public BigDecimal getTravelFee() {
        return this.travelFee;
    }
    
    public void setTravelFee(BigDecimal travelFee) {
        this.travelFee = travelFee;
    }
    
    @Column(name="BUSINESS_SERVE", precision=14)
    public BigDecimal getBusinessServe() {
        return this.businessServe;
    }
    
    public void setBusinessServe(BigDecimal businessServe) {
        this.businessServe = businessServe;
    }
    
    @Column(name="ADIVERTISE", precision=14)
    public BigDecimal getAdivertise() {
        return this.adivertise;
    }
    
    public void setAdivertise(BigDecimal adivertise) {
        this.adivertise = adivertise;
    }
    
    @Column(name="INVITE_REWARD", precision=14)
    public BigDecimal getInviteReward() {
        return this.inviteReward;
    }
    
    public void setInviteReward(BigDecimal inviteReward) {
        this.inviteReward = inviteReward;
    }
    
    @Column(name="CLEAN_HEALTH_COST", precision=14)
    public BigDecimal getCleanHealthCost() {
        return this.cleanHealthCost;
    }
    
    public void setCleanHealthCost(BigDecimal cleanHealthCost) {
        this.cleanHealthCost = cleanHealthCost;
    }
    
    @Column(name="SAFE_GUARD", precision=14)
    public BigDecimal getSafeGuard() {
        return this.safeGuard;
    }
    
    public void setSafeGuard(BigDecimal safeGuard) {
        this.safeGuard = safeGuard;
    }
    
    @Column(name="AFFORE_MAINTEN", precision=14)
    public BigDecimal getAfforeMainten() {
        return this.afforeMainten;
    }
    
    public void setAfforeMainten(BigDecimal afforeMainten) {
        this.afforeMainten = afforeMainten;
    }
    
    @Column(name="ENGINEER_MAINTEN", precision=14)
    public BigDecimal getEngineerMainten() {
        return this.engineerMainten;
    }
    
    public void setEngineerMainten(BigDecimal engineerMainten) {
        this.engineerMainten = engineerMainten;
    }
    
    @Column(name="ENERGY_COST", precision=14)
    public BigDecimal getEnergyCost() {
        return this.energyCost;
    }
    
    public void setEnergyCost(BigDecimal energyCost) {
        this.energyCost = energyCost;
    }
    
    @Column(name="OTHER_PAY", precision=14)
    public BigDecimal getOtherPay() {
        return this.otherPay;
    }
    
    public void setOtherPay(BigDecimal otherPay) {
        this.otherPay = otherPay;
    }
    
    @Column(name="CAPITAL_EXPEND", precision=14)
    public BigDecimal getCapitalExpend() {
        return this.capitalExpend;
    }
    
    public void setCapitalExpend(BigDecimal capitalExpend) {
        this.capitalExpend = capitalExpend;
    }
    
    @Column(name="SALES_EXTRA", precision=14)
    public BigDecimal getSalesExtra() {
        return this.salesExtra;
    }
    
    public void setSalesExtra(BigDecimal salesExtra) {
        this.salesExtra = salesExtra;
    }
    
    @Column(name="PROXY_RENT", precision=14)
    public BigDecimal getProxyRent() {
        return this.proxyRent;
    }
    
    public void setProxyRent(BigDecimal proxyRent) {
        this.proxyRent = proxyRent;
    }
    
    @Column(name="SETUP_PROJECT", precision=14)
    public BigDecimal getSetupProject() {
        return this.setupProject;
    }
    
    public void setSetupProject(BigDecimal setupProject) {
        this.setupProject = setupProject;
    }
    
    @Column(name="PRE_PAY_FEE", precision=14)
    public BigDecimal getPrePayFee() {
        return this.prePayFee;
    }
    
    public void setPrePayFee(BigDecimal prePayFee) {
        this.prePayFee = prePayFee;
    }
    
    @Column(name="NET_PROFIT", precision=14)
    public BigDecimal getNetProfit() {
        return this.netProfit;
    }
    
    public void setNetProfit(BigDecimal netProfit) {
        this.netProfit = netProfit;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="BIS_PROJECT_ID", length=50)
    public String getBisProjectId() {
        return this.bisProjectId;
    }
    
    public void setBisProjectId(String bisProjectId) {
        this.bisProjectId = bisProjectId;
    }
    
    @Column(name="MONTH_STR", length=7)
    public String getMonthStr() {
        return this.monthStr;
    }
    
    public void setMonthStr(String monthStr) {
        this.monthStr = monthStr;
    }
    
    @Column(name="PAY_TOTAL", precision=14)
    public BigDecimal getPayTotal() {
        return this.payTotal;
    }
    
    public void setPayTotal(BigDecimal payTotal) {
        this.payTotal = payTotal;
    }
    
    @Column(name="INCOME_TOTAL", precision=14)
    public BigDecimal getIncomeTotal() {
        return this.incomeTotal;
    }
    
    public void setIncomeTotal(BigDecimal incomeTotal) {
        this.incomeTotal = incomeTotal;
    }

    @Column(name="YEAR_STATUS", length=2)
	public String getYearStatus() {
		return yearStatus;
	}


	public void setYearStatus(String yearStatus) {
		this.yearStatus = yearStatus;
	}


	@Column(name="RENT_TOTAL", precision=14)
	public BigDecimal getRentTotal() {
		return rentTotal;
	}


	public void setRentTotal(BigDecimal rentTotal) {
		this.rentTotal = rentTotal;
	}

	
    @Column(name="SALARYFARE_BISCOST", precision=18)
	public BigDecimal getSalaryFareBiscost() {
		return salaryFareBiscost;
	}


	public void setSalaryFareBiscost(BigDecimal salaryFareBiscost) {
		this.salaryFareBiscost = salaryFareBiscost;
	}

	@Column(name="SALARYFARE_SALES", precision=18)
	public BigDecimal getSalaryFareSales() {
		return salaryFareSales;
	}


	public void setSalaryFareSales(BigDecimal salaryFareSales) {
		this.salaryFareSales = salaryFareSales;
	}

	@Column(name="PARK_CHARGE", precision=18)
	public BigDecimal getParkCharge() {
		return parkCharge;
	}


	public void setParkCharge(BigDecimal parkCharge) {
		this.parkCharge = parkCharge;
	}

	@Column(name="OTHER_BISCOST", precision=18)
	public BigDecimal getOtherBisCost() {
		return otherBisCost;
	}


	public void setOtherBisCost(BigDecimal otherBisCost) {
		this.otherBisCost = otherBisCost;
	}

	@Column(name="OTHER_MG_CHARGE", precision=18)
	public BigDecimal getOtherMgCharge() {
		return otherMgCharge;
	}


	public void setOtherMgCharge(BigDecimal otherMgCharge) {
		this.otherMgCharge = otherMgCharge;
	}

	@Column(name="FINANCIAL_CHARGE", precision=18)
	public BigDecimal getFinacialCharge() {
		return finacialCharge;
	}


	public void setFinacialCharge(BigDecimal finacialCharge) {
		this.finacialCharge = finacialCharge;
	}

	@Column(name="BIS_PROFIT", precision=18)
	public BigDecimal getBisProfit() {
		return bisProfit;
	}


	public void setBisProfit(BigDecimal bisProfit) {
		this.bisProfit = bisProfit;
	}

	@Column(name="BIS_INCOME", precision=18)
	public BigDecimal getBisIncome() {
		return bisIncome;
	}


	public void setBisIncome(BigDecimal bisIncome) {
		this.bisIncome = bisIncome;
	}

	@Column(name="BIS_EXPENSE", precision=18)
	public BigDecimal getBisExpense() {
		return bisExpense;
	}


	public void setBisExpense(BigDecimal bisExpense) {
		this.bisExpense = bisExpense;
	}

	@Column(name="PROFIT_TOTAL", precision=18)
	public BigDecimal getProfitTotal() {
		return profitTotal;
	}


	public void setProfitTotal(BigDecimal profitTotal) {
		this.profitTotal = profitTotal;
	}

	@Column(name="INCOME_TAX", precision=18)
	public BigDecimal getIncomeTax() {
		return incomeTax;
	}


	public void setIncomeTax(BigDecimal incomeTax) {
		this.incomeTax = incomeTax;
	}
	@Column(name="OTHER_SALE_CHARGE", precision=18)
	public BigDecimal getOtherSaleCharge() {
		return otherSaleCharge;
	}

	public void setOtherSaleCharge(BigDecimal otherSaleCharge) {
		this.otherSaleCharge = otherSaleCharge;
	}
	@Column(name="SALE_CHARGE_TOTAL", precision=18)
	public BigDecimal getSaleChargeTotal() {
		return saleChargeTotal;
	}

	public void setSaleChargeTotal(BigDecimal saleChargeTotal) {
		this.saleChargeTotal = saleChargeTotal;
	}
	
}


