// 
package com.hhz.ump.entity.bis;
// Generated 2011-8-3 22:32:28 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * BisContShopRent generated by hbm2java
 */
@Entity
@Table(name="BIS_CONT_SHOP_RENT"
    ,schema="POWERDESK"
)
public class BisContShopRent  implements java.io.Serializable {


     private String bisContShopRentId;
     private BisCont bisCont;
     private String storeNo;
     private String shopNameCn;
     private String freeRentPeriod;
     private String layoutCd;
     private String paymentModeCd;
     private String payCycleCd;
     private String payWay;
     private String payMonth;
     private String payDay;
     private String moneyScale;
     private BigDecimal earnestMoney;
     private BigDecimal rentUnit1;
     private BigDecimal rentUnit2;
     private BigDecimal rentUnit3;
     private BigDecimal rentUnit4;
     private BigDecimal rentUnit5;
     private BigDecimal rentUnit6;
     private BigDecimal rentUnit7;
     private BigDecimal rentUnit8;
     private BigDecimal rentUnit9;
     private BigDecimal rentUnit10;
     private BigDecimal rentMonth1;
     private BigDecimal rentMonth2;
     private BigDecimal rentMonth3;
     private BigDecimal rentMonth4;
     private BigDecimal rentMonth5;
     private BigDecimal rentMonth6;
     private BigDecimal rentMonth7;
     private BigDecimal rentMonth8;
     private BigDecimal rentMonth9;
     private BigDecimal rentMonth10;
     private String rentYears;
     private Date signTime;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;

    public BisContShopRent() {
    }

	
    public BisContShopRent(String bisContShopRentId, BisCont bisCont, String storeNo, long recordVersion) {
        this.bisContShopRentId = bisContShopRentId;
        this.bisCont = bisCont;
        this.storeNo = storeNo;
        this.recordVersion = recordVersion;
    }
    public BisContShopRent(String bisContShopRentId, BisCont bisCont, String storeNo, String shopNameCn, String freeRentPeriod, String layoutCd, String paymentModeCd, BigDecimal earnestMoney, BigDecimal rentUnit1, BigDecimal rentUnit2, BigDecimal rentUnit3, BigDecimal rentUnit4, BigDecimal rentUnit5, BigDecimal rentUnit6, BigDecimal rentUnit7, BigDecimal rentUnit8, BigDecimal rentUnit9, BigDecimal rentUnit10, BigDecimal rentMonth1, BigDecimal rentMonth2, BigDecimal rentMonth3, BigDecimal rentMonth4, BigDecimal rentMonth5, BigDecimal rentMonth6, BigDecimal rentMonth7, BigDecimal rentMonth8, BigDecimal rentMonth9, BigDecimal rentMonth10, String rentYears, Date signTime, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion) {
       this.bisContShopRentId = bisContShopRentId;
       this.bisCont = bisCont;
       this.storeNo = storeNo;
       this.shopNameCn = shopNameCn;
       this.freeRentPeriod = freeRentPeriod;
       this.layoutCd = layoutCd;
       this.paymentModeCd = paymentModeCd;
       this.earnestMoney = earnestMoney;
       this.rentUnit1 = rentUnit1;
       this.rentUnit2 = rentUnit2;
       this.rentUnit3 = rentUnit3;
       this.rentUnit4 = rentUnit4;
       this.rentUnit5 = rentUnit5;
       this.rentUnit6 = rentUnit6;
       this.rentUnit7 = rentUnit7;
       this.rentUnit8 = rentUnit8;
       this.rentUnit9 = rentUnit9;
       this.rentUnit10 = rentUnit10;
       this.rentMonth1 = rentMonth1;
       this.rentMonth2 = rentMonth2;
       this.rentMonth3 = rentMonth3;
       this.rentMonth4 = rentMonth4;
       this.rentMonth5 = rentMonth5;
       this.rentMonth6 = rentMonth6;
       this.rentMonth7 = rentMonth7;
       this.rentMonth8 = rentMonth8;
       this.rentMonth9 = rentMonth9;
       this.rentMonth10 = rentMonth10;
       this.rentYears = rentYears;
       this.signTime = signTime;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_CONT_SHOP_RENT_ID", unique=true, nullable=false, length=50)
    public String getBisContShopRentId() {
        return this.bisContShopRentId;
    }
    
    public void setBisContShopRentId(String bisContShopRentId) {
        this.bisContShopRentId = bisContShopRentId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIS_CONT_ID", nullable=false)
    public BisCont getBisCont() {
        return this.bisCont;
    }
    
    public void setBisCont(BisCont bisCont) {
        this.bisCont = bisCont;
    }
    
    @Column(name="STORE_NO", nullable=false, length=100)
    public String getStoreNo() {
        return this.storeNo;
    }
    
    public void setStoreNo(String storeNo) {
        this.storeNo = storeNo;
    }
    
    @Column(name="SHOP_NAME_CN", length=100)
    public String getShopNameCn() {
        return this.shopNameCn;
    }
    
    public void setShopNameCn(String shopNameCn) {
        this.shopNameCn = shopNameCn;
    }
    
    @Column(name="FREE_RENT_PERIOD", length=100)
    public String getFreeRentPeriod() {
        return this.freeRentPeriod;
    }
    
    public void setFreeRentPeriod(String freeRentPeriod) {
        this.freeRentPeriod = freeRentPeriod;
    }
    
    @Column(name="LAYOUT_CD", length=20)
    public String getLayoutCd() {
        return this.layoutCd;
    }
    
    public void setLayoutCd(String layoutCd) {
        this.layoutCd = layoutCd;
    }
    
    @Column(name="PAYMENT_MODE_CD", length=20)
    public String getPaymentModeCd() {
        return this.paymentModeCd;
    }
    
    public void setPaymentModeCd(String paymentModeCd) {
        this.paymentModeCd = paymentModeCd;
    }

    @Column(name="PAY_CYCLE_CD", length=20)
    public String getPayCycleCd() {
        return this.payCycleCd;
    }
    
    public void setPayCycleCd(String payCycleCd) {
        this.payCycleCd = payCycleCd;
    }

    @Column(name="PAY_WAY", length=20)
    public String getPayWay() {
        return this.payWay;
    }
    
    public void setPayWay(String payWay) {
        this.payWay = payWay;
    }
    
    @Column(name="PAY_MONTH", length=2)
    public String getPayMonth() {
		return payMonth;
	}

	public void setPayMonth(String payMonth) {
		this.payMonth = payMonth;
	}

	@Column(name="PAY_DAY", length=2)
    public String getPayDay() {
        return this.payDay;
    }
    
    public void setPayDay(String payDay) {
        this.payDay = payDay;
    }

    @Column(name="MONEY_SCALE", length=20)
    public String getMoneyScale() {
		return moneyScale;
	}

	public void setMoneyScale(String moneyScale) {
		this.moneyScale = moneyScale;
	}

	@Column(name="EARNEST_MONEY", precision=10)
    public BigDecimal getEarnestMoney() {
        return this.earnestMoney;
    }
    
    public void setEarnestMoney(BigDecimal earnestMoney) {
        this.earnestMoney = earnestMoney;
    }
    
    @Column(name="RENT_UNIT1", precision=10)
    public BigDecimal getRentUnit1() {
        return this.rentUnit1;
    }
    
    public void setRentUnit1(BigDecimal rentUnit1) {
        this.rentUnit1 = rentUnit1;
    }
    
    @Column(name="RENT_UNIT2", precision=10)
    public BigDecimal getRentUnit2() {
        return this.rentUnit2;
    }
    
    public void setRentUnit2(BigDecimal rentUnit2) {
        this.rentUnit2 = rentUnit2;
    }
    
    @Column(name="RENT_UNIT3", precision=10)
    public BigDecimal getRentUnit3() {
        return this.rentUnit3;
    }
    
    public void setRentUnit3(BigDecimal rentUnit3) {
        this.rentUnit3 = rentUnit3;
    }
    
    @Column(name="RENT_UNIT4", precision=10)
    public BigDecimal getRentUnit4() {
        return this.rentUnit4;
    }
    
    public void setRentUnit4(BigDecimal rentUnit4) {
        this.rentUnit4 = rentUnit4;
    }
    
    @Column(name="RENT_UNIT5", precision=10)
    public BigDecimal getRentUnit5() {
        return this.rentUnit5;
    }
    
    public void setRentUnit5(BigDecimal rentUnit5) {
        this.rentUnit5 = rentUnit5;
    }
    
    @Column(name="RENT_UNIT6", precision=10)
    public BigDecimal getRentUnit6() {
        return this.rentUnit6;
    }
    
    public void setRentUnit6(BigDecimal rentUnit6) {
        this.rentUnit6 = rentUnit6;
    }
    
    @Column(name="RENT_UNIT7", precision=10)
    public BigDecimal getRentUnit7() {
        return this.rentUnit7;
    }
    
    public void setRentUnit7(BigDecimal rentUnit7) {
        this.rentUnit7 = rentUnit7;
    }
    
    @Column(name="RENT_UNIT8", precision=10)
    public BigDecimal getRentUnit8() {
        return this.rentUnit8;
    }
    
    public void setRentUnit8(BigDecimal rentUnit8) {
        this.rentUnit8 = rentUnit8;
    }
    
    @Column(name="RENT_UNIT9", precision=10)
    public BigDecimal getRentUnit9() {
        return this.rentUnit9;
    }
    
    public void setRentUnit9(BigDecimal rentUnit9) {
        this.rentUnit9 = rentUnit9;
    }
    
    @Column(name="RENT_UNIT10", precision=10)
    public BigDecimal getRentUnit10() {
        return this.rentUnit10;
    }
    
    public void setRentUnit10(BigDecimal rentUnit10) {
        this.rentUnit10 = rentUnit10;
    }
    
    @Column(name="RENT_MONTH1", precision=10)
    public BigDecimal getRentMonth1() {
        return this.rentMonth1;
    }
    
    public void setRentMonth1(BigDecimal rentMonth1) {
        this.rentMonth1 = rentMonth1;
    }
    
    @Column(name="RENT_MONTH2", precision=10)
    public BigDecimal getRentMonth2() {
        return this.rentMonth2;
    }
    
    public void setRentMonth2(BigDecimal rentMonth2) {
        this.rentMonth2 = rentMonth2;
    }
    
    @Column(name="RENT_MONTH3", precision=10)
    public BigDecimal getRentMonth3() {
        return this.rentMonth3;
    }
    
    public void setRentMonth3(BigDecimal rentMonth3) {
        this.rentMonth3 = rentMonth3;
    }
    
    @Column(name="RENT_MONTH4", precision=10)
    public BigDecimal getRentMonth4() {
        return this.rentMonth4;
    }
    
    public void setRentMonth4(BigDecimal rentMonth4) {
        this.rentMonth4 = rentMonth4;
    }
    
    @Column(name="RENT_MONTH5", precision=10)
    public BigDecimal getRentMonth5() {
        return this.rentMonth5;
    }
    
    public void setRentMonth5(BigDecimal rentMonth5) {
        this.rentMonth5 = rentMonth5;
    }
    
    @Column(name="RENT_MONTH6", precision=10)
    public BigDecimal getRentMonth6() {
        return this.rentMonth6;
    }
    
    public void setRentMonth6(BigDecimal rentMonth6) {
        this.rentMonth6 = rentMonth6;
    }
    
    @Column(name="RENT_MONTH7", precision=10)
    public BigDecimal getRentMonth7() {
        return this.rentMonth7;
    }
    
    public void setRentMonth7(BigDecimal rentMonth7) {
        this.rentMonth7 = rentMonth7;
    }
    
    @Column(name="RENT_MONTH8", precision=10)
    public BigDecimal getRentMonth8() {
        return this.rentMonth8;
    }
    
    public void setRentMonth8(BigDecimal rentMonth8) {
        this.rentMonth8 = rentMonth8;
    }
    
    @Column(name="RENT_MONTH9", precision=10)
    public BigDecimal getRentMonth9() {
        return this.rentMonth9;
    }
    
    public void setRentMonth9(BigDecimal rentMonth9) {
        this.rentMonth9 = rentMonth9;
    }
    
    @Column(name="RENT_MONTH10", precision=10)
    public BigDecimal getRentMonth10() {
        return this.rentMonth10;
    }
    
    public void setRentMonth10(BigDecimal rentMonth10) {
        this.rentMonth10 = rentMonth10;
    }
    
    @Column(name="RENT_YEARS", length=50)
    public String getRentYears() {
        return this.rentYears;
    }
    
    public void setRentYears(String rentYears) {
        this.rentYears = rentYears;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SIGN_TIME", length=7)
    public Date getSignTime() {
        return this.signTime;
    }
    
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }




}


