// 
package com.hhz.ump.entity.bis;
// Generated 2011-8-12 15:06:32 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * BisContHis generated by hbm2java
 */
@Entity
@Table(name="BIS_CONT_HIS"
    ,schema="POWERDESK"
)
public class BisContHis  implements java.io.Serializable {


     private String bisContHisId;
     private String contNo;
     private String bisTenantId;
     private String bisProjectId;
     private String contName;
     private String bisPeople;
     private String brand;
     private String partyA;
     private String partyB;
     private String partyC;
     private String partyD;
     private String connAddr;
     private String connTel;
     private String connPeople;
     private String connFax;
     private String connAccountNo;
     private BigDecimal square;
     private BigDecimal innerSquare;
     private BigDecimal rentSquare;
     private String equityNature;
     private String buildingName;
     private Date rentDate;
     private Date contStartDate;
     private Date contEndDate;
     private Date contToFailDate;
     private String coopWayCd;
     private String contBigTypeCd;
     private String contSmallTypeCd;
     private BigDecimal contMoney;
     private Date signDate;
     private String contContent;
     private String checkUserCd;
     private Date checkDate;
     private String attachFlg;
     private boolean activeBl;
     private String statusCd;
     private String chargerTypeArr;
     private String bisContId;
     private String bisShopId;
     private String storeFlatIds;
     private String storeFlatNos;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String shopNameCn;
     private String freeRentPeriod;
     private String layoutCd;
     private String paymentModeCd;
     private String payCycleCd;
     private BigDecimal earnestMoney;
     private String rentYears;
     private Date signTime;
     private String backRentYears;
     private String contDeadline;
     private String beEntrustedRenter;
     private String paymentTime;
     private BigDecimal performanceBond;
     private BigDecimal operationBond;
     private BigDecimal integMoneyStandard;
     private Date integMoneyFirstRentDay;
     private String integMoneyFreeRentPeriod;
     private String entrRentYears;
     private String beEntrRenter;
     private String owner;
     private String idCardNo;
     private String housingTypeCd;
     private BigDecimal firstCycleMustRent;
     private BigDecimal propertyDerateMoney;
     private String renterName;
     private String operationProjectCd;
     private String operationArea;
     private BigDecimal contPromiseBond;
     private BigDecimal receivedBond;
     private BigDecimal sellPrice;
     private String manageCd;
     private BigDecimal rentUnit1;
     private BigDecimal rentUnit2;
     private BigDecimal rentUnit3;
     private BigDecimal rentUnit4;
     private BigDecimal rentUnit5;
     private BigDecimal rentUnit6;
     private BigDecimal rentUnit7;
     private BigDecimal rentUnit8;
     private BigDecimal rentUnit9;
     private BigDecimal rentUnit10;
     private BigDecimal rentMonth1;
     private BigDecimal rentMonth2;
     private BigDecimal rentMonth3;
     private BigDecimal rentMonth4;
     private BigDecimal rentMonth5;
     private BigDecimal rentMonth6;
     private BigDecimal rentMonth7;
     private BigDecimal rentMonth8;
     private BigDecimal rentMonth9;
     private BigDecimal rentMonth10;
     private BigDecimal rent1;
     private BigDecimal rent2;
     private BigDecimal rent3;
     private BigDecimal rent4;
     private BigDecimal rent5;
     private BigDecimal rent6;
     private BigDecimal rent7;
     private BigDecimal rent8;
     private BigDecimal rent9;
     private BigDecimal rent10;
     private BigDecimal rentRatio1;
     private BigDecimal rentRatio2;
     private BigDecimal rentRatio3;
     private BigDecimal rentRatio4;
     private BigDecimal rentRatio5;
     private BigDecimal rentRatio6;
     private BigDecimal rentRatio7;
     private BigDecimal rentRatio8;
     private BigDecimal rentRatio9;
     private BigDecimal rentRatio10;
     private BigDecimal manageFee1;
     private BigDecimal manageFee2;
     private BigDecimal manageFee3;
     private BigDecimal manageFee4;
     private BigDecimal manageFee5;
     private BigDecimal manageFee6;
     private BigDecimal manageFee7;
     private BigDecimal manageFee8;
     private BigDecimal manageFee9;
     private BigDecimal manageFee10;
     private Boolean inPoolBl;
     private String changeUser;
     private Date changeDate;
     private String chargeTypeCd;
     private String formula;
     private BigDecimal unitPrice;
     private BigDecimal formulaSquare;
     private BigDecimal countPrice;
     private BigDecimal totalPrice;
     private String payWay;
     private String payMonth;
     private String payDay;
     private String moneyScale;
     private String contApproval;
     private String contApprovalId;
     private String approvalAttachFlg;
     
     private List<BisContCreditHis> bisContCreditHises = new ArrayList<BisContCreditHis>();
     private List<BisContAddiHis> bisContAddiHises = new ArrayList<BisContAddiHis>();
     private List<BisMustRentHis> bisMustRentHises = new ArrayList<BisMustRentHis>();

    public BisContHis() {
    }

	
    public BisContHis(String bisContHisId, String contNo, String bisProjectId, Date contStartDate, Date contEndDate, boolean activeBl, String bisContId, long recordVersion) {
        this.bisContHisId = bisContHisId;
        this.contNo = contNo;
        this.bisProjectId = bisProjectId;
        this.contStartDate = contStartDate;
        this.contEndDate = contEndDate;
        this.activeBl = activeBl;
        this.bisContId = bisContId;
        this.recordVersion = recordVersion;
    }
    public BisContHis(String bisContHisId, String contNo, String bisTenantId, String bisProjectId, String contName, String bisPeople, String brand, String partyA, String partyB, String partyC, String partyD, String connAddr, String connTel, String connPeople, String connFax, String connAccountNo, BigDecimal square, BigDecimal innerSquare, BigDecimal rentSquare, String equityNature, String buildingName, Date rentDate, Date contStartDate, Date contEndDate, Date contToFailDate, String coopWayCd, String contBigTypeCd, String contSmallTypeCd, BigDecimal contMoney, Date signDate, String contContent, String checkUserCd, Date checkDate, String attachFlg, boolean activeBl, String statusCd, String chargerTypeArr, String bisContId, String bisShopId, String storeFlatIds, String storeFlatNos, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, String shopNameCn, String freeRentPeriod, String layoutCd, String paymentModeCd, BigDecimal earnestMoney, String rentYears, Date signTime, String backRentYears, String contDeadline, String beEntrustedRenter, String paymentTime, BigDecimal performanceBond, BigDecimal operationBond, BigDecimal integMoneyStandard, Date integMoneyFirstRentDay, String integMoneyFreeRentPeriod, String entrRentYears, String beEntrRenter, String owner, String idCardNo, String housingTypeCd, BigDecimal firstCycleMustRent, BigDecimal propertyDerateMoney, String renterName, String operationProjectCd, String operationArea, BigDecimal contPromiseBond, BigDecimal receivedBond, BigDecimal sellPrice, BigDecimal rentUnit1, BigDecimal rentUnit2, BigDecimal rentUnit3, BigDecimal rentUnit4, BigDecimal rentUnit5, BigDecimal rentUnit6, BigDecimal rentUnit7, BigDecimal rentUnit8, BigDecimal rentUnit9, BigDecimal rentUnit10, BigDecimal rentMonth1, BigDecimal rentMonth2, BigDecimal rentMonth3, BigDecimal rentMonth4, BigDecimal rentMonth5, BigDecimal rentMonth6, BigDecimal rentMonth7, BigDecimal rentMonth8, BigDecimal rentMonth9, BigDecimal rentMonth10, BigDecimal rent1, BigDecimal rent2, BigDecimal rent3, BigDecimal rent4, BigDecimal rent5, BigDecimal rent6, BigDecimal rent7, BigDecimal rent8, BigDecimal rent9, BigDecimal rent10, BigDecimal rentRatio1, BigDecimal rentRatio2, BigDecimal rentRatio3, BigDecimal rentRatio4, BigDecimal rentRatio5, BigDecimal rentRatio6, BigDecimal rentRatio7, BigDecimal rentRatio8, BigDecimal rentRatio9, BigDecimal rentRatio10, BigDecimal manageFee1, BigDecimal manageFee2, BigDecimal manageFee3, BigDecimal manageFee4, BigDecimal manageFee5, BigDecimal manageFee6, BigDecimal manageFee7, BigDecimal manageFee8, BigDecimal manageFee9, BigDecimal manageFee10, List<BisContCreditHis> bisContCreditHises, List<BisContAddiHis> bisContAddiHises) {
       this.bisContHisId = bisContHisId;
       this.contNo = contNo;
       this.bisTenantId = bisTenantId;
       this.bisProjectId = bisProjectId;
       this.contName = contName;
       this.bisPeople = bisPeople;
       this.brand = brand;
       this.partyA = partyA;
       this.partyB = partyB;
       this.partyC = partyC;
       this.partyD = partyD;
       this.connAddr = connAddr;
       this.connTel = connTel;
       this.connPeople = connPeople;
       this.connFax = connFax;
       this.connAccountNo = connAccountNo;
       this.square = square;
       this.innerSquare = innerSquare;
       this.rentSquare = rentSquare;
       this.equityNature = equityNature;
       this.buildingName = buildingName;
       this.rentDate = rentDate;
       this.contStartDate = contStartDate;
       this.contEndDate = contEndDate;
       this.contToFailDate = contToFailDate;
       this.coopWayCd = coopWayCd;
       this.contBigTypeCd = contBigTypeCd;
       this.contSmallTypeCd = contSmallTypeCd;
       this.contMoney = contMoney;
       this.signDate = signDate;
       this.contContent = contContent;
       this.checkUserCd = checkUserCd;
       this.checkDate = checkDate;
       this.attachFlg = attachFlg;
       this.activeBl = activeBl;
       this.statusCd = statusCd;
       this.chargerTypeArr = chargerTypeArr;
       this.bisContId = bisContId;
       this.bisShopId = bisShopId;
       this.storeFlatIds = storeFlatIds;
       this.storeFlatNos = storeFlatNos;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.shopNameCn = shopNameCn;
       this.freeRentPeriod = freeRentPeriod;
       this.layoutCd = layoutCd;
       this.paymentModeCd = paymentModeCd;
       this.earnestMoney = earnestMoney;
       this.rentYears = rentYears;
       this.signTime = signTime;
       this.backRentYears = backRentYears;
       this.contDeadline = contDeadline;
       this.beEntrustedRenter = beEntrustedRenter;
       this.paymentTime = paymentTime;
       this.performanceBond = performanceBond;
       this.operationBond = operationBond;
       this.integMoneyStandard = integMoneyStandard;
       this.integMoneyFirstRentDay = integMoneyFirstRentDay;
       this.integMoneyFreeRentPeriod = integMoneyFreeRentPeriod;
       this.entrRentYears = entrRentYears;
       this.beEntrRenter = beEntrRenter;
       this.owner = owner;
       this.idCardNo = idCardNo;
       this.housingTypeCd = housingTypeCd;
       this.firstCycleMustRent = firstCycleMustRent;
       this.propertyDerateMoney = propertyDerateMoney;
       this.renterName = renterName;
       this.operationProjectCd = operationProjectCd;
       this.operationArea = operationArea;
       this.contPromiseBond = contPromiseBond;
       this.receivedBond = receivedBond;
       this.sellPrice = sellPrice;
       this.rentUnit1 = rentUnit1;
       this.rentUnit2 = rentUnit2;
       this.rentUnit3 = rentUnit3;
       this.rentUnit4 = rentUnit4;
       this.rentUnit5 = rentUnit5;
       this.rentUnit6 = rentUnit6;
       this.rentUnit7 = rentUnit7;
       this.rentUnit8 = rentUnit8;
       this.rentUnit9 = rentUnit9;
       this.rentUnit10 = rentUnit10;
       this.rentMonth1 = rentMonth1;
       this.rentMonth2 = rentMonth2;
       this.rentMonth3 = rentMonth3;
       this.rentMonth4 = rentMonth4;
       this.rentMonth5 = rentMonth5;
       this.rentMonth6 = rentMonth6;
       this.rentMonth7 = rentMonth7;
       this.rentMonth8 = rentMonth8;
       this.rentMonth9 = rentMonth9;
       this.rentMonth10 = rentMonth10;
       this.rent1 = rent1;
       this.rent2 = rent2;
       this.rent3 = rent3;
       this.rent4 = rent4;
       this.rent5 = rent5;
       this.rent6 = rent6;
       this.rent7 = rent7;
       this.rent8 = rent8;
       this.rent9 = rent9;
       this.rent10 = rent10;
       this.rentRatio1 = rentRatio1;
       this.rentRatio2 = rentRatio2;
       this.rentRatio3 = rentRatio3;
       this.rentRatio4 = rentRatio4;
       this.rentRatio5 = rentRatio5;
       this.rentRatio6 = rentRatio6;
       this.rentRatio7 = rentRatio7;
       this.rentRatio8 = rentRatio8;
       this.rentRatio9 = rentRatio9;
       this.rentRatio10 = rentRatio10;
       this.manageFee1 = manageFee1;
       this.manageFee2 = manageFee2;
       this.manageFee3 = manageFee3;
       this.manageFee4 = manageFee4;
       this.manageFee5 = manageFee5;
       this.manageFee6 = manageFee6;
       this.manageFee7 = manageFee7;
       this.manageFee8 = manageFee8;
       this.manageFee9 = manageFee9;
       this.manageFee10 = manageFee10;
       this.bisContCreditHises = bisContCreditHises;
       this.bisContAddiHises = bisContAddiHises;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_CONT_HIS_ID", unique=true, nullable=false, length=50)
    public String getBisContHisId() {
        return this.bisContHisId;
    }
    
    public void setBisContHisId(String bisContHisId) {
        this.bisContHisId = bisContHisId;
    }
    
    @Column(name="CONT_NO", nullable=false, length=100)
    public String getContNo() {
        return this.contNo;
    }
    
    public void setContNo(String contNo) {
        this.contNo = contNo;
    }
    
    @Column(name="BIS_TENANT_ID", length=50)
    public String getBisTenantId() {
        return this.bisTenantId;
    }
    
    public void setBisTenantId(String bisTenantId) {
        this.bisTenantId = bisTenantId;
    }
    
    @Column(name="BIS_PROJECT_ID", nullable=false, length=50)
    public String getBisProjectId() {
        return this.bisProjectId;
    }
    
    public void setBisProjectId(String bisProjectId) {
        this.bisProjectId = bisProjectId;
    }
    
    @Column(name="CONT_NAME", length=300)
    public String getContName() {
        return this.contName;
    }
    
    public void setContName(String contName) {
        this.contName = contName;
    }
    
    @Column(name="BIS_PEOPLE", length=100)
    public String getBisPeople() {
        return this.bisPeople;
    }
    
    public void setBisPeople(String bisPeople) {
        this.bisPeople = bisPeople;
    }
    
    @Column(name="BRAND", length=300)
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    
    @Column(name="PARTY_A", length=100)
    public String getPartyA() {
        return this.partyA;
    }
    
    public void setPartyA(String partyA) {
        this.partyA = partyA;
    }
    
    @Column(name="PARTY_B", length=100)
    public String getPartyB() {
        return this.partyB;
    }
    
    public void setPartyB(String partyB) {
        this.partyB = partyB;
    }
    
    @Column(name="PARTY_C", length=100)
    public String getPartyC() {
        return this.partyC;
    }
    
    public void setPartyC(String partyC) {
        this.partyC = partyC;
    }
    
    @Column(name="PARTY_D", length=100)
    public String getPartyD() {
        return this.partyD;
    }
    
    public void setPartyD(String partyD) {
        this.partyD = partyD;
    }
    
    @Column(name="CONN_ADDR", length=1000)
    public String getConnAddr() {
        return this.connAddr;
    }
    
    public void setConnAddr(String connAddr) {
        this.connAddr = connAddr;
    }
    
    @Column(name="CONN_TEL", length=300)
    public String getConnTel() {
        return this.connTel;
    }
    
    public void setConnTel(String connTel) {
        this.connTel = connTel;
    }
    
    @Column(name="CONN_PEOPLE", length=100)
    public String getConnPeople() {
        return this.connPeople;
    }
    
    public void setConnPeople(String connPeople) {
        this.connPeople = connPeople;
    }
    
    @Column(name="CONN_FAX", length=100)
    public String getConnFax() {
        return this.connFax;
    }
    
    public void setConnFax(String connFax) {
        this.connFax = connFax;
    }
    
    @Column(name="CONN_ACCOUNT_NO", length=100)
    public String getConnAccountNo() {
        return this.connAccountNo;
    }
    
    public void setConnAccountNo(String connAccountNo) {
        this.connAccountNo = connAccountNo;
    }
    
    @Column(name="SQUARE", precision=10)
    public BigDecimal getSquare() {
        return this.square;
    }
    
    public void setSquare(BigDecimal square) {
        this.square = square;
    }
    
    @Column(name="INNER_SQUARE", precision=10)
    public BigDecimal getInnerSquare() {
        return this.innerSquare;
    }
    
    public void setInnerSquare(BigDecimal innerSquare) {
        this.innerSquare = innerSquare;
    }
    
    @Column(name="RENT_SQUARE", precision=10)
    public BigDecimal getRentSquare() {
        return this.rentSquare;
    }
    
    public void setRentSquare(BigDecimal rentSquare) {
        this.rentSquare = rentSquare;
    }
    
    @Column(name="EQUITY_NATURE", length=100)
    public String getEquityNature() {
        return this.equityNature;
    }
    
    public void setEquityNature(String equityNature) {
        this.equityNature = equityNature;
    }
    
    @Column(name="BUILDING_NAME", length=300)
    public String getBuildingName() {
        return this.buildingName;
    }
    
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RENT_DATE", length=7)
    public Date getRentDate() {
        return this.rentDate;
    }
    
    public void setRentDate(Date rentDate) {
        this.rentDate = rentDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CONT_START_DATE", nullable=false, length=7)
    public Date getContStartDate() {
        return this.contStartDate;
    }
    
    public void setContStartDate(Date contStartDate) {
        this.contStartDate = contStartDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CONT_END_DATE", length=7)
    public Date getContEndDate() {
        return this.contEndDate;
    }
    
    public void setContEndDate(Date contEndDate) {
        this.contEndDate = contEndDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CONT_TO_FAIL_DATE", length=7)
    public Date getContToFailDate() {
        return this.contToFailDate;
    }
    
    public void setContToFailDate(Date contToFailDate) {
        this.contToFailDate = contToFailDate;
    }
    
    @Column(name="COOP_WAY_CD", length=20)
    public String getCoopWayCd() {
        return this.coopWayCd;
    }
    
    public void setCoopWayCd(String coopWayCd) {
        this.coopWayCd = coopWayCd;
    }
    
    @Column(name="CONT_BIG_TYPE_CD", length=20)
    public String getContBigTypeCd() {
        return this.contBigTypeCd;
    }
    
    public void setContBigTypeCd(String contBigTypeCd) {
        this.contBigTypeCd = contBigTypeCd;
    }
    
    @Column(name="CONT_SMALL_TYPE_CD", length=20)
    public String getContSmallTypeCd() {
        return this.contSmallTypeCd;
    }
    
    public void setContSmallTypeCd(String contSmallTypeCd) {
        this.contSmallTypeCd = contSmallTypeCd;
    }
    
    @Column(name="CONT_MONEY", precision=10)
    public BigDecimal getContMoney() {
        return this.contMoney;
    }
    
    public void setContMoney(BigDecimal contMoney) {
        this.contMoney = contMoney;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SIGN_DATE", length=7)
    public Date getSignDate() {
        return this.signDate;
    }
    
    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }
    
    @Column(name="CONT_CONTENT", length=4000)
    public String getContContent() {
        return this.contContent;
    }
    
    public void setContContent(String contContent) {
        this.contContent = contContent;
    }
    
    @Column(name="CHECK_USER_CD", length=20)
    public String getCheckUserCd() {
        return this.checkUserCd;
    }
    
    public void setCheckUserCd(String checkUserCd) {
        this.checkUserCd = checkUserCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CHECK_DATE", length=7)
    public Date getCheckDate() {
        return this.checkDate;
    }
    
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }
    
    @Column(name="ATTACH_FLG", length=1)
    public String getAttachFlg() {
        return this.attachFlg;
    }
    
    public void setAttachFlg(String attachFlg) {
        this.attachFlg = attachFlg;
    }
    
    @Column(name="ACTIVE_BL", nullable=false, precision=1, scale=0)
    public boolean isActiveBl() {
        return this.activeBl;
    }
    
    public void setActiveBl(boolean activeBl) {
        this.activeBl = activeBl;
    }
    
    @Column(name="STATUS_CD", length=20)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }
    
    @Column(name="CHARGER_TYPE_ARR", length=100)
    public String getChargerTypeArr() {
        return this.chargerTypeArr;
    }
    
    public void setChargerTypeArr(String chargerTypeArr) {
        this.chargerTypeArr = chargerTypeArr;
    }
    
    @Column(name="BIS_CONT_ID", nullable=false, length=50)
    public String getBisContId() {
        return this.bisContId;
    }
    
    public void setBisContId(String bisContId) {
        this.bisContId = bisContId;
    }
    
    @Column(name="BIS_SHOP_ID", length=50)
    public String getBisShopId() {
        return this.bisShopId;
    }
    
    public void setBisShopId(String bisShopId) {
        this.bisShopId = bisShopId;
    }
    
    @Column(name="STORE_FLAT_IDS", length=1000)
    public String getStoreFlatIds() {
        return this.storeFlatIds;
    }
    
    public void setStoreFlatIds(String storeFlatIds) {
        this.storeFlatIds = storeFlatIds;
    }
    
    @Column(name="STORE_FLAT_NOS", length=200)
    public String getStoreFlatNos() {
        return this.storeFlatNos;
    }
    
    public void setStoreFlatNos(String storeFlatNos) {
        this.storeFlatNos = storeFlatNos;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="SHOP_NAME_CN", length=100)
    public String getShopNameCn() {
        return this.shopNameCn;
    }
    
    public void setShopNameCn(String shopNameCn) {
        this.shopNameCn = shopNameCn;
    }
    
    @Column(name="FREE_RENT_PERIOD", length=100)
    public String getFreeRentPeriod() {
        return this.freeRentPeriod;
    }
    
    public void setFreeRentPeriod(String freeRentPeriod) {
        this.freeRentPeriod = freeRentPeriod;
    }
    
    @Column(name="LAYOUT_CD", length=20)
    public String getLayoutCd() {
        return this.layoutCd;
    }
    
    public void setLayoutCd(String layoutCd) {
        this.layoutCd = layoutCd;
    }
    
    @Column(name="PAYMENT_MODE_CD", length=20)
    public String getPaymentModeCd() {
        return this.paymentModeCd;
    }
    
    public void setPaymentModeCd(String paymentModeCd) {
        this.paymentModeCd = paymentModeCd;
    }

    @Column(name="PAY_CYCLE_CD", length=20)
    public String getPayCycleCd() {
        return this.payCycleCd;
    }
    
    public void setPayCycleCd(String payCycleCd) {
        this.payCycleCd = payCycleCd;
    }

    @Column(name="EARNEST_MONEY", precision=10)
    public BigDecimal getEarnestMoney() {
        return this.earnestMoney;
    }
    
    public void setEarnestMoney(BigDecimal earnestMoney) {
        this.earnestMoney = earnestMoney;
    }
    
    @Column(name="RENT_YEARS", length=50)
    public String getRentYears() {
        return this.rentYears;
    }
    
    public void setRentYears(String rentYears) {
        this.rentYears = rentYears;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SIGN_TIME", length=7)
    public Date getSignTime() {
        return this.signTime;
    }
    
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }
    
    @Column(name="BACK_RENT_YEARS", length=100)
    public String getBackRentYears() {
        return this.backRentYears;
    }
    
    public void setBackRentYears(String backRentYears) {
        this.backRentYears = backRentYears;
    }
    
    @Column(name="CONT_DEADLINE", length=100)
    public String getContDeadline() {
        return this.contDeadline;
    }
    
    public void setContDeadline(String contDeadline) {
        this.contDeadline = contDeadline;
    }
    
    @Column(name="BE_ENTRUSTED_RENTER", length=100)
    public String getBeEntrustedRenter() {
        return this.beEntrustedRenter;
    }
    
    public void setBeEntrustedRenter(String beEntrustedRenter) {
        this.beEntrustedRenter = beEntrustedRenter;
    }
    
    @Column(name="PAYMENT_TIME", length=100)
    public String getPaymentTime() {
        return this.paymentTime;
    }
    
    public void setPaymentTime(String paymentTime) {
        this.paymentTime = paymentTime;
    }
    
    @Column(name="PERFORMANCE_BOND", precision=10)
    public BigDecimal getPerformanceBond() {
        return this.performanceBond;
    }
    
    public void setPerformanceBond(BigDecimal performanceBond) {
        this.performanceBond = performanceBond;
    }
    
    @Column(name="OPERATION_BOND", precision=10)
    public BigDecimal getOperationBond() {
        return this.operationBond;
    }
    
    public void setOperationBond(BigDecimal operationBond) {
        this.operationBond = operationBond;
    }
    
    @Column(name="INTEG_MONEY_STANDARD", precision=10)
    public BigDecimal getIntegMoneyStandard() {
        return this.integMoneyStandard;
    }
    
    public void setIntegMoneyStandard(BigDecimal integMoneyStandard) {
        this.integMoneyStandard = integMoneyStandard;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INTEG_MONEY_FIRST_RENT_DAY", length=7)
    public Date getIntegMoneyFirstRentDay() {
        return this.integMoneyFirstRentDay;
    }
    
    public void setIntegMoneyFirstRentDay(Date integMoneyFirstRentDay) {
        this.integMoneyFirstRentDay = integMoneyFirstRentDay;
    }
    
    @Column(name="INTEG_MONEY_FREE_RENT_PERIOD", length=100)
    public String getIntegMoneyFreeRentPeriod() {
        return this.integMoneyFreeRentPeriod;
    }
    
    public void setIntegMoneyFreeRentPeriod(String integMoneyFreeRentPeriod) {
        this.integMoneyFreeRentPeriod = integMoneyFreeRentPeriod;
    }
    
    @Column(name="ENTR_RENT_YEARS", length=100)
    public String getEntrRentYears() {
        return this.entrRentYears;
    }
    
    public void setEntrRentYears(String entrRentYears) {
        this.entrRentYears = entrRentYears;
    }
    
    @Column(name="BE_ENTR_RENTER", length=100)
    public String getBeEntrRenter() {
        return this.beEntrRenter;
    }
    
    public void setBeEntrRenter(String beEntrRenter) {
        this.beEntrRenter = beEntrRenter;
    }
    
    @Column(name="OWNER", length=100)
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }
    
    @Column(name="ID_CARD_NO", length=100)
    public String getIdCardNo() {
        return this.idCardNo;
    }
    
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo;
    }
    
    @Column(name="HOUSING_TYPE_CD", length=20)
    public String getHousingTypeCd() {
        return this.housingTypeCd;
    }
    
    public void setHousingTypeCd(String housingTypeCd) {
        this.housingTypeCd = housingTypeCd;
    }
    
    @Column(name="FIRST_CYCLE_MUST_RENT", precision=10)
    public BigDecimal getFirstCycleMustRent() {
        return this.firstCycleMustRent;
    }
    
    public void setFirstCycleMustRent(BigDecimal firstCycleMustRent) {
        this.firstCycleMustRent = firstCycleMustRent;
    }
    
    @Column(name="PROPERTY_DERATE_MONEY", precision=10)
    public BigDecimal getPropertyDerateMoney() {
        return this.propertyDerateMoney;
    }
    
    public void setPropertyDerateMoney(BigDecimal propertyDerateMoney) {
        this.propertyDerateMoney = propertyDerateMoney;
    }
    
    @Column(name="RENTER_NAME", length=100)
    public String getRenterName() {
        return this.renterName;
    }
    
    public void setRenterName(String renterName) {
        this.renterName = renterName;
    }
    
    @Column(name="OPERATION_PROJECT_CD", length=20)
    public String getOperationProjectCd() {
        return this.operationProjectCd;
    }
    
    public void setOperationProjectCd(String operationProjectCd) {
        this.operationProjectCd = operationProjectCd;
    }
    
    @Column(name="OPERATION_AREA", length=200)
    public String getOperationArea() {
        return this.operationArea;
    }
    
    public void setOperationArea(String operationArea) {
        this.operationArea = operationArea;
    }
    
    @Column(name="CONT_PROMISE_BOND", precision=10)
    public BigDecimal getContPromiseBond() {
        return this.contPromiseBond;
    }
    
    public void setContPromiseBond(BigDecimal contPromiseBond) {
        this.contPromiseBond = contPromiseBond;
    }
    
    @Column(name="RECEIVED_BOND", precision=10)
    public BigDecimal getReceivedBond() {
        return this.receivedBond;
    }
    
    public void setReceivedBond(BigDecimal receivedBond) {
        this.receivedBond = receivedBond;
    }
    
    @Column(name="SELL_PRICE", precision=10)
    public BigDecimal getSellPrice() {
        return this.sellPrice;
    }
    
    public void setSellPrice(BigDecimal sellPrice) {
        this.sellPrice = sellPrice;
    }
    
    @Column(name="MANAGE_CD", length=20)
    public String getManageCd() {
        return this.manageCd;
    }
    
    public void setManageCd(String manageCd) {
        this.manageCd = manageCd;
    }
    
    @Column(name="RENT_UNIT1", precision=10)
    public BigDecimal getRentUnit1() {
        return this.rentUnit1;
    }
    
    public void setRentUnit1(BigDecimal rentUnit1) {
        this.rentUnit1 = rentUnit1;
    }
    
    @Column(name="RENT_UNIT2", precision=10)
    public BigDecimal getRentUnit2() {
        return this.rentUnit2;
    }
    
    public void setRentUnit2(BigDecimal rentUnit2) {
        this.rentUnit2 = rentUnit2;
    }
    
    @Column(name="RENT_UNIT3", precision=10)
    public BigDecimal getRentUnit3() {
        return this.rentUnit3;
    }
    
    public void setRentUnit3(BigDecimal rentUnit3) {
        this.rentUnit3 = rentUnit3;
    }
    
    @Column(name="RENT_UNIT4", precision=10)
    public BigDecimal getRentUnit4() {
        return this.rentUnit4;
    }
    
    public void setRentUnit4(BigDecimal rentUnit4) {
        this.rentUnit4 = rentUnit4;
    }
    
    @Column(name="RENT_UNIT5", precision=10)
    public BigDecimal getRentUnit5() {
        return this.rentUnit5;
    }
    
    public void setRentUnit5(BigDecimal rentUnit5) {
        this.rentUnit5 = rentUnit5;
    }
    
    @Column(name="RENT_UNIT6", precision=10)
    public BigDecimal getRentUnit6() {
        return this.rentUnit6;
    }
    
    public void setRentUnit6(BigDecimal rentUnit6) {
        this.rentUnit6 = rentUnit6;
    }
    
    @Column(name="RENT_UNIT7", precision=10)
    public BigDecimal getRentUnit7() {
        return this.rentUnit7;
    }
    
    public void setRentUnit7(BigDecimal rentUnit7) {
        this.rentUnit7 = rentUnit7;
    }
    
    @Column(name="RENT_UNIT8", precision=10)
    public BigDecimal getRentUnit8() {
        return this.rentUnit8;
    }
    
    public void setRentUnit8(BigDecimal rentUnit8) {
        this.rentUnit8 = rentUnit8;
    }
    
    @Column(name="RENT_UNIT9", precision=10)
    public BigDecimal getRentUnit9() {
        return this.rentUnit9;
    }
    
    public void setRentUnit9(BigDecimal rentUnit9) {
        this.rentUnit9 = rentUnit9;
    }
    
    @Column(name="RENT_UNIT10", precision=10)
    public BigDecimal getRentUnit10() {
        return this.rentUnit10;
    }
    
    public void setRentUnit10(BigDecimal rentUnit10) {
        this.rentUnit10 = rentUnit10;
    }
    
    @Column(name="RENT_MONTH1", precision=10)
    public BigDecimal getRentMonth1() {
        return this.rentMonth1;
    }
    
    public void setRentMonth1(BigDecimal rentMonth1) {
        this.rentMonth1 = rentMonth1;
    }
    
    @Column(name="RENT_MONTH2", precision=10)
    public BigDecimal getRentMonth2() {
        return this.rentMonth2;
    }
    
    public void setRentMonth2(BigDecimal rentMonth2) {
        this.rentMonth2 = rentMonth2;
    }
    
    @Column(name="RENT_MONTH3", precision=10)
    public BigDecimal getRentMonth3() {
        return this.rentMonth3;
    }
    
    public void setRentMonth3(BigDecimal rentMonth3) {
        this.rentMonth3 = rentMonth3;
    }
    
    @Column(name="RENT_MONTH4", precision=10)
    public BigDecimal getRentMonth4() {
        return this.rentMonth4;
    }
    
    public void setRentMonth4(BigDecimal rentMonth4) {
        this.rentMonth4 = rentMonth4;
    }
    
    @Column(name="RENT_MONTH5", precision=10)
    public BigDecimal getRentMonth5() {
        return this.rentMonth5;
    }
    
    public void setRentMonth5(BigDecimal rentMonth5) {
        this.rentMonth5 = rentMonth5;
    }
    
    @Column(name="RENT_MONTH6", precision=10)
    public BigDecimal getRentMonth6() {
        return this.rentMonth6;
    }
    
    public void setRentMonth6(BigDecimal rentMonth6) {
        this.rentMonth6 = rentMonth6;
    }
    
    @Column(name="RENT_MONTH7", precision=10)
    public BigDecimal getRentMonth7() {
        return this.rentMonth7;
    }
    
    public void setRentMonth7(BigDecimal rentMonth7) {
        this.rentMonth7 = rentMonth7;
    }
    
    @Column(name="RENT_MONTH8", precision=10)
    public BigDecimal getRentMonth8() {
        return this.rentMonth8;
    }
    
    public void setRentMonth8(BigDecimal rentMonth8) {
        this.rentMonth8 = rentMonth8;
    }
    
    @Column(name="RENT_MONTH9", precision=10)
    public BigDecimal getRentMonth9() {
        return this.rentMonth9;
    }
    
    public void setRentMonth9(BigDecimal rentMonth9) {
        this.rentMonth9 = rentMonth9;
    }
    
    @Column(name="RENT_MONTH10", precision=10)
    public BigDecimal getRentMonth10() {
        return this.rentMonth10;
    }
    
    public void setRentMonth10(BigDecimal rentMonth10) {
        this.rentMonth10 = rentMonth10;
    }
    
    @Column(name="RENT1", precision=10)
    public BigDecimal getRent1() {
        return this.rent1;
    }
    
    public void setRent1(BigDecimal rent1) {
        this.rent1 = rent1;
    }
    
    @Column(name="RENT2", precision=10)
    public BigDecimal getRent2() {
        return this.rent2;
    }
    
    public void setRent2(BigDecimal rent2) {
        this.rent2 = rent2;
    }
    
    @Column(name="RENT3", precision=10)
    public BigDecimal getRent3() {
        return this.rent3;
    }
    
    public void setRent3(BigDecimal rent3) {
        this.rent3 = rent3;
    }
    
    @Column(name="RENT4", precision=10)
    public BigDecimal getRent4() {
        return this.rent4;
    }
    
    public void setRent4(BigDecimal rent4) {
        this.rent4 = rent4;
    }
    
    @Column(name="RENT5", precision=10)
    public BigDecimal getRent5() {
        return this.rent5;
    }
    
    public void setRent5(BigDecimal rent5) {
        this.rent5 = rent5;
    }
    
    @Column(name="RENT6", precision=10)
    public BigDecimal getRent6() {
        return this.rent6;
    }
    
    public void setRent6(BigDecimal rent6) {
        this.rent6 = rent6;
    }
    
    @Column(name="RENT7", precision=10)
    public BigDecimal getRent7() {
        return this.rent7;
    }
    
    public void setRent7(BigDecimal rent7) {
        this.rent7 = rent7;
    }
    
    @Column(name="RENT8", precision=10)
    public BigDecimal getRent8() {
        return this.rent8;
    }
    
    public void setRent8(BigDecimal rent8) {
        this.rent8 = rent8;
    }
    
    @Column(name="RENT9", precision=10)
    public BigDecimal getRent9() {
        return this.rent9;
    }
    
    public void setRent9(BigDecimal rent9) {
        this.rent9 = rent9;
    }
    
    @Column(name="RENT10", precision=10)
    public BigDecimal getRent10() {
        return this.rent10;
    }
    
    public void setRent10(BigDecimal rent10) {
        this.rent10 = rent10;
    }
    
    @Column(name="RENT_RATIO1", precision=10)
    public BigDecimal getRentRatio1() {
        return this.rentRatio1;
    }
    
    public void setRentRatio1(BigDecimal rentRatio1) {
        this.rentRatio1 = rentRatio1;
    }
    
    @Column(name="RENT_RATIO2", precision=10)
    public BigDecimal getRentRatio2() {
        return this.rentRatio2;
    }
    
    public void setRentRatio2(BigDecimal rentRatio2) {
        this.rentRatio2 = rentRatio2;
    }
    
    @Column(name="RENT_RATIO3", precision=10)
    public BigDecimal getRentRatio3() {
        return this.rentRatio3;
    }
    
    public void setRentRatio3(BigDecimal rentRatio3) {
        this.rentRatio3 = rentRatio3;
    }
    
    @Column(name="RENT_RATIO4", precision=10)
    public BigDecimal getRentRatio4() {
        return this.rentRatio4;
    }
    
    public void setRentRatio4(BigDecimal rentRatio4) {
        this.rentRatio4 = rentRatio4;
    }
    
    @Column(name="RENT_RATIO5", precision=10)
    public BigDecimal getRentRatio5() {
        return this.rentRatio5;
    }
    
    public void setRentRatio5(BigDecimal rentRatio5) {
        this.rentRatio5 = rentRatio5;
    }
    
    @Column(name="RENT_RATIO6", precision=10)
    public BigDecimal getRentRatio6() {
        return this.rentRatio6;
    }
    
    public void setRentRatio6(BigDecimal rentRatio6) {
        this.rentRatio6 = rentRatio6;
    }
    
    @Column(name="RENT_RATIO7", precision=10)
    public BigDecimal getRentRatio7() {
        return this.rentRatio7;
    }
    
    public void setRentRatio7(BigDecimal rentRatio7) {
        this.rentRatio7 = rentRatio7;
    }
    
    @Column(name="RENT_RATIO8", precision=10)
    public BigDecimal getRentRatio8() {
        return this.rentRatio8;
    }
    
    public void setRentRatio8(BigDecimal rentRatio8) {
        this.rentRatio8 = rentRatio8;
    }
    
    @Column(name="RENT_RATIO9", precision=10)
    public BigDecimal getRentRatio9() {
        return this.rentRatio9;
    }
    
    public void setRentRatio9(BigDecimal rentRatio9) {
        this.rentRatio9 = rentRatio9;
    }
    
    @Column(name="RENT_RATIO10", precision=10)
    public BigDecimal getRentRatio10() {
        return this.rentRatio10;
    }
    
    public void setRentRatio10(BigDecimal rentRatio10) {
        this.rentRatio10 = rentRatio10;
    }
    
    @Column(name="MANAGE_FEE1", precision=10)
    public BigDecimal getManageFee1() {
        return this.manageFee1;
    }
    
    public void setManageFee1(BigDecimal manageFee1) {
        this.manageFee1 = manageFee1;
    }
    
    @Column(name="MANAGE_FEE2", precision=10)
    public BigDecimal getManageFee2() {
        return this.manageFee2;
    }
    
    public void setManageFee2(BigDecimal manageFee2) {
        this.manageFee2 = manageFee2;
    }
    
    @Column(name="MANAGE_FEE3", precision=10)
    public BigDecimal getManageFee3() {
        return this.manageFee3;
    }
    
    public void setManageFee3(BigDecimal manageFee3) {
        this.manageFee3 = manageFee3;
    }
    
    @Column(name="MANAGE_FEE4", precision=10)
    public BigDecimal getManageFee4() {
        return this.manageFee4;
    }
    
    public void setManageFee4(BigDecimal manageFee4) {
        this.manageFee4 = manageFee4;
    }
    
    @Column(name="MANAGE_FEE5", precision=10)
    public BigDecimal getManageFee5() {
        return this.manageFee5;
    }
    
    public void setManageFee5(BigDecimal manageFee5) {
        this.manageFee5 = manageFee5;
    }
    
    @Column(name="MANAGE_FEE6", precision=10)
    public BigDecimal getManageFee6() {
        return this.manageFee6;
    }
    
    public void setManageFee6(BigDecimal manageFee6) {
        this.manageFee6 = manageFee6;
    }
    
    @Column(name="MANAGE_FEE7", precision=10)
    public BigDecimal getManageFee7() {
        return this.manageFee7;
    }
    
    public void setManageFee7(BigDecimal manageFee7) {
        this.manageFee7 = manageFee7;
    }
    
    @Column(name="MANAGE_FEE8", precision=10)
    public BigDecimal getManageFee8() {
        return this.manageFee8;
    }
    
    public void setManageFee8(BigDecimal manageFee8) {
        this.manageFee8 = manageFee8;
    }
    
    @Column(name="MANAGE_FEE9", precision=10)
    public BigDecimal getManageFee9() {
        return this.manageFee9;
    }
    
    public void setManageFee9(BigDecimal manageFee9) {
        this.manageFee9 = manageFee9;
    }
    
    @Column(name="MANAGE_FEE10", precision=10)
    public BigDecimal getManageFee10() {
        return this.manageFee10;
    }
    
    public void setManageFee10(BigDecimal manageFee10) {
        this.manageFee10 = manageFee10;
    }

    @Column(name="IN_POOL_BL", precision=1, scale=0)
    public Boolean getInPoolBl() {
        return this.inPoolBl;
    }
    
    public void setInPoolBl(Boolean inPoolBl) {
        this.inPoolBl = inPoolBl;
    }

    @Column(name="CHANGE_USER", length=20)
    public String getChangeUser() {
        return this.changeUser;
    }
    
    public void setChangeUser(String changeUser) {
        this.changeUser = changeUser;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CHANGE_DATE", length=7)
    public Date getChangeDate() {
        return this.changeDate;
    }
    
    public void setChangeDate(Date changeDate) {
        this.changeDate = changeDate;
    }
    
    @Column(name="CHARGE_TYPE_CD", length=20)
    public String getChargeTypeCd() {
        return this.chargeTypeCd;
    }
    
    public void setChargeTypeCd(String chargeTypeCd) {
        this.chargeTypeCd = chargeTypeCd;
    }
    
    @Column(name="FORMULA", length=20)
    public String getFormula() {
        return this.formula;
    }
    
    public void setFormula(String formula) {
        this.formula = formula;
    }
    
    @Column(name="UNIT_PRICE", precision=10)
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
    
    @Column(name="FORMULA_SQUARE", precision=10)
    public BigDecimal getFormulaSquare() {
        return this.formulaSquare;
    }
    
    public void setFormulaSquare(BigDecimal formulaSquare) {
        this.formulaSquare = formulaSquare;
    }
    
    @Column(name="COUNT_PRICE", precision=10)
    public BigDecimal getCountPrice() {
        return this.countPrice;
    }
    
    public void setCountPrice(BigDecimal countPrice) {
        this.countPrice = countPrice;
    }
    
    @Column(name="TOTAL_PRICE", precision=10)
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    @Column(name="PAY_WAY", length=20)
    public String getPayWay() {
        return this.payWay;
    }
    
    public void setPayWay(String payWay) {
        this.payWay = payWay;
    }

    @Column(name="PAY_MONTH", length=2)
    public String getPayMonth() {
		return payMonth;
	}

	public void setPayMonth(String payMonth) {
		this.payMonth = payMonth;
	}
	
    @Column(name="PAY_DAY", length=10)
    public String getPayDay() {
        return this.payDay;
    }
    
    public void setPayDay(String payDay) {
        this.payDay = payDay;
    }

    @Column(name="MONEY_SCALE", length=20)
    public String getMoneyScale() {
		return moneyScale;
	}

	public void setMoneyScale(String moneyScale) {
		this.moneyScale = moneyScale;
	}
	
    @Column(name="CONT_APPROVAL", length=4000)
    public String getContApproval() {
        return this.contApproval;
    }
    
    public void setContApproval(String contApproval) {
        this.contApproval = contApproval;
    }
    
    @Column(name="CONT_APPROVAL_ID", length=50)
    public String getContApprovalId() {
        return this.contApprovalId;
    }
    
    public void setContApprovalId(String contApprovalId) {
        this.contApprovalId = contApprovalId;
    }
    
    @Column(name="APPROVAL_ATTACH_FLG", length=1)
    public String getApprovalAttachFlg() {
        return this.approvalAttachFlg;
    }
    
    public void setApprovalAttachFlg(String approvalAttachFlg) {
        this.approvalAttachFlg = approvalAttachFlg;
    }
    
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisContHis")
    @BatchSize(size=10)
public List<BisContCreditHis> getBisContCreditHises() {
        return this.bisContCreditHises;
    }
    
    public void setBisContCreditHises(List<BisContCreditHis> bisContCreditHises) {
        this.bisContCreditHises = bisContCreditHises;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisContHis")
    @BatchSize(size=10)
public List<BisContAddiHis> getBisContAddiHises() {
        return this.bisContAddiHises;
    }
    
    public void setBisContAddiHises(List<BisContAddiHis> bisContAddiHises) {
        this.bisContAddiHises = bisContAddiHises;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="bisContHis")
    @BatchSize(size=10)
    public List<BisMustRentHis> getBisMustRentHises() {
        return this.bisMustRentHises;
    }
    
    public void setBisMustRentHises(List<BisMustRentHis> bisMustRentHises) {
        this.bisMustRentHises = bisMustRentHises;
    }



}


