// 
package com.hhz.ump.entity.bis;
// Generated 2011-8-3 22:51:02 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * BisContAddiHis generated by hbm2java
 */
@Entity
@Table(name="BIS_CONT_ADDI_HIS"
    ,schema="POWERDESK"
)
public class BisContAddiHis  implements java.io.Serializable {


     private String bisContAddiHisId;
     private BisContHis bisContHis;
     private Date signDate;
     private String contAdditionalName;
     private String contAdditionalContent;
     private String contAdditionalDesc;
     private String attachFlg;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String bisContAdditionalId;

    public BisContAddiHis() {
    }

	
    public BisContAddiHis(String bisContAddiHisId, BisContHis bisContHis, long recordVersion) {
        this.bisContAddiHisId = bisContAddiHisId;
        this.bisContHis = bisContHis;
        this.recordVersion = recordVersion;
    }
    public BisContAddiHis(String bisContAddiHisId, BisContHis bisContHis, Date signDate, String contAdditionalName, String contAdditionalContent, String contAdditionalDesc, String attachFlg, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, String bisContAdditionalId) {
       this.bisContAddiHisId = bisContAddiHisId;
       this.bisContHis = bisContHis;
       this.signDate = signDate;
       this.contAdditionalName = contAdditionalName;
       this.contAdditionalContent = contAdditionalContent;
       this.contAdditionalDesc = contAdditionalDesc;
       this.attachFlg = attachFlg;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.bisContAdditionalId = bisContAdditionalId;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_CONT_ADDI_HIS_ID", unique=true, nullable=false, length=50)
    public String getBisContAddiHisId() {
        return this.bisContAddiHisId;
    }
    
    public void setBisContAddiHisId(String bisContAddiHisId) {
        this.bisContAddiHisId = bisContAddiHisId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIS_CONT_HIS_ID", nullable=false)
    public BisContHis getBisContHis() {
        return this.bisContHis;
    }
    
    public void setBisContHis(BisContHis bisContHis) {
        this.bisContHis = bisContHis;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SIGN_DATE", length=7)
    public Date getSignDate() {
        return this.signDate;
    }
    
    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }
    
    @Column(name="CONT_ADDITIONAL_NAME", length=100)
    public String getContAdditionalName() {
        return this.contAdditionalName;
    }
    
    public void setContAdditionalName(String contAdditionalName) {
        this.contAdditionalName = contAdditionalName;
    }
    
    @Column(name="CONT_ADDITIONAL_CONTENT", length=1000)
    public String getContAdditionalContent() {
        return this.contAdditionalContent;
    }
    
    public void setContAdditionalContent(String contAdditionalContent) {
        this.contAdditionalContent = contAdditionalContent;
    }
    
    @Column(name="CONT_ADDITIONAL_DESC", length=4000)
    public String getContAdditionalDesc() {
        return this.contAdditionalDesc;
    }
    
    public void setContAdditionalDesc(String contAdditionalDesc) {
        this.contAdditionalDesc = contAdditionalDesc;
    }
    
    @Column(name="ATTACH_FLG", length=1)
    public String getAttachFlg() {
        return this.attachFlg;
    }
    
    public void setAttachFlg(String attachFlg) {
        this.attachFlg = attachFlg;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="BIS_CONT_ADDITIONAL_ID", length=50)
    public String getBisContAdditionalId() {
        return this.bisContAdditionalId;
    }
    
    public void setBisContAdditionalId(String bisContAdditionalId) {
        this.bisContAdditionalId = bisContAdditionalId;
    }




}


