// 
package com.hhz.ump.entity.bis;
// Generated 2011-8-3 22:32:28 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * BisFactStore generated by hbm2java
 */
@Entity
@Table(name="BIS_FACT_STORE"
    ,schema="POWERDESK"
)
public class BisFactStore  implements java.io.Serializable {


     private String bisFactStoreId;
     private BisFact bisFact;
     private BisStore bisStore;
     private String chargeTypeCd;
     private String factYear;
     private String factMonth;
     private BigDecimal money;
     private Date factDate;
     private String describe;
     private String checkUserCd;
     private String checkDate;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;

    public BisFactStore() {
    }

	
    public BisFactStore(String bisFactStoreId, BisFact bisFact, BisStore bisStore, long recordVersion) {
        this.bisFactStoreId = bisFactStoreId;
        this.bisFact = bisFact;
        this.bisStore = bisStore;
        this.recordVersion = recordVersion;
    }
    public BisFactStore(String bisFactStoreId, BisFact bisFact, BisStore bisStore, String chargeTypeCd, String factYear, String factMonth, BigDecimal money, Date factDate, String describe, String checkUserCd, String checkDate, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion) {
       this.bisFactStoreId = bisFactStoreId;
       this.bisFact = bisFact;
       this.bisStore = bisStore;
       this.chargeTypeCd = chargeTypeCd;
       this.factYear = factYear;
       this.factMonth = factMonth;
       this.money = money;
       this.factDate = factDate;
       this.describe = describe;
       this.checkUserCd = checkUserCd;
       this.checkDate = checkDate;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_FACT_STORE_ID", unique=true, nullable=false, length=50)
    public String getBisFactStoreId() {
        return this.bisFactStoreId;
    }
    
    public void setBisFactStoreId(String bisFactStoreId) {
        this.bisFactStoreId = bisFactStoreId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIS_FACT_ID", nullable=false)
    public BisFact getBisFact() {
        return this.bisFact;
    }
    
    public void setBisFact(BisFact bisFact) {
        this.bisFact = bisFact;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIS_STORE_ID", nullable=false)
    public BisStore getBisStore() {
        return this.bisStore;
    }
    
    public void setBisStore(BisStore bisStore) {
        this.bisStore = bisStore;
    }
    
    @Column(name="CHARGE_TYPE_CD", length=20)
    public String getChargeTypeCd() {
        return this.chargeTypeCd;
    }
    
    public void setChargeTypeCd(String chargeTypeCd) {
        this.chargeTypeCd = chargeTypeCd;
    }
    
    @Column(name="FACT_YEAR", length=4)
    public String getFactYear() {
        return this.factYear;
    }
    
    public void setFactYear(String factYear) {
        this.factYear = factYear;
    }
    
    @Column(name="FACT_MONTH", length=2)
    public String getFactMonth() {
        return this.factMonth;
    }
    
    public void setFactMonth(String factMonth) {
        this.factMonth = factMonth;
    }
    
    @Column(name="MONEY", precision=10)
    public BigDecimal getMoney() {
        return this.money;
    }
    
    public void setMoney(BigDecimal money) {
        this.money = money;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FACT_DATE", length=7)
    public Date getFactDate() {
        return this.factDate;
    }
    
    public void setFactDate(Date factDate) {
        this.factDate = factDate;
    }
    
    @Column(name="DESCRIBE", length=10)
    public String getDescribe() {
        return this.describe;
    }
    
    public void setDescribe(String describe) {
        this.describe = describe;
    }
    
    @Column(name="CHECK_USER_CD", length=20)
    public String getCheckUserCd() {
        return this.checkUserCd;
    }
    
    public void setCheckUserCd(String checkUserCd) {
        this.checkUserCd = checkUserCd;
    }
    
    @Column(name="CHECK_DATE", length=10)
    public String getCheckDate() {
        return this.checkDate;
    }
    
    public void setCheckDate(String checkDate) {
        this.checkDate = checkDate;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }




}


