// 
package com.hhz.ump.entity.bis;
// Generated 2011-10-26 17:39:15 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * BisMustFormula generated by hbm2java
 */
@Entity
@Table(name="BIS_MUST_FORMULA"
    ,schema="POWERDESK"
)
public class BisMustFormula  implements java.io.Serializable {


     private String bisMustFormulaId;
     private BisCont bisCont;
     private String chargeTypeCd;
     private String formula;
     private BigDecimal unitPrice;
     private BigDecimal formulaSquare;
     private BigDecimal countPrice;
     private BigDecimal totalPrice;
     private String payDay;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;

    public BisMustFormula() {
    }

	
    public BisMustFormula(String bisMustFormulaId, BisCont bisCont, long recordVersion) {
        this.bisMustFormulaId = bisMustFormulaId;
        this.bisCont = bisCont;
        this.recordVersion = recordVersion;
    }
    public BisMustFormula(String bisMustFormulaId, BisCont bisCont, String chargeTypeCd, String formula, BigDecimal unitPrice, BigDecimal formulaSquare, BigDecimal countPrice, BigDecimal totalPrice, String payDay, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion) {
       this.bisMustFormulaId = bisMustFormulaId;
       this.bisCont = bisCont;
       this.chargeTypeCd = chargeTypeCd;
       this.formula = formula;
       this.unitPrice = unitPrice;
       this.formulaSquare = formulaSquare;
       this.countPrice = countPrice;
       this.totalPrice = totalPrice;
       this.payDay = payDay;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_MUST_FORMULA_ID", unique=true, nullable=false, length=50)
    public String getBisMustFormulaId() {
        return this.bisMustFormulaId;
    }
    
    public void setBisMustFormulaId(String bisMustFormulaId) {
        this.bisMustFormulaId = bisMustFormulaId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIS_CONT_ID", nullable=false)
    public BisCont getBisCont() {
        return this.bisCont;
    }
    
    public void setBisCont(BisCont bisCont) {
        this.bisCont = bisCont;
    }
    
    @Column(name="CHARGE_TYPE_CD", length=20)
    public String getChargeTypeCd() {
        return this.chargeTypeCd;
    }
    
    public void setChargeTypeCd(String chargeTypeCd) {
        this.chargeTypeCd = chargeTypeCd;
    }
    
    @Column(name="FORMULA", length=20)
    public String getFormula() {
        return this.formula;
    }
    
    public void setFormula(String formula) {
        this.formula = formula;
    }
    
    @Column(name="UNIT_PRICE", precision=10)
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
    
    @Column(name="FORMULA_SQUARE", precision=10)
    public BigDecimal getFormulaSquare() {
		return formulaSquare;
	}

	public void setFormulaSquare(BigDecimal formulaSquare) {
		this.formulaSquare = formulaSquare;
	}
    
    @Column(name="COUNT_PRICE", precision=10)
    public BigDecimal getCountPrice() {
        return this.countPrice;
    }

	public void setCountPrice(BigDecimal countPrice) {
        this.countPrice = countPrice;
    }
    
    @Column(name="TOTAL_PRICE", precision=10)
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }
    
    @Column(name="PAY_DAY", length=10)
    public String getPayDay() {
        return this.payDay;
    }
    
    public void setPayDay(String payDay) {
        this.payDay = payDay;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }




}


