// 
package com.hhz.ump.entity.bis;
// Generated 2011-8-3 22:32:28 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * BisMust generated by hbm2java
 */
@Entity
@Table(name="BIS_MUST"
    ,schema="POWERDESK"
)
public class BisMust  implements java.io.Serializable {


     private String bisMustId;
     private BisCont bisCont;
     private Long sequenceNo;
     private String chargeTypeCd;
     private String mustYear;
     private String mustMonth;
     private BigDecimal money;
     private Boolean countBl;
     private Date collDate;
     private String describe;
     private String checkUserCd;
     private Date checkDate;
     private String statusCd;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String bisTenantId;
     private String bisShopId;
     private String bisProjectId;
     private String attachFlg;
     private String entityTmpId;
     private BigDecimal turnover;
     private String bisFloorId;
     private String bisFlatId;
     private String bisMultiId;
     private String typeCd;
     private String floorType;
     private BigDecimal totalFactMoney;

    public BisMust() {
    }

	
    public BisMust(String bisMustId, long recordVersion) {
        this.bisMustId = bisMustId;
        this.recordVersion = recordVersion;
    }
    public BisMust(String bisMustId, BisCont bisCont, Long sequenceNo, String chargeTypeCd, String mustYear, String mustMonth, BigDecimal money, Boolean countBl, Date collDate, String describe, String checkUserCd, Date checkDate, String statusCd, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, String bisTenantId, String bisShopId) {
       this.bisMustId = bisMustId;
       this.bisCont = bisCont;
       this.sequenceNo = sequenceNo;
       this.chargeTypeCd = chargeTypeCd;
       this.mustYear = mustYear;
       this.mustMonth = mustMonth;
       this.money = money;
       this.countBl = countBl;
       this.collDate = collDate;
       this.describe = describe;
       this.checkUserCd = checkUserCd;
       this.checkDate = checkDate;
       this.statusCd = statusCd;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.bisTenantId = bisTenantId;
       this.bisShopId = bisShopId;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_MUST_ID", unique=true, nullable=false, length=50)
    public String getBisMustId() {
        return this.bisMustId;
    }
    
    public void setBisMustId(String bisMustId) {
        this.bisMustId = bisMustId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIS_CONT_ID")
    public BisCont getBisCont() {
        return this.bisCont;
    }
    
    public void setBisCont(BisCont bisCont) {
        this.bisCont = bisCont;
    }
    
    @Column(name="SEQUENCE_NO", precision=10, scale=0)
    public Long getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Long sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    
    @Column(name="CHARGE_TYPE_CD", length=20)
    public String getChargeTypeCd() {
        return this.chargeTypeCd;
    }
    
    public void setChargeTypeCd(String chargeTypeCd) {
        this.chargeTypeCd = chargeTypeCd;
    }
    
    @Column(name="MUST_YEAR", length=4)
    public String getMustYear() {
        return this.mustYear;
    }
    
    public void setMustYear(String mustYear) {
        this.mustYear = mustYear;
    }
    
    @Column(name="MUST_MONTH", length=2)
    public String getMustMonth() {
        return this.mustMonth;
    }
    
    public void setMustMonth(String mustMonth) {
        this.mustMonth = mustMonth;
    }
    
    @Column(name="MONEY", precision=10)
    public BigDecimal getMoney() {
        return this.money;
    }
    
    public void setMoney(BigDecimal money) {
        this.money = money;
    }
    
    @Column(name="COUNT_BL", precision=1, scale=0)
    public Boolean getCountBl() {
        return this.countBl;
    }
    
    public void setCountBl(Boolean countBl) {
        this.countBl = countBl;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="COLL_DATE", length=7)
    public Date getCollDate() {
        return this.collDate;
    }
    
    public void setCollDate(Date collDate) {
        this.collDate = collDate;
    }
    
    @Column(name="DESCRIBE", length=1000)
    public String getDescribe() {
        return this.describe;
    }
    
    public void setDescribe(String describe) {
        this.describe = describe;
    }
    
    @Column(name="CHECK_USER_CD", length=20)
    public String getCheckUserCd() {
        return this.checkUserCd;
    }
    
    public void setCheckUserCd(String checkUserCd) {
        this.checkUserCd = checkUserCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CHECK_DATE", length=7)
    public Date getCheckDate() {
        return this.checkDate;
    }
    
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }
    
    @Column(name="STATUS_CD", length=20)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="BIS_TENANT_ID", length=50)
    public String getBisTenantId() {
        return this.bisTenantId;
    }
    
    public void setBisTenantId(String bisTenantId) {
        this.bisTenantId = bisTenantId;
    }
    
    @Column(name="BIS_SHOP_ID", length=50)
    public String getBisShopId() {
        return this.bisShopId;
    }
    
    public void setBisShopId(String bisShopId) {
        this.bisShopId = bisShopId;
    }

    @Column(name="BIS_PROJECT_ID", length=50)
    public String getBisProjectId() {
        return this.bisProjectId;
    }
    
    public void setBisProjectId(String bisProjectId) {
        this.bisProjectId = bisProjectId;
    }
    
    @Column(name="ATTACH_FLG", length=1)
    public String getAttachFlg() {
        return this.attachFlg;
    }
    
    public void setAttachFlg(String attachFlg) {
        this.attachFlg = attachFlg;
    }
    
    @Column(name="ENTITY_TMP_ID", length=50)
    public String getEntityTmpId() {
        return this.entityTmpId;
    }
    
    public void setEntityTmpId(String entityTmpId) {
        this.entityTmpId = entityTmpId;
    }

    @Column(name="TURNOVER", precision=10)
    public BigDecimal getTurnover() {
        return this.turnover;
    }
    
    public void setTurnover(BigDecimal turnover) {
        this.turnover = turnover;
    }
    
    @Column(name="BIS_FLOOR_ID", length=50)
    public String getBisFloorId() {
        return this.bisFloorId;
    }
    
    public void setBisFloorId(String bisFloorId) {
        this.bisFloorId = bisFloorId;
    }
    
    @Column(name="BIS_FLAT_ID", length=50)
    public String getBisFlatId() {
        return this.bisFlatId;
    }
    
    public void setBisFlatId(String bisFlatId) {
        this.bisFlatId = bisFlatId;
    }
    
    @Column(name="BIS_MULTI_ID", length=50)
    public String getBisMultiId() {
        return this.bisMultiId;
    }
    
    public void setBisMultiId(String bisMultiId) {
        this.bisMultiId = bisMultiId;
    }
    
    @Column(name="TYPE_CD", length=1)
    public String getTypeCd() {
        return this.typeCd;
    }
    
    public void setTypeCd(String typeCd) {
        this.typeCd = typeCd;
    }

    @Column(name="FLOOR_TYPE", length=1)
    public String getFloorType() {
        return this.floorType;
    }
    
    public void setFloorType(String floorType) {
        this.floorType = floorType;
    }
    
    @Column(name="TOTAL_FACT_MONEY", precision=10)
    public BigDecimal getTotalFactMoney() {
        return this.totalFactMoney;
    }
    
    public void setTotalFactMoney(BigDecimal totalFactMoney) {
        this.totalFactMoney = totalFactMoney;
    }
}


