// 
package com.hhz.ump.entity.bis;
// Generated 2012-4-16 18:37:21 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * BisRentalCollectionRate generated by hbm2java
 */
@Entity
@Table(name="BIS_RENTAL_COLLECTION_RATE"
    ,schema="POWERDESK"
)
public class BisRentalCollectionRate  implements java.io.Serializable {


     private String bisRentalCollectionRatId;
     private String startDay;
     private String endDay;
     private String bisProjectId;
     private String cumulativeRecAmountRent;
     private String cumulativeColRateRent;
     private String cumulativeRecAmountProperty;
     private String cumulativeColRateProperty;
     private String statusFlg;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private BigDecimal recordVersion;
     /**租费收缴率 rent*/
     private String rentalCollPointRent;
     /**租费收缴率 property*/
     private String rentalCollPointProperty;
     /**当月情况*/
     private String cumulativeRecAmountCurRent;
     private String cumulativeColRateCurRent;
     private String cumulativeRecAmountCurPpt;
     private String cumulativeColRateCurPpt;
     
     /**
      * 能耗相关5个字段-add by liuzhihui 2012-06-26
      */
     private BigDecimal cumulativeRecAmountCurEner;
     private BigDecimal cumulativeColRateCurEner;
     private BigDecimal rentalCollPointEner;
     private BigDecimal cumulativeRecAmountEner;
     private BigDecimal cumulativeColRateEner;

    public BisRentalCollectionRate() {
    }
    /***
     * 新增下周报的构造方法
     * @param startDay
     * @param endDay
     * @param bisProjectId
     * @param cumulativeRecAmountRent
     * @param cumulativeColRateRent
     * @param cumulativeRecAmountProperty
     * @param cumulativeColRateProperty
     * @param rentalCollPointRent
     * @param rentalCollPointProperty
     * @param remark
     */
    public BisRentalCollectionRate(String startDay, String endDay, String bisProjectId, String cumulativeRecAmountRent, String cumulativeColRateRent, String cumulativeRecAmountProperty, String cumulativeColRateProperty, String rentalCollPointRent, String rentalCollPointProperty, String remark){
    	this.startDay = startDay;
    	this.endDay = endDay;
    	this.bisProjectId = bisProjectId;
    	this.cumulativeRecAmountRent = cumulativeRecAmountRent;
    	this.cumulativeColRateRent = cumulativeColRateRent;
    	this.cumulativeRecAmountProperty = cumulativeRecAmountProperty;
    	this.cumulativeColRateProperty = cumulativeColRateProperty;
    	this.rentalCollPointRent = rentalCollPointRent;
    	this.rentalCollPointProperty = rentalCollPointProperty;
    	this.remark = remark;
    }
    /***
     * 新增周报的构造方法，增加“当月”字段
     * @param startDay
     * @param endDay
     * @param bisProjectId
     * @param cumulativeRecAmountRent
     * @param cumulativeColRateRent
     * @param cumulativeRecAmountProperty
     * @param cumulativeColRateProperty
     * @param rentalCollPointRent
     * @param rentalCollPointProperty
     * @param remark
     * @param cumulativeRecAmountCurRent
     * @param cumulativeColRateCurRent
     * @param cumulativeRecAmountCurPpt
     * @param cumulativeColRateCurPpt
     */
    public BisRentalCollectionRate(String startDay, String endDay, String bisProjectId, String cumulativeRecAmountRent, String cumulativeColRateRent, String cumulativeRecAmountProperty, String cumulativeColRateProperty, String rentalCollPointRent, String rentalCollPointProperty, String remark,String cumulativeRecAmountCurRent,String cumulativeColRateCurRent,String cumulativeRecAmountCurPpt,String cumulativeColRateCurPpt){
    	this.startDay = startDay;
    	this.endDay = endDay;
    	this.bisProjectId = bisProjectId;
    	this.cumulativeRecAmountRent = cumulativeRecAmountRent;
    	this.cumulativeColRateRent = cumulativeColRateRent;
    	this.cumulativeRecAmountProperty = cumulativeRecAmountProperty;
    	this.cumulativeColRateProperty = cumulativeColRateProperty;
    	this.rentalCollPointRent = rentalCollPointRent;
    	this.rentalCollPointProperty = rentalCollPointProperty;
    	this.remark = remark;
    	this.cumulativeRecAmountCurRent = cumulativeRecAmountCurRent;
    	this.cumulativeColRateCurRent = cumulativeColRateCurRent;
    	this.cumulativeRecAmountCurPpt = cumulativeRecAmountCurPpt;
    	this.cumulativeColRateCurPpt = cumulativeColRateCurPpt;
    }
    public BisRentalCollectionRate(String bisProjectId,String startDay,String endDay){
		this.bisProjectId = bisProjectId;
		this.startDay = startDay;
		this.endDay = endDay;
	}
    
    public BisRentalCollectionRate(String bisRentalCollectionRatId) {
        this.bisRentalCollectionRatId = bisRentalCollectionRatId;
    }
    public BisRentalCollectionRate(String bisRentalCollectionRatId, String startDay, String endDay, String bisProjectId, String cumulativeRecAmountRent, String cumulativeColRateRent, String cumulativeRecAmountProperty, String cumulativeColRateProperty, String statusFlg, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, BigDecimal recordVersion, String rentalCollPointRent, String rentalCollPointProperty, BigDecimal cumulativeRecAmountCurEner, BigDecimal cumulativeColRateCurEner, BigDecimal rentalCollPointEner, BigDecimal cumulativeRecAmountEner, BigDecimal cumulativeColRateEner) {
       this.bisRentalCollectionRatId = bisRentalCollectionRatId;
       this.startDay = startDay;
       this.endDay = endDay;
       this.bisProjectId = bisProjectId;
       this.cumulativeRecAmountRent = cumulativeRecAmountRent;
       this.cumulativeColRateRent = cumulativeColRateRent;
       this.cumulativeRecAmountProperty = cumulativeRecAmountProperty;
       this.cumulativeColRateProperty = cumulativeColRateProperty;
       this.statusFlg = statusFlg;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.rentalCollPointRent = rentalCollPointRent;
       this.rentalCollPointProperty = rentalCollPointProperty;
       this.cumulativeRecAmountCurEner = cumulativeRecAmountCurEner;
       this.cumulativeColRateCurEner = cumulativeColRateCurEner;
       this.rentalCollPointEner = rentalCollPointEner;
       this.cumulativeRecAmountEner = cumulativeRecAmountEner;
       this.cumulativeColRateEner = cumulativeColRateEner;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_RENTAL_COLLECTION_RAT_ID", unique=true, nullable=false, length=50)
    public String getBisRentalCollectionRatId() {
        return this.bisRentalCollectionRatId;
    }
    
    public void setBisRentalCollectionRatId(String bisRentalCollectionRatId) {
        this.bisRentalCollectionRatId = bisRentalCollectionRatId;
    }
    
    @Column(name="START_DAY", length=10)
    public String getStartDay() {
        return this.startDay;
    }
    
    public void setStartDay(String startDay) {
        this.startDay = startDay;
    }
    
    @Column(name="END_DAY", length=10)
    public String getEndDay() {
        return this.endDay;
    }
    
    public void setEndDay(String endDay) {
        this.endDay = endDay;
    }
    
    @Column(name="BIS_PROJECT_ID", length=50)
    public String getBisProjectId() {
        return this.bisProjectId;
    }
    
    public void setBisProjectId(String bisProjectId) {
        this.bisProjectId = bisProjectId;
    }
    
    @Column(name="CUMULATIVE_REC_AMOUNT_RENT", length=50)
    public String getCumulativeRecAmountRent() {
        return this.cumulativeRecAmountRent;
    }
    
    public void setCumulativeRecAmountRent(String cumulativeRecAmountRent) {
        this.cumulativeRecAmountRent = cumulativeRecAmountRent;
    }
    
    @Column(name="CUMULATIVE_COL_RATE_RENT", length=50)
    public String getCumulativeColRateRent() {
        return this.cumulativeColRateRent;
    }
    
    public void setCumulativeColRateRent(String cumulativeColRateRent) {
        this.cumulativeColRateRent = cumulativeColRateRent;
    }
    
    @Column(name="CUMULATIVE_REC_AMOUNT_PROPERTY", length=50)
    public String getCumulativeRecAmountProperty() {
        return this.cumulativeRecAmountProperty;
    }
    
    public void setCumulativeRecAmountProperty(String cumulativeRecAmountProperty) {
        this.cumulativeRecAmountProperty = cumulativeRecAmountProperty;
    }
    
    @Column(name="CUMULATIVE_COL_RATE_PROPERTY", length=50)
    public String getCumulativeColRateProperty() {
        return this.cumulativeColRateProperty;
    }
    
    public void setCumulativeColRateProperty(String cumulativeColRateProperty) {
        this.cumulativeColRateProperty = cumulativeColRateProperty;
    }
    
    @Column(name="STATUS_FLG", length=2)
    public String getStatusFlg() {
        return this.statusFlg;
    }
    
    public void setStatusFlg(String statusFlg) {
        this.statusFlg = statusFlg;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", precision=10, scale=3)
    public BigDecimal getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(BigDecimal recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="RENTAL_COLL_POINT_RENT", length=50)
    public String getRentalCollPointRent() {
        return this.rentalCollPointRent;
    }
    
    public void setRentalCollPointRent(String rentalCollPointRent) {
        this.rentalCollPointRent = rentalCollPointRent;
    }
    
    @Column(name="RENTAL_COLL_POINT_PROPERTY", length=50)
    public String getRentalCollPointProperty() {
        return this.rentalCollPointProperty;
    }
    

    @Column(name="CUMULATIVE_REC_AMOUNT_CUR_ENER", precision=18)
    public BigDecimal getCumulativeRecAmountCurEner() {
        return this.cumulativeRecAmountCurEner;
    }
    
    public void setCumulativeRecAmountCurEner(BigDecimal cumulativeRecAmountCurEner) {
        this.cumulativeRecAmountCurEner = cumulativeRecAmountCurEner;
    }
    
    @Column(name="CUMULATIVE_COL_RATE_CUR_ENER", precision=18)
    public BigDecimal getCumulativeColRateCurEner() {
        return this.cumulativeColRateCurEner;
    }
    
    public void setCumulativeColRateCurEner(BigDecimal cumulativeColRateCurEner) {
        this.cumulativeColRateCurEner = cumulativeColRateCurEner;
    }
    
    @Column(name="RENTAL_COLL_POINT_ENER", precision=18)
    public BigDecimal getRentalCollPointEner() {
        return this.rentalCollPointEner;
    }
    
    public void setRentalCollPointEner(BigDecimal rentalCollPointEner) {
        this.rentalCollPointEner = rentalCollPointEner;
    }
    
    @Column(name="CUMULATIVE_REC_AMOUNT_ENER", precision=18)
    public BigDecimal getCumulativeRecAmountEner() {
        return this.cumulativeRecAmountEner;
    }
    
    public void setCumulativeRecAmountEner(BigDecimal cumulativeRecAmountEner) {
        this.cumulativeRecAmountEner = cumulativeRecAmountEner;
    }
    
    @Column(name="CUMULATIVE_COL_RATE_ENER", precision=18)
    public BigDecimal getCumulativeColRateEner() {
        return this.cumulativeColRateEner;
    }
    
    public void setCumulativeColRateEner(BigDecimal cumulativeColRateEner) {
        this.cumulativeColRateEner = cumulativeColRateEner;
    }
    
    public void setRentalCollPointProperty(String rentalCollPointProperty) {
        this.rentalCollPointProperty = rentalCollPointProperty;
    }
	public String getCumulativeRecAmountCurRent() {
		return cumulativeRecAmountCurRent;
	}
	public void setCumulativeRecAmountCurRent(String cumulativeRecAmountCurRent) {
		this.cumulativeRecAmountCurRent = cumulativeRecAmountCurRent;
	}
	public String getCumulativeColRateCurRent() {
		return cumulativeColRateCurRent;
	}
	public void setCumulativeColRateCurRent(String cumulativeColRateCurRent) {
		this.cumulativeColRateCurRent = cumulativeColRateCurRent;
	}
	public String getCumulativeRecAmountCurPpt() {
		return cumulativeRecAmountCurPpt;
	}
	public void setCumulativeRecAmountCurPpt(String cumulativeRecAmountCurPpt) {
		this.cumulativeRecAmountCurPpt = cumulativeRecAmountCurPpt;
	}
	public String getCumulativeColRateCurPpt() {
		return cumulativeColRateCurPpt;
	}
	public void setCumulativeColRateCurPpt(String cumulativeColRateCurPpt) {
		this.cumulativeColRateCurPpt = cumulativeColRateCurPpt;
	}

}


