// 
package com.hhz.ump.entity.dly;

// Generated 2010-9-1 11:09:47 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * DlyNote generated by hbm2java
 */
@Entity
@Table(name = "DLY_NOTE")
public class DlyNote implements java.io.Serializable {

	private String dlyNoteId;
	private String noteTitle;
	private String noteContent;
	private String noteBizTypeCd;
	private String tipFlg;
	private Date tipStartDate;
	private Date tipEndDate;
	private String tipTypeCd;
	private String tipPeriodCd;
	private String sendMailFlg;
	private String remark;
	private String creator;
	private String createdDeptCd;
	private Date createdDate;
	private String updator;
	private String updatedDeptCd;
	private Date updatedDate;
	private long recordVersion;
	private Long seq;

	public DlyNote() {
	}

	public DlyNote(String dlyNoteId, long recordVersion) {
		this.dlyNoteId = dlyNoteId;
		this.recordVersion = recordVersion;
	}

	public DlyNote(String dlyNoteId, String noteTitle, String noteContent, String noteBizTypeCd, String tipFlg,
			Date tipStartDate, Date tipEndDate, String tipTypeCd, String tipPeriodCd, String sendMailFlg,
			String remark, String creator, String createdDeptCd, Date createdDate, String updator,
			String updatedDeptCd, Date updatedDate, long recordVersion, Long seq) {
		this.dlyNoteId = dlyNoteId;
		this.noteTitle = noteTitle;
		this.noteContent = noteContent;
		this.noteBizTypeCd = noteBizTypeCd;
		this.tipFlg = tipFlg;
		this.tipStartDate = tipStartDate;
		this.tipEndDate = tipEndDate;
		this.tipTypeCd = tipTypeCd;
		this.tipPeriodCd = tipPeriodCd;
		this.sendMailFlg = sendMailFlg;
		this.remark = remark;
		this.creator = creator;
		this.createdDeptCd = createdDeptCd;
		this.createdDate = createdDate;
		this.updator = updator;
		this.updatedDeptCd = updatedDeptCd;
		this.updatedDate = updatedDate;
		this.recordVersion = recordVersion;
		this.seq = seq;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	@Column(name = "DLY_NOTE_ID", unique = true, nullable = false, length = 50)
	public String getDlyNoteId() {
		return this.dlyNoteId;
	}

	public void setDlyNoteId(String dlyNoteId) {
		this.dlyNoteId = dlyNoteId;
	}

	@Column(name = "NOTE_TITLE", length = 200)
	public String getNoteTitle() {
		return this.noteTitle;
	}

	public void setNoteTitle(String noteTitle) {
		this.noteTitle = noteTitle;
	}

	@Column(name = "NOTE_CONTENT", length = 4000)
	public String getNoteContent() {
		return this.noteContent;
	}

	public void setNoteContent(String noteContent) {
		this.noteContent = noteContent;
	}

	@Column(name = "NOTE_BIZ_TYPE_CD", length = 20)
	public String getNoteBizTypeCd() {
		return this.noteBizTypeCd;
	}

	public void setNoteBizTypeCd(String noteBizTypeCd) {
		this.noteBizTypeCd = noteBizTypeCd;
	}

	@Column(name = "TIP_FLG", length = 1)
	public String getTipFlg() {
		return this.tipFlg;
	}

	public void setTipFlg(String tipFlg) {
		this.tipFlg = tipFlg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIP_START_DATE", length = 7)
	public Date getTipStartDate() {
		return this.tipStartDate;
	}

	public void setTipStartDate(Date tipStartDate) {
		this.tipStartDate = tipStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIP_END_DATE", length = 7)
	public Date getTipEndDate() {
		return this.tipEndDate;
	}

	public void setTipEndDate(Date tipEndDate) {
		this.tipEndDate = tipEndDate;
	}

	@Column(name = "TIP_TYPE_CD", length = 20)
	public String getTipTypeCd() {
		return this.tipTypeCd;
	}

	public void setTipTypeCd(String tipTypeCd) {
		this.tipTypeCd = tipTypeCd;
	}

	@Column(name = "TIP_PERIOD_CD", length = 20)
	public String getTipPeriodCd() {
		return this.tipPeriodCd;
	}

	public void setTipPeriodCd(String tipPeriodCd) {
		this.tipPeriodCd = tipPeriodCd;
	}

	@Column(name = "SEND_MAIL_FLG", length = 1)
	public String getSendMailFlg() {
		return this.sendMailFlg;
	}

	public void setSendMailFlg(String sendMailFlg) {
		this.sendMailFlg = sendMailFlg;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "CREATOR", length = 20)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATED_DEPT_CD", length = 20)
	public String getCreatedDeptCd() {
		return this.createdDeptCd;
	}

	public void setCreatedDeptCd(String createdDeptCd) {
		this.createdDeptCd = createdDeptCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATOR", length = 20)
	public String getUpdator() {
		return this.updator;
	}

	public void setUpdator(String updator) {
		this.updator = updator;
	}

	@Column(name = "UPDATED_DEPT_CD", length = 20)
	public String getUpdatedDeptCd() {
		return this.updatedDeptCd;
	}

	public void setUpdatedDeptCd(String updatedDeptCd) {
		this.updatedDeptCd = updatedDeptCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 7)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "RECORD_VERSION", nullable = false, precision = 10, scale = 0)
	@Version
	public long getRecordVersion() {
		return this.recordVersion;
	}

	public void setRecordVersion(long recordVersion) {
		this.recordVersion = recordVersion;
	}

	@Column(name = "SEQ", precision = 10, scale = 0)
	public Long getSeq() {
		return this.seq;
	}

	public void setSeq(Long seq) {
		this.seq = seq;
	}

    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }

}
