// 
package com.hhz.ump.entity.assm;
// Generated 2012-4-17 9:46:50 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * AssmAccount generated by hbm2java
 */
@Entity
@Table(name="ASSM_ACCOUNT"
    
)
public class AssmAccount  implements java.io.Serializable {


     private String assmAccountId;
     private AssmModelStandard assmModelStandard;
     private AssmModel assmModel;
     private String projectCd;
     private String assmCode;
     private String code;
     private String assmName;
     private String useDepartment;
     private String useStatus;
     private String storageSites;
     private String keeperName;   //PD账号的保管人员
     private String keeperCd;     //PD账号的保管人员CD
     private String keeperName2;  //非PD账号的保管人员
     private String addWay;
     private BigDecimal srcValue;
     private BigDecimal netValue;
     private BigDecimal depreYeadNum;
     private Date useDate;
     private String depreWay;
     private BigDecimal remainVal;
     private String resCds;
     private String assmLevle;
     private String resIds;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;

    public AssmAccount() {
    }

	
    public AssmAccount(String assmAccountId, long recordVersion) {
        this.assmAccountId = assmAccountId;
        this.recordVersion = recordVersion;
    }
    public AssmAccount(String assmAccountId, AssmModelStandard assmModelStandard, AssmModel assmModel,String projectCd,String assmCode, String code, String assmName, String useDepartment, String useStatus, String keeperName, String keeperCd, String keeperName2, String addWay, BigDecimal srcValue,BigDecimal netValue, BigDecimal depreYeadNum, Date useDate, String depreWay, BigDecimal remainVal, String resCds, String assmLevle, String resIds, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion) {
       this.assmAccountId = assmAccountId;
       this.assmModelStandard = assmModelStandard;
       this.assmModel = assmModel;
       this.projectCd = projectCd;
       this.assmCode = assmCode;
       this.code = code;
       this.assmName = assmName;
       this.useDepartment = useDepartment;
       this.useStatus = useStatus;
       this.keeperName = keeperName;
       this.keeperCd = keeperCd;
       this.keeperName2 = keeperName2;
       this.addWay = addWay;
       this.srcValue = srcValue;
       this.netValue = netValue;
       this.depreYeadNum = depreYeadNum;
       this.useDate = useDate;
       this.depreWay = depreWay;
       this.remainVal = remainVal;
       this.resCds = resCds;
       this.assmLevle = assmLevle;
       this.resIds = resIds;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="ASSM_ACCOUNT_ID", unique=true, nullable=false, length=50)
    public String getAssmAccountId() {
        return this.assmAccountId;
    }
    
    public void setAssmAccountId(String assmAccountId) {
        this.assmAccountId = assmAccountId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ASSM_MODEL_STANDARD_ID")
    public AssmModelStandard getAssmModelStandard() {
        return this.assmModelStandard;
    }
    
    public void setAssmModelStandard(AssmModelStandard assmModelStandard) {
        this.assmModelStandard = assmModelStandard;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ASSM_MODEL_ID")
    public AssmModel getAssmModel() {
		return assmModel;
	}

	public void setAssmModel(AssmModel assmModel) {
		this.assmModel = assmModel;
	}


	@Column(name="PROJECT_CD", length=50)
    public String getProjectCd() {
        return this.projectCd;
    }
    
    public void setProjectCd(String projectCd) {
        this.projectCd = projectCd;
    }
    
    @Column(name="ASSM_CODE", length=50)
    public String getAssmCode() {
        return this.assmCode;
    }
    
    public void setAssmCode(String assmCode) {
        this.assmCode = assmCode;
    }
    
    @Column(name="CODE", length=50)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="ASSM_NAME", length=100)
    public String getAssmName() {
        return this.assmName;
    }
    
    public void setAssmName(String assmName) {
        this.assmName = assmName;
    }
    
    @Column(name="USE_DEPARTMENT", length=50)
    public String getUseDepartment() {
        return this.useDepartment;
    }
    
    public void setUseDepartment(String useDepartment) {
        this.useDepartment = useDepartment;
    }
    
    @Column(name="USE_STATUS", length=100)
    public String getUseStatus() {
        return this.useStatus;
    }
    
    public void setUseStatus(String useStatus) {
        this.useStatus = useStatus;
    }
    
    @Column(name="STORAGE_SITES", length=50)
    public String getStorageSites() {
		return storageSites;
	}

	public void setStorageSites(String storageSites) {
		this.storageSites = storageSites;
	}
    
    @Column(name="KEEPER_NAME", length=50)
    public String getKeeperName() {
        return this.keeperName;
    }
    
    public void setKeeperName(String keeperName) {
        this.keeperName = keeperName;
    }
    
    @Column(name="KEEPER_CD", length=50)
    public String getKeeperCd() {
        return this.keeperCd;
    }
    
    public void setKeeperCd(String keeperCd) {
        this.keeperCd = keeperCd;
    }

    @Column(name="KEEPER_NAME2", length=50)
    public String getKeeperName2() {
		return keeperName2;
	}
	public void setKeeperName2(String keeperName2) {
		this.keeperName2 = keeperName2;
	}

	@Column(name="ADD_WAY", length=50)
    public String getAddWay() {
        return this.addWay;
    }
    
    public void setAddWay(String addWay) {
        this.addWay = addWay;
    }
    
    @Column(name="SRC_VALUE", precision=18)
    public BigDecimal getSrcValue() {
        return this.srcValue;
    }
    
    public void setSrcValue(BigDecimal srcValue) {
        this.srcValue = srcValue;
    }
    
    @Column(name="DEPRE_YEAD_NUM", precision=5)
    public BigDecimal getDepreYeadNum() {
        return this.depreYeadNum;
    }
    
    public void setDepreYeadNum(BigDecimal depreYeadNum) {
        this.depreYeadNum = depreYeadNum;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="USE_DATE", length=7)
    public Date getUseDate() {
        return this.useDate;
    }
    
    public void setUseDate(Date useDate) {
        this.useDate = useDate;
    }
    
    @Column(name="DEPRE_WAY", length=100)
    public String getDepreWay() {
        return this.depreWay;
    }
    
    public void setDepreWay(String depreWay) {
        this.depreWay = depreWay;
    }
    
    @Column(name="REMAIN_VAL", precision=18)
    public BigDecimal getRemainVal() {
        return this.remainVal;
    }
    
    public void setRemainVal(BigDecimal remainVal) {
        this.remainVal = remainVal;
    }
    
    @Column(name="RES_CDS", length=1000)
    public String getResCds() {
        return this.resCds;
    }
    
    public void setResCds(String resCds) {
        this.resCds = resCds;
    }
    
    @Column(name="ASSM_LEVLE", length=3)
    public String getAssmLevle() {
        return this.assmLevle;
    }
    
    public void setAssmLevle(String assmLevle) {
        this.assmLevle = assmLevle;
    }
    
    @Column(name="RES_IDS", length=1000)
    public String getResIds() {
        return this.resIds;
    }
    
    public void setResIds(String resIds) {
        this.resIds = resIds;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }

    @Column(name="NET_VALUE", precision=18)
	public BigDecimal getNetValue() {
		return netValue;
	}

    public void setNetValue(BigDecimal netValue) {
		this.netValue = netValue;
	}

}


