// 
package com.hhz.ump.entity.biz;
// Generated 2011-9-22 13:08:46 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.BatchSize;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BizHtlPurchase generated by hbm2java
 */
@Entity
@Table(name="BIZ_HTL_PURCHASE"
    ,schema="POWERDESK"
)
public class BizHtlPurchase  implements java.io.Serializable {


     private String bizHtlPurchaseId;
     private String hotelCd;
     private String hotelName;
     private String itemName;
     private String unitName;
     private BigDecimal marketPrice;
     private BigDecimal lastPrice;
     private BigDecimal price;
     private Date fromDate;
     private Date toDate;
     private String itemTypeCd;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;

    public BizHtlPurchase() {
    }

	
    public BizHtlPurchase(String bizHtlPurchaseId, long recordVersion) {
        this.bizHtlPurchaseId = bizHtlPurchaseId;
        this.recordVersion = recordVersion;
    }
    public BizHtlPurchase(String bizHtlPurchaseId, String hotelCd, String hotelName, String itemName, String unitName, BigDecimal marketPrice, BigDecimal lastPrice, BigDecimal price, Date fromDate, Date toDate, String itemTypeCd, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion) {
       this.bizHtlPurchaseId = bizHtlPurchaseId;
       this.hotelCd = hotelCd;
       this.hotelName = hotelName;
       this.itemName = itemName;
       this.unitName = unitName;
       this.marketPrice = marketPrice;
       this.lastPrice = lastPrice;
       this.price = price;
       this.fromDate = fromDate;
       this.toDate = toDate;
       this.itemTypeCd = itemTypeCd;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIZ_HTL_PURCHASE_ID", unique=true, nullable=false, length=50)
    public String getBizHtlPurchaseId() {
        return this.bizHtlPurchaseId;
    }
    
    public void setBizHtlPurchaseId(String bizHtlPurchaseId) {
        this.bizHtlPurchaseId = bizHtlPurchaseId;
    }
    
    @Column(name="HOTEL_CD", length=20)
    public String getHotelCd() {
        return this.hotelCd;
    }
    
    public void setHotelCd(String hotelCd) {
        this.hotelCd = hotelCd;
    }
    
    @Column(name="HOTEL_NAME", length=100)
    public String getHotelName() {
        return this.hotelName;
    }
    
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }
    
    @Column(name="ITEM_NAME", length=100)
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    
    @Column(name="UNIT_NAME", length=20)
    public String getUnitName() {
        return this.unitName;
    }
    
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }
    
    @Column(name="MARKET_PRICE", precision=10)
    public BigDecimal getMarketPrice() {
        return this.marketPrice;
    }
    
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }
    
    @Column(name="LAST_PRICE", precision=10)
    public BigDecimal getLastPrice() {
        return this.lastPrice;
    }
    
    public void setLastPrice(BigDecimal lastPrice) {
        this.lastPrice = lastPrice;
    }
    
    @Column(name="PRICE", precision=10)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FROM_DATE", length=7)
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TO_DATE", length=7)
    public Date getToDate() {
        return this.toDate;
    }
    
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
    
    @Column(name="ITEM_TYPE_CD", length=20)
    public String getItemTypeCd() {
        return this.itemTypeCd;
    }
    
    public void setItemTypeCd(String itemTypeCd) {
        this.itemTypeCd = itemTypeCd;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }




}


