// 
package com.hhz.uums.entity.bis;
// Generated 2011-1-26 18:57:17 by Hibernate Tools 3.2.2.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * BisSecGroup generated by hbm2java
 */
@Entity
@Table(name="BIS_SEC_GROUP"
    
)
public class BisSecGroup  implements java.io.Serializable {


     private String bisSecGroupId;
     private String groupName;
     private String groupBizCd;
     private Long dispOrderNo;
     private String parentGroupId;
     private String tagTypeCd;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private List<BisSecGroupUserRel> bisSecGroupUserRels = new ArrayList<BisSecGroupUserRel>();

    public BisSecGroup() {
    }

	
    public BisSecGroup(String bisSecGroupId, long recordVersion) {
        this.bisSecGroupId = bisSecGroupId;
        this.recordVersion = recordVersion;
    }
    public BisSecGroup(String bisSecGroupId, String groupName, String groupBizCd, Long dispOrderNo, String parentGroupId, String tagTypeCd, String remark, String creator, String createdCenterCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedPositionCd, Date updatedDate, long recordVersion, List<BisSecGroupUserRel> bisSecGroupUserRels) {
       this.bisSecGroupId = bisSecGroupId;
       this.groupName = groupName;
       this.groupBizCd = groupBizCd;
       this.dispOrderNo = dispOrderNo;
       this.parentGroupId = parentGroupId;
       this.tagTypeCd = tagTypeCd;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.bisSecGroupUserRels = bisSecGroupUserRels;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_SEC_GROUP_ID", unique=true, nullable=false, length=50)
    public String getBisSecGroupId() {
        return this.bisSecGroupId;
    }
    
    public void setBisSecGroupId(String bisSecGroupId) {
        this.bisSecGroupId = bisSecGroupId;
    }
    
    @Column(name="GROUP_NAME", length=50)
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    
    @Column(name="GROUP_BIZ_CD", length=20)
    public String getGroupBizCd() {
        return this.groupBizCd;
    }
    
    public void setGroupBizCd(String groupBizCd) {
        this.groupBizCd = groupBizCd;
    }
    
    @Column(name="DISP_ORDER_NO", precision=18, scale=0)
    public Long getDispOrderNo() {
        return this.dispOrderNo;
    }
    
    public void setDispOrderNo(Long dispOrderNo) {
        this.dispOrderNo = dispOrderNo;
    }
    
    @Column(name="PARENT_GROUP_ID", length=50)
    public String getParentGroupId() {
        return this.parentGroupId;
    }
    
    public void setParentGroupId(String parentGroupId) {
        this.parentGroupId = parentGroupId;
    }
    
    @Column(name="TAG_TYPE_CD", length=20)
    public String getTagTypeCd() {
        return this.tagTypeCd;
    }
    
    public void setTagTypeCd(String tagTypeCd) {
        this.tagTypeCd = tagTypeCd;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="bisSecGroup")
    @BatchSize(size=10)
public List<BisSecGroupUserRel> getBisSecGroupUserRels() {
        return this.bisSecGroupUserRels;
    }
    
    public void setBisSecGroupUserRels(List<BisSecGroupUserRel> bisSecGroupUserRels) {
        this.bisSecGroupUserRels = bisSecGroupUserRels;
    }

    private String createdDeptCd;
    private String updatedDeptCd;
    @Column(name="CREATED_DEPT_CD", length=20)
	public String getCreatedDeptCd() {
		return createdDeptCd;
	}


	public void setCreatedDeptCd(String createdDeptCd) {
		this.createdDeptCd = createdDeptCd;
	}

	@Column(name="UPDATED_DEPT_CD", length=20)
	public String getUpdatedDeptCd() {
		return updatedDeptCd;
	}


	public void setUpdatedDeptCd(String updatedDeptCd) {
		this.updatedDeptCd = updatedDeptCd;
	}




}


