// 
package com.hhz.ump.entity.res;
// Generated 2011-3-30 13:29:48 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * ResApproveStep generated by hbm2java
 */
@Entity
@Table(name="RES_APPROVE_STEP"
    
)
public class ResApproveStep  implements java.io.Serializable {


     private String resApproveStepId;
     private ResConditonType resConditonType;
     private String nodeCd;
     private Long approveLevel;
     private String remark;
     private Long timeLimit;
     private String creator;
     private String verifyCd;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private String groupNodeCd;
     private String createdCenterCd;
     private String createdPositionCd;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Long sequenceNo;
     private String stepOptionCd;
     private String backFlg;//是否有驳回权限
     private Long approveRank;//
     
     @Column(name="BACK_FLG", length=1)
	public String getBackFlg() {
		return backFlg;
	}

	public void setBackFlg(String backFlg) {
		this.backFlg = backFlg;
	}
	 @Column(name="APPROVE_RANK", length=20)
	public Long getApproveRank() {
		return approveRank;
	}

	public void setApproveRank(Long approveRank) {
		this.approveRank = approveRank;
	}

	@Column(name="SEQUENCE_NO", precision=10, scale=0)
     public Long getSequenceNo() {
         return this.sequenceNo;
     }
     
     public void setSequenceNo(Long sequenceNo) {
         this.sequenceNo = sequenceNo;
     }
    public ResApproveStep() {
    }

	
    public ResApproveStep(String resApproveStepId, ResConditonType resConditonType, long recordVersion) {
        this.resApproveStepId = resApproveStepId;
        this.resConditonType = resConditonType;
        this.recordVersion = recordVersion;
    }
    public ResApproveStep(String resApproveStepId, ResConditonType resConditonType, String nodeCd, Long approveLevel, String remark, Long timeLimit, String creator, String verifyCd, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion, String groupNodeCd, String createdCenterCd, String createdPositionCd, String updatedCenterCd, String updatedPositionCd,long approveRank) {
       this.resApproveStepId = resApproveStepId;
       this.resConditonType = resConditonType;
       this.nodeCd = nodeCd;
       this.approveLevel = approveLevel;
       this.remark = remark;
       this.timeLimit = timeLimit;
       this.creator = creator;
       this.verifyCd = verifyCd;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.groupNodeCd = groupNodeCd;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.approveRank = approveRank;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="RES_APPROVE_STEP_ID", unique=true, nullable=false, length=50)
    public String getResApproveStepId() {
        return this.resApproveStepId;
    }
    
    public void setResApproveStepId(String resApproveStepId) {
        this.resApproveStepId = resApproveStepId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RES_CONDITON_TYPE_ID", nullable=false)
    public ResConditonType getResConditonType() {
        return this.resConditonType;
    }
    
    public void setResConditonType(ResConditonType resConditonType) {
        this.resConditonType = resConditonType;
    }
    
    @Column(name="NODE_CD", length=20)
    public String getNodeCd() {
        return this.nodeCd;
    }
    
    public void setNodeCd(String nodeCd) {
        this.nodeCd = nodeCd;
    }
    
    @Column(name="APPROVE_LEVEL", precision=10, scale=0)
    public Long getApproveLevel() {
        return this.approveLevel;
    }
    
    public void setApproveLevel(Long approveLevel) {
        this.approveLevel = approveLevel;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="TIME_LIMIT", precision=10, scale=0)
    public Long getTimeLimit() {
        return this.timeLimit;
    }
    
    public void setTimeLimit(Long timeLimit) {
        this.timeLimit = timeLimit;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="VERIFY_CD", length=20)
    public String getVerifyCd() {
        return this.verifyCd;
    }
    
    public void setVerifyCd(String verifyCd) {
        this.verifyCd = verifyCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="GROUP_NODE_CD", length=20)
    public String getGroupNodeCd() {
        return this.groupNodeCd;
    }
    
    public void setGroupNodeCd(String groupNodeCd) {
        this.groupNodeCd = groupNodeCd;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    
    @Column(name="STEP_OPTION_CD", length=20)
	public String getStepOptionCd() {
		return stepOptionCd;
	}

	public void setStepOptionCd(String stepOptionCd) {
		this.stepOptionCd = stepOptionCd;
	}




}


