// 
package com.hhz.ump.entity.planold;
// Generated 2010-8-9 15:22:34 by Hibernate Tools 3.2.4.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * PlanExecutionPlanNode generated by hbm2java
 */
@Entity
@Table(name="PLAN_EXECUTION_PLAN_NODE_OLD"
    ,schema="POWERDESK"
)
public class PlanExecutionPlanNodeOld  implements java.io.Serializable {

	private static final long serialVersionUID = 5710881072417731691L;
	private String planExecutionPlanNodeId;
     private String resOrgCd;
     private String resOrgName;
     private String corOrgName;
     private String outputFiles;
     private String corOrgCd;
     private String controlNodeFlg;
     private String nodeCd;
     private String nodeName;
     private String activeFlg;
     private String resCenterOrgCd;
     private String planTypeCd;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private String treeType;
     private String treeParentNodeId;
     private String treeParentNodeName;
     private long order1;
     private long order2;
     private long order3;
     private String relDisplayNodeId;
     private String relDisplayNodeName;
     
    public PlanExecutionPlanNodeOld() {
    }

	
    public PlanExecutionPlanNodeOld(String planExecutionPlanNodeId, long recordVersion) {
        this.planExecutionPlanNodeId = planExecutionPlanNodeId;
        this.recordVersion = recordVersion;
    }
    public PlanExecutionPlanNodeOld(String planExecutionPlanNodeId, String resOrgCd, String resOrgName, String corOrgName, String outputFiles, String corOrgCd, String controlNodeFlg, String nodeCd, String nodeName, String activeFlg, String resCenterOrgCd,String planTypeCd, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion, String treeType, String treeParentNodeId,String treeParentNodeName, long order1, long order2, long order3,String relDisplayNodeId,String relDisplayNodeName) {
       this.planExecutionPlanNodeId = planExecutionPlanNodeId;
       this.resOrgCd = resOrgCd;
       this.resOrgName = resOrgName;
       this.corOrgName = corOrgName;
       this.outputFiles = outputFiles;
       this.corOrgCd = corOrgCd;
       this.controlNodeFlg = controlNodeFlg;
       this.nodeCd = nodeCd;
       this.nodeName = nodeName;
       this.activeFlg = activeFlg;
       this.resCenterOrgCd = resCenterOrgCd;
       this.planTypeCd = planTypeCd;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.treeType = treeType;
       this.treeParentNodeId = treeParentNodeId;
       this.treeParentNodeName = treeParentNodeName;
       this.order1 = order1;
       this.order2 = order2;
       this.order3 = order3;
       this.relDisplayNodeId = relDisplayNodeId;
       this.relDisplayNodeName = relDisplayNodeName;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="PLAN_EXECUTION_PLAN_NODE_ID", unique=true, nullable=false, length=50)
    public String getPlanExecutionPlanNodeId() {
        return this.planExecutionPlanNodeId;
    }
    
    public void setPlanExecutionPlanNodeId(String planExecutionPlanNodeId) {
        this.planExecutionPlanNodeId = planExecutionPlanNodeId;
    }

    
    @Column(name="RES_ORG_CD", length=50)
    public String getResOrgCd() {
        return this.resOrgCd;
    }
    
    public void setResOrgCd(String resOrgCd) {
        this.resOrgCd = resOrgCd;
    }

    
    @Column(name="RES_ORG_NAME", length=100)
    public String getResOrgName() {
        return this.resOrgName;
    }
    
    public void setResOrgName(String resOrgName) {
        this.resOrgName = resOrgName;
    }

    
    @Column(name="COR_ORG_NAME", length=100)
    public String getCorOrgName() {
        return this.corOrgName;
    }
    
    public void setCorOrgName(String corOrgName) {
        this.corOrgName = corOrgName;
    }

    
    @Column(name="OUTPUT_FILES", length=200)
    public String getOutputFiles() {
        return this.outputFiles;
    }
    
    public void setOutputFiles(String outputFiles) {
        this.outputFiles = outputFiles;
    }

    
    @Column(name="COR_ORG_CD", length=50)
    public String getCorOrgCd() {
        return this.corOrgCd;
    }
    
    public void setCorOrgCd(String corOrgCd) {
        this.corOrgCd = corOrgCd;
    }

    
    @Column(name="CONTROL_NODE_FLG", length=1)
    public String getControlNodeFlg() {
        return this.controlNodeFlg;
    }
    
    public void setControlNodeFlg(String controlNodeFlg) {
        this.controlNodeFlg = controlNodeFlg;
    }

    
    @Column(name="NODE_CD", length=20)
    public String getNodeCd() {
        return this.nodeCd;
    }
    
    public void setNodeCd(String nodeCd) {
        this.nodeCd = nodeCd;
    }

    
    @Column(name="NODE_NAME", length=100)
    public String getNodeName() {
        return this.nodeName;
    }
    
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    
    @Column(name="ACTIVE_FLG", length=1)
    public String getActiveFlg() {
        return this.activeFlg;
    }
    
    public void setActiveFlg(String activeFlg) {
        this.activeFlg = activeFlg;
    }

    
    @Column(name="RES_CENTER_ORG_CD", length=20)
    public String getResCenterOrgCd() {
        return this.resCenterOrgCd;
    }
    
    public void setResCenterOrgCd(String resCenterOrgCd) {
        this.resCenterOrgCd = resCenterOrgCd;
    }

    @Column(name="PLAN_TYPE_CD", length=20)
    public String getPlanTypeCd() {
        return this.planTypeCd;
    }
    
    public void setPlanTypeCd(String planTypeCd) {
        this.planTypeCd = planTypeCd;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }


    @Column(name="TREE_TYPE", length=1)
    public String getTreeType() {
        return this.treeType;
    }
    
    public void setTreeType(String treeType) {
        this.treeType = treeType;
    }
    
    @Column(name="TREE_PARENT_NODE_ID", length=50)
    public String getTreeParentNodeId() {
        return this.treeParentNodeId;
    }
    
    public void setTreeParentNodeId(String treeParentNodeId) {
        this.treeParentNodeId = treeParentNodeId;
    }

    @Column(name="TREE_PARENT_NODE_NAME", length=100)
    public String getTreeParentNodeName() {
        return this.treeParentNodeName;
    }
    
    public void setTreeParentNodeName(String treeParentNodeName) {
        this.treeParentNodeName = treeParentNodeName;
    }
    @Column(name="ORDER1", nullable=true, precision=10, scale=0)
    @Version 
    public long getOrder1() {
        return this.order1;
    }
    
    public void setOrder1(long order1) {
        this.order1 = order1;
    }
    
    @Column(name="ORDER2", nullable=true, precision=10, scale=0)
    @Version 
    public long getOrder2() {
        return this.order2;
    }
    
    public void setOrder2(long order2) {
        this.order2 = order2;
    }

    @Column(name="ORDER3", nullable=true, precision=10, scale=0)
    @Version 
    public long getOrder3() {
        return this.order3;
    }
    
    public void setOrder3(long order3) {
        this.order3 = order3;
    }

    
    @Column(name="REL_DISPLAY_NODE_ID", length=50)
	public String getRelDisplayNodeId() {
		return relDisplayNodeId;
	}


	public void setRelDisplayNodeId(String relDisplayNodeId) {
		this.relDisplayNodeId = relDisplayNodeId;
	}
    @Column(name="REL_DISPLAY_NODE_NAME", length=100)
	public String getRelDisplayNodeName() {
		return relDisplayNodeName;
	}


	public void setRelDisplayNodeName(String relDisplayNodeName) {
		this.relDisplayNodeName = relDisplayNodeName;
	}
}


