// 
package com.hhz.ump.entity.cost;
// Generated 2012-6-14 19:08:43 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * CostMate generated by hbm2java
 */
@Entity
@Table(name="COST_MATE"
    ,schema="POWERDESK"
)
public class CostMate  implements java.io.Serializable {


     private String costMateId;
     private String mateName;
     private Long enableFlg;
     private String memoDesc;
     private String fomuDesc;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String calcTypeCd;
     private String parentModuleId;
     private String mateBizCd;
     private BigDecimal basePrice;
     private BigDecimal lowPrice;
     private BigDecimal highPrice;
     private BigDecimal floatRate;
     private BigDecimal floatRateZa;
     private BigDecimal floatRateZb;
     private BigDecimal floatRateZc;
     private String specTypeCd;
     private BigDecimal totalFloatRate;
     private List<CostMatePrice> costMatePrices = new ArrayList<CostMatePrice>();
     private List<CostMateCol> costMateCols = new ArrayList<CostMateCol>();

    public CostMate() {
    }

	
    public CostMate(String costMateId, long recordVersion) {
        this.costMateId = costMateId;
        this.recordVersion = recordVersion;
    }
    public CostMate(String costMateId, String mateName, Long enableFlg, String memoDesc, String fomuDesc, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, String calcTypeCd, String parentModuleId, String mateBizCd, BigDecimal basePrice, BigDecimal lowPrice, BigDecimal highPrice, BigDecimal floatRate, BigDecimal floatRateZa, BigDecimal floatRateZb, BigDecimal floatRateZc, String specTypeCd, BigDecimal totalFloatRate, List<CostMatePrice> costMatePrices, List<CostMateCol> costMateCols) {
       this.costMateId = costMateId;
       this.mateName = mateName;
       this.enableFlg = enableFlg;
       this.memoDesc = memoDesc;
       this.fomuDesc = fomuDesc;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.calcTypeCd = calcTypeCd;
       this.parentModuleId = parentModuleId;
       this.mateBizCd = mateBizCd;
       this.basePrice = basePrice;
       this.lowPrice = lowPrice;
       this.highPrice = highPrice;
       this.floatRate = floatRate;
       this.floatRateZa = floatRateZa;
       this.floatRateZb = floatRateZb;
       this.floatRateZc = floatRateZc;
       this.specTypeCd = specTypeCd;
       this.totalFloatRate = totalFloatRate;
       this.costMatePrices = costMatePrices;
       this.costMateCols = costMateCols;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="COST_MATE_ID", unique=true, nullable=false, length=50)
    public String getCostMateId() {
        return this.costMateId;
    }
    
    public void setCostMateId(String costMateId) {
        this.costMateId = costMateId;
    }
    
    @Column(name="MATE_NAME", length=400)
    public String getMateName() {
        return this.mateName;
    }
    
    public void setMateName(String mateName) {
        this.mateName = mateName;
    }
    
    @Column(name="ENABLE_FLG", precision=10, scale=0)
    public Long getEnableFlg() {
        return this.enableFlg;
    }
    
    public void setEnableFlg(Long enableFlg) {
        this.enableFlg = enableFlg;
    }
    
    @Column(name="MEMO_DESC", length=400)
    public String getMemoDesc() {
        return this.memoDesc;
    }
    
    public void setMemoDesc(String memoDesc) {
        this.memoDesc = memoDesc;
    }
    
    @Column(name="FOMU_DESC", length=400)
    public String getFomuDesc() {
        return this.fomuDesc;
    }
    
    public void setFomuDesc(String fomuDesc) {
        this.fomuDesc = fomuDesc;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="CALC_TYPE_CD", length=20)
    public String getCalcTypeCd() {
        return this.calcTypeCd;
    }
    
    public void setCalcTypeCd(String calcTypeCd) {
        this.calcTypeCd = calcTypeCd;
    }
    
    @Column(name="PARENT_MODULE_ID", length=50)
    public String getParentModuleId() {
        return this.parentModuleId;
    }
    
    public void setParentModuleId(String parentModuleId) {
        this.parentModuleId = parentModuleId;
    }
    
    @Column(name="MATE_BIZ_CD", length=50)
    public String getMateBizCd() {
        return this.mateBizCd;
    }
    
    public void setMateBizCd(String mateBizCd) {
        this.mateBizCd = mateBizCd;
    }
    
    @Column(name="BASE_PRICE", precision=18, scale=2)
    public BigDecimal getBasePrice() {
        return this.basePrice;
    }
    
    public void setBasePrice(BigDecimal basePrice) {
        this.basePrice = basePrice;
    }
    
    @Column(name="LOW_PRICE", precision=18, scale=2)
    public BigDecimal getLowPrice() {
        return this.lowPrice;
    }
    
    public void setLowPrice(BigDecimal lowPrice) {
        this.lowPrice = lowPrice;
    }
    
    @Column(name="HIGH_PRICE", precision=18, scale=2)
    public BigDecimal getHighPrice() {
        return this.highPrice;
    }
    
    public void setHighPrice(BigDecimal highPrice) {
        this.highPrice = highPrice;
    }
    
    @Column(name="FLOAT_RATE", precision=18, scale=2)
    public BigDecimal getFloatRate() {
        return this.floatRate;
    }
    
    public void setFloatRate(BigDecimal floatRate) {
        this.floatRate = floatRate;
    }
    
    @Column(name="FLOAT_RATE_ZA", precision=18, scale=2)
    public BigDecimal getFloatRateZa() {
        return this.floatRateZa;
    }
    
    public void setFloatRateZa(BigDecimal floatRateZa) {
        this.floatRateZa = floatRateZa;
    }
    
    @Column(name="FLOAT_RATE_ZB", precision=18, scale=2)
    public BigDecimal getFloatRateZb() {
        return this.floatRateZb;
    }
    
    public void setFloatRateZb(BigDecimal floatRateZb) {
        this.floatRateZb = floatRateZb;
    }
    
    @Column(name="FLOAT_RATE_ZC", precision=18, scale=2)
    public BigDecimal getFloatRateZc() {
        return this.floatRateZc;
    }
    
    public void setFloatRateZc(BigDecimal floatRateZc) {
        this.floatRateZc = floatRateZc;
    }
    
    @Column(name="SPEC_TYPE_CD", length=20)
    public String getSpecTypeCd() {
        return this.specTypeCd;
    }
    
    public void setSpecTypeCd(String specTypeCd) {
        this.specTypeCd = specTypeCd;
    }
    
    @Column(name="TOTAL_FLOAT_RATE", precision=18, scale=2)
    public BigDecimal getTotalFloatRate() {
        return this.totalFloatRate;
    }
    
    public void setTotalFloatRate(BigDecimal totalFloatRate) {
        this.totalFloatRate = totalFloatRate;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="costMate")
    @BatchSize(size=10)
public List<CostMatePrice> getCostMatePrices() {
        return this.costMatePrices;
    }
    
    public void setCostMatePrices(List<CostMatePrice> costMatePrices) {
        this.costMatePrices = costMatePrices;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="costMate")
    @BatchSize(size=10)
public List<CostMateCol> getCostMateCols() {
        return this.costMateCols;
    }
    
    public void setCostMateCols(List<CostMateCol> costMateCols) {
        this.costMateCols = costMateCols;
    }




}


