// 
package com.hhz.ump.entity.cost;
// Generated 2012-2-20 20:44:07 by Hibernate Tools 3.2.2.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * CostProjectSection generated by hbm2java
 */
@Entity
@Table(name="COST_PROJECT_SECTION"
    ,schema="POWERDESK"
)
public class CostProjectSection  implements java.io.Serializable {


     private String costProjectSectionId;
     private String projectCd;
     private String projectName;
     private String sectionCd;
     private String sectionBizCd;
     private String sectionName;
     private String briefName;
     private String defaultFlg;
     private Long sequenceNo;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private List<CostBudgetMonth> costBudgetMonths = new ArrayList<CostBudgetMonth>();
     private List<CostBudgetYear> costBudgetYears = new ArrayList<CostBudgetYear>();

    public CostProjectSection() {
    }

	
    public CostProjectSection(String costProjectSectionId, long recordVersion) {
        this.costProjectSectionId = costProjectSectionId;
        this.recordVersion = recordVersion;
    }
    public CostProjectSection(String costProjectSectionId, String projectCd, String projectName,String sectionCd, String sectionBizCd, String sectionName,String briefName,String defaultFlg, Long sequenceNo, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, List<CostBudgetMonth> costBudgetMonths, List<CostBudgetYear> costBudgetYears) {
       this.costProjectSectionId = costProjectSectionId;
       this.projectCd = projectCd;
       this.projectName = projectName;
       this.sectionCd = sectionCd;
       this.sectionBizCd = sectionBizCd;
       this.sectionName = sectionName;
       this.briefName = briefName;
       this.defaultFlg = defaultFlg;
       this.sequenceNo = sequenceNo;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.costBudgetMonths = costBudgetMonths;
       this.costBudgetYears = costBudgetYears;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="COST_PROJECT_SECTION_ID", unique=true, nullable=false, length=50)
    public String getCostProjectSectionId() {
        return this.costProjectSectionId;
    }
    
    public void setCostProjectSectionId(String costProjectSectionId) {
        this.costProjectSectionId = costProjectSectionId;
    }
    
    @Column(name="PROJECT_CD", length=50)
    public String getProjectCd() {
        return this.projectCd;
    }
    
    public void setProjectCd(String projectCd) {
        this.projectCd = projectCd;
    }
    
    @Column(name="PROJECT_NAME", length=100)
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    @Column(name="SECTION_CD", length=50)
    public String getSectionCd() {
        return this.sectionCd;
    }
    
    public void setSectionCd(String sectionCd) {
        this.sectionCd = sectionCd;
    }
    
    @Column(name="SECTION_BIZ_CD", length=50)
    public String getSectionBizCd() {
        return this.sectionBizCd;
    }
    
    public void setSectionBizCd(String sectionBizCd) {
        this.sectionBizCd = sectionBizCd;
    }
    
    @Column(name="SECTION_NAME", length=100)
    public String getSectionName() {
        return this.sectionName;
    }
    
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }
    
    @Column(name="BRIEF_NAME", length=100)
    public String getBriefName() {
        return this.briefName;
    }
    
    public void setBriefName(String briefName) {
        this.briefName = briefName;
    }

    @Column(name="DEFAULT_FLG", length=1)
    public String getDefaultFlg() {
        return this.defaultFlg;
    }
    
    public void setDefaultFlg(String defaultFlg) {
        this.defaultFlg = defaultFlg;
    }
    
    @Column(name="SEQUENCE_NO", precision=10, scale=0)
    public Long getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Long sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="costProjectSection")
    @BatchSize(size=10)
public List<CostBudgetMonth> getCostBudgetMonths() {
        return this.costBudgetMonths;
    }
    
    public void setCostBudgetMonths(List<CostBudgetMonth> costBudgetMonths) {
        this.costBudgetMonths = costBudgetMonths;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="costProjectSection")
    @BatchSize(size=10)
public List<CostBudgetYear> getCostBudgetYears() {
        return this.costBudgetYears;
    }
    
    public void setCostBudgetYears(List<CostBudgetYear> costBudgetYears) {
        this.costBudgetYears = costBudgetYears;
    }




}


