// 
package com.hhz.ump.entity.mate;
// Generated 2011-8-4 11:53:15 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * MateCountDetail generated by hbm2java
 */
@Entity
@Table(name="MATE_COUNT_DETAIL"
    
)
public class MateCountDetail  implements java.io.Serializable {


     private String mateCountDetailId;
     private MateCountBasic mateCountBasic;
     private String useUnitName;
     private String exeContName;
     private String useSpace;
     private Date insDate;
     private Date fadeDate;
     private String mateTasname;
     private String mateBrand;
     private String mateChar;
     private String mateStan;
     private String mateType;
     private String unit;
     private BigDecimal exeUnitApplBud;
     private BigDecimal realSupply;
     private BigDecimal exeUnitRealUse;
     private BigDecimal stockAll;
     private String projectCd;
     private String contNo;
     private BigDecimal exeCoutSingle;
     private BigDecimal exeCoutGroup;
     private BigDecimal countSupplyBud;
     private BigDecimal buyCoutSingle;
     private BigDecimal buyCoutGroup;
     private String insRegisterNumber;
     private Boolean insOutBl;
     private String priceWay;
     private String remark;
     private Date createdDate;
     private Date updatedDate;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private long recordVersion;
     private String mateAttaId;
     private String clearAudit;
     private String stockManager;
     private String storeSignAtta;
     private Boolean importTypeFlg;

    public MateCountDetail() {
    }

	
    public MateCountDetail(String mateCountDetailId, MateCountBasic mateCountBasic, long recordVersion) {
        this.mateCountDetailId = mateCountDetailId;
        this.mateCountBasic = mateCountBasic;
        this.recordVersion = recordVersion;
    }
    public MateCountDetail(String mateCountDetailId, MateCountBasic mateCountBasic, String useUnitName, String exeContName, String useSpace, Date insDate, Date fadeDate, String mateTasname, String mateBrand, String mateChar, String mateStan, String mateType, String unit, BigDecimal exeUnitApplBud, BigDecimal realSupply, BigDecimal exeUnitRealUse, BigDecimal stockAll, String projectCd, String contNo, BigDecimal exeCoutSingle, BigDecimal exeCoutGroup, BigDecimal countSupplyBud, BigDecimal buyCoutSingle, BigDecimal buyCoutGroup, String insRegisterNumber, Boolean insOutBl, String priceWay, String remark, Date createdDate, Date updatedDate, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, long recordVersion, String mateAttaId, String clearAudit, String stockManager, String storeSignAtta, boolean importTypeFlg) {
       this.mateCountDetailId = mateCountDetailId;
       this.mateCountBasic = mateCountBasic;
       this.useUnitName = useUnitName;
       this.exeContName = exeContName;
       this.useSpace = useSpace;
       this.insDate = insDate;
       this.fadeDate = fadeDate;
       this.mateTasname = mateTasname;
       this.mateBrand = mateBrand;
       this.mateChar = mateChar;
       this.mateStan = mateStan;
       this.mateType = mateType;
       this.unit = unit;
       this.exeUnitApplBud = exeUnitApplBud;
       this.realSupply = realSupply;
       this.exeUnitRealUse = exeUnitRealUse;
       this.stockAll = stockAll;
       this.projectCd = projectCd;
       this.contNo = contNo;
       this.exeCoutSingle = exeCoutSingle;
       this.exeCoutGroup = exeCoutGroup;
       this.countSupplyBud = countSupplyBud;
       this.buyCoutSingle = buyCoutSingle;
       this.buyCoutGroup = buyCoutGroup;
       this.insRegisterNumber = insRegisterNumber;
       this.insOutBl = insOutBl;
       this.priceWay = priceWay;
       this.remark = remark;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.recordVersion = recordVersion;
       this.mateAttaId = mateAttaId;
       this.clearAudit = clearAudit;
       this.stockManager = stockManager;
       this.storeSignAtta = storeSignAtta;
       this.importTypeFlg = importTypeFlg;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="MATE_COUNT_DETAIL_ID", unique=true, nullable=false, length=50)
    public String getMateCountDetailId() {
        return this.mateCountDetailId;
    }
    
    public void setMateCountDetailId(String mateCountDetailId) {
        this.mateCountDetailId = mateCountDetailId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MATE_COUNT_BASIC_ID", nullable=false)
    public MateCountBasic getMateCountBasic() {
        return this.mateCountBasic;
    }
    
    public void setMateCountBasic(MateCountBasic mateCountBasic) {
        this.mateCountBasic = mateCountBasic;
    }
    
    @Column(name="USE_UNIT_NAME", length=100)
    public String getUseUnitName() {
        return this.useUnitName;
    }
    
    public void setUseUnitName(String useUnitName) {
        this.useUnitName = useUnitName;
    }
    
    @Column(name="EXE_CONT_NAME", length=100)
    public String getExeContName() {
        return this.exeContName;
    }
    
    public void setExeContName(String exeContName) {
        this.exeContName = exeContName;
    }
    
    @Column(name="USE_SPACE", length=100)
    public String getUseSpace() {
        return this.useSpace;
    }
    
    public void setUseSpace(String useSpace) {
        this.useSpace = useSpace;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INS_DATE", length=7)
    public Date getInsDate() {
        return this.insDate;
    }
    
    public void setInsDate(Date insDate) {
        this.insDate = insDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FADE_DATE", length=7)
    public Date getFadeDate() {
        return this.fadeDate;
    }
    
    public void setFadeDate(Date fadeDate) {
        this.fadeDate = fadeDate;
    }
    
    @Column(name="MATE_TASNAME", length=100)
    public String getMateTasname() {
        return this.mateTasname;
    }
    
    public void setMateTasname(String mateTasname) {
        this.mateTasname = mateTasname;
    }
    
    @Column(name="MATE_BRAND", length=100)
    public String getMateBrand() {
        return this.mateBrand;
    }
    
    public void setMateBrand(String mateBrand) {
        this.mateBrand = mateBrand;
    }
    
    @Column(name="MATE_CHAR", length=100)
    public String getMateChar() {
        return this.mateChar;
    }
    
    public void setMateChar(String mateChar) {
        this.mateChar = mateChar;
    }
    
    @Column(name="MATE_STAN", length=100)
    public String getMateStan() {
        return this.mateStan;
    }
    
    public void setMateStan(String mateStan) {
        this.mateStan = mateStan;
    }
    
    @Column(name="MATE_TYPE", length=100)
    public String getMateType() {
        return this.mateType;
    }
    
    public void setMateType(String mateType) {
        this.mateType = mateType;
    }
    
    @Column(name="UNIT", length=200)
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    
    @Column(name="EXE_UNIT_APPL_BUD", precision=15, scale=3)
    public BigDecimal getExeUnitApplBud() {
        return this.exeUnitApplBud;
    }
    
    public void setExeUnitApplBud(BigDecimal exeUnitApplBud) {
        this.exeUnitApplBud = exeUnitApplBud;
    }
    
    @Column(name="REAL_SUPPLY", precision=15, scale=3)
    public BigDecimal getRealSupply() {
        return this.realSupply;
    }
    
    public void setRealSupply(BigDecimal realSupply) {
        this.realSupply = realSupply;
    }
    
    @Column(name="EXE_UNIT_REAL_USE", precision=15, scale=3)
    public BigDecimal getExeUnitRealUse() {
        return this.exeUnitRealUse;
    }
    
    public void setExeUnitRealUse(BigDecimal exeUnitRealUse) {
        this.exeUnitRealUse = exeUnitRealUse;
    }
    
    @Column(name="STOCK_ALL", precision=20)
    public BigDecimal getStockAll() {
        return this.stockAll;
    }
    
    public void setStockAll(BigDecimal stockAll) {
        this.stockAll = stockAll;
    }
    
    @Column(name="PROJECT_CD", length=10)
    public String getProjectCd() {
        return this.projectCd;
    }
    
    public void setProjectCd(String projectCd) {
        this.projectCd = projectCd;
    }
    
    @Column(name="CONT_NO", length=50)
    public String getContNo() {
        return this.contNo;
    }
    
    public void setContNo(String contNo) {
        this.contNo = contNo;
    }
    
    @Column(name="EXE_COUT_SINGLE", precision=15, scale=3)
    public BigDecimal getExeCoutSingle() {
        return this.exeCoutSingle;
    }
    
    public void setExeCoutSingle(BigDecimal exeCoutSingle) {
        this.exeCoutSingle = exeCoutSingle;
    }
    
    @Column(name="EXE_COUT_GROUP", precision=21, scale=3)
    public BigDecimal getExeCoutGroup() {
        return this.exeCoutGroup;
    }
    
    public void setExeCoutGroup(BigDecimal exeCoutGroup) {
        this.exeCoutGroup = exeCoutGroup;
    }
    
    @Column(name="COUNT_SUPPLY_BUD", precision=15, scale=3)
    public BigDecimal getCountSupplyBud() {
        return this.countSupplyBud;
    }
    
    public void setCountSupplyBud(BigDecimal countSupplyBud) {
        this.countSupplyBud = countSupplyBud;
    }
    
    @Column(name="BUY_COUT_SINGLE", precision=15, scale=3)
    public BigDecimal getBuyCoutSingle() {
        return this.buyCoutSingle;
    }
    
    public void setBuyCoutSingle(BigDecimal buyCoutSingle) {
        this.buyCoutSingle = buyCoutSingle;
    }
    
    @Column(name="BUY_COUT_GROUP", precision=21, scale=3)
    public BigDecimal getBuyCoutGroup() {
        return this.buyCoutGroup;
    }
    
    public void setBuyCoutGroup(BigDecimal buyCoutGroup) {
        this.buyCoutGroup = buyCoutGroup;
    }
    
    @Column(name="INS_REGISTER_NUMBER", length=50)
    public String getInsRegisterNumber() {
        return this.insRegisterNumber;
    }
    
    public void setInsRegisterNumber(String insRegisterNumber) {
        this.insRegisterNumber = insRegisterNumber;
    }
    
    @Column(name="INS_OUT_BL", precision=1, scale=0)
    public Boolean getInsOutBl() {
        return this.insOutBl;
    }
    
    public void setInsOutBl(Boolean insOutBl) {
        this.insOutBl = insOutBl;
    }

    
    @Column(name="IMPORT_TYPE_FLG", precision=1, scale=0)
    public Boolean getImportTypeFlg() {
        return this.importTypeFlg;
    }
    
    public void setImportTypeFlg(Boolean importTypeFlg) {
        this.importTypeFlg = importTypeFlg;
    }
    
    
    
    @Column(name="PRICE_WAY", length=2)
    public String getPriceWay() {
        return this.priceWay;
    }
    
    public void setPriceWay(String priceWay) {
        this.priceWay = priceWay;
    }
    
    @Column(name="REMARK", length=1000)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="MATE_ATTA_ID", length=50)
    public String getMateAttaId() {
        return this.mateAttaId;
    }
    
    public void setMateAttaId(String mateAttaId) {
        this.mateAttaId = mateAttaId;
    }
    
    @Column(name="CLEAR_AUDIT", length=2)
    public String getClearAudit() {
        return this.clearAudit;
    }
    
    public void setClearAudit(String clearAudit) {
        this.clearAudit = clearAudit;
    }
    
    @Column(name="STOCK_MANAGER", length=200)
    public String getStockManager() {
        return this.stockManager;
    }
    
    public void setStockManager(String stockManager) {
        this.stockManager = stockManager;
    }
    
    @Column(name="STORE_SIGN_ATTA", length=50)
    public String getStoreSignAtta() {
        return this.storeSignAtta;
    }
    
    public void setStoreSignAtta(String storeSignAtta) {
        this.storeSignAtta = storeSignAtta;
    }




}


