// 
package com.hhz.ump.entity.res;
// Generated 2011-3-30 13:29:48 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * ResApproveDelay generated by hbm2java
 */
@Entity
@Table(name="RES_APPROVE_DELAY"
    ,schema="POWERDESK"
)
public class ResApproveDelay  implements java.io.Serializable {


     private String resApproveDelayId;
     private ResApproveInfo resApproveInfo;
     private String applyUserCd;
     private long delayTime;
     private String applyReason;
     private String approveUserCd;
     private Date approveDate;
     private String approveOptionCd;
     private String applyTypeCd;
     private String confirmUserCd;
     private Date confirmDate;
     private String confirmOptionCd;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private String statusCd;
     private String nodeCd;
     private String approveRemark;
     private String confirmRemark;
     private Date updatedDate;
     private long recordVersion;
     private Long approveLevel;
    public ResApproveDelay() {
    }

	
    public ResApproveDelay(String resApproveDelayId, ResApproveInfo resApproveInfo, String applyUserCd, long delayTime, long recordVersion) {
        this.resApproveDelayId = resApproveDelayId;
        this.resApproveInfo = resApproveInfo;
        this.applyUserCd = applyUserCd;
        this.delayTime = delayTime;
        this.recordVersion = recordVersion;
    }
    public ResApproveDelay(String resApproveDelayId, ResApproveInfo resApproveInfo, String applyUserCd, long delayTime, String applyReason, String approveUserCd, Date approveDate, String approveOptionCd, String confirmUserCd, Date confirmDate, String confirmOptionCd, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion) {
       this.resApproveDelayId = resApproveDelayId;
       this.resApproveInfo = resApproveInfo;
       this.applyUserCd = applyUserCd;
       this.delayTime = delayTime;
       this.applyReason = applyReason;
       this.approveUserCd = approveUserCd;
       this.approveDate = approveDate;
       this.approveOptionCd = approveOptionCd;
       this.confirmUserCd = confirmUserCd;
       this.confirmDate = confirmDate;
       this.confirmOptionCd = confirmOptionCd;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="RESAPPROVEDELAY_ID", unique=true, nullable=false, length=50)
    public String getResApproveDelayId() {
        return this.resApproveDelayId;
    }
    
    public void setResApproveDelayId(String resApproveDelayId) {
        this.resApproveDelayId = resApproveDelayId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RES_APPROVE_INFO_ID", nullable=false)
    public ResApproveInfo getResApproveInfo() {
        return this.resApproveInfo;
    }
    
    public void setResApproveInfo(ResApproveInfo resApproveInfo) {
        this.resApproveInfo = resApproveInfo;
    }
    
    @Column(name="APPLY_USER_CD", nullable=false, length=20)
    public String getApplyUserCd() {
        return this.applyUserCd;
    }
    
    public void setApplyUserCd(String applyUserCd) {
        this.applyUserCd = applyUserCd;
    }
    
    @Column(name="DELAY_TIME", nullable=false, precision=10, scale=0)
    public long getDelayTime() {
        return this.delayTime;
    }
    
    public void setDelayTime(long delayTime) {
        this.delayTime = delayTime;
    }
    
    @Column(name="APPLY_REASON", length=1000)
    public String getApplyReason() {
        return this.applyReason;
    }
    
    public void setApplyReason(String applyReason) {
        this.applyReason = applyReason;
    }
    
    @Column(name="APPROVE_USER_CD", length=20)
    public String getApproveUserCd() {
        return this.approveUserCd;
    }
    
    public void setApproveUserCd(String approveUserCd) {
        this.approveUserCd = approveUserCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="APPROVE_DATE", length=7)
    public Date getApproveDate() {
        return this.approveDate;
    }
    
    public void setApproveDate(Date approveDate) {
        this.approveDate = approveDate;
    }
    
    @Column(name="APPROVE_OPTION_CD", length=20)
    public String getApproveOptionCd() {
        return this.approveOptionCd;
    }
    
    public void setApproveOptionCd(String approveOptionCd) {
        this.approveOptionCd = approveOptionCd;
    }
    
    @Column(name="CONFIRM_USER_CD", length=20)
    public String getConfirmUserCd() {
        return this.confirmUserCd;
    }
    
    public void setConfirmUserCd(String confirmUserCd) {
        this.confirmUserCd = confirmUserCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CONFIRM_DATE", length=7)
    public Date getConfirmDate() {
        return this.confirmDate;
    }
    
    public void setConfirmDate(Date confirmDate) {
        this.confirmDate = confirmDate;
    }
    
    @Column(name="CONFIRM_OPTION_CD", length=20)
    public String getConfirmOptionCd() {
        return this.confirmOptionCd;
    }
    
    public void setConfirmOptionCd(String confirmOptionCd) {
        this.confirmOptionCd = confirmOptionCd;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }

    @Column(name="STATUS_CD",length=20)
	public String getStatusCd() {
		return statusCd;
	}


	public void setStatusCd(String statusCd) {
		this.statusCd = statusCd;
	}

	@Column(name="NODE_CD", length=20)
	public String getNodeCd() {
		return nodeCd;
	}


	public void setNodeCd(String nodeCd) {
		this.nodeCd = nodeCd;
	}

	@Column(name="APPLY_TYPE_CD", length=20)
	public String getApplyTypeCd() {
		return applyTypeCd;
	}


	public void setApplyTypeCd(String applyTypeCd) {
		this.applyTypeCd = applyTypeCd;
	}

	@Column(name="APPROVE_REMARK", length=1000)
	public String getApproveRemark() {
		return approveRemark;
	}


	public void setApproveRemark(String approveRemark) {
		this.approveRemark = approveRemark;
	}

	@Column(name="CONFIRM_REMARK", length=1000)
	public String getConfirmRemark() {
		return confirmRemark;
	}


	public void setConfirmRemark(String confirmRemark) {
		this.confirmRemark = confirmRemark;
	}
	@Column(name="APPROVE_LEVEL", precision=10, scale=0)
    public Long getApproveLevel() {
        return this.approveLevel;
    }
    
    public void setApproveLevel(Long approveLevel) {
        this.approveLevel = approveLevel;
    }
    



}


