// 
package com.hhz.ump.entity.res;
// Generated 2011-3-30 13:29:48 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * ResApproveNode generated by hbm2java
 */
@Entity
@Table(name="RES_APPROVE_NODE"
    ,schema="POWERDESK"
)
public class ResApproveNode  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 3575353678613967591L;
	
	private String resApproveNodeId;
     private ResApproveInfo resApproveInfo;
     private String userCd;
     private String userName;
     private String nodeCd;
     private Date approveDate;
     private String approveOptionCd;
     private Long approveLevel;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Long timeLimit;
     private Date createdDate;
     private String verifyCd;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private String groupNodeCd;
     private String positionCd;
     private String workDutyDesc;
     private String createdCenterCd;
     private String createdPositionCd;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private Long sequenceNo;
	private String backFlg;//是否有驳回权限
    private Boolean isDefault;//是否默认审批人
    private Long approveRank; //
    private String recoverMark;//追回时用到，判断一个节点是在上会的时候加的，还是本身流程就有的，目前只有"toMeeing"这个值
    
	     @Column(name="BACK_FLG", length=1)
		public String getBackFlg() {
			return backFlg;
		}
	
		public void setBackFlg(String backFlg) {
			this.backFlg = backFlg;
		}

     @Column(name="SEQUENCE_NO", precision=10, scale=0)
     public Long getSequenceNo() {
         return this.sequenceNo;
     }
     
     public void setSequenceNo(Long sequenceNo) {
         this.sequenceNo = sequenceNo;
     }

    public ResApproveNode() {
    }

	
    public ResApproveNode(String resApproveNodeId, ResApproveInfo resApproveInfo, long recordVersion) {
        this.resApproveNodeId = resApproveNodeId;
        this.resApproveInfo = resApproveInfo;
        this.recordVersion = recordVersion;
    }
    public ResApproveNode(String resApproveNodeId, ResApproveInfo resApproveInfo, String userCd, String userName, String nodeCd, Date approveDate, String approveOptionCd, Long approveLevel, String remark, String creator, String createdDeptCd, Long timeLimit, Date createdDate, String verifyCd, String updator, String updatedDeptCd, Date updatedDate, long recordVersion, String groupNodeCd, String positionCd, String workDutyDesc, String createdCenterCd, String createdPositionCd, String updatedCenterCd, String updatedPositionCd,long approveRank,String recoverMark) {
       this.resApproveNodeId = resApproveNodeId;
       this.resApproveInfo = resApproveInfo;
       this.userCd = userCd;
       this.userName = userName;
       this.nodeCd = nodeCd;
       this.approveDate = approveDate;
       this.approveOptionCd = approveOptionCd;
       this.approveLevel = approveLevel;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.timeLimit = timeLimit;
       this.createdDate = createdDate;
       this.verifyCd = verifyCd;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.groupNodeCd = groupNodeCd;
       this.positionCd = positionCd;
       this.workDutyDesc = workDutyDesc;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.approveRank  = approveRank;
       this.recoverMark = recoverMark;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="RES_APPROVE_NODE_ID", unique=true, nullable=false, length=50)
    public String getResApproveNodeId() {
        return this.resApproveNodeId;
    }
    
    public void setResApproveNodeId(String resApproveNodeId) {
        this.resApproveNodeId = resApproveNodeId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RES_APPROVE_INFO_ID", nullable=false)
    public ResApproveInfo getResApproveInfo() {
        return this.resApproveInfo;
    }
    
    public void setResApproveInfo(ResApproveInfo resApproveInfo) {
        this.resApproveInfo = resApproveInfo;
    }
    
    @Column(name="USER_CD", length=20)
    public String getUserCd() {
        return this.userCd;
    }
    
    public void setUserCd(String userCd) {
        this.userCd = userCd;
    }
    
    @Column(name="USER_NAME", length=50)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="NODE_CD", length=20)
    public String getNodeCd() {
        return this.nodeCd;
    }
    
    public void setNodeCd(String nodeCd) {
        this.nodeCd = nodeCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="APPROVE_DATE", length=7)
    public Date getApproveDate() {
        return this.approveDate;
    }
    
    public void setApproveDate(Date approveDate) {
        this.approveDate = approveDate;
    }
    
    @Column(name="APPROVE_OPTION_CD", length=20)
    public String getApproveOptionCd() {
        return this.approveOptionCd;
    }
    @Column(name="APPROVE_RANK", length=20)
    public Long getApproveRank() {
		return approveRank;
	}

	public void setApproveRank(Long approveRank) {
		this.approveRank = approveRank;
	}

	public void setApproveOptionCd(String approveOptionCd) {
        this.approveOptionCd = approveOptionCd;
    }
    
    @Column(name="APPROVE_LEVEL", precision=10, scale=0)
    public Long getApproveLevel() {
        return this.approveLevel;
    }
    
    public void setApproveLevel(Long approveLevel) {
        this.approveLevel = approveLevel;
    }
    
    @Column(name="REMARK", length=4000)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="TIME_LIMIT", precision=10, scale=0)
    public Long getTimeLimit() {
        return this.timeLimit;
    }
    
    public void setTimeLimit(Long timeLimit) {
        this.timeLimit = timeLimit;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="VERIFY_CD", length=20)
    public String getVerifyCd() {
        return this.verifyCd;
    }
    
    public void setVerifyCd(String verifyCd) {
        this.verifyCd = verifyCd;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="GROUP_NODE_CD", length=20)
    public String getGroupNodeCd() {
        return this.groupNodeCd;
    }
    
    public void setGroupNodeCd(String groupNodeCd) {
        this.groupNodeCd = groupNodeCd;
    }
    
    @Column(name="POSITION_CD", length=20)
    public String getPositionCd() {
        return this.positionCd;
    }
    
    public void setPositionCd(String positionCd) {
        this.positionCd = positionCd;
    }
    
    @Column(name="WORK_DUTY_DESC", length=100)
    public String getWorkDutyDesc() {
        return this.workDutyDesc;
    }
    
    public void setWorkDutyDesc(String workDutyDesc) {
        this.workDutyDesc = workDutyDesc;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Column(name="IS_DEFAULT", precision=1, scale=0)
	public Boolean getIsDefault() {
		return isDefault;
	}

	public void setIsDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}
	@Column(name="RECOVER_MARK", length=50)
	public String getRecoverMark() {
		return recoverMark;
	}

	public void setRecoverMark(String recoverMark) {
		this.recoverMark = recoverMark;
	}




}


