// 
package com.hhz.ump.entity.res;

// Generated 2011-3-30 13:29:48 by Hibernate Tools 3.2.2.GA

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OrderBy;

/**
 * ResApproveInfo generated by hbm2java
 */
@Entity
@Table(name = "RES_APPROVE_INFO", schema = "POWERDESK")
public class ResApproveInfo implements java.io.Serializable {

	private String resApproveInfoId;
	private String approveCd;
	private Long serialNo;
	private String authTypeCd;
	private String conditionCd;
	private String templetCd;
	// private Clob approveContent;
	private String userCd;
	private String userName;
	private String approveUserCd;
	private String nodeCd;      //一级节点 
	private Long approveLevel;  //一级节点对应的level
	private String nodeCd2;     //二级节点
	private Long approveLevel2; //二级节点对应的level2
	private String statusCd;
	private Date startDate;
	private String attachFlg;
	private String lockUser;
	private String remark;
	private Date lockDate;
	private String creator;
	private String createdDeptCd;
	private Date createdDate;
	private String updator;
	private String updatedDeptCd;
	private Date updatedDate;
	private long recordVersion;
	private String signFile;
	private String randomNo;
	private String titleName;
	private String landProject;
	private String landProjectCd;
	private String signFileX;
	private Date completeDate;
	private String completeUser;
	private String shareStatusCd;
	private String delayApproveUser;
	private String delayStatusCd;
	private Boolean isSync;
	private Boolean isImported;
	private Long timeLimit;
	private String createdCenterCd;
	private String createdPositionCd;
	private String updatedCenterCd;
	private String updatedPositionCd;
	private Date lastApproveDate;
	private String approveUserCd2;

	private List<ResApproveContent> resApproveContents = new ArrayList<ResApproveContent>();
	private List<ResApproveMessage> resApproveMessages = new ArrayList<ResApproveMessage>();
	private List<ResApproveShare> resApproveShares = new ArrayList<ResApproveShare>();
	private List<ResApproveShareHis> resApproveShareHises = new ArrayList<ResApproveShareHis>();
	private List<ResApproveHis> resApproveHises = new ArrayList<ResApproveHis>();
	private List<ResApproveDelay> resApproveDelaies = new ArrayList<ResApproveDelay>();
	private List<ResCenterConfirmInfo> resCenterConfirmInfos = new ArrayList<ResCenterConfirmInfo>();
	private List<ResApprovePush> resApprovePushs = new ArrayList<ResApprovePush>();
	private List<ResApproveNode> resApproveNodes = new ArrayList<ResApproveNode>();
	private List<ResApproveLock> resApproveLocks = new ArrayList<ResApproveLock>();
	private List<ResApproveUser> resApproveUsers = new ArrayList<ResApproveUser>();
	private Long displayNo;
	private String moduleTypeCd;

	public ResApproveInfo() {
	}

	private String backFlg;// 是否有驳回权限

	@Column(name = "BACK_FLG", length = 1)
	public String getBackFlg() {
		return backFlg;
	}

	public void setBackFlg(String backFlg) {
		this.backFlg = backFlg;
	}

	public ResApproveInfo(String resApproveInfoId, long recordVersion) {
		this.resApproveInfoId = resApproveInfoId;
		this.recordVersion = recordVersion;
	}

	public ResApproveInfo(String resApproveInfoId, String approveCd,
			Long serialNo, String authTypeCd, String conditionCd,
			String templetCd, String userCd, String userName,
			String approveUserCd, String nodeCd, String statusCd,
			Date startDate, String attachFlg, String lockUser, String remark,
			Date lockDate, String creator, String createdDeptCd,
			Date createdDate, String updator, String updatedDeptCd,
			Date updatedDate, long recordVersion, String signFile,
			String randomNo, String titleName, String landProject,
			String landProjectCd, String signFileX, Date completeDate,
			String completeUser, String shareStatusCd, String delayApproveUser,
			Boolean isSync, String createdCenterCd, String createdPositionCd,
			String updatedCenterCd, String updatedPositionCd,
			List<ResApproveMessage> resApproveMessages,
			List<ResApproveShare> resApproveShares,
			List<ResApproveHis> resApproveHises,
			List<ResApproveDelay> resApproveDelaies,
			List<ResCenterConfirmInfo> resCenterConfirmInfos,
			List<ResApprovePush> resApprovePushs,
			List<ResApproveNode> resApproveNodes,
			List<ResApproveLock> resApproveLocks, String approveUserCd2,String nodeCd2  ) {
		this.resApproveInfoId = resApproveInfoId;
		this.approveCd = approveCd;
		this.serialNo = serialNo;
		this.authTypeCd = authTypeCd;
		this.conditionCd = conditionCd;
		this.templetCd = templetCd;
		this.userCd = userCd;
		this.userName = userName;
		this.approveUserCd = approveUserCd;
		this.nodeCd = nodeCd;
		this.statusCd = statusCd;
		this.startDate = startDate;
		this.attachFlg = attachFlg;
		this.lockUser = lockUser;
		this.remark = remark;
		this.lockDate = lockDate;
		this.creator = creator;
		this.createdDeptCd = createdDeptCd;
		this.createdDate = createdDate;
		this.updator = updator;
		this.updatedDeptCd = updatedDeptCd;
		this.updatedDate = updatedDate;
		this.recordVersion = recordVersion;
		this.signFile = signFile;
		this.randomNo = randomNo;
		this.titleName = titleName;
		this.landProject = landProject;
		this.landProjectCd = landProjectCd;
		this.signFileX = signFileX;
		this.completeDate = completeDate;
		this.completeUser = completeUser;
		this.shareStatusCd = shareStatusCd;
		this.delayApproveUser = delayApproveUser;
		this.isSync = isSync;
		this.createdCenterCd = createdCenterCd;
		this.createdPositionCd = createdPositionCd;
		this.updatedCenterCd = updatedCenterCd;
		this.updatedPositionCd = updatedPositionCd;
		this.resApproveMessages = resApproveMessages;
		this.resApproveShares = resApproveShares;
		this.resApproveHises = resApproveHises;
		this.resApproveDelaies = resApproveDelaies;
		this.resCenterConfirmInfos = resCenterConfirmInfos;
		this.resApprovePushs = resApprovePushs;
		this.resApproveNodes = resApproveNodes;
		this.resApproveLocks = resApproveLocks;
		this.approveUserCd2 = approveUserCd2;
		this.nodeCd2 = nodeCd2;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	@Column(name = "RES_APPROVE_INFO_ID", unique = true, nullable = false, length = 50)
	public String getResApproveInfoId() {
		return this.resApproveInfoId;
	}

	public void setResApproveInfoId(String resApproveInfoId) {
		this.resApproveInfoId = resApproveInfoId;
	}

	@Column(name = "APPROVE_CD", length = 50)
	public String getApproveCd() {
		return this.approveCd;
	}

	public void setApproveCd(String approveCd) {
		this.approveCd = approveCd;
	}

	@Column(name = "APPROVE_USER_CD2", length = 50)
	public String getApproveUserCd2() {
		return approveUserCd2;
	}

	public void setApproveUserCd2(String approveUserCd2) {
		this.approveUserCd2 = approveUserCd2;
	}

	@Column(name = "SERIAL_NO", precision = 10, scale = 0)
	public Long getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(Long serialNo) {
		this.serialNo = serialNo;
	}

	@Column(name = "AUTH_TYPE_CD", length = 20)
	public String getAuthTypeCd() {
		return this.authTypeCd;
	}

	public void setAuthTypeCd(String authTypeCd) {
		this.authTypeCd = authTypeCd;
	}

	@Column(name = "CONDITION_CD", length = 20)
	public String getConditionCd() {
		return this.conditionCd;
	}

	public void setConditionCd(String conditionCd) {
		this.conditionCd = conditionCd;
	}

	@Column(name = "TEMPLET_CD", length = 20)
	public String getTempletCd() {
		return this.templetCd;
	}

	public void setTempletCd(String templetCd) {
		this.templetCd = templetCd;
	}

	@Column(name = "USER_CD", length = 200)
	public String getUserCd() {
		return this.userCd;
	}

	public void setUserCd(String userCd) {
		this.userCd = userCd;
	}

	@Column(name = "USER_NAME", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "APPROVE_USER_CD", length = 200)
	public String getApproveUserCd() {
		return this.approveUserCd;
	}

	public void setApproveUserCd(String approveUserCd) {
		this.approveUserCd = approveUserCd;
	}

	@Column(name = "NODE_CD", length = 20)
	public String getNodeCd() {
		return this.nodeCd;
	}

	public void setNodeCd(String nodeCd) {
		this.nodeCd = nodeCd;
	}

	@Column(name = "STATUS_CD", length = 20)
	public String getStatusCd() {
		return this.statusCd;
	}

	public void setStatusCd(String statusCd) {
		this.statusCd = statusCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "ATTACH_FLG", length = 1)
	public String getAttachFlg() {
		return this.attachFlg;
	}

	public void setAttachFlg(String attachFlg) {
		this.attachFlg = attachFlg;
	}

	@Column(name = "LOCK_USER", length = 20)
	public String getLockUser() {
		return this.lockUser;
	}

	public void setLockUser(String lockUser) {
		this.lockUser = lockUser;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LOCK_DATE", length = 7)
	public Date getLockDate() {
		return this.lockDate;
	}

	public void setLockDate(Date lockDate) {
		this.lockDate = lockDate;
	}

	@Column(name = "CREATOR", length = 20)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATED_DEPT_CD", length = 20)
	public String getCreatedDeptCd() {
		return this.createdDeptCd;
	}

	public void setCreatedDeptCd(String createdDeptCd) {
		this.createdDeptCd = createdDeptCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATOR", length = 20)
	public String getUpdator() {
		return this.updator;
	}

	public void setUpdator(String updator) {
		this.updator = updator;
	}

	@Column(name = "UPDATED_DEPT_CD", length = 20)
	public String getUpdatedDeptCd() {
		return this.updatedDeptCd;
	}

	public void setUpdatedDeptCd(String updatedDeptCd) {
		this.updatedDeptCd = updatedDeptCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 7)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "RECORD_VERSION", nullable = false, precision = 10, scale = 0)
	@Version
	public long getRecordVersion() {
		return this.recordVersion;
	}

	public void setRecordVersion(long recordVersion) {
		this.recordVersion = recordVersion;
	}

	@Column(name = "SIGN_FILE", length = 100)
	public String getSignFile() {
		return this.signFile;
	}

	public void setSignFile(String signFile) {
		this.signFile = signFile;
	}

	@Column(name = "RANDOM_NO", length = 20)
	public String getRandomNo() {
		return this.randomNo;
	}

	public void setRandomNo(String randomNo) {
		this.randomNo = randomNo;
	}

	@Column(name = "TITLE_NAME", length = 200)
	public String getTitleName() {
		return this.titleName;
	}

	public void setTitleName(String titleName) {
		this.titleName = titleName;
	}

	@Column(name = "LAND_PROJECT", length = 50)
	public String getLandProject() {
		return this.landProject;
	}

	public void setLandProject(String landProject) {
		this.landProject = landProject;
	}

	@Column(name = "LAND_PROJECT_CD", length = 20)
	public String getLandProjectCd() {
		return this.landProjectCd;
	}

	public void setLandProjectCd(String landProjectCd) {
		this.landProjectCd = landProjectCd;
	}

	@Column(name = "SIGN_FILE_X", length = 100)
	public String getSignFileX() {
		return this.signFileX;
	}

	public void setSignFileX(String signFileX) {
		this.signFileX = signFileX;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "COMPLETE_DATE", length = 7)
	public Date getCompleteDate() {
		return this.completeDate;
	}

	public void setCompleteDate(Date completeDate) {
		this.completeDate = completeDate;
	}

	@Column(name = "COMPLETE_USER", length = 20)
	public String getCompleteUser() {
		return this.completeUser;
	}

	public void setCompleteUser(String completeUser) {
		this.completeUser = completeUser;
	}

	@Column(name = "SHARE_STATUS_CD", length = 20)
	public String getShareStatusCd() {
		return this.shareStatusCd;
	}

	public void setShareStatusCd(String shareStatusCd) {
		this.shareStatusCd = shareStatusCd;
	}

	@Column(name = "DELAY_APPROVE_USER", length = 20)
	public String getDelayApproveUser() {
		return this.delayApproveUser;
	}

	public void setDelayApproveUser(String delayApproveUser) {
		this.delayApproveUser = delayApproveUser;
	}

	@Column(name = "IS_SYNC", precision = 1, scale = 0)
	public Boolean getIsSync() {
		return this.isSync;
	}

	public void setIsSync(Boolean isSync) {
		this.isSync = isSync;
	}

	@Column(name = "CREATED_CENTER_CD", length = 20)
	public String getCreatedCenterCd() {
		return this.createdCenterCd;
	}

	public void setCreatedCenterCd(String createdCenterCd) {
		this.createdCenterCd = createdCenterCd;
	}

	@Column(name = "CREATED_POSITION_CD", length = 20)
	public String getCreatedPositionCd() {
		return this.createdPositionCd;
	}

	public void setCreatedPositionCd(String createdPositionCd) {
		this.createdPositionCd = createdPositionCd;
	}

	@Column(name = "UPDATED_CENTER_CD", length = 20)
	public String getUpdatedCenterCd() {
		return this.updatedCenterCd;
	}

	public void setUpdatedCenterCd(String updatedCenterCd) {
		this.updatedCenterCd = updatedCenterCd;
	}

	@Column(name = "UPDATED_POSITION_CD", length = 20)
	public String getUpdatedPositionCd() {
		return this.updatedPositionCd;
	}

	public void setUpdatedPositionCd(String updatedPositionCd) {
		this.updatedPositionCd = updatedPositionCd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resApproveInfo")
	@BatchSize(size = 10)
	@OrderBy(clause = "CREATED_DATE ASC")
	public List<ResApproveMessage> getResApproveMessages() {
		return this.resApproveMessages;
	}

	public void setResApproveMessages(List<ResApproveMessage> resApproveMessages) {
		this.resApproveMessages = resApproveMessages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resApproveInfo")
	@BatchSize(size = 10)
	public List<ResApproveShare> getResApproveShares() {
		return this.resApproveShares;
	}

	public void setResApproveShares(List<ResApproveShare> resApproveShares) {
		this.resApproveShares = resApproveShares;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resApproveInfo")
	@BatchSize(size = 10)
	@OrderBy(clause = "CREATED_DATE DESC")
	public List<ResApproveHis> getResApproveHises() {
		return this.resApproveHises;
	}

	public void setResApproveHises(List<ResApproveHis> resApproveHises) {
		this.resApproveHises = resApproveHises;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resApproveInfo")
	@BatchSize(size = 10)
	@OrderBy(clause = "CREATED_DATE DESC")
	public List<ResApproveDelay> getResApproveDelaies() {
		return this.resApproveDelaies;
	}

	public void setResApproveDelaies(List<ResApproveDelay> resApproveDelaies) {
		this.resApproveDelaies = resApproveDelaies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resApproveInfo")
	@BatchSize(size = 10)
	public List<ResCenterConfirmInfo> getResCenterConfirmInfos() {
		return this.resCenterConfirmInfos;
	}

	public void setResCenterConfirmInfos(
			List<ResCenterConfirmInfo> resCenterConfirmInfos) {
		this.resCenterConfirmInfos = resCenterConfirmInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resApproveInfo")
	@BatchSize(size = 10)
	public List<ResApprovePush> getResApprovePushs() {
		return this.resApprovePushs;
	}

	public void setResApprovePushs(List<ResApprovePush> resApprovePushs) {
		this.resApprovePushs = resApprovePushs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resApproveInfo")
	@BatchSize(size = 10)
	@OrderBy(clause = "APPROVE_LEVEL ASC,SEQUENCE_NO ASC")
	public List<ResApproveNode> getResApproveNodes() {
		return this.resApproveNodes;
	}

	public void setResApproveNodes(List<ResApproveNode> resApproveNodes) {
		this.resApproveNodes = resApproveNodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resApproveInfo")
	@BatchSize(size = 10)
	@OrderBy(clause = "LOCK_DATE DESC")
	public List<ResApproveLock> getResApproveLocks() {
		return this.resApproveLocks;
	}

	public void setResApproveLocks(List<ResApproveLock> resApproveLocks) {
		this.resApproveLocks = resApproveLocks;
	}

	@Column(name = "APPROVE_LEVEL", precision = 10, scale = 0)
	public Long getApproveLevel() {
		return approveLevel;
	}

	public void setApproveLevel(Long approveLevel) {
		this.approveLevel = approveLevel;
	}
	
	@Column(name = "NODE_CD2", length = 20)
	public String getNodeCd2() {
		return nodeCd2;
	}

	public void setNodeCd2(String nodeCd2) {
		this.nodeCd2 = nodeCd2;
	}
	@Column(name = "APPROVE_LEVEL2", precision = 10, scale = 0)
	public Long getApproveLevel2() {
		return approveLevel2;
	}

	public void setApproveLevel2(Long approveLevel2) {
		this.approveLevel2 = approveLevel2;
	}

	@Column(name = "DELAY_STATUS_CD", length = 20)
	public String getDelayStatusCd() {
		return delayStatusCd;
	}

	public void setDelayStatusCd(String delayStatusCd) {
		this.delayStatusCd = delayStatusCd;
	}

	@Column(name = "IS_IMPORTED", precision = 1, scale = 0)
	public Boolean getIsImported() {
		return isImported;
	}

	public void setIsImported(Boolean isImported) {
		this.isImported = isImported;
	}

	@Column(name = "TIME_LIMIT", precision = 10, scale = 0)
	public Long getTimeLimit() {
		return timeLimit;
	}

	public void setTimeLimit(Long timeLimit) {
		this.timeLimit = timeLimit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_APPROVE_DATE", length = 7)
	public Date getLastApproveDate() {
		return lastApproveDate;
	}

	public void setLastApproveDate(Date lastApproveDate) {
		this.lastApproveDate = lastApproveDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resApproveInfo")
	@BatchSize(size = 10)
	public List<ResApproveUser> getResApproveUsers() {
		return this.resApproveUsers;
	}

	public void setResApproveUsers(List<ResApproveUser> resApproveUsers) {
		this.resApproveUsers = resApproveUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resApproveInfo")
	@BatchSize(size = 10)
	public List<ResApproveContent> getResApproveContents() {
		return this.resApproveContents;
	}

	public void setResApproveContents(List<ResApproveContent> resApproveContents) {
		this.resApproveContents = resApproveContents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resApproveInfo")
	@BatchSize(size = 10)
	public List<ResApproveShareHis> getResApproveShareHises() {
		return resApproveShareHises;
	}

	public void setResApproveShareHises(
			List<ResApproveShareHis> resApproveShareHises) {
		this.resApproveShareHises = resApproveShareHises;
	}

	@Column(name = "DISPLAY_NO", precision = 10, scale = 0)
	public Long getDisplayNo() {
		return displayNo;
	}

	public void setDisplayNo(Long displayNo) {
		this.displayNo = displayNo;
	}

	@Column(name = "MODULE_TYPE_CD", length = 20)
	public String getModuleTypeCd() {
		return moduleTypeCd;
	}

	public void setModuleTypeCd(String moduleTypeCd) {
		this.moduleTypeCd = moduleTypeCd;
	}
}
