// 
package com.hhz.ump.entity.res;
// Generated 2011-3-30 13:29:48 by Hibernate Tools 3.2.2.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OrderBy;

/**
 * ResConditonType generated by hbm2java
 */
@Entity
@Table(name="RES_CONDITON_TYPE"
    ,schema="POWERDESK"
)
public class ResConditonType  implements java.io.Serializable {


     private String resConditonTypeId;
     private ResAuthType resAuthType;
     private String conditionCd;
     private String conditionName;
     private String conditionValue;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private String createdCenterCd;
     private String createdPositionCd;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private List<ResApproveStep> resApproveSteps = new ArrayList<ResApproveStep>();
     private List<ResCenterInfo> resCenterInfos = new ArrayList<ResCenterInfo>();
    public ResConditonType() {
    }

	
    public ResConditonType(String resConditonTypeId, ResAuthType resAuthType, long recordVersion) {
        this.resConditonTypeId = resConditonTypeId;
        this.resAuthType = resAuthType;
        this.recordVersion = recordVersion;
    }
    public ResConditonType(String resConditonTypeId, ResAuthType resAuthType, String conditionCd, String conditionName, String conditionValue, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion, String createdCenterCd, String createdPositionCd, String updatedCenterCd, String updatedPositionCd, List<ResApproveStep> resApproveSteps, List<ResCenterInfo> resCenterInfos) {
       this.resConditonTypeId = resConditonTypeId;
       this.resAuthType = resAuthType;
       this.conditionCd = conditionCd;
       this.conditionName = conditionName;
       this.conditionValue = conditionValue;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
       this.resApproveSteps = resApproveSteps;
       this.resCenterInfos = resCenterInfos;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="RES_CONDITON_TYPE_ID", unique=true, nullable=false, length=50)
    public String getResConditonTypeId() {
        return this.resConditonTypeId;
    }
    
    public void setResConditonTypeId(String resConditonTypeId) {
        this.resConditonTypeId = resConditonTypeId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RES_AUTH_TYPE_ID", nullable=false)
    public ResAuthType getResAuthType() {
        return this.resAuthType;
    }
    
    public void setResAuthType(ResAuthType resAuthType) {
        this.resAuthType = resAuthType;
    }
    
    @Column(name="CONDITION_CD", length=20)
    public String getConditionCd() {
        return this.conditionCd;
    }
    
    public void setConditionCd(String conditionCd) {
        this.conditionCd = conditionCd;
    }
    
    @Column(name="CONDITION_NAME", length=50)
    public String getConditionName() {
        return this.conditionName;
    }
    
    public void setConditionName(String conditionName) {
        this.conditionName = conditionName;
    }
    
    @Column(name="CONDITION_VALUE", length=100)
    public String getConditionValue() {
        return this.conditionValue;
    }
    
    public void setConditionValue(String conditionValue) {
        this.conditionValue = conditionValue;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="resConditonType")
    @BatchSize(size=10)
    @OrderBy(clause="APPROVE_LEVEL asc,SEQUENCE_NO asc")
public List<ResApproveStep> getResApproveSteps() {
        return this.resApproveSteps;
    }
    
    public void setResApproveSteps(List<ResApproveStep> resApproveSteps) {
        this.resApproveSteps = resApproveSteps;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="resConditonType")
    @BatchSize(size=10)
public List<ResCenterInfo> getResCenterInfos() {
        return this.resCenterInfos;
    }
    
    public void setResCenterInfos(List<ResCenterInfo> resCenterInfos) {
        this.resCenterInfos = resCenterInfos;
    }


}


