// 
package com.hhz.ump.entity.res;
// Generated 2011-3-30 13:29:48 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * ResNode generated by hbm2java
 */
@Entity
@Table(name="RES_NODE"
    ,schema="POWERDESK"
)
public class ResNode  implements java.io.Serializable {


     private String resNodeId;
     private String nodeCd;
     private String nodeName;
     private String nodeUser;
     private String nodeTypeCd;
     private Long sequenceNo;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private Boolean isMuti;
     private Boolean isLock;
     private String createdCenterCd;
     private String createdPositionCd;
     private String updatedCenterCd;
     private String updatedPositionCd;
     private String orgKindCd;
     private String userKindCd;
     private String nodeLevelCd;
     private Boolean active;

    public ResNode() {
    }

	
    public ResNode(String resNodeId, long recordVersion) {
        this.resNodeId = resNodeId;
        this.recordVersion = recordVersion;
    }
    public ResNode(String resNodeId, String nodeCd, String nodeName, String nodeUser, String nodeTypeCd, Long sequenceNo, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion, Boolean isMuti, String createdCenterCd, String createdPositionCd, String updatedCenterCd, String updatedPositionCd) {
       this.resNodeId = resNodeId;
       this.nodeCd = nodeCd;
       this.nodeName = nodeName;
       this.nodeUser = nodeUser;
       this.nodeTypeCd = nodeTypeCd;
       this.sequenceNo = sequenceNo;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.isMuti = isMuti;
       this.createdCenterCd = createdCenterCd;
       this.createdPositionCd = createdPositionCd;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedPositionCd = updatedPositionCd;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="RES_NODE_ID", unique=true, nullable=false, length=50)
    public String getResNodeId() {
        return this.resNodeId;
    }
    
    public void setResNodeId(String resNodeId) {
        this.resNodeId = resNodeId;
    }
    
    @Column(name="NODE_CD", length=20)
    public String getNodeCd() {
        return this.nodeCd;
    }
    
    public void setNodeCd(String nodeCd) {
        this.nodeCd = nodeCd;
    }
    
    @Column(name="NODE_NAME", length=50)
    public String getNodeName() {
        return this.nodeName;
    }
    
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }
    
    @Column(name="NODE_USER", length=20)
    public String getNodeUser() {
        return this.nodeUser;
    }
    
    public void setNodeUser(String nodeUser) {
        this.nodeUser = nodeUser;
    }
    
    @Column(name="NODE_TYPE_CD", length=20)
    public String getNodeTypeCd() {
        return this.nodeTypeCd;
    }
    
    public void setNodeTypeCd(String nodeTypeCd) {
        this.nodeTypeCd = nodeTypeCd;
    }
    
    @Column(name="SEQUENCE_NO", precision=10, scale=0)
    public Long getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Long sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="IS_MUTI", precision=1, scale=0)
    public Boolean getIsMuti() {
        return this.isMuti;
    }
    
    public void setIsMuti(Boolean isMuti) {
        this.isMuti = isMuti;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }

    @Column(name="ORG_KIND_CD", length=20)
	public String getOrgKindCd() {
		return orgKindCd;
	}


	public void setOrgKindCd(String orgKindCd) {
		this.orgKindCd = orgKindCd;
	}

	@Column(name="USER_KIND_CD", length=20)
	public String getUserKindCd() {
		return userKindCd;
	}


	public void setUserKindCd(String userKindCd) {
		this.userKindCd = userKindCd;
	}

	@Column(name="NODE_LEVEL_CD", length=20)
	public String getNodeLevelCd() {
		return nodeLevelCd;
	}


	public void setNodeLevelCd(String nodeLevelCd) {
		this.nodeLevelCd = nodeLevelCd;
	}


    @Column(name="ACTIVE", precision=1, scale=0)
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }

    @Column(name="IS_LOCK", precision=1, scale=0)
	public Boolean getIsLock() {
		return isLock;
	}


	public void setIsLock(Boolean isLock) {
		this.isLock = isLock;
	}


}


