// 
package com.hhz.ump.entity.plan;
// Generated 2011-4-23 21:04:46 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.BatchSize;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlanWork2Weight generated by hbm2java
 */
@Entity
@Table(name="PLAN_WORK2_WEIGHT"
    
)
public class PlanWork2Weight  implements java.io.Serializable {


     private String planWork2WeightId;
     private PlanWork2 planWork2;
     private BigDecimal weightPoint;
     private BigDecimal bogusWeightPoint;
     private BigDecimal selfPoint;
     private BigDecimal selfCheckPoint;
     private BigDecimal evaluatePoint;
     private BigDecimal finalPoint;
     private BigDecimal planYear;
     private BigDecimal planQuarter;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;

    public PlanWork2Weight() {
    }

	
    public PlanWork2Weight(String planWork2WeightId, PlanWork2 planWork2, long recordVersion) {
        this.planWork2WeightId = planWork2WeightId;
        this.planWork2 = planWork2;
        this.recordVersion = recordVersion;
    }
    public PlanWork2Weight(String planWork2WeightId, PlanWork2 planWork2, BigDecimal weightPoint, BigDecimal bogusWeightPoint, BigDecimal selfPoint, BigDecimal selfCheckPoint, BigDecimal evaluatePoint, BigDecimal finalPoint, BigDecimal planYear, BigDecimal planQuarter, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion) {
       this.planWork2WeightId = planWork2WeightId;
       this.planWork2 = planWork2;
       this.weightPoint = weightPoint;
       this.bogusWeightPoint = bogusWeightPoint;
       this.selfPoint = selfPoint;
       this.selfCheckPoint = selfCheckPoint;
       this.evaluatePoint = evaluatePoint;
       this.finalPoint = finalPoint;
       this.planYear = planYear;
       this.planQuarter = planQuarter;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="PLAN_WORK2_WEIGHT_ID", unique=true, nullable=false, length=50)
    public String getPlanWork2WeightId() {
        return this.planWork2WeightId;
    }
    
    public void setPlanWork2WeightId(String planWork2WeightId) {
        this.planWork2WeightId = planWork2WeightId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PLAN_WORK2_ID", nullable=false)
    public PlanWork2 getPlanWork2() {
        return this.planWork2;
    }
    
    public void setPlanWork2(PlanWork2 planWork2) {
        this.planWork2 = planWork2;
    }
    
    @Column(name="WEIGHT_POINT", precision=10)
    public BigDecimal getWeightPoint() {
        return this.weightPoint;
    }
    
    public void setWeightPoint(BigDecimal weightPoint) {
        this.weightPoint = weightPoint;
    }
    
    @Column(name="BOGUS_WEIGHT_POINT", precision=10)
    public BigDecimal getBogusWeightPoint() {
        return this.bogusWeightPoint;
    }
    
    public void setBogusWeightPoint(BigDecimal bogusWeightPoint) {
        this.bogusWeightPoint = bogusWeightPoint;
    }
    
    @Column(name="SELF_POINT", precision=10)
    public BigDecimal getSelfPoint() {
        return this.selfPoint;
    }
    
    public void setSelfPoint(BigDecimal selfPoint) {
        this.selfPoint = selfPoint;
    }
    
    @Column(name="SELF_CHECK_POINT", precision=10)
    public BigDecimal getSelfCheckPoint() {
        return this.selfCheckPoint;
    }
    
    public void setSelfCheckPoint(BigDecimal selfCheckPoint) {
        this.selfCheckPoint = selfCheckPoint;
    }
    
    @Column(name="EVALUATE_POINT", precision=10)
    public BigDecimal getEvaluatePoint() {
        return this.evaluatePoint;
    }
    
    public void setEvaluatePoint(BigDecimal evaluatePoint) {
        this.evaluatePoint = evaluatePoint;
    }
    
    @Column(name="FINAL_POINT", precision=10)
    public BigDecimal getFinalPoint() {
        return this.finalPoint;
    }
    
    public void setFinalPoint(BigDecimal finalPoint) {
        this.finalPoint = finalPoint;
    }
    
    @Column(name="PLAN_YEAR", precision=38, scale=0)
    public BigDecimal getPlanYear() {
        return this.planYear;
    }
    
    public void setPlanYear(BigDecimal planYear) {
        this.planYear = planYear;
    }
    
    @Column(name="PLAN_QUARTER", precision=38, scale=0)
    public BigDecimal getPlanQuarter() {
        return this.planQuarter;
    }
    
    public void setPlanQuarter(BigDecimal planQuarter) {
        this.planQuarter = planQuarter;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }




}


