// 
package com.hhz.ump.entity.plan;
// Generated 2011-2-16 16:39:45 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * PlanWork2Status generated by hbm2java
 */
@Entity
@Table(name="PLAN_WORK2_STATUS"
    
)
public class PlanWork2Status  implements java.io.Serializable {


     private String planWork2StatusId;
     private BigDecimal planYear;
     private BigDecimal planMonth;
     private BigDecimal planQuarter;
     private String isQuarter;
     private String statusCd;
     private String creator;
     private String centerCd;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private String remark;
     private long recordVersion;

    public PlanWork2Status() {
    }

	
    public PlanWork2Status(String planWork2StatusId, long recordVersion) {
        this.planWork2StatusId = planWork2StatusId;
        this.recordVersion = recordVersion;
    }
    public PlanWork2Status(String planWork2StatusId, BigDecimal planYear, BigDecimal planMonth, BigDecimal planQuarter,String isQuarter, String statusCd, String creator, String centerCd, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, String remark, long recordVersion) {
       this.planWork2StatusId = planWork2StatusId;
       this.planYear = planYear;
       this.planMonth = planMonth;
       this.planQuarter = planQuarter;
       this.isQuarter = isQuarter;
       this.statusCd = statusCd;
       this.creator = creator;
       this.centerCd = centerCd;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.remark = remark;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="PLAN_WORK2_STATUS_ID", unique=true, nullable=false, length=50)
    public String getPlanWork2StatusId() {
        return this.planWork2StatusId;
    }
    
    public void setPlanWork2StatusId(String planWork2StatusId) {
        this.planWork2StatusId = planWork2StatusId;
    }

    @Column(name="PLAN_YEAR", precision=38, scale=0)
    public BigDecimal getPlanYear() {
        return this.planYear;
    }
    
    public void setPlanYear(BigDecimal planYear) {
        this.planYear = planYear;
    }

    @Column(name="PLAN_MONTH", precision=38, scale=0)
    public BigDecimal getPlanMonth() {
        return this.planMonth;
    }
    
    public void setPlanMonth(BigDecimal planMonth) {
        this.planMonth = planMonth;
    }

    @Column(name="PLAN_QUARTER", precision=38, scale=0)
    public BigDecimal getPlanQuarter() {
        return this.planQuarter;
    }
    
    public void setPlanQuarter(BigDecimal planQuarter) {
        this.planQuarter = planQuarter;
    }

    @Column(name="IS_QUARTER", length=10)
    public String getIsQuarter() {
        return this.isQuarter;
    }
    
    public void setIsQuarter(String isQuarter) {
        this.isQuarter = isQuarter;
    }

    @Column(name="STATUS_CD", length=50)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CENTER_CD", length=50)
    public String getCenterCd() {
        return this.centerCd;
    }
    
    public void setCenterCd(String centerCd) {
        this.centerCd = centerCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }


    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }



}


