// 
package com.hhz.ump.entity.plan;
// Generated 2011-4-23 21:04:46 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OrderBy;

/**
 * PlanWork2 generated by hbm2java
 */
@Entity
@Table(name="PLAN_WORK2"
    
)
public class PlanWork2  implements java.io.Serializable {


     private String planWork2Id;
     private String serialNumber;
     private BigDecimal serialOrder;
     private BigDecimal planYear;
     private BigDecimal planMonth;
     private BigDecimal planQuarter;
     private String centerCd;
     private String targetPointCd;
     private String area;
     private String content;
     private String statusCd;
     private String principal;
     private String attachFlg;
     private Date targetDate;
     private Date endDate;
     private BigDecimal planType;
     private BigDecimal weightPoint;
     private BigDecimal selfPoint;
     private BigDecimal selfCheckPoint;
     private BigDecimal evaluatePoint;
     private BigDecimal finalPoint;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private String remark;
     private long recordVersion;
     private String planWork2YearId;
     private Long sequenceNo;
     private String suspendId;
     private String ifSuspend;
     private String ifSuspendCreated;
     private BigDecimal bogusWeightPoint;
     private List<PlanWork2Month> planWork2Months = new ArrayList<PlanWork2Month>();
     private List<PlanWork2Weight> planWork2Weights = new ArrayList<PlanWork2Weight>();
     private List<PlanWork2Message> planWork2Messages = new ArrayList<PlanWork2Message>();

    public PlanWork2() {
    }

	
    public PlanWork2(String planWork2Id, long recordVersion) {
        this.planWork2Id = planWork2Id;
        this.recordVersion = recordVersion;
    }
    public PlanWork2(String planWork2Id, String serialNumber, BigDecimal serialOrder, BigDecimal planYear, BigDecimal planMonth, BigDecimal planQuarter, String centerCd, String targetPointCd, String area, String content, String statusCd, String principal, String attachFlg, Date targetDate, Date endDate, BigDecimal planType, BigDecimal weightPoint, BigDecimal selfPoint, BigDecimal selfCheckPoint, BigDecimal evaluatePoint, BigDecimal finalPoint, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, String remark, long recordVersion, String planWork2YearId, Long sequenceNo, String suspendId, String ifSuspend, String ifSuspendCreated, BigDecimal bogusWeightPoint, List<PlanWork2Month> planWork2Months, List<PlanWork2Weight> planWork2Weights, List<PlanWork2Message> planWork2Messages) {
       this.planWork2Id = planWork2Id;
       this.serialNumber = serialNumber;
       this.serialOrder = serialOrder;
       this.planYear = planYear;
       this.planMonth = planMonth;
       this.planQuarter = planQuarter;
       this.centerCd = centerCd;
       this.targetPointCd = targetPointCd;
       this.area = area;
       this.content = content;
       this.statusCd = statusCd;
       this.principal = principal;
       this.attachFlg = attachFlg;
       this.targetDate = targetDate;
       this.endDate = endDate;
       this.planType = planType;
       this.weightPoint = weightPoint;
       this.selfPoint = selfPoint;
       this.selfCheckPoint = selfCheckPoint;
       this.evaluatePoint = evaluatePoint;
       this.finalPoint = finalPoint;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.remark = remark;
       this.recordVersion = recordVersion;
       this.planWork2YearId = planWork2YearId;
       this.sequenceNo = sequenceNo;
       this.suspendId = suspendId;
       this.ifSuspend = ifSuspend;
       this.ifSuspendCreated = ifSuspendCreated;
       this.bogusWeightPoint = bogusWeightPoint;
       this.planWork2Months = planWork2Months;
       this.planWork2Weights = planWork2Weights;
       this.planWork2Messages = planWork2Messages;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="PLAN_WORK2_ID", unique=true, nullable=false, length=50)
    public String getPlanWork2Id() {
        return this.planWork2Id;
    }
    
    public void setPlanWork2Id(String planWork2Id) {
        this.planWork2Id = planWork2Id;
    }
    
    @Column(name="SERIAL_NUMBER", length=50)
    public String getSerialNumber() {
        return this.serialNumber;
    }
    
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }
    
    @Column(name="SERIAL_ORDER", precision=38, scale=0)
    public BigDecimal getSerialOrder() {
        return this.serialOrder;
    }
    
    public void setSerialOrder(BigDecimal serialOrder) {
        this.serialOrder = serialOrder;
    }
    
    @Column(name="PLAN_YEAR", precision=38, scale=0)
    public BigDecimal getPlanYear() {
        return this.planYear;
    }
    
    public void setPlanYear(BigDecimal planYear) {
        this.planYear = planYear;
    }
    
    @Column(name="PLAN_MONTH", precision=38, scale=0)
    public BigDecimal getPlanMonth() {
        return this.planMonth;
    }
    
    public void setPlanMonth(BigDecimal planMonth) {
        this.planMonth = planMonth;
    }
    
    @Column(name="PLAN_QUARTER", precision=38, scale=0)
    public BigDecimal getPlanQuarter() {
        return this.planQuarter;
    }
    
    public void setPlanQuarter(BigDecimal planQuarter) {
        this.planQuarter = planQuarter;
    }
    
    @Column(name="CENTER_CD", length=20)
    public String getCenterCd() {
        return this.centerCd;
    }
    
    public void setCenterCd(String centerCd) {
        this.centerCd = centerCd;
    }
    
    @Column(name="TARGET_POINT_CD", length=20)
    public String getTargetPointCd() {
        return this.targetPointCd;
    }
    
    public void setTargetPointCd(String targetPointCd) {
        this.targetPointCd = targetPointCd;
    }
    
    @Column(name="AREA", length=50)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    
    @Column(name="CONTENT", length=4000)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    
    @Column(name="STATUS_CD", length=20)
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }
    
    @Column(name="PRINCIPAL", length=200)
    public String getPrincipal() {
        return this.principal;
    }
    
    public void setPrincipal(String principal) {
        this.principal = principal;
    }
    
    @Column(name="ATTACH_FLG", length=1)
    public String getAttachFlg() {
        return this.attachFlg;
    }
    
    public void setAttachFlg(String attachFlg) {
        this.attachFlg = attachFlg;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TARGET_DATE", length=7)
    public Date getTargetDate() {
        return this.targetDate;
    }
    
    public void setTargetDate(Date targetDate) {
        this.targetDate = targetDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_DATE", length=7)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    
    @Column(name="PLAN_TYPE", precision=38, scale=0)
    public BigDecimal getPlanType() {
        return this.planType;
    }
    
    public void setPlanType(BigDecimal planType) {
        this.planType = planType;
    }
    
    @Column(name="WEIGHT_POINT", precision=10)
    public BigDecimal getWeightPoint() {
        return this.weightPoint;
    }
    
    public void setWeightPoint(BigDecimal weightPoint) {
        this.weightPoint = weightPoint;
    }
    
    @Column(name="SELF_POINT", precision=10)
    public BigDecimal getSelfPoint() {
        return this.selfPoint;
    }
    
    public void setSelfPoint(BigDecimal selfPoint) {
        this.selfPoint = selfPoint;
    }
    
    @Column(name="SELF_CHECK_POINT", precision=10)
    public BigDecimal getSelfCheckPoint() {
        return this.selfCheckPoint;
    }
    
    public void setSelfCheckPoint(BigDecimal selfCheckPoint) {
        this.selfCheckPoint = selfCheckPoint;
    }
    
    @Column(name="EVALUATE_POINT", precision=10)
    public BigDecimal getEvaluatePoint() {
        return this.evaluatePoint;
    }
    
    public void setEvaluatePoint(BigDecimal evaluatePoint) {
        this.evaluatePoint = evaluatePoint;
    }
    
    @Column(name="FINAL_POINT", precision=10)
    public BigDecimal getFinalPoint() {
        return this.finalPoint;
    }
    
    public void setFinalPoint(BigDecimal finalPoint) {
        this.finalPoint = finalPoint;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="PLAN_WORK2_YEAR_ID", length=50)
    public String getPlanWork2YearId() {
        return this.planWork2YearId;
    }
    
    public void setPlanWork2YearId(String planWork2YearId) {
        this.planWork2YearId = planWork2YearId;
    }
    
    @Column(name="SEQUENCE_NO", precision=10, scale=0)
    public Long getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Long sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    
    @Column(name="SUSPEND_ID", length=50)
    public String getSuspendId() {
        return this.suspendId;
    }
    
    public void setSuspendId(String suspendId) {
        this.suspendId = suspendId;
    }
    
    @Column(name="IF_SUSPEND", length=20)
    public String getIfSuspend() {
        return this.ifSuspend;
    }
    
    public void setIfSuspend(String ifSuspend) {
        this.ifSuspend = ifSuspend;
    }
    
    @Column(name="IF_SUSPEND_CREATED", length=20)
    public String getIfSuspendCreated() {
        return this.ifSuspendCreated;
    }
    
    public void setIfSuspendCreated(String ifSuspendCreated) {
        this.ifSuspendCreated = ifSuspendCreated;
    }
    
    @Column(name="BOGUS_WEIGHT_POINT", precision=10)
    public BigDecimal getBogusWeightPoint() {
        return this.bogusWeightPoint;
    }
    
    public void setBogusWeightPoint(BigDecimal bogusWeightPoint) {
        this.bogusWeightPoint = bogusWeightPoint;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="planWork2")
    @BatchSize(size=10)
    @OrderBy(clause="PLAN_YEAR ASC,PLAN_MONTH ASC")
public List<PlanWork2Month> getPlanWork2Months() {
        return this.planWork2Months;
    }
    
    public void setPlanWork2Months(List<PlanWork2Month> planWork2Months) {
        this.planWork2Months = planWork2Months;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="planWork2")
    @BatchSize(size=10)
public List<PlanWork2Weight> getPlanWork2Weights() {
        return this.planWork2Weights;
    }
    
    public void setPlanWork2Weights(List<PlanWork2Weight> planWork2Weights) {
        this.planWork2Weights = planWork2Weights;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="planWork2")
    @BatchSize(size=10)
    @OrderBy(clause="CREATED_DATE DESC")
public List<PlanWork2Message> getPlanWork2Messages() {
        return this.planWork2Messages;
    }
    
    public void setPlanWork2Messages(List<PlanWork2Message> planWork2Messages) {
        this.planWork2Messages = planWork2Messages;
    }



    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }


}


