// 
package com.hhz.ump.entity.prod;
// Generated 2011-11-10 13:11:29 by Hibernate Tools 3.2.2.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;

/**
 * ProdBasicVersion generated by hbm2java
 */
@Entity
@Table(name="PROD_BASIC_VERSION"
    
)
public class ProdBasicVersion  implements java.io.Serializable {


     private String prodBasicVersionId;
     private String versionNo;
     private String yearCd;
     private String monthCd;
     private String versionDes;
     private String active;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private List<ProdVersionDetail> prodVersionDetails = new ArrayList<ProdVersionDetail>();

    public ProdBasicVersion() {
    }

	
    public ProdBasicVersion(String prodBasicVersionId, long recordVersion) {
        this.prodBasicVersionId = prodBasicVersionId;
        this.recordVersion = recordVersion;
    }
    public ProdBasicVersion(String prodBasicVersionId, String versionNo, String yearCd, String monthCd, String versionDes, String active, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, List<ProdVersionDetail> prodVersionDetails) {
       this.prodBasicVersionId = prodBasicVersionId;
       this.versionNo = versionNo;
       this.yearCd = yearCd;
       this.monthCd = monthCd;
       this.versionDes = versionDes;
       this.active = active;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.prodVersionDetails = prodVersionDetails;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="PROD_BASIC_VERSION_ID", unique=true, nullable=false, length=50)
    public String getProdBasicVersionId() {
        return this.prodBasicVersionId;
    }
    
    public void setProdBasicVersionId(String prodBasicVersionId) {
        this.prodBasicVersionId = prodBasicVersionId;
    }
    
    @Column(name="VERSION_NO", length=20)
    public String getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(String versionNo) {
        this.versionNo = versionNo;
    }
    
    @Column(name="YEAR_CD", length=4)
    public String getYearCd() {
        return this.yearCd;
    }
    
    public void setYearCd(String yearCd) {
        this.yearCd = yearCd;
    }
    
    @Column(name="MONTH_CD", length=2)
    public String getMonthCd() {
        return this.monthCd;
    }
    
    public void setMonthCd(String monthCd) {
        this.monthCd = monthCd;
    }
    
    @Column(name="VERSION_DES", length=1000)
    public String getVersionDes() {
        return this.versionDes;
    }
    
    public void setVersionDes(String versionDes) {
        this.versionDes = versionDes;
    }
    
    @Column(name="ACTIVE", length=2)
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="prodBasicVersion")
    @BatchSize(size=10)
public List<ProdVersionDetail> getProdVersionDetails() {
        return this.prodVersionDetails;
    }
    
    public void setProdVersionDetails(List<ProdVersionDetail> prodVersionDetails) {
        this.prodVersionDetails = prodVersionDetails;
    }




}


