// 
package com.hhz.ump.entity.prod;
// Generated 2011-11-10 13:11:29 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * ProdMaterialPrice generated by hbm2java
 */
@Entity
@Table(name="PROD_MATERIAL_PRICE"
    
)
public class ProdMaterialPrice  implements java.io.Serializable {


     private String prodMaterialPriceId;
     private String yearCd;
     private String monthCd;
     private String areaCd;
     private String materialZoneCd;
     private String bussinessCd;
     private BigDecimal currentMonthPrice;
     private String priceDesc;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;

    public ProdMaterialPrice() {
    }

	
    public ProdMaterialPrice(String prodMaterialPriceId, String areaCd, String bussinessCd, long recordVersion) {
        this.prodMaterialPriceId = prodMaterialPriceId;
        this.areaCd = areaCd;
        this.bussinessCd = bussinessCd;
        this.recordVersion = recordVersion;
    }
    public ProdMaterialPrice(String prodMaterialPriceId, String yearCd, String monthCd, String areaCd, String materialZoneCd, String bussinessCd, BigDecimal currentMonthPrice, String priceDesc, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion) {
       this.prodMaterialPriceId = prodMaterialPriceId;
       this.yearCd = yearCd;
       this.monthCd = monthCd;
       this.areaCd = areaCd;
       this.materialZoneCd = materialZoneCd;
       this.bussinessCd = bussinessCd;
       this.currentMonthPrice = currentMonthPrice;
       this.priceDesc = priceDesc;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="PROD_MATERIAL_PRICE_ID", unique=true, nullable=false, length=50)
    public String getProdMaterialPriceId() {
        return this.prodMaterialPriceId;
    }
    
    public void setProdMaterialPriceId(String prodMaterialPriceId) {
        this.prodMaterialPriceId = prodMaterialPriceId;
    }
    
    @Column(name="YEAR_CD", length=4)
    public String getYearCd() {
        return this.yearCd;
    }
    
    public void setYearCd(String yearCd) {
        this.yearCd = yearCd;
    }
    
    @Column(name="MONTH_CD", length=2)
    public String getMonthCd() {
        return this.monthCd;
    }
    
    public void setMonthCd(String monthCd) {
        this.monthCd = monthCd;
    }
    
    @Column(name="AREA_CD", nullable=false, length=2)
    public String getAreaCd() {
        return this.areaCd;
    }
    
    public void setAreaCd(String areaCd) {
        this.areaCd = areaCd;
    }
    
    @Column(name="MATERIAL_ZONE_CD", length=30)
    public String getMaterialZoneCd() {
        return this.materialZoneCd;
    }
    
    public void setMaterialZoneCd(String materialZoneCd) {
        this.materialZoneCd = materialZoneCd;
    }
    
    @Column(name="BUSSINESS_CD", nullable=false, length=30)
    public String getBussinessCd() {
        return this.bussinessCd;
    }
    
    public void setBussinessCd(String bussinessCd) {
        this.bussinessCd = bussinessCd;
    }
    
    @Column(name="CURRENT_MONTH_PRICE", precision=10)
    public BigDecimal getCurrentMonthPrice() {
        return this.currentMonthPrice;
    }
    
    public void setCurrentMonthPrice(BigDecimal currentMonthPrice) {
        this.currentMonthPrice = currentMonthPrice;
    }
    
    @Column(name="PRICE_DESC", length=50)
    public String getPriceDesc() {
        return this.priceDesc;
    }
    
    public void setPriceDesc(String priceDesc) {
        this.priceDesc = priceDesc;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }




}


