CREATE TABLE INTT_OUTBOUNDASSIGNED (INTT_ID VARCHAR2(255 CHAR) NOT NULL, INTT_OUTORDERITEMID VARCHAR2(255 CHAR), INTT_STORAGEITEMID VARCHAR2(255 CHAR), INTT_ASSIGNEDQTY FLOAT, INTT_ISDELETE INT, PRIMARY KEY (INTT_ID));

alter table INTT_OUTBOUNDASSIGNED add CONSTRAINT FK9D725F786D278E6F FOREIGN KEY (INTT_STORAGEITEMID) REFERENCES INTT_STORAGEITEM;
alter table INTT_OUTBOUNDASSIGNED add CONSTRAINT FK9D725F7875FF532B FOREIGN KEY (INTT_OUTORDERITEMID) REFERENCES INTT_OUTBOUNDORDERITEM;
