--有用
CREATE TABLE INTT_USER (
	USER_ID NUMBER,
  	USER_NAME VARCHAR(255) NOT NULL,
  	USER_PASSWORD VARCHAR(255) NOT NULL,
    USER_STATUS INT NULL,
    SESSION_TIME_OUT INT NULL,
    TIME_ZONE VARCHAR(50),
  	LANGUAGE VARCHAR(50) NOT NULL,
    CREATION_TIME DATE NOT NULL,
  	LAST_LOGIN DATE NULL,
    CREATOR INT NULL,
    CUSTOMER INT,
    EMAIL VARCHAR(400),
  	PRIMARY KEY(USER_ID) 
);

-------------------------------------------------------------------------------------------------------------------

CREATE TABLE INTT_ROLE (
	ROLE_ID NUMBER,
	ROLE_NAME VARCHAR(255) NOT NULL,
	TEMPLATE VARCHAR(500) NOT NULL,
	DESCRIPTION VARCHAR(500) NOT NULL,
  	PRIMARY KEY(ROLE_ID) 
);


-------------------------------------------------------------------------------------------------------------------


CREATE TABLE INTT_USER_ROLE (
	USER_ROLE_ID NUMBER,
	ROLE_ID INT NOT NULL,
	USER_ID INT NOT NULL,
  	PRIMARY KEY(USER_ROLE_ID) 
);
-------------------------------------------------------------------------------------------------------------------
CREATE TABLE INTT_CUSTOMER (
	ID NUMBER,
	NAME VARCHAR(255) NOT NULL,
	CREATION_TIME DATE NOT NULL,
	ADDRESS VARCHAR(255) NOT NULL,
	REMARK VARCHAR(255) NOT NULL,
  	PRIMARY KEY(ID) 
);



-------------------------------------------------------------------------------------------------------------------
CREATE TABLE INTT_USER_CUSTOMER (
	ID NUMBER,
	USER_ID INT NOT NULL,
	CLIENT_ID INT NOT NULL,
  	PRIMARY KEY(ID) 
);


CREATE SEQUENCE SEQ_USER
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
nocache;

CREATE SEQUENCE SEQ_CUSTOMER
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
nocache;

CREATE SEQUENCE SEQ_USER_CUSTOMER
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
nocache;

CREATE SEQUENCE SEQ_USER_ROLE
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
nocache;

CREATE SEQUENCE SEQ_ROLE
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
nocache;




ALTER TABLE INTT_USER_ROLE
ADD CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES INTT_USER (USER_ID);

ALTER TABLE INTT_USER_ROLE
ADD CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES INTT_ROLE (ROLE_ID);

ALTER TABLE INTT_USER_CUSTOMER
ADD CONSTRAINT FK_USER_CUSTOMER FOREIGN KEY (USER_ID) REFERENCES INTT_USER (USER_ID);

ALTER TABLE INTT_USER_CUSTOMER
ADD CONSTRAINT FK_CUSTOMER_USER FOREIGN KEY (CLIENT_ID) REFERENCES INTT_CUSTOMER (ID);


INSERT INTO INTT_USER
VALUES (SEQ_USER.nextval,'admin','C4CA4238A0B923820DCC509A6F75849B',0,600000,'','cn',SYSDATE,SYSDATE,-1,1,'SH');

INSERT INTO INTT_ROLE
VALUES (SEQ_ROLE.nextval, 'admin','white','admin');

INSERT INTO INTT_USER_ROLE
VALUES (SEQ_USER_ROLE.nextval,1,1);
