// 
package com.hhz.ump.entity.cont;
// Generated 2011-5-31 16:09:18 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * ContSettlement generated by hbm2java
 */
@Entity
@Table(name="CONT_SETTLEMENT"
    ,schema="POWERDESK"
)
public class ContSettlement  implements java.io.Serializable {


     private String contSettlementId;
     private ContLedger contLedger;
     private BigDecimal clearPrice;
     private BigDecimal guaranteeMoney;
     private BigDecimal matieralPrice;
     private BigDecimal currentPay;
     private BigDecimal currentAdd;
     private BigDecimal payMoney;
     private String remark;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private String resApproveCd;
     private String resApproveId;

    public ContSettlement() {
    }

	
    public ContSettlement(String contSettlementId, ContLedger contLedger, long recordVersion) {
        this.contSettlementId = contSettlementId;
        this.contLedger = contLedger;
        this.recordVersion = recordVersion;
    }
    public ContSettlement(String contSettlementId, ContLedger contLedger, BigDecimal clearPrice, BigDecimal guaranteeMoney, BigDecimal matieralPrice, BigDecimal currentPay, BigDecimal currentAdd, BigDecimal payMoney, String remark, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, String resApproveCd, String resApproveId) {
       this.contSettlementId = contSettlementId;
       this.contLedger = contLedger;
       this.clearPrice = clearPrice;
       this.guaranteeMoney = guaranteeMoney;
       this.matieralPrice = matieralPrice;
       this.currentPay = currentPay;
       this.currentAdd = currentAdd;
       this.payMoney = payMoney;
       this.remark = remark;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.resApproveCd = resApproveCd;
       this.resApproveId = resApproveId;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="CONT_SETTLEMENT_ID", unique=true, nullable=false, length=50)
    public String getContSettlementId() {
        return this.contSettlementId;
    }
    
    public void setContSettlementId(String contSettlementId) {
        this.contSettlementId = contSettlementId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONT_LEDGER_ID", nullable=false)
    public ContLedger getContLedger() {
        return this.contLedger;
    }
    
    public void setContLedger(ContLedger contLedger) {
        this.contLedger = contLedger;
    }
    
    @Column(name="CLEAR_PRICE", precision=18, scale=2)
    public BigDecimal getClearPrice() {
        return this.clearPrice;
    }
    
    public void setClearPrice(BigDecimal clearPrice) {
        this.clearPrice = clearPrice;
    }
    
    @Column(name="GUARANTEE_MONEY", precision=18, scale=2)
    public BigDecimal getGuaranteeMoney() {
        return this.guaranteeMoney;
    }
    
    public void setGuaranteeMoney(BigDecimal guaranteeMoney) {
        this.guaranteeMoney = guaranteeMoney;
    }
    
    @Column(name="MATIERAL_PRICE", precision=18, scale=2)
    public BigDecimal getMatieralPrice() {
        return this.matieralPrice;
    }
    
    public void setMatieralPrice(BigDecimal matieralPrice) {
        this.matieralPrice = matieralPrice;
    }
    
    @Column(name="CURRENT_PAY", precision=18, scale=2)
    public BigDecimal getCurrentPay() {
        return this.currentPay;
    }
    
    public void setCurrentPay(BigDecimal currentPay) {
        this.currentPay = currentPay;
    }
    
    @Column(name="CURRENT_ADD", precision=18, scale=2)
    public BigDecimal getCurrentAdd() {
        return this.currentAdd;
    }
    
    public void setCurrentAdd(BigDecimal currentAdd) {
        this.currentAdd = currentAdd;
    }
    
    @Column(name="PAY_MONEY", precision=18, scale=2)
    public BigDecimal getPayMoney() {
        return this.payMoney;
    }
    
    public void setPayMoney(BigDecimal payMoney) {
        this.payMoney = payMoney;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
    
    @Column(name="RES_APPROVE_CD", length=50)
    public String getResApproveCd() {
        return this.resApproveCd;
    }
    
    public void setResApproveCd(String resApproveCd) {
        this.resApproveCd = resApproveCd;
    }
    
    @Column(name="RES_APPROVE_ID", length=50)
    public String getResApproveId() {
        return this.resApproveId;
    }
    
    public void setResApproveId(String resApproveId) {
        this.resApproveId = resApproveId;
    }




}


