// 
package com.hhz.ump.entity.cont;
// Generated 2010-12-2 14:55:08 by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * ContPay generated by hbm2java
 */
@Entity
@Table(name="CONT_PAY"
    ,schema="POWERDESK"
)
public class ContPay  implements java.io.Serializable {


     private String contPayId;
     private ContLedger contLedger;
     private Date payTime;
     private BigDecimal completeNum;
     private BigDecimal matieralNum;
     private BigDecimal currentPay;
     private BigDecimal currentAdd;
     private String payProperty;
     private String attaBizId;
     private BigDecimal payMoney;
     private BigDecimal payRate;
     private String remark;
     private String creator;
     private String createdDeptCd;
     private Date createdDate;
     private String updator;
     private String updatedDeptCd;
     private Date updatedDate;
     private long recordVersion;
     private String resApproveCd;
     private String resApproveId;
     private BigDecimal currentRealPay;

    public ContPay() {
    }

	
    public ContPay(String contPayId, ContLedger contLedger, long recordVersion) {
        this.contPayId = contPayId;
        this.contLedger = contLedger;
        this.recordVersion = recordVersion;
    }
    public ContPay(String contPayId, ContLedger contLedger, Date payTime, BigDecimal completeNum, BigDecimal matieralNum, BigDecimal currentPay, BigDecimal currentAdd, String payProperty, String attaBizId, BigDecimal payMoney, BigDecimal payRate, String remark, String creator, String createdDeptCd, Date createdDate, String updator, String updatedDeptCd, Date updatedDate, long recordVersion,String resApproveCd,String resApproveId,BigDecimal currentRealPay) {
       this.contPayId = contPayId;
       this.contLedger = contLedger;
       this.payTime = payTime;
       this.completeNum = completeNum;
       this.matieralNum = matieralNum;
       this.currentPay = currentPay;
       this.currentAdd = currentAdd;
       this.payProperty = payProperty;
       this.attaBizId = attaBizId;
       this.payMoney = payMoney;
       this.payRate = payRate;
       this.remark = remark;
       this.creator = creator;
       this.createdDeptCd = createdDeptCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.resApproveCd = resApproveCd;
       this.resApproveId = resApproveId;
       this.currentRealPay = currentRealPay;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 

    
    @Column(name="CONT_PAY_ID", unique=true, nullable=false, length=50)
    public String getContPayId() {
        return this.contPayId;
    }
    
    public void setContPayId(String contPayId) {
        this.contPayId = contPayId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONT_LEDGER_ID", nullable=false)
    public ContLedger getContLedger() {
        return this.contLedger;
    }
    
    public void setContLedger(ContLedger contLedger) {
        this.contLedger = contLedger;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PAY_TIME", length=7)
    public Date getPayTime() {
        return this.payTime;
    }
    
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    
    @Column(name="COMPLETE_NUM", precision=18, scale=2)
    public BigDecimal getCompleteNum() {
        return this.completeNum;
    }
    
    public void setCompleteNum(BigDecimal completeNum) {
        this.completeNum = completeNum;
    }

    
    @Column(name="MATIERAL_NUM", precision=18, scale=2)
    public BigDecimal getMatieralNum() {
        return this.matieralNum;
    }
    
    public void setMatieralNum(BigDecimal matieralNum) {
        this.matieralNum = matieralNum;
    }

    
    @Column(name="CURRENT_PAY", precision=18, scale=2)
    public BigDecimal getCurrentPay() {
        return this.currentPay;
    }
    
    public void setCurrentPay(BigDecimal currentPay) {
        this.currentPay = currentPay;
    }

    
    @Column(name="CURRENT_ADD", precision=18, scale=2)
    public BigDecimal getCurrentAdd() {
        return this.currentAdd;
    }
    
    public void setCurrentAdd(BigDecimal currentAdd) {
        this.currentAdd = currentAdd;
    }

    
    @Column(name="PAY_PROPERTY", length=50)
    public String getPayProperty() {
        return this.payProperty;
    }
    
    public void setPayProperty(String payProperty) {
        this.payProperty = payProperty;
    }

    
    @Column(name="ATTA_BIZ_ID", length=100)
    public String getAttaBizId() {
        return this.attaBizId;
    }
    
    public void setAttaBizId(String attaBizId) {
        this.attaBizId = attaBizId;
    }

    
    @Column(name="PAY_MONEY", precision=18, scale=2)
    public BigDecimal getPayMoney() {
        return this.payMoney;
    }
    
    public void setPayMoney(BigDecimal payMoney) {
        this.payMoney = payMoney;
    }

    
    @Column(name="PAY_RATE", precision=18, scale=2)
    public BigDecimal getPayRate() {
        return this.payRate;
    }
    
    public void setPayRate(BigDecimal payRate) {
        this.payRate = payRate;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
	
	@Column(name="RES_APPROVE_CD", length=50)
	public String getResApproveCd() {
		return resApproveCd;
	}


	public void setResApproveCd(String resApproveCd) {
		this.resApproveCd = resApproveCd;
	}


	@Column(name="RES_APPROVE_ID", length=50)
	public String getResApproveId() {
		return resApproveId;
	}


	public void setResApproveId(String resApproveId) {
		this.resApproveId = resApproveId;
	}



    private String createdCenterCd;
    private String createdPositionCd;
    private String updatedCenterCd;
    private String updatedPositionCd;
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }

}


